lfortran/lfortran

src/libasr/ASR.asdl
src/libasr/codegen/asr_to_llvm.cpp
src/runtime/impure/lfortran_intrinsics.c
src/runtime/impure/lfortran_intrinsics.h

Corresponding LPython PR: https://github.com/lcompilers/lpython/pull/754

Add `CharacterToInteger` cast kind to the ASR

---

.github/workflows/CI.yml
ci/tarball_update_json.py
ci/upload_tarball.sh

CI: Upload tarball

---

src/libasr/ASR.asdl
src/libasr/codegen/asr_to_llvm.cpp
src/runtime/impure/lfortran_intrinsics.c
src/runtime/impure/lfortran_intrinsics.h

LPython PR: https://github.com/lcompilers/lpython/pull/804

Add `StringChr` and `StringOrd` nodes to the ASR

---

ci/tarball_update_json.py

See the working commit: https://github.com/lfortran/tarballs/commit/5c2f0803cd62167906774726c35f0c66520377cc
cc @certik

Use the correct json file for tarball upload

---

src/lfortran/semantics/ast_body_visitor.cpp

comment sentence restructured

---

.github/workflows/CI.yml
ci/upload_docs.sh
doc/src/index.md

towards https://github.com/lfortran/docs.lfortran.org/issues/1
CC: @Smit-create @certik

CI: Add support for Uploading Documentation

---

.github/workflows/CI.yml
ci/build.xsh
ci/build_tmp.xsh
ci/environment.yml
ci/environment_linux.yml
ci/test.xsh

This PR switches to micromamba, and uses `sscache` and `ninja` wherever possible.

try to speed up CI with micromamba

---

.github/workflows/CI.yml

use mamba-org/provision-with-micromamba@main now

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_wasm.cpp
src/libasr/codegen/wasm_assembler.h
src/libasr/codegen/wasm_to_wat.h

This `PR` adds basic support for Arrays in the `WebAssembly` Backend.

WASM: Initial support for Arrays

---

doc/mkdocs.yml
doc/src/intrinsics/character/achar.md
doc/src/intrinsics/character/adjustl.md
doc/src/intrinsics/character/adjustr.md
doc/src/intrinsics/mathematical/trigonometric/acosh.md
doc/src/intrinsics/numeric/abs.md
doc/src/intrinsics/numeric/aimag.md
doc/src/intrinsics/numeric/aint.md

A's. 
ref: https://github.com/lfortran/docs.lfortran.org/issues/1.

Add a few more intrinsics function docs

---

ci/build_tmp.xsh

Fixes https://gitlab.com/lfortran/lfortran/-/issues/747

Do not build in Release mode on Linux

---

grammar/asdl_cpp.py
integration_tests/CMakeLists.txt
integration_tests/arrays_inputs_15.f90
src/libasr/CMakeLists.txt
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
src/libasr/codegen/llvm_array_utils.h
src/libasr/pass/pass_manager.h
src/libasr/pass/update_array_dim_intrinsic_calls.cpp
src/libasr/pass/update_array_dim_intrinsic_calls.h

N.B. - https://lfortran.zulipchat.com/#narrow/stream/197339-general/topic/passing.20arrays.20by.20a.20pointer

Array arguments in procedures with non-empty dimensions

---

src/libasr/asr_utils.h
src/libasr/codegen/llvm_utils.cpp

The corresponding LPython's PR: https://github.com/lcompilers/lpython/pull/887

Update ASR from LPython

---

grammar/asdl_cpp.py

Not every change is ported yet, but most of them are.

Port asdl_cpp from LPython

---

grammar/asdl_cpp.py
src/libasr/serialization.cpp

For now we still set it to 0 for LFortran until we support multiple files with location.

Serialize location information

---

src/libasr/codegen/asr_to_llvm.cpp

Corresponding LPython PR: https://github.com/lcompilers/lpython/pull/912/

LLVM: Implement `IfExp` visitor

---

src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_utils.cpp
src/libasr/codegen/llvm_utils.h

Corresponding LPython PR: https://github.com/lcompilers/lpython/pull/930

LLVM: Add ListLen visitor

---

doc/src/installation.md
environment_win.yml

Add the Conda environment for Windows.

Add Windows instructions how to build from git

---

src/libasr/ASR.asdl
src/libasr/codegen/asr_to_llvm.cpp

Corresponding LPython PR: https://github.com/lcompilers/lpython/pull/935

Add TupleLen visitor in LLVM

---

run_tests.py
src/libasr/compiler_tester/tester.py

https://github.com/lcompilers/lpython/pull/945

Use absolute path for testing

---

integration_tests/CMakeLists.txt
integration_tests/data_01.f90
src/lfortran/semantics/ast_common_visitor.h

AST->ASR: Implement data statements

---

integration_tests/CMakeLists.txt
integration_tests/arithmetic_if_01.f90
integration_tests/arithmetic_if_02.f90
integration_tests/arithmetic_if_03.f90
integration_tests/arithmetic_if_04.f90
src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/arithmetic_if1.f90
tests/reference/asr-arithmetic_if1-f119c2a.json
tests/reference/asr-arithmetic_if1-f119c2a.stderr
tests/tests.toml

Implement arithmetic if

---

src/lfortran/parser/fixedform_tokenizer.cpp
tests/fixedform_return2.f
tests/reference/ast-fixedform_return2-597f864.json
tests/reference/ast-fixedform_return2-597f864.stdout
tests/tests.toml

Fixed-form: fix multiple return statements

---

.github/workflows/CI.yml
ci/environment.yml

Also move rapidjson into the main env file.

Install zlib in the Conda env file

---

doc/mkdocs.yml

- Header Navigation
- Suggestions in search
- GitHub URL
- Toggle to dark mode
- Sidebar navigation improvement
- Footer Navigation

Add a few improvements to UI/UX

---

doc/mkdocs.yml
doc/src/intrinsics/numeric/gamma.md

G.
ref: https://gitlab.com/lfortran/lfortran/-/wikis/Implementation%20Status%20of%20Intrinsic%20Functions

Add Gamma intrinsic function documentation

---

.github/workflows/CI.yml
ci/upload_lfortran_wasm.sh

towards https://github.com/lfortran/lcompilers_frontend/issues/3

CI: Building LFortran to WASM

---

src/libasr/asdl_cpp.py
tests/reference/asr_indent-subroutine1-5dfc71f.json
tests/reference/asr_indent-subroutine1-5dfc71f.stdout
tests/reference/ast_indent-subroutine1-3a55d20.json
tests/reference/ast_indent-subroutine1-3a55d20.stdout

Closes: #405
Closes: https://gitlab.com/lfortran/lfortran/-/issues/533

Refactor `indent` handling in asdl_cpp.py

---

integration_tests/data_01.f90
src/lfortran/semantics/ast_common_visitor.h

Allow data attr for arrays

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_45.f90
src/runtime/pure/lfortran_intrinsic_iso_fortran_env.f90

Implement real_kinds

---

ci/upload_docs.sh

CI: Add .nojekyll to docs

---

integration_tests/data_01.f90
src/lfortran/semantics/ast_common_visitor.h

Allow multiple data declaration

---

doc/.gitignore
doc/README.md
doc/build.py
doc/intl.py
doc/src/ast_and_asr.ipynb

- add README with instructions for sphinx build
- add script to update translations
- link to weblate

Documentation for sphinx pages

---

src/libasr/codegen/asr_to_wasm.cpp
tests/reference/wat-abs_01-0c0b4df.json
tests/reference/wat-abs_01-0c0b4df.stdout
tests/reference/wat-abs_03-5d62cca.json
tests/reference/wat-abs_03-5d62cca.stdout
tests/reference/wat-cpu_time_02_wasm-fa2b15f.json
tests/reference/wat-cpu_time_02_wasm-fa2b15f.stdout
tests/reference/wat-expr_08-74f99b7.json
tests/reference/wat-expr_08-74f99b7.stdout
tests/reference/wat-wasm_bind_c-c463a65.json
tests/reference/wat-wasm_bind_c-c463a65.stdout

Bug details: https://github.com/lfortran/lfortran/issues/555#issuecomment-1222924780

WASM: Fix import functions bug

---

src/libasr/modfile.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/999

Refactor save/load modfile to comply with LPython changes

---

src/libasr/pass/array_op.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1076

Generalised elemental for any number of arguments

---

src/lfortran/parser/fixedform_tokenizer.cpp
tests/loop_test1.f
tests/reference/asr-loop_test1-716ccb0.json
tests/reference/ast-loop_test1-7800c18.json

Do: Recognize a comma after label

---

README.md

Add links to donations to the README

---

grammar/AST.asdl
src/lfortran/parser/fixedform_tokenizer.cpp
src/lfortran/parser/parser.yy
src/lfortran/parser/tokenizer.re
tests/fixed_form/double_complex1.f
tests/reference/ast-double_complex1-c5abb47.json
tests/reference/ast-double_complex1-c5abb47.stdout
tests/tests.toml

Test added. No new essential conflicts created in the parser.

Fixed-form: implement double complex

---

run_tests.py
src/libasr/compiler_tester/tester.py

Refactor test suite: add `-b | --backend` option to specify backend (fix #756)

---

integration_tests/intrinsics_46.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/ASR.asdl
tests/reference/asr-intrinsics_46-6a18bcb.json
tests/reference/asr-intrinsics_46-6a18bcb.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/issues/758
Commit - ef46507d6ac8fcef734de9bc642fd298c7f79968 in https://gitlab.com/lfortran/lfortran/-/merge_requests/1754/commits

Implemented ``ichar`` intrinsic

---

doc/locale/ru/LC_MESSAGES/docs.po
doc/src/_static/languages.json

Add Russian translation

---

src/libasr/codegen/asr_to_c_cpp.h
tests/reference/c-case_01-2ff47e6.json
tests/reference/c-case_01-2ff47e6.stdout
tests/reference/c-case_02-eff3752.json
tests/reference/c-case_02-eff3752.stdout
tests/reference/c-case_03-b50b4bf.json
tests/reference/c-case_03-b50b4bf.stdout
tests/reference/c-case_05-2fed69e.json
tests/reference/c-case_05-2fed69e.stdout
tests/reference/c-case_06-ecc9f3c.json
tests/reference/c-case_06-ecc9f3c.stdout
tests/reference/cpp-case_01-49038b7.json
tests/reference/cpp-case_01-49038b7.stdout
tests/reference/cpp-case_02-9e53b61.json
tests/reference/cpp-case_02-9e53b61.stdout
tests/reference/cpp-case_03-5c7be5c.json
tests/reference/cpp-case_03-5c7be5c.stdout
tests/reference/cpp-case_05-96724df.json
tests/reference/cpp-case_05-96724df.stdout
tests/reference/cpp-case_06-57ebc6f.json
tests/reference/cpp-case_06-57ebc6f.stdout
tests/tests.toml

Port the Julia select implementation to C & C++.

[C] Implement select for C & C++ backends

---

src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/asr_to_julia.cpp

Since I cannot push commits to @certik's branch, I start a new PR. I do not add tests in this PR and would like to leave that for @sloorush.

[C, Julia] convert no-var do-loop into while (fix #821)

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/intrinsics_06.f90
integration_tests/run_tests.py
tests/reference/asr-intrinsics_06-ad7a712.json
tests/reference/asr-intrinsics_06-ad7a712.stdout
tests/reference/llvm-intrinsics_06-15c0eef.json
tests/reference/llvm-intrinsics_06-15c0eef.stdout

These were disabled by a mistake.

Enable gfortran tests again

---

integration_tests/int_03.f90
src/lfortran/semantics/asr_implicit_cast_rules.h
src/libasr/ASR.asdl
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/asr-int_03-6a315be.json
tests/reference/asr-int_03-6a315be.stdout

Add Complex to Integer Cast

---

integration_tests/CMakeLists.txt
integration_tests/doloop_08.f90
tests/reference/c-doloop_08-2839ed5.json
tests/reference/c-doloop_08-2839ed5.stdout
tests/reference/cpp-doloop_08-cf3820d.json
tests/reference/cpp-doloop_08-cf3820d.stdout
tests/reference/julia-doloop_08-f0d8fe6.json
tests/reference/julia-doloop_08-f0d8fe6.stdout

Add the doloop_08 test to cmake

---

src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/asr_to_julia.cpp
tests/reference/asr-doloop_04-e5818ae.json
tests/reference/asr-doloop_04-e5818ae.stdout

@certik I reverted the changes in #823 and made the change at ASR level instead.

[ASR] Convert do loops without a header into while loops

---

doc/locale/bn/LC_MESSAGES/docs.po
doc/locale/pl/LC_MESSAGES/docs.po
doc/src/_static/languages.json

i18n: Add Polish and Bengali po files

---

src/lfortran/semantics/ast_common_visitor.h

We also reworked the logic to by strictly if/else structure, and we give error messages for all cases that are not handled yet or are errors.

Semantics: Document how data is handled

---

src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/ASR.asdl
src/libasr/asr_utils.h
tests/reference/asr-template_add-b53d132.json
tests/reference/asr-template_add-b53d132.stdout

https://github.com/lcompilers/lpython/pull/1188#pullrequestreview-1136184445

Revert to latest generics design in ``libasr``

---

integration_tests/complex_07.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
tests/reference/asr-complex_07-8d914e3.json
tests/reference/asr-complex_07-8d914e3.stdout

Implement double complex type

---

src/libasr/asr_verify.cpp
tests/loop_test2.f
tests/reference/asr-loop_test2-1f6fc05.json
tests/reference/asr-loop_test2-1f6fc05.stdout
tests/reference/ast-loop_test2-bd9b49b.json
tests/reference/ast-loop_test2-bd9b49b.stdout

Check that the variable is an array.

Improve ArrayItem verify()

---

tests/implicit11.f90
tests/reference/asr-implicit11-71e42a3.json
tests/reference/asr-implicit11-71e42a3.stdout
tests/tests.toml

Add a test for implicit typing and dimag

---

.github/workflows/CI.yml
ci/environment_linux_llvm10.yml

We now test LLVM 10, 11, 14 and 15. We do not test 12 and 13, it will most likely work and we can add those tests later.
See #903.

CI: Test LLVM 10

---

integration_tests/doloop_04.f90
src/libasr/pass/pass_utils.cpp
tests/reference/asr-doloop_04-e5818ae.json
tests/reference/asr-doloop_04-e5818ae.stdout
tests/reference/ast-doloop_04-ebdda1b.json
tests/reference/ast-doloop_04-ebdda1b.stdout
tests/reference/ast_f90-doloop_04-5f9c26b.json
tests/reference/ast_f90-doloop_04-5f9c26b.stdout

Trying to fix https://github.com/certik/minpack/commit/5ab467d37313d1c61e45b5a7bf94d167575b2685.
#512

Support variable do loop increment

---

src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/implicit12.f90
tests/reference/asr-implicit11-71e42a3.json
tests/reference/asr-implicit11-71e42a3.stdout
tests/reference/asr-implicit12-49c4b73.json
tests/reference/asr-implicit12-49c4b73.stderr
tests/reference/asr-implicit12-ed98f7b.json
tests/reference/asr-implicit12-ed98f7b.stdout
tests/tests.toml

Implement ```implicit``` for ```subroutine```

---

src/libasr/codegen/asr_to_llvm.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1215
Testing here to know the changes work for both the compilers as these are important ones so shouldn't be delayed till syncing of libasr.

``CPtr`` related updates from LPython

---

src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/asr_to_llvm.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1220

Fix nested structs by using non-pointer member types in the backend

---

integration_tests/CMakeLists.txt
integration_tests/include_02.f90
src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/parser/parser.cpp
src/lfortran/parser/parser.h

Prescanner: make include prescanning more robust

---

src/lfortran/semantics/ast_common_visitor.h
tests/implicit_interface2.f90
tests/reference/asr-implicit_interface2-0a34057.json
tests/reference/asr-implicit_interface2-0a34057.stdout
tests/tests.toml

Of the type:
real :: x
print *, x(5)  ! Implicit function call
Tests added.

Implement implicit function declarations

---

src/libasr/codegen/asr_to_llvm.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1230

Handle pointer to `cptr` case

---

run_tests.py
src/lfortran/semantics/ast_body_visitor.cpp
tests/allow_implicit_interface2.f90
tests/reference/asr-allow_implicit_interface2-094c0f8.json
tests/reference/asr-allow_implicit_interface2-094c0f8.stdout
tests/tests.toml

#512 
Trying to fix: https://github.com/certik/minpack/commit/a9fe0f715472f7c359c5ffec6f7d5ae974982d40

Fix implicit interface failure with callback argument

---

integration_tests/CMakeLists.txt
integration_tests/expr_10.f90
src/libasr/asr_utils.h
tests/reference/asr-implicit5-0330703.json
tests/reference/asr-implicit5-0330703.stdout

Fix converting "2.2d-3"

---

src/libasr/codegen/asr_to_llvm.cpp

Corresponding - https://github.com/lcompilers/lpython/pull/1248

`Pointer[CPtr]` passing to `BindC` functions change

---

src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/implicit_interface3.f90
tests/implicit_interface4.f90
tests/reference/asr-allow_implicit_interface2-094c0f8.json
tests/reference/asr-implicit_interface3-9e2dea4.json
tests/reference/asr-implicit_interface3-9e2dea4.stdout
tests/reference/asr-implicit_interface4-c8961c3.json
tests/reference/asr-implicit_interface4-c8961c3.stdout
tests/tests.toml

Fix implicit callback

---

integration_tests/doloop_04.f90
src/libasr/pass/pass_utils.cpp
tests/reference/asr-doloop_04-e5818ae.json
tests/reference/asr-doloop_04-e5818ae.stdout
tests/reference/ast-doloop_04-ebdda1b.stdout
tests/reference/ast_f90-doloop_04-5f9c26b.json
tests/reference/ast_f90-doloop_04-5f9c26b.stdout
tests/reference/llvm-doloop_04-e25bf76.json
tests/reference/llvm-doloop_04-e25bf76.stdout
tests/reference/pass_do_loops-doloop_01-7bd6b32.json
tests/reference/pass_do_loops-doloop_01-7bd6b32.stdout
tests/reference/pass_do_loops-doloop_04-3703380.json
tests/reference/pass_do_loops-doloop_04-3703380.stdout
tests/reference/pass_loop_unroll-loop_unroll_large-3677d89.json
tests/reference/pass_loop_unroll-loop_unroll_large-3677d89.stdout
tests/tests.toml

Fix doloop with variable increment

---

src/bin/lfortran.cpp

Print version in startup message in Interactive LFortran

---

src/runtime/impure/lfortran_intrinsic_math.f90
tests/reference/julia-arrays_02-849d7b0.json
tests/reference/julia-arrays_02-849d7b0.stdout

Implement conjg more robustly

---

integration_tests/CMakeLists.txt
integration_tests/implied_do_loops1.f90
integration_tests/implied_do_loops2.f90
integration_tests/implied_do_loops3.f90

With this PR, I am trying to add tests for `implied do loops`, that works correctly on `gfortran`.
@certik

Added test for implied do loops.

---

doc/src/asr/asr_nodes/type_nodes/ttype.md

Ref: 
- https://github.com/lfortran/lfortran/issues/842
- https://github.com/lfortran/lfortran/pull/866#discussion_r990231086

Add ASR docs for ttype

---

doc/src/asr/asr_nodes/cast_kind_nodes/cast_kind.md

Ref:
- https://github.com/lfortran/lfortran/issues/842.
- https://github.com/lfortran/lfortran/pull/866#discussion_r990228141.

Add ASR docs for cast_kind nodes

---

doc/src/asr/asr_nodes/kinds_nodes/kinds.md

Ref https://github.com/lfortran/lfortran/issues/842.

Add ASR docs for kinds nodes

---

doc/src/asr/asr_nodes/symbol_nodes/symbol.md

Ref https://github.com/lfortran/lfortran/issues/842.

Add ASR docs for symbol nodes

---

src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_llvm.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1292

Changes for `Struct` and `StructInstanceMember` use cases

---

integration_tests/intrinsics_19.f90
src/lfortran/semantics/comptime_eval.h

Fixes related to https://github.com/certik/minpack/issues/11

Add missing dlog10

---

src/libasr/codegen/asr_to_llvm.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1308

Changes for handling of member access of pointer to structs

---

src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_utils.cpp

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1310

Changes for CPtr deepcopy and handle CPtr type passing into functions

---

doc/src/asr/asr_nodes/statement_nodes/assign.md
doc/src/asr/asr_nodes/statement_nodes/assignment.md
doc/src/asr/asr_nodes/statement_nodes/associate.md
doc/src/asr/asr_nodes/statement_nodes/cycle.md

Ref https://github.com/lfortran/lfortran/issues/842.

Add a few statement ASR nodes docs

---

integration_tests/CMakeLists.txt
integration_tests/arrays_14.f90
src/libasr/codegen/asr_to_llvm.cpp

Fixes #1009 
Also related to https://github.com/certik/minpack/issues/11

Allow to access Nested array variables

---

.gitignore
src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/fortran_kernel.cpp
src/lfortran/parser/parser.cpp
src/lfortran/parser/preprocessor.re
src/lfortran/tests/test_error_rendering.cpp
src/lfortran/tests/test_llvm.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/diagnostics.cpp
src/libasr/diagnostics.h
src/libasr/location.h
src/libasr/lsp_interface.h

Co-authored-by: Thirumalai Shaktivel <74826228+Thirumalai-Shaktivel@users.noreply.github.com>
Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1297
I get several build errors due to `processor.re` (see below),
```bash
[ 66%] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/cwrapper.cpp.o
[ 67%] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/ast_serialization.cpp.o
[ 68%] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/__/bin/tpl/whereami/whereami.cpp.o
preprocessor.re:147:8: error: no member named 'out_start0' in 'LFortran::LocationManager'
lm.out_start0.push_back(output_len);
~~ ^
preprocessor.re:148:8: error: no member named 'in_start0' in 'LFortran::LocationManager'
lm.in_start0.push_back(input_len);
~~ ^ …
```

Extend Location manger to handle multi-file import errors

---

integration_tests/CMakeLists.txt
integration_tests/subroutines_08.f90
src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_cpp.cpp
src/libasr/codegen/asr_to_wasm.cpp

towards https://github.com/lfortran/lfortran/issues/1027

WASM, C, CPP: Subroutine intent unspecified

---

src/bin/lfortran.cpp

fixes https://github.com/lfortran/lcompilers_frontend/issues/50

WASM: Fix duplicate storage of newline locations

---

integration_tests/CMakeLists.txt
integration_tests/arrays_15.f90
src/libasr/pass/nested_vars.cpp

https://github.com/certik/minpack/issues/11#issuecomment-1326381812

Visit Call args in nested vars pass

---

src/libasr/codegen/asr_to_c_cpp.h
tests/reference/cpp-expr_05-3b5ec63.json
tests/reference/cpp-expr_05-3b5ec63.stdout

[C/Cpp] Add parentheses for Div

---

doc/src/asr/asr_nodes/expression_nodes/expression_nodes.md
doc/src/asr/asr_nodes/statement_nodes/statement_nodes.md
doc/src/index.md

Ref https://github.com/lfortran/lfortran/issues/842.

Add ASR nodes listing on https://docs.lfortran.org

---

doc/README.md
doc/environment.yml
doc/src/asr/asr_nodes/cast_kind_nodes/cast_kind.md
doc/src/asr/asr_nodes/expression_nodes/expression_nodes.md
doc/src/asr/asr_nodes/statement_nodes/statement_nodes.md
doc/src/index.md

Also fix some warnings and improve the instructions in the README.

Docs: Include all ASR nodes in the toctree

---

tests/reference/asr-variable1-9579363.json
tests/reference/asr-variable1-9579363.stdout
tests/variable1.f90

Update reference test results.

Fix a test to be valid Fortran

---

src/libasr/asr_utils.h
src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
src/libasr/codegen/llvm_array_utils.h

Corresponding LPython array - https://github.com/lcompilers/lpython/pull/1346

Create "char buffer[...]" for "i8[...]" typed arrays

---

src/lfortran/semantics/ast_common_visitor.h
tests/implicit_interface5.f90
tests/reference/asr-allow_implicit_interface-b700617.json
tests/reference/asr-allow_implicit_interface-b700617.stdout
tests/reference/asr-allow_implicit_interface2-094c0f8.json
tests/reference/asr-allow_implicit_interface2-094c0f8.stdout
tests/reference/asr-fixed_form_call1-8fadeb1.json
tests/reference/asr-fixed_form_call1-8fadeb1.stdout
tests/reference/asr-fixed_form_call2-366730d.json
tests/reference/asr-fixed_form_call2-366730d.stdout
tests/reference/asr-implicit_interface2-0a34057.json
tests/reference/asr-implicit_interface2-0a34057.stdout
tests/reference/asr-implicit_interface3-9e2dea4.json
tests/reference/asr-implicit_interface3-9e2dea4.stdout
tests/reference/asr-implicit_interface4-c8961c3.json
tests/reference/asr-implicit_interface4-c8961c3.stdout
tests/reference/asr-implicit_interface5-40b9ee9.json
tests/reference/asr-implicit_interface5-40b9ee9.stdout
tests/reference/asr-variable1-9579363.json
tests/reference/asr-variable1-9579363.stdout
tests/tests.toml

Make all implicit interface BindC

---

src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/pickle.cpp
src/lfortran/pickle.h
src/libasr/asdl_cpp.py
src/libasr/utils.h

towards https://github.com/lfortran/lfortran/issues/724, https://github.com/lfortran/lfortran/issues/324
I attempted to create a visualization of the generated json at https://shaikh-ubaid.github.io/ast_asr_json_visualizer/. It seems to work.

AST, ASR to Json

---

integration_tests/CMakeLists.txt
integration_tests/recursion_02.f90
integration_tests/recursion_03.f90
tests/reference/asr-recursion_02-b35e7ac.json
tests/reference/asr-recursion_02-b35e7ac.stdout
tests/reference/asr-recursion_03-7881aa7.json
tests/reference/asr-recursion_03-7881aa7.stdout
tests/reference/llvm-recursion_02-76da7b3.json
tests/reference/llvm-recursion_02-76da7b3.stdout
tests/reference/llvm-recursion_03-3285725.json
tests/reference/llvm-recursion_03-3285725.stdout

Fix recursion tests

---

.github/workflows/CI.yml

Fix failing CI

---

.gitignore
integration_tests/CMakeLists.txt
integration_tests/implicit_interface_01.f90
integration_tests/implicit_interface_02.f90
integration_tests/implicit_interface_03.f90
integration_tests/implicit_interface_04.f90
integration_tests/run_tests.py
run_tests.py
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
tests/reference/llvm-implicit_interface_04-ec2da0d.json
tests/reference/llvm-implicit_interface_04-ec2da0d.stdout
tests/tests.toml

Fix LLVM backend for implicit interface and BindC changes

---

integration_tests/functions_12.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/reference/asr-functions_12-19076ea.json
tests/reference/asr-functions_12-19076ea.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/pull/1037#issuecomment-1340432737

Fix dependencies for Functions

---

src/lfortran/semantics/ast_common_visitor.h
tests/redeclaration1.f90
tests/reference/asr-redeclaration1-0adcc00.json
tests/reference/asr-redeclaration1-0adcc00.stdout
tests/tests.toml

Resolves #651 & #573.
This PR generates ASR for `scipy/linalg/src/lu.f`

Fix re declaration error in `--implicit-typing`

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_10.f90
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp

https://github.com/lfortran/lfortran/commit/af9e844bd211ada4f05308791f403432cba0f97c

Bug fixes for StructType declaration and its symbol table

---

integration_tests/case_07.f90
src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-case_07-aeb5237.json
tests/reference/asr-case_07-aeb5237.stdout
tests/tests.toml

Allow strings in select case range conditions

---

integration_tests/arrays_21.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/ASR.asdl
tests/reference/asr-arrays_21-7cdec59.json
tests/reference/asr-arrays_21-7cdec59.stdout
tests/tests.toml

Implement ``maxloc`` intrinsic at ASR level

---

integration_tests/CMakeLists.txt
integration_tests/expr_12.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h

3af4774ca1f769456197df8873 and a24576123868d73f882c87

Set type of compile time values of ``character`` type correctly

---

integration_tests/derived_types_11.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-derived_types_11-8524582.json
tests/reference/asr-derived_types_11-8524582.stdout
tests/tests.toml

db8bfc5c7a85d36d3c81afa6bbcf925f70516945 and 427c7c2bc9dd0047884f582e045bc5c073f8737e

Fix some derived type issues

---

integration_tests/select_type_02.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/libasr/ASR.asdl
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
tests/reference/asr-select_type_01-fec2d3a.json
tests/reference/asr-select_type_01-fec2d3a.stdout
tests/reference/asr-select_type_02-507a333.json
tests/reference/asr-select_type_02-507a333.stdout
tests/tests.toml

Implement ``select type``

---

integration_tests/functions_13.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/runtime/pure/lfortran_intrinsic_string.f90
tests/reference/asr-functions_13-3540564.json
tests/reference/asr-functions_13-3540564.stdout
tests/reference/asr-intrinsics_36-140824b.json
tests/reference/asr-intrinsics_36-140824b.stdout
tests/tests.toml

Closes https://github.com/lfortran/lfortran/issues/1067

Implement Scan/Verify as functions

---

integration_tests/types_09.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/ast-types_09-4ca127b.json
tests/reference/ast-types_09-4ca127b.stdout

02f81053e8480c40d1291228ebb14a8b4d7e5c7b and b757048380bdc488d0448f5aac019a20bd37bee0

[Sprint] [FPM] Fix some issues in ASR

---

integration_tests/CMakeLists.txt
integration_tests/print_arr_02.f90
src/libasr/pass/pass_utils.h

https://github.com/lfortran/lfortran/issues/1138#issuecomment-1366343971

ASR PASS: Fix `print_arr` pass with `SelectCase`

---

integration_tests/CMakeLists.txt
integration_tests/print_03.f90
src/libasr/pass/pass_utils.h
src/libasr/pass/print_arr.cpp

Fix print pass that contain more than one values

---

src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
src/libasr/codegen/llvm_array_utils.h
tests/reference/llvm-array2_derived-ecff8f2.json
tests/reference/llvm-array2_derived-ecff8f2.stdout
tests/reference/llvm-class_03-d370451.json
tests/reference/llvm-class_03-d370451.stdout
tests/reference/llvm-derived_types_01-ca40b30.json
tests/reference/llvm-derived_types_01-ca40b30.stdout

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1388

Generate data only arrays for fixed array members of bindC structs

---

src/bin/example_input.txt

This should help the CI log output

CI: Simplify the example interactive input

---

integration_tests/CMakeLists.txt
integration_tests/functions_13.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-functions_13-3540564.json
tests/reference/asr-functions_13-3540564.stdout

https://github.com/lfortran/lfortran/pull/1109#issuecomment-1369643920

Track ``scan``/``verify`` in function dependencies

---

integration_tests/CMakeLists.txt
integration_tests/associate_02.f90
integration_tests/associate_07.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/ASR.asdl
src/libasr/asr_verify.cpp
tests/reference/asr-associate_02-9b80c4b.json
tests/reference/asr-associate_07-7060bac.json
tests/reference/asr-associate_07-7060bac.stdout
tests/reference/llvm-associate_02-558b0e6.json
tests/tests.toml

https://github.com/lfortran/lfortran/commit/af13b8ae5eb931a0c7b0c988ce64d14c401fd117
https://github.com/lfortran/lfortran/commit/2f082684bd6f2d30a6a0ea904d1741f822046ad6

Implemented `null` and `associated` intrinsic

---

doc/src/asr/asr_nodes/symbol_nodes/symbol.md
integration_tests/CMakeLists.txt
integration_tests/derived_types_12.f90
integration_tests/derived_types_13.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/ASR.asdl
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/class_constructor.cpp
tests/reference/asr-class_01-233a8ad.json
tests/reference/asr-class_01-233a8ad.stdout
tests/reference/asr-class_02-4331b31.json
tests/reference/asr-class_02-4331b31.stdout
tests/reference/asr-derived_types_04-2d77333.json
tests/reference/asr-derived_types_04-2d77333.stdout
tests/reference/asr-derived_types_08-3466b0c.json
tests/reference/asr-derived_types_08-3466b0c.stdout
tests/reference/asr-generic_name_01-3bbd36d.json
tests/reference/asr-generic_name_01-3bbd36d.stdout
tests/reference/asr-kwargs_02-5f7dccf.json
tests/reference/asr-kwargs_02-5f7dccf.stdout

https://github.com/lfortran/lfortran/commit/2cc6460b37b5545676178e4b7f7821356d774f8d
https://github.com/lfortran/lfortran/commit/aaea271d3bc3e826dec456bf5f3776a69d4aaec5
https://github.com/lfortran/lfortran/commit/6aa545c611beb0370b60a084542648d750e195ad

Implement GenericAssignment for DerivedTypes

---

src/bin/lfortran.cpp
src/libasr/pass/pass_manager.h

https://github.com/lcompilers/lpython/pull/1069

Add an option to skip pass

---

integration_tests/functions_14.f90
src/libasr/pass/unused_functions.cpp
tests/reference/llvm-functions_14-f13c087.json
tests/reference/llvm-functions_14-f13c087.stdout
tests/tests.toml

Closes https://github.com/lfortran/lfortran/issues/1164

Avoid removing functions present as argument

---

src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/asr_to_wasm.cpp
tests/reference/llvm-write3-49c0266.json
tests/reference/llvm-write3-49c0266.stderr
tests/reference/llvm-write3-49c0266.stdout
tests/tests.toml
tests/write3.f90

Turn error into warning for unit in write()

---

src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/ASR.asdl
src/libasr/asr_utils.cpp
tests/fn6.f90
tests/reference/asr-fn6-5b1f799.json
tests/reference/asr-fn6-5b1f799.stdout
tests/reference/asr-select_type2-efb8c76.json
tests/reference/asr-select_type2-efb8c76.stdout
tests/reference/asr-select_type_01-fec2d3a.json
tests/reference/asr-select_type_01-fec2d3a.stdout
tests/reference/asr-select_type_02-507a333.json
tests/reference/asr-select_type_02-507a333.stdout
tests/select_type2.f90
tests/tests.toml

https://github.com/lfortran/lfortran/commit/7f94ae266b61ffd5938c3725339be5b015d623cc

Extend ``SelectType`` for intrinsic types in select type cases

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-select_type3-888b0f1.json
tests/reference/asr-select_type3-888b0f1.stdout
tests/select_type3.f90
tests/tests.toml

https://github.com/lfortran/lfortran/commit/50d5ed8a890f7be1f8e4cbcaef602b0f9b62d61d

Fix scope of default class in select type

---

integration_tests/implied_do_loops1.f90
integration_tests/interface_10.f90
integration_tests/interface_11.f90
integration_tests/modules_20.f90
integration_tests/modules_20b.f90
integration_tests/types_09.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/lfortran/semantics/comptime_eval.h
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/pass/class_constructor.cpp
tests/array12.f90
tests/derived_type1.f90
tests/reference/asr-array12-ea199d1.json
tests/reference/asr-array12-ea199d1.stdout
tests/reference/asr-derived_type1-0b4c060.json
tests/reference/asr-derived_type1-0b4c060.stdout
tests/reference/asr-derived_types_11-8524582.json
tests/reference/asr-derived_types_11-8524582.stdout
tests/reference/asr-implied_do_loops1-f5adada.json
tests/reference/asr-implied_do_loops1-f5adada.stdout
tests/reference/asr-interface_10-4001f17.json
tests/reference/asr-interface_10-4001f17.stdout
tests/reference/asr-select_type3-888b0f1.json
tests/reference/asr-select_type3-888b0f1.stdout
tests/reference/ast-types_09-4ca127b.json
tests/reference/ast-types_09-4ca127b.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/commit/1d1eaaca20426785d0126415a382cb1cbeddbd1d, https://github.com/lfortran/lfortran/commit/8369010066567d04ca89aeca860dc852e88e0ac7, https://github.com/lfortran/lfortran/commit/bd4f240db49d292a46c3c3f773c47821dffe6f42, https://github.com/lfortran/lfortran/commit/36ec2030027ec2d26591721d1fcbf359e6bf65a3, https://github.com/lfortran/lfortran/commit/a708951349ac6a31b33305b6a97a864c2e352a15, https://github.com/lfortran/lfortran/commit/8b34b51d444e88cb86092ea3406048a411e97af1, and https://github.com/lfortran/lfortran/commit/4a7e81e7a9a7ed37afc8eef91b3624690697c40e

[STF] Fix some issues in ASR 

---

integration_tests/select_type_02.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/asr_utils.h
tests/reference/asr-modules_24-a9644cf.stderr
tests/reference/asr-select_type_02-507a333.json
tests/reference/asr-select_type_02-507a333.stdout

https://github.com/lfortran/lfortran/commit/5143dd57c638dea6281a7aba586a9627f01c17ea

Fixing select type for imported derived types

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/template_error.f90
tests/reference/asr-template_error-8ad11a2.json
tests/reference/asr-template_error-8ad11a2.stderr
tests/tests.toml

Added type check for function calls in templates

---

.github/workflows/CI.yml

All tests compile and run correctly, bit to bit exact results as GFortran. We test all answers.
Depends on #1227.

CI: Update Minpack (all tests now fully work)

---

src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-program4-eba2b22.json
tests/reference/asr-program4-eba2b22.stderr
tests/reference/asr-save1-8d4fefe.json
tests/reference/asr-save1-8d4fefe.stderr
tests/reference/c-program4-d60edeb.json
tests/reference/c-program4-d60edeb.stderr
tests/reference/cpp-program4-1796cb6.json
tests/reference/cpp-program4-1796cb6.stderr

Change `save` warning messages.

---

src/libasr/compiler_tester/tester.py

Run tests with extra_files in serial

---

src/lfortran/parser/fixedform_tokenizer.cpp
tests/fixed_form/error_stop1.f
tests/fixed_form/error_stop2.f
tests/reference/ast-error_stop1-71e357f.json
tests/reference/ast-error_stop1-71e357f.stdout
tests/reference/ast-error_stop2-2acf6d2.json
tests/reference/ast-error_stop2-2acf6d2.stdout
tests/tests.toml

Fixed-form: tokenize "error stop" correctly

---

integration_tests/CMakeLists.txt
integration_tests/arrays_22.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_llvm.cpp

Fixes https://github.com/lfortran/lfortran/issues/1246, #1265.

Fix compile time array indexing

---

integration_tests/CMakeLists.txt
integration_tests/subroutines_09.f90
src/libasr/asr_utils.cpp
tests/reference/asr-subroutines_09-a7ad086.json
tests/reference/asr-subroutines_09-a7ad086.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/commit/19fe4305ce5321e7e7d218871eb5567a66fe3e26

Fix optional arguments in Call

---

integration_tests/CMakeLists.txt
integration_tests/enum_01.f90
integration_tests/enum_02.f90
integration_tests/enum_02_module.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/serialization.cpp

Implement EnumType in AST to ASR

---

integration_tests/CMakeLists.txt
integration_tests/associate_08.f90
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h

Import the StructType symbol for the Pointer Type

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_47.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/ASR.asdl
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
tests/reference/asr-intrinsics_47-5a350ac.json
tests/reference/asr-intrinsics_47-5a350ac.stdout
tests/tests.toml

Implement all intrinsic function

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/ASR.asdl
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/asr-intrinsics_47-5a350ac.json
tests/reference/asr-intrinsics_47-5a350ac.stdout

https://github.com/lfortran/lfortran/pull/1283#discussion_r1105061948

Rename `All` to `ArrayAll`

---

integration_tests/CMakeLists.txt
integration_tests/functions_15.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-dependency_test_03-0d48615.json
tests/reference/asr-dependency_test_03-0d48615.stdout
tests/reference/asr-functions_15-c4640a1.json
tests/reference/asr-functions_15-c4640a1.stdout
tests/reference/asr-intrinsics_39-5bf3f79.json
tests/reference/asr-intrinsics_39-5bf3f79.stdout
tests/tests.toml

8728172dcb3471bbb437e5d3d26a99ed61b56507

Determine the correct index for the function args

---

integration_tests/CMakeLists.txt
integration_tests/functions_16.f90
tests/reference/asr-functions_16-f863e4a.json
tests/reference/asr-functions_16-f863e4a.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/pull/1209

Added test for callbacks in Fortran source code

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_wasm.cpp

towards https://github.com/lfortran/lfortran/issues/1294
```bash
(lf) lfortran$ lfortran integration_tests/template_array_03.f90               
1
2
0
1
(lf) lfortran$ lfortran integration_tests/template_array_03.f90 --backend wasm        
(lf) lfortran$ node a.out.js
1
2
0
1
```

WASM: Support integration_tests/template_array_03.f90

---

integration_tests/array_section_01.f90
src/libasr/pass/implied_do_loops.cpp

Create ArrayBound correctly

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_11.f90
tests/reference/asr-derived_types_11-8524582.json
tests/reference/asr-derived_types_11-8524582.stdout

LLVM: Enable tests

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/do_loop_01.f90
tests/reference/asr-do_loop_01-a27456b.json
tests/reference/asr-do_loop_01-a27456b.stderr
tests/tests.toml

Restrict assignment of do loop variable in do loop body.

---

src/libasr/asr_verify.cpp

Add `visit_ImplicitDeallocate` in asr_verify.cpp

---

doc/src/asr/asr_nodes/expression_nodes/IntrinsicFunction.md
integration_tests/intrinsics_19.f90
src/lfortran/pickle.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/ASR.asdl
src/libasr/CMakeLists.txt
src/libasr/asdl_cpp.py
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function.cpp
src/libasr/pass/intrinsic_function.h
src/libasr/pass/pass_manager.h

Port `log_gamma` to use it, both compile time and runtime.
This PR is a polished git history version of #1045.

Initial implementation of IntrinsicFunction

---

integration_tests/CMakeLists.txt
integration_tests/template_array_04.f90
src/libasr/pass/instantiate_template.cpp
tests/reference/asr-template_array_04-bb5f542.json
tests/reference/asr-template_array_04-bb5f542.stdout
tests/tests.toml

Solved the bug mentioned in #1385.

Added support for SubroutineCall during template instantiation

---

integration_tests/CMakeLists.txt
integration_tests/minpack_02.f90
src/libasr/asdl_cpp.py
src/libasr/asr_utils.h
src/libasr/pass/pass_array_by_data.cpp

https://github.com/lfortran/lfortran/pull/1306
cc: @Shaikh-Ubaid

Support ``visit_Module`` in ``pass_array_by_data.cpp``

---

integration_tests/CMakeLists.txt
integration_tests/arrays_23.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/asr-arrays_23-b542514.json
tests/reference/asr-arrays_23-b542514.stdout
tests/tests.toml

Part of extending #1148 to LLVM

Consider pointer to char - 0 dim as strings

---

integration_tests/CMakeLists.txt
integration_tests/do_loop_01.f90
src/libasr/pass/pass_utils.h

Fix handling of do loops in pass

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/kind1.f90
tests/reference/asr-kind1-50bd091.json
tests/reference/asr-kind1-50bd091.stderr
tests/tests.toml

Add provision to check for incorrect kinds

---

integration_tests/string_10.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
tests/reference/asr-allocate_04-91b8bc0.json
tests/reference/asr-allocate_04-91b8bc0.stdout
tests/reference/asr-allocate_05-36f4b17.json
tests/reference/asr-allocate_05-36f4b17.stdout
tests/reference/asr-arrays_23-b542514.json
tests/reference/asr-arrays_23-b542514.stdout
tests/reference/asr-fn6-5b1f799.json
tests/reference/asr-fn6-5b1f799.stdout
tests/reference/asr-string_10-bf50060.json
tests/reference/asr-string_10-bf50060.stdout
tests/reference/asr-string_12-041f3da.json
tests/reference/asr-string_12-041f3da.stdout
tests/reference/llvm-string_10-ef0078f.json
tests/reference/llvm-string_10-ef0078f.stdout

https://github.com/lcompilers/libasr/issues/11
#1381

Fix StringSection Assignment

---

integration_tests/CMakeLists.txt
integration_tests/do_loop_02.f90
src/libasr/codegen/asr_to_llvm.cpp

Fix handling of exit statements in nested do loop

---

src/bin/lfortran.cpp
src/libasr/pass/pass_manager.h
src/libasr/utils.h

https://github.com/lfortran/lfortran/pull/1400#issuecomment-1462880075
https://github.com/lfortran/lfortran/issues/416

Add verbose option for passes

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/intent1.f90
tests/reference/asr-intent1-4eee5ff.json
tests/reference/asr-intent1-4eee5ff.stderr
tests/tests.toml

Prevent modification of value in `INTENT(IN)`

---

integration_tests/arrays_op_12.f90
src/libasr/pass/array_op.cpp
tests/reference/llvm-arrays_op_6-ae38631.json
tests/reference/llvm-arrays_op_6-ae38631.stdout

Closes https://github.com/lfortran/lfortran/issues/1364

Improve conversion of function calls returning arrays to subroutine calls

---

src/libasr/asdl_cpp.py
src/libasr/pass/pass_utils.h

https://github.com/lfortran/lfortran/pull/1401#discussion_r1128311837

``ASRPassBaseWalkVisitor`` for calling ``transform_stmts`` over any body

---

integration_tests/CMakeLists.txt
integration_tests/complex_11.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-complex_07-8d914e3.json
tests/reference/asr-complex_07-8d914e3.stdout

Allow creating `ComplexConstant_` in `DCMPLX` for compile time arguments

---

integration_tests/CMakeLists.txt
integration_tests/expr_13.f90
run_tests.py
src/bin/lfortran.cpp
src/libasr/pass/pass_manager.h
src/libasr/utils.h
tests/reference/asr-expr_13-09211b8.json
tests/reference/asr-expr_13-09211b8.stdout
tests/reference/pass_flip_sign-expr_13-76c967c.json
tests/reference/pass_flip_sign-expr_13-76c967c.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/issues/1384#issuecomment-1451365193

Add an option to use cumulative ASR pass

---

integration_tests/CMakeLists.txt
integration_tests/array_op_01.f90
src/libasr/pass/array_op.cpp

Handle variables of zero rank in `array_op` while create_do_loop

---

run_tests.py
src/bin/lfortran.cpp
src/lfortran/pickle.cpp
src/lfortran/pickle.h
tests/modules_10.f90
tests/reference/asr_json-modules_10-2facf2f.json
tests/reference/asr_json-modules_10-2facf2f.stdout
tests/tests.toml

fixes https://github.com/lfortran/lfortran/issues/724#issuecomment-1477545143

ASR: Support modules in ASR to JSON

---

integration_tests/CMakeLists.txt
integration_tests/arrays_op_13.f90
integration_tests/associate_09.f90
integration_tests/string_20.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/array_op.cpp
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
tests/reference/asr-array12-ea199d1.json
tests/reference/asr-array12-ea199d1.stdout
tests/reference/asr-modules_15b-5be0f8a.json
tests/reference/asr-modules_15b-5be0f8a.stdout

Fix char with star dimension and array_op pass

---

integration_tests/nbody.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/CMakeLists.txt
src/libasr/pass/class_constructor.cpp
src/libasr/pass/implied_do_loops.cpp
src/libasr/pass/init_expr.cpp
src/libasr/pass/init_expr.h
src/libasr/pass/pass_manager.h
src/libasr/pass/pass_utils.h
tests/reference/llvm-implicit_interface_04-9b6786e.json
tests/reference/llvm-implicit_interface_04-9b6786e.stdout

https://github.com/lfortran/lfortran/issues/1313

Improve ``implied_do_loops.cpp`` by using replacer APIs

---

integration_tests/CMakeLists.txt
integration_tests/array_op_02.f90
integration_tests/array_op_03.f90
src/libasr/pass/array_op.cpp

Add provision for operand with zero rank in replace_UnaryOp, array_op

---

integration_tests/CMakeLists.txt
integration_tests/modules_38.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/llvm-modules_38-8886f9a.json
tests/reference/llvm-modules_38-8886f9a.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/commit/2cd04dd99772c691713de89fb5ed73962121ae4f

Use ExternalSymbol to refer enum members

---

integration_tests/CMakeLists.txt
integration_tests/modules_35.f90
run_tests.py
tests/reference/asr-modules_35-2a0333c.json
tests/reference/asr-modules_35-2a0333c.stdout
tests/reference/pass_implied_do_loops-modules_35-fde962b.json
tests/reference/pass_implied_do_loops-modules_35-fde962b.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/commit/38afa5e1db8737d776138fcc9d6956da79607473

Added test for ``implied_do_loops`` pass

---

integration_tests/CMakeLists.txt
integration_tests/pass_array_by_data_02.f90
src/libasr/asr_utils.h
src/libasr/pass/pass_array_by_data.cpp

Add provision to pass function as an argument in pass_array_by_data

---

ci/environment.yml

See https://github.com/jupyter/nbconvert/issues/1970

CI: Avoid broken nbconvert

---

src/libasr/codegen/asr_to_wasm.cpp
src/libasr/codegen/wasm_assembler.h

fixes https://fortran-lang.discourse.group/t/lfortran-installation-problem/5439
Also towards https://github.com/lcompilers/lpython/issues/1485

WASM: Minor Improvement

---

CMakeLists.txt
build_to_wasm.sh
ci/upload_lfortran_wasm.sh
src/bin/CMakeLists.txt
src/lfortran/parser/parser_stype.h
src/libasr/alloc.h

fixes https://github.com/lfortran/lfortran/issues/1240
Also towards https://github.com/lcompilers/lpython/issues/1485

WASM: Use release build

---

tests/reference/asr-associate_08-291d395.json
tests/reference/asr-associate_08-291d395.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/pull/1290#issuecomment-1428757432

Test ASR for associate_08.f90

---

integration_tests/CMakeLists.txt
integration_tests/pass_array_by_data_03.f90
src/libasr/pass/pass_array_by_data.cpp

Replace SubroutineCall when any of its arguments are updated in pass_array_by_data

---

src/libasr/codegen/asr_to_llvm.cpp

LLVM: Remove nested globals logic

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/do_zero_increment.f90
tests/reference/asr-do_zero_increment-0b0300c.json
tests/reference/asr-do_zero_increment-0b0300c.stderr
tests/tests.toml

Restrict step size 0 in for loop

---

src/libasr/pass/nested_vars.cpp

Add docs for `pass_nested_vars`

---

.gitignore
integration_tests/CMakeLists.txt
integration_tests/modules_26.f90
integration_tests/pass_array_by_data_02.f90
integration_tests/pass_array_by_data_04.f90
integration_tests/pass_array_by_data_05.f90
integration_tests/pass_array_by_data_06.f90
src/libasr/asr_utils.h
src/libasr/pass/pass_array_by_data.cpp
src/libasr/pass/pass_utils.h
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_39-eb4201f.json
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_39-eb4201f.stdout

Closes https://github.com/lfortran/lfortran/issues/1510
Closes https://github.com/lfortran/lfortran/issues/1518
https://github.com/lfortran/lfortran/pull/1517

Fixes for ``pass_array_by_data`` ASR pass

---

src/libasr/codegen/asr_to_wasm.cpp
src/libasr/codegen/wasm_assembler.h
src/libasr/codegen/wasm_decoder.h
src/libasr/codegen/wasm_to_wat.cpp
src/libasr/codegen/wasm_to_x64.cpp
src/libasr/codegen/wasm_to_x86.cpp
src/libasr/codegen/wasm_utils.h
src/libasr/wasm_instructions_visitor.py

There are considerable changes in https://github.com/lcompilers/lpython/pull/1675. As it is merged, I think it is better to sync the wasm backend early to avoid potential conflicts in future.

WASM: Sync files from LPython

---

src/libasr/codegen/asr_to_wasm.cpp

fixes https://github.com/lfortran/lfortran/pull/1542#issuecomment-1503720987, https://github.com/lfortran/lfortran/pull/1542#issuecomment-1503736965.

WASM: Allocate SymbolFuncInfo on stack

---

integration_tests/CMakeLists.txt
integration_tests/arrays_13.f90
integration_tests/arrays_15.f90
integration_tests/nested_09.f90
integration_tests/nested_10.f90
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/nested_vars.cpp
tests/reference/llvm-arrays_13-8ff7d44.json
tests/reference/llvm-arrays_13-8ff7d44.stdout

Closes https://github.com/lfortran/lfortran/issues/1529

Use pointer type for creating auxiliary variables for nested arrays

---

integration_tests/CMakeLists.txt
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/errors/implicit_typing1.f90
tests/errors/implicit_typing2.f90
tests/errors/implicit_typing3.f90
tests/reference/asr-implicit_typing1-e105a73.json
tests/reference/asr-implicit_typing1-e105a73.stderr
tests/reference/asr-implicit_typing2-440714f.json
tests/reference/asr-implicit_typing2-440714f.stderr
tests/reference/asr-implicit_typing3-96744b9.json
tests/reference/asr-implicit_typing3-96744b9.stderr
tests/tests.toml

[1499#comment](https://github.com/lfortran/lfortran/issues/1499#issuecomment-1504633084)
[1499#comment](https://github.com/lfortran/lfortran/issues/1499#issuecomment-1504627621)

Fix implicit none handling

---

integration_tests/CMakeLists.txt
integration_tests/associate_10.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
src/libasr/codegen/llvm_array_utils.h

Fixes https://github.com/lfortran/lfortran/issues/1555
N.B. - https://github.com/lfortran/lfortran/pull/1567#issuecomment-1512903251

Associating data only array with descriptor based arrays

---

doc/src/asr/asr_nodes/symbol_nodes/Block.md

fixes https://github.com/lfortran/lfortran/pull/1550#issuecomment-1510032727

DOC: Add Block(Call) vs Function(Call)

---

integration_tests/CMakeLists.txt
integration_tests/allocated_01.f90
integration_tests/allocated_02.f90
integration_tests/allocated_03.f90
src/libasr/codegen/asr_to_llvm.cpp

Fixes #1353.
Once this gets merged, I will open up PR to implement `deallocate`. We already have implementation for that (ImplicitDeallocate).

Implement intrinsic `allocated`

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-where2-43d5853.json
tests/reference/asr-where2-43d5853.stdout
tests/tests.toml
tests/where2.f90

#1312
```fortran
subroutine where_1
implicit none
integer a(10)
integer b(10)
where (a > b) 
a = 1
endwhere
end subroutine
program main
call where_1
end program
```
<details>
<summary>ASR</summary>
<p>
```clojure
(TranslationUnit
(SymbolTable
1
{
main:
(Program
(SymbolTable
3
{
})
main
[]
[(SubroutineCall
1 where_1
()
[]
()
)]
),
where_1:
(Function
(SymbolTable
2
{
a:
(Variable
2
a
[]
Local
()
()
Default
(Integer 4 [((IntegerConstant 1 (Integer 4 []))
(IntegerConstant 10 (Integer 4 [])))])
Source
Public
Required
.false.
),
b:
(Variable
2
b
[]
Local
()
()
Default
(Integer 4 [((IntegerConstant 1 (Integer 4 []))
(IntegerConstant 10 (Integer 4 [])))])
Source
Public
Required
.false.
)
})
where_1
(FunctionType
[]
()
Source
Implementation
()
.false.
.false.
.false.
.false.
.false.
[]
[]
.false. …
```

Implement `where`

---

src/libasr/codegen/asr_to_llvm.cpp

Last commit has a TODO list how to fix:
```console
$ lfortran  procedure_01.f90     
code generation error: FunctionType not implemented
--> procedure_01.f90:5:5 - 7:17
|
5 |        integer function fn(n)
|        ^^^^^^^^^^^^^^^^^^^^^^...
...
|
7 |        end function
| ...^^^^^^^^^^^^^^^^^ 
```
The ASR for this test is already correct (contains `type_declaration` correctly populated in `Variable`).
This should fix one bug. There might be more, we'll see.

Implementation of `procedure(fn) :: x` (IV)

---

integration_tests/CMakeLists.txt
integration_tests/procedure_02.f90
integration_tests/procedure_03.f90
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/codegen/asr_to_llvm.cpp

Get function callbacks working for subroutines

---

integration_tests/CMakeLists.txt
integration_tests/procedure_03.f90
integration_tests/procedure_04.f90
src/libasr/ASR.asdl
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/asr-implicit_interface5-4e61259.json
tests/reference/asr-implicit_interface5-4e61259.stdout
tests/reference/asr-implicit_typing2-4e0bae9.json
tests/reference/asr-implicit_typing2-4e0bae9.stdout
tests/reference/asr-modules_15b-5be0f8a.json
tests/reference/asr-modules_15b-5be0f8a.stdout
tests/reference/asr-redeclaration1-0adcc00.json
tests/reference/asr-redeclaration1-0adcc00.stdout
tests/reference/asr-template_array_03-81d3ec4.json
tests/reference/asr-template_array_03-81d3ec4.stdout

Fix nested callbacks

---

.gitignore
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/pass/intrinsic_function_registry.h
tests/reference/asr-array_size_01-d0f0677.json
tests/reference/asr-array_size_01-d0f0677.stderr
tests/reference/asr-derived_types_20-5724ce0.json
tests/reference/asr-derived_types_20-5724ce0.stdout
tests/reference/pass_class_constructor-derived_types_20-4eab69b.json
tests/reference/pass_class_constructor-derived_types_20-4eab69b.stdout

https://github.com/lfortran/lfortran/pull/1577#discussion_r1176861633

Enhancements in ``IntrinsicFunction``

---

src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/asdl_cpp.py
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/pass/pass_utils.h
tests/reference/asr-fn5-93e28ec.json
tests/reference/asr-fn5-93e28ec.stdout
tests/reference/asr-functions_06-0cedd98.json
tests/reference/asr-functions_06-0cedd98.stdout
tests/reference/asr-functions_12-19076ea.json
tests/reference/asr-functions_12-19076ea.stdout
tests/reference/asr-string1-489c714.json
tests/reference/asr-string1-489c714.stdout
tests/reference/asr-string2-ccc8ec4.json
tests/reference/asr-string2-ccc8ec4.stdout
tests/reference/asr-string_17-f3c0915.json
tests/reference/asr-string_17-f3c0915.stdout
tests/reference/asr-string_19-5592188.json
tests/reference/asr-string_19-5592188.stdout

https://github.com/lfortran/lfortran/pull/1309

Ensure that ``FunctionType`` isn't tied to any scope

---

integration_tests/CMakeLists.txt
integration_tests/types_18.f90
integration_tests/types_19.f90
src/lfortran/semantics/ast_common_visitor.h

fixes https://github.com/lfortran/lfortran/issues/1628.

ASR: Support Declaration attribute as type

---

src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/lfortran/tests/test_llvm.cpp
src/libasr/asr_scopes.cpp

fixes https://github.com/lfortran/lfortran/issues/1588.

Fix importing modules in interactive mode

---

integration_tests/CMakeLists.txt
integration_tests/where_05.f90
src/libasr/pass/where.cpp

Remove hard coded types in pass `where`

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/assign_01.f90
tests/reference/asr-assign_01-a6dc017.json
tests/reference/asr-assign_01-a6dc017.stderr
tests/tests.toml

fixes #1639, https://github.com/lfortran/lfortran/issues/433

Print Error when assigning to constant variables

---

.gitignore
src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/utils.cpp
src/lfortran/utils.h
src/libasr/utils.h
src/libasr/utils2.cpp

towards https://github.com/lfortran/lfortran/issues/324.
This is a experimental PR.

Initial ASTR Visualization

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
src/libasr/codegen/llvm_array_utils.h
src/libasr/pass/array_op.cpp
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/pass_manager.h
tests/reference/asr-array_bound_1-b0c2255.json
tests/reference/asr-array_bound_1-b0c2255.stdout
tests/reference/asr-arrays_07-354d066.json
tests/reference/asr-arrays_07-354d066.stdout
tests/reference/asr-bindc2-62a702e.json
tests/reference/asr-bindc2-62a702e.stdout
tests/reference/asr-intrinsics_37-8df004d.json
tests/reference/asr-intrinsics_37-8df004d.stdout
tests/reference/llvm-allocate_02-7f23768.json
tests/reference/llvm-allocate_02-7f23768.stdout
tests/reference/llvm-arrays_07-e8d0d0e.json
tests/reference/llvm-arrays_07-e8d0d0e.stdout
tests/reference/llvm-arrays_op_6-ae38631.json
tests/reference/llvm-arrays_op_6-ae38631.stdout

Work in progress. Not ready for review.

Handle `ArraySection` in ``array_op.cpp`` ASR pass

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_21.f90
src/libasr/asr_verify.cpp
src/libasr/codegen/asr_to_llvm.cpp

https://github.com/lfortran/lfortran/commit/8e872c86787f19f37468b856ac8679137c04bdd0
https://github.com/lfortran/lfortran/commit/62772aeca53b0783d957805cb9eff177ae4114ac
https://github.com/lfortran/lfortran/commit/04e62d8790be3ef5a4cea746bfd0edf68295de9a

LLVM: Fix cyclic struct dependencies

---

integration_tests/CMakeLists.txt
integration_tests/modules_44.f90
integration_tests/modules_44_module.f90
src/libasr/pass/pass_array_by_data.cpp
tests/reference/asr-modules_44-ec0baa3.json
tests/reference/asr-modules_44-ec0baa3.stdout
tests/reference/pass_pass_array_by_data-modules_44-cd82150.json
tests/reference/pass_pass_array_by_data-modules_44-cd82150.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/commit/2dc1ef5931226f9ce90260d411972d89ad362715

Add ``ExternalSymbol`` in ``pass_array_by_data`` ASR pass

---

integration_tests/CMakeLists.txt
integration_tests/modules_43.f90
src/libasr/pass/array_op.cpp
tests/reference/asr-modules_43-d01691f.json
tests/reference/asr-modules_43-d01691f.stdout
tests/reference/pass_array_op-modules_43-6930881.json
tests/reference/pass_array_op-modules_43-6930881.stdout
tests/tests.toml

https://github.com/lfortran/lfortran/commit/4e1e7591cf50c181468fa180c3f5f422f652dcaa

Fix for ``array_op`` pass

---

src/lfortran/parser/preprocessor.re

fixes https://github.com/lfortran/lfortran/issues/1669

Support include path in C Preprocessor

---

integration_tests/modules_15.f90
integration_tests/modules_15b.f90
src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
tests/reference/asr-modules_15b-09f8335.json
tests/reference/asr-modules_15b-09f8335.stdout

Add missing variables to iso_c_binding

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_verify.cpp
tests/external_01.f90
tests/reference/asr-external_01-6754623.json
tests/reference/asr-external_01-6754623.stdout
tests/tests.toml

fixes https://github.com/lfortran/lfortran/issues/1668

Fix external dummy arg

---

integration_tests/modules_15b.f90
tests/reference/asr-modules_15b-09f8335.json

Test c_float_complex and c_double_complex

---

integration_tests/CMakeLists.txt
integration_tests/class_06.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

Allow "pass" to have no arguments

---

src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/errors/derived_type_01.f90
tests/errors/derived_type_02.f90
tests/errors/derived_type_03.f90
tests/errors/derived_type_04.f90
tests/reference/asr-derived_type_01-d480dc4.json
tests/reference/asr-derived_type_01-d480dc4.stderr
tests/reference/asr-derived_type_02-3e6510f.json
tests/reference/asr-derived_type_02-3e6510f.stderr
tests/reference/asr-derived_type_03-a9e3c15.json
tests/reference/asr-derived_type_03-a9e3c15.stderr
tests/reference/asr-derived_type_04-0a4f388.json
tests/reference/asr-derived_type_04-0a4f388.stderr
tests/tests.toml

fixes https://github.com/lfortran/lfortran/issues/1687

Catch type mismatch in Passed Object Dummy Argument

---

integration_tests/CMakeLists.txt
integration_tests/double_complex_01.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

Add DOUBLE COMPLEX as return type in function

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/array_01.f90
tests/errors/array_02.f90
tests/reference/asr-array_01-6a86c32.json
tests/reference/asr-array_01-6a86c32.stderr
tests/reference/asr-array_02-f2b519f.json
tests/reference/asr-array_02-f2b519f.stderr
tests/tests.toml

Catch error for empty array constructor

---

integration_tests/intrinsics_46.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
tests/reference/asr-array12-cb81afc.json
tests/reference/asr-array12-cb81afc.stdout
tests/reference/asr-bindc1-6cc9005.json
tests/reference/asr-bindc1-6cc9005.stdout
tests/reference/asr-bindc2-62a702e.json
tests/reference/asr-bindc2-62a702e.stdout
tests/reference/asr-bindc3-91bce68.json
tests/reference/asr-bindc3-91bce68.stdout
tests/reference/asr-bindc4-22df995.json
tests/reference/asr-bindc4-22df995.stdout
tests/reference/asr-intrinsics_46-0ef4d7a.json
tests/reference/asr-intrinsics_46-0ef4d7a.stdout
tests/reference/asr-modules_15b-09f8335.json
tests/reference/asr-modules_15b-09f8335.stdout
tests/reference/asr-string1-f6332d9.json
tests/reference/asr-string1-f6332d9.stdout
tests/reference/asr-string2-3425046.json
tests/reference/asr-string2-3425046.stdout
tests/reference/llvm-bindc1-345b88c.json
tests/reference/llvm-bindc1-345b88c.stdout
tests/reference/llvm-bindc3-d064ff7.json
tests/reference/llvm-bindc3-d064ff7.stdout
tests/reference/llvm-intrinsics_03-0771f1b.json
tests/reference/llvm-intrinsics_03-0771f1b.stdout
tests/reference/llvm-intrinsics_06-15c0eef.json
tests/reference/llvm-intrinsics_06-15c0eef.stdout

https://github.com/lfortran/lfortran/commit/e5af76236b485b77d9e7c8b9a9bdb012f4cf3ae6

ASR: Implement char node

---

src/lfortran/parser/parser.yy
tests/derived_types_09.f90
tests/reference/ast-derived_types_09-0e83add.json
tests/reference/ast-derived_types_09-0e83add.stdout
tests/tests.toml

fixes https://github.com/lfortran/lfortran/issues/1707

Parse empty derived type with contains

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_50.f90
integration_tests/intrinsics_51.f90
integration_tests/minpack_02.f90
integration_tests/nested_07.f90
integration_tests/nested_08.f90
integration_tests/print_arr_03.f90
integration_tests/write_02.f90
src/libasr/asdl_cpp.py
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
src/libasr/pass/array_op.cpp
src/libasr/pass/implied_do_loops.cpp
src/libasr/pass/init_expr.cpp
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
src/runtime/pure/lfortran_intrinsic_math2.f90
tests/reference/pass_init_expr-array13-db4fb0f.json
tests/reference/pass_init_expr-array13-db4fb0f.stdout
tests/reference/pass_pass_array_by_data-modules_44-cd82150.json
tests/reference/pass_pass_array_by_data-modules_44-cd82150.stdout
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_39-906d6cb.json
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_39-906d6cb.stdout

https://github.com/lfortran/lfortran/commit/6736d16d476651a997dfc37575a0470b98144593
https://github.com/lfortran/lfortran/commit/f411c43acbf79f03c3058e7bc1acc7134cba3062
https://github.com/lfortran/lfortran/commit/1e65a01f327cf5fb1240e777be0c01ceb9e07a7d
Closes https://github.com/lfortran/lfortran/pull/1638
Closes https://github.com/lfortran/lfortran/issues/1405

Enhanced support for ``ArrayConstant``

---

integration_tests/CMakeLists.txt
integration_tests/class_07.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/errors/derived_type_05.f90
tests/reference/asr-derived_type_01-d480dc4.json
tests/reference/asr-derived_type_01-d480dc4.stderr
tests/reference/asr-derived_type_05-3836aa5.json
tests/reference/asr-derived_type_05-3836aa5.stderr
tests/tests.toml

fixes https://github.com/lfortran/lfortran/issues/1712

Support nopass attribute in procedure declaration

---

integration_tests/file_01.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c

https://github.com/lfortran/lfortran/commit/03bf99a3ca0243bd864a30765c77152b8e4f7e95

LLVM: Implement rewind

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_13.f90
integration_tests/operator_overloading_06.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/ASR.asdl
src/libasr/CMakeLists.txt
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_utils.cpp
src/libasr/pass/pass_manager.h
src/libasr/pass/print_struct_type.cpp
src/libasr/pass/print_struct_type.h
src/libasr/pass/subroutine_from_function.cpp

Fixes https://github.com/lfortran/lfortran/issues/1697
Not ready for review.

Overloading binary and unary operators

---

integration_tests/bindc4.f90
integration_tests/string_04.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/asr-array12-cb81afc.json
tests/reference/asr-array12-cb81afc.stdout
tests/reference/asr-bindc4-22df995.json
tests/reference/asr-bindc4-22df995.stdout
tests/reference/asr-string2-3425046.json
tests/reference/asr-string2-3425046.stdout
tests/reference/asr-string_04-2ebc0e6.json
tests/reference/asr-string_04-2ebc0e6.stdout
tests/reference/llvm-string_04-2d3483c.json
tests/reference/llvm-string_04-2d3483c.stdout

https://github.com/lfortran/lfortran/commit/4711107dae148f53457ed189e8d4bb41e7a3f29d
https://github.com/lfortran/lfortran/commit/808e5d6bd940cf270643dfb50aa4ab579756822c

LLVM: Implement c_associated 

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_22.f90
integration_tests/struct_01.f90
src/libasr/codegen/asr_to_llvm.cpp

Add provision to declare non `c_ptr` structs

---

.github/workflows/CI.yml
.gitignore
integration_tests/CMakeLists.txt
integration_tests/run_tests.py
src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp

CI: Add C tests

---

integration_tests/CMakeLists.txt
integration_tests/data_06.f90
integration_tests/data_07.f90
src/lfortran/semantics/ast_common_visitor.h

Towards implementation of `BLOCK_DATA`

Allow struct instance member in data stmts

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_llvm.cpp

Fill in m_dims correctly in Release mode

---

integration_tests/CMakeLists.txt
integration_tests/product_01.f90
integration_tests/product_02.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function_registry.h

fixes https://github.com/lfortran/lfortran/issues/1696

IntrinsicRegistry: Support product() intrinsic

---

src/lfortran/semantics/ast_common_visitor.h
tests/external3.f90
tests/reference/asr-external3-2aafcb3.json
tests/reference/asr-external3-2aafcb3.stdout
tests/tests.toml

Handle update of external symbol not present in current scope

---

.github/workflows/CI.yml
src/lfortran/tests/CMakeLists.txt

CI: Fix node tests failure

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_23.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
tests/reference/asr-intrinsics_36-1cb3d03.json
tests/reference/asr-intrinsics_36-1cb3d03.stdout

fixes https://github.com/lfortran/lfortran/issues/1673

Fix module dependency for intrinsic function return type

---

integration_tests/CMakeLists.txt
integration_tests/doloop_10.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h

fixes https://github.com/lfortran/lfortran/issues/1807

ASR: Support loop variable implicit cast

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_53.f90

Add a test for repeat()

---

integration_tests/intrinsics_46.f90
src/lfortran/semantics/comptime_eval.h
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/asr-intrinsics_46-0ef4d7a.json
tests/reference/asr-intrinsics_46-0ef4d7a.stdout

Implement achar

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_24.f90
src/libasr/codegen/asr_to_llvm.cpp

https://github.com/lfortran/lfortran/commit/01cc2e6a793aa8d8131e2ba440500238cab4ecdc

Create a polymorphic class variable for StructInstanceMember

---

integration_tests/bindc4.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-bindc4-22df995.json
tests/reference/asr-bindc4-22df995.stdout

Support c_null_ptr

---

integration_tests/CMakeLists.txt
integration_tests/file_02.f90
src/lfortran/pickle.cpp
src/lfortran/semantics/ast_common_visitor.h
src/libasr/ASR.asdl
src/libasr/asdl_cpp.py
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/intrinsic_function_registry.h

https://github.com/lfortran/lfortran/commit/b3d97ce95d78a25d33c7c6e6dfe5945b96fc29d7

Initial IntrinsicImpureFunction implementation

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_17b.f90
src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_c_cpp.h

Get log(x) working in the C backend

---

integration_tests/CMakeLists.txt
integration_tests/external_03.f90
integration_tests/external_04.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-external_01-6754623.json
tests/reference/asr-external_01-6754623.stdout

Add provision to handle `external` declaration with non null vartype

---

integration_tests/CMakeLists.txt
integration_tests/data_implied_do_01.f90
integration_tests/data_implied_do_02.f90
integration_tests/data_implied_do_03.f90
integration_tests/data_implied_do_04.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-data_implied_do_01-737a2b1.json
tests/reference/asr-data_implied_do_01-737a2b1.stdout
tests/tests.toml

Implement `DataImpliedDo`

---

integration_tests/CMakeLists.txt
integration_tests/save_01.f90
integration_tests/save_02.f90
integration_tests/save_03.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/reference/asr-save2-63c8bcc.json
tests/reference/asr-save2-63c8bcc.stderr
tests/reference/asr-save2-63c8bcc.stdout
tests/reference/asr-save_03-1103dd0.json
tests/reference/asr-save_03-1103dd0.stdout
tests/save2.f90
tests/tests.toml

Implement `SAVE` attribute

---

integration_tests/CMakeLists.txt
integration_tests/format_05.f90

This adds a GFortran test.
See https://github.com/lfortran/lfortran/issues/1848 to implement this feature in LFortran.

Add a test for internal write to a string

---

.github/workflows/CI.yml

Use the sources from fortran-lang directly.

CI: rework Minpack tests

---

.github/workflows/CI.yml

CI: make bash fail on errors

---

src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function_registry.h

This gets ASR->ASR passes fixed for fastgpt and gets it to LLVM.

Fix pointer handling in ASR passes

---

integration_tests/CMakeLists.txt
integration_tests/arrays_24.f90

Fix https://github.com/lfortran/lfortran/issues/840

add test for array with expression type

---

integration_tests/CMakeLists.txt
integration_tests/string_22.f90
src/libasr/codegen/llvm_utils.cpp

Implement derived types with allocatable strings

---

integration_tests/CMakeLists.txt
integration_tests/entry_01.f90
integration_tests/entry_02.f90
integration_tests/entry_03.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
tests/entry1.f90
tests/reference/asr-entry1-3075e81.json
tests/reference/asr-entry1-3075e81.stdout
tests/reference/asr-entry_02-b8ee2e2.json
tests/reference/asr-entry_02-b8ee2e2.stdout
tests/reference/ast-entry1-5b02d99.json
tests/reference/ast-entry1-5b02d99.stdout
tests/reference/ast_f90-entry1-5f14c6d.json
tests/reference/ast_f90-entry1-5f14c6d.stdout
tests/tests.toml

Implement `visit_Entry()`

---

integration_tests/CMakeLists.txt
integration_tests/arrays_26.f90
src/libasr/codegen/asr_to_llvm.cpp

The problem was in not going past Allocatable in visit_ArrayItem, a one line fix.
Add a test for allocatable array of structs, which was failing in main, but works in this PR.

Fix "der_type_name.size() != 0"

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/subroutine1.f90
tests/reference/asr-subroutine1-b6656b7.json
tests/reference/asr-subroutine1-b6656b7.stderr
tests/tests.toml

Fix https://github.com/lfortran/lfortran/issues/1878

throw error while assigning to a subroutine

---

integration_tests/CMakeLists.txt
integration_tests/string_23.f90
src/libasr/codegen/asr_to_llvm.cpp

Fix a problem with string slices

---

integration_tests/CMakeLists.txt
integration_tests/string_24.f90

For now LFortran doesn't work yet.
Towards https://github.com/lfortran/lfortran/issues/1884.

Add a test for array of string slice

---

integration_tests/CMakeLists.txt
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-associate_08-570ac7d.json
tests/reference/asr-associate_08-570ac7d.stdout

ASR: Fix struct array members

---

.github/workflows/CI.yml
ci/test.xsh
integration_tests/CMakeLists.txt
integration_tests/run_tests.py

fixes https://github.com/lfortran/lfortran/issues/1825

Tests fix race failure

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/subroutine2.f90
tests/reference/asr-subroutine2-2e9b84b.json
tests/reference/asr-subroutine2-2e9b84b.stderr
tests/tests.toml

Fix https://github.com/lfortran/lfortran/issues/1877

calling a subroutine as a function should give an error message

---

src/libasr/asr_utils.h

Fix https://github.com/lfortran/lfortran/issues/1620

replaced string comparison with node comparison

---

src/libasr/asr_verify.cpp

fixes https://github.com/lfortran/lfortran/issues/1881

Verify: Add a check for order of Allocatable and Array

---

integration_tests/CMakeLists.txt
integration_tests/arrays_intrin_03.f90
integration_tests/arrays_intrin_04.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/intrinsic_function_registry.h
src/libasr/runtime/lfortran_intrinsics.c

fixes https://github.com/lfortran/lfortran/issues/1863

Support maxval() intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/arrays_27.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/reference/asr-implicit8-03c7a90.json
tests/reference/asr-implicit8-03c7a90.stderr

Allow implicit array dimensions declaration

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/subroutine3.f90
tests/reference/asr-subroutine3-9c6f5d1.json
tests/reference/asr-subroutine3-9c6f5d1.stderr
tests/tests.toml

Fix https://github.com/lfortran/lfortran/issues/1899

Throw error on calling size() on a subroutine 

---

integration_tests/CMakeLists.txt
src/bin/lfortran.cpp
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_scopes.cpp
src/libasr/pass/intrinsic_function_registry.h

Implementation of min0() using IntrinsicFunction 

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_55.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_function_registry.h
tests/reference/asr-derived_types_07-c5a29e3.json
tests/reference/asr-derived_types_07-c5a29e3.stdout
tests/reference/asr-intrinsics_28-7703b7d.json
tests/reference/asr-intrinsics_28-7703b7d.stdout
tests/reference/asr-template_triple-54fa485.json
tests/reference/asr-template_triple-54fa485.stdout

Fixes #1896. I am not sure if this is the correct fix.

Modify `min0` to implement `min`

---

integration_tests/CMakeLists.txt
integration_tests/arrays_25.f90
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/llvm-arrays_25-5b87ac7.json
tests/reference/llvm-arrays_25-5b87ac7.stdout
tests/tests.toml

Test added.
Towards https://github.com/lfortran/lfortran/issues/1874.

Add the extra load for allocatable

---

integration_tests/CMakeLists.txt
integration_tests/c_ptr_01.f90

Add test for `c_ptr` casting

---

src/bin/lfortran.cpp
src/libasr/utils.h

Add `--implicit-argument-casting` flag

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_56.f90
integration_tests/intrinsics_57.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/pass/array_op.cpp
src/libasr/pass/intrinsic_function_registry.h
src/libasr/serialization.cpp
src/runtime/pure/lfortran_intrinsic_math2.f90
tests/reference/asr-fn5-3d75eb7.json
tests/reference/asr-fn5-3d75eb7.stdout
tests/reference/asr-intrinsics_32-86443d8.json
tests/reference/asr-intrinsics_32-86443d8.stdout
tests/reference/asr-intrinsics_37-8df004d.json
tests/reference/asr-intrinsics_37-8df004d.stdout
tests/reference/asr-string_19-d880475.json
tests/reference/asr-string_19-d880475.stdout
tests/reference/pass_flip_sign-expr_13-e24d940.json
tests/reference/pass_flip_sign-expr_13-e24d940.stdout
tests/reference/pass_flip_sign-flip_sign-16b288c.json
tests/reference/pass_flip_sign-flip_sign-16b288c.stdout

https://github.com/lfortran/lfortran/commit/4dc0c5253142c93455236a3577b7ec8e5ded57f8

Implement ``merge`` intrinsic as ``IntrinsicFunction``

---

integration_tests/CMakeLists.txt
integration_tests/expr_14.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-modules_07-7f671c1.json
tests/reference/asr-modules_07-7f671c1.stdout

fixes https://github.com/lfortran/lfortran/issues/1948

Fix updating variable access and presence provided by attributes

---

integration_tests/CMakeLists.txt
integration_tests/entry_04.f90
src/lfortran/semantics/ast_body_visitor.cpp

Fixes https://github.com/lfortran/lfortran/issues/1955.

Add provision to handle function return type in entry function

---

integration_tests/CMakeLists.txt
integration_tests/arrayitem_01.f90

Fix: https://github.com/lfortran/lfortran/issues/1734#issuecomment-1626886324

Test added for accessing ArrayItem from struct instance member

---

integration_tests/CMakeLists.txt
integration_tests/common_12.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h

Handle common block variables in statement function

---

.github/workflows/CI.yml

CI: Test SciPy ASR with every commit 

---

src/libasr/diagnostics.cpp

Fixes: https://github.com/lfortran/lfortran/issues/1978

Fixed grammatical mistake in note

---

integration_tests/CMakeLists.txt
integration_tests/entry_07.f90
src/lfortran/semantics/ast_body_visitor.cpp

Add provision to update `intentType` when variable is arg of entry function

---

.github/workflows/CI.yml

Test fastGPT with the full separate compilation, just a few workarounds left as described at https://github.com/lfortran/lfortran/issues/1997.

CI fastGPT: bugs fixed remove some workarounds

---

.github/workflows/CI.yml

CI fastGPT: Remove the declaration workaround

---

src/bin/lfortran.cpp
src/libasr/utils.h

Add `-Wl,-rpath` option

---

src/bin/lfortran.cpp

https://github.com/lfortran/lfortran/pull/2005#issuecomment-1645478069

Fix `-Wl,-rpath`

---

.github/workflows/CI.yml

This just tests the latest status (https://github.com/lfortran/lfortran/issues/1997#issuecomment-1645648561) by the CI, to ensure we do not regress.

CI fastGPT: compile to a binary

---

.github/workflows/CI.yml

CI: build all tests for fastGPT

---

.github/workflows/CI.yml

CI: fastGPT all executables now compile

---

examples/chat_01.f90
src/libasr/runtime/lfortran_intrinsics.c

```bash
$ cat examples/chat_01.f90     
program chat_01
implicit none
integer :: choice
character(len = 10) :: name
print *, "Please enter your name:"
read(*, *) name
print *, "---------WELCOME TO CHAT_01---------"
do while (.true.)
print *, "Please pick an option:"
print *, "1) Say Hi"
print *, "2) Say Hello"
print *, "3) Say Good Morning"
print *, "4) Say Happy Birthday"
print *, "5) Exit the chat"
print *, ""
print *, "Enter your choice:"
read(*, *) choice
if (choice == 1) then
print *, "Hi "//name
else if (choice == 2) then
print *, "Hello "//name
else if (choice == 3) then
print *, "Good Morning "//name
else if (choice == 4) then
print *, "Happy Birthday "//name//"!"
else if (choice == 5) then
exit
else
print *, "Wrong choice. Try again..."
end if
print *, ""
end do
end program
$ …
```

Support standard IO

---

ci/test.xsh
integration_tests/CMakeLists.txt
integration_tests/file_01.f90
integration_tests/file_02.f90
integration_tests/file_03.f90
integration_tests/file_03_data.txt
integration_tests/flush_01.f90
src/libasr/runtime/lfortran_intrinsics.c

fixes https://github.com/lfortran/lfortran/issues/1931

Refactor, Improve and Fix File read

---

src/libasr/runtime/lfortran_intrinsics.c

Closes https://github.com/lfortran/lfortran/issues/2029
I get the following now,
```zsh
(fastgpt) 14:04:10:~/lfortran_project/fastGPT % ./test_basic_input
Loading the model...
Error in opening the file!
model.dat: No such file or directory
```

Generalise unit numbers to file pointer by using a simple array for mapping

---

.github/workflows/CI.yml

It will print:
```
Loading the model...
done. Time:.686E+01s, Model file version: 1
Model parameters:
n_vocab = 50257
n_ctx   =  1024
n_embd  =   768
n_layer =    12
n_head  =    12
Input text
Alan Turing theorized that computers would one day become very powerful, but even he could not imagine
Encoding: tokenizing input text into tokens (currently slow)...
done. Time:.375E+00s
Input parameters:
n_seq                =  19
n_tokens_to_generate =  20
Input tokens:
36235 39141 18765 1143 326 9061 561 530 1110 1716 845 3665 11 475 772 339 714 407 5967
```
The input tokens are computed correctly.

CI: run fastGPT until Input tokens

---

integration_tests/CMakeLists.txt
integration_tests/arrays_29.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/pass_manager.h
tests/reference/llvm-allocate_01-573b1f6.json
tests/reference/llvm-allocate_01-573b1f6.stdout
tests/reference/llvm-arrays_25-5b87ac7.json
tests/reference/llvm-arrays_25-5b87ac7.stdout

Offset data pointer in ``ArrayPhysicalCast``

---

.github/workflows/CI.yml

Cache is disabled, but it now works.

CI: fastGPT now fully runs

---

integration_tests/CMakeLists.txt
integration_tests/do_loop_03.f90
integration_tests/do_loop_04.f90
integration_tests/run_tests.py
integration_tests/specfun_01.f90
run_tests.py
src/bin/lfortran.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/do_loops.cpp
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
src/libasr/utils.h

Continuation of #2079. Fixes #2067, Fixes #2078.

Implement `--use-loop-variable-after-loop`

---

integration_tests/do_loop_04.f90
src/libasr/pass/pass_utils.cpp

Apply code review for implementation `--use-loop-variable-after-loop`

---

src/bin/lfortran.cpp

fixes https://github.com/lfortran/lfortran/issues/2092

Fix linking for Fortran77 files

---

integration_tests/warning_realstar.f90
src/lfortran/parser/parser.yy
src/lfortran/parser/semantics.h
tests/reference/asr-implicit10-23a5156.json
tests/reference/asr-implicit10-23a5156.stderr
tests/reference/asr-implicit10-f531a25.json
tests/reference/asr-implicit10-f531a25.stderr
tests/reference/ast-types_13-76138b5.json
tests/reference/ast-types_13-76138b5.stderr
tests/reference/ast_f90-types_13-ddae644.json
tests/reference/ast_f90-types_13-ddae644.stderr
tests/reference/c-expr_11-8e5ae80.json
tests/reference/c-expr_11-8e5ae80.stderr
tests/reference/julia-expr_11-ab53b8f.json
tests/reference/julia-expr_11-ab53b8f.stderr

Fixes: https://github.com/lfortran/lfortran/issues/1680

Emit a warning for "real*4 x"

---

integration_tests/warning_characterstar.f90
src/lfortran/parser/parser.yy
src/lfortran/parser/semantics.h
tests/reference/ast-types_13-76138b5.json
tests/reference/ast-types_13-76138b5.stderr
tests/reference/ast_f90-types_13-ddae644.json
tests/reference/ast_f90-types_13-ddae644.stderr

Fixes: https://github.com/lfortran/lfortran/issues/2102

Emit a warning for "character*4 x" 

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_63.f90
src/libasr/pass/array_op.cpp

Closes https://github.com/lfortran/lfortran/issues/2089

Fix incorrect nesting of loop for `array = scalar` assignment

---

integration_tests/CMakeLists.txt
integration_tests/data_09.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h

Improve DATA statement handling in case of array assignment to equal values

---

.github/workflows/CI.yml

CI: Test `scipy/special/specfun` 

---

integration_tests/CMakeLists.txt
integration_tests/cpp_pre_01.f90
integration_tests/cpp_pre_02.f90
src/lfortran/parser/preprocessor.re

towards https://github.com/lfortran/lfortran/pull/2113#discussion_r1287436872.

Minor suggestion, fix for CPP Preprocessor comment handling

---

src/libasr/pass/intrinsic_function_registry.h

Continuation of https://github.com/lfortran/lfortran/pull/2110. I forgot to push this changes there.

Simplify instantiate_maxloc handling

---

integration_tests/CMakeLists.txt
integration_tests/dabs_01.f90
src/runtime/impure/lfortran_intrinsic_math.f90
src/runtime/pure/lfortran_intrinsic_math2.f90
tests/reference/llvm-intrinsics_03-0771f1b.json
tests/reference/llvm-intrinsics_03-0771f1b.stdout

Refactor implementation of `dabs`

---

.github/workflows/CI.yml

Now, we have majority of tests passing the main trouble we have right now is:

CI: Test latest commit after refactoring tests 

---

integration_tests/CMakeLists.txt
integration_tests/arrays_31.f90
src/libasr/codegen/asr_to_llvm.cpp

LLVM: Fix init expression for fixed size array

---

integration_tests/CMakeLists.txt
integration_tests/run_tests.py
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/implied_do_loops.cpp

fixes https://github.com/lfortran/lfortran/issues/2150
continuation of https://github.com/lfortran/lfortran/pull/2116.

LLVM: Fix implicit args test case

---

integration_tests/CMakeLists.txt
integration_tests/run_tests.py

fixes https://github.com/lfortran/lfortran/issues/2152

Refactor: CMake Integration tests

---

integration_tests/CMakeLists.txt
integration_tests/implicit_argument_casting_02.f90

towards https://github.com/lfortran/lfortran/pull/2151#pullrequestreview-1575653341

TEST: Add another test for --implicit-argument-casting

---

src/lfortran/parser/parser.yy
src/lfortran/parser/semantics.h
src/lfortran/tests/test_parse.cpp
tests/errors/end_program_name.f90
tests/reference/asr-end_program_name-2d38a01.json
tests/reference/asr-end_program_name-2d38a01.stderr
tests/reference/asr_json-special_chars_json-70bba3a.json
tests/reference/asr_json-special_chars_json-70bba3a.stdout
tests/reference/ast_json-special_chars_json-219ee5a.json
tests/reference/ast_json-special_chars_json-219ee5a.stdout
tests/tests.toml

Fixes: https://github.com/lfortran/lfortran/issues/2179

Error if end program name does not match program name

---

integration_tests/CMakeLists.txt
integration_tests/data_10.f90
src/lfortran/semantics/ast_common_visitor.h

Towards #1991, I am not sure why that case is not working. It is generating LLVM.

Refactor DataStmt Implementation

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_27.f90
src/lfortran/semantics/ast_body_visitor.cpp

Handle derived types in statement function.

---

src/libasr/pass/fma.cpp
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
tests/reference/pass_fma-fma-071ac0d.json
tests/reference/pass_fma-fma-071ac0d.stdout

https://github.com/lcompilers/lpython/pull/2282

Update FMA pass to use intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_64.f90
src/libasr/ASR.asdl
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/asr_to_wasm.cpp
src/libasr/pass/intrinsic_function_registry.h

Fixes #2187. Fixes #2139. Fixes #2131.

Introduce and Implement `RealCopySign`

---

integration_tests/CMakeLists.txt
integration_tests/nested_vars1.f90
integration_tests/nested_vars2.f90
src/libasr/codegen/asr_to_wasm.cpp

towards https://github.com/lcompilers/lpython/issues/2288, https://github.com/lcompilers/lpython/issues/1485

WASM: Support for Nested functions II

---

integration_tests/CMakeLists.txt
integration_tests/nested_vars3.f90
src/libasr/pass/nested_vars.cpp

Support constants in pass nested vars

---

integration_tests/CMakeLists.txt
integration_tests/expr_15.f90
src/libasr/codegen/asr_to_c_cpp.h

fixes https://github.com/lfortran/lfortran/issues/2224
related https://github.com/lcompilers/lpython/pull/2289

C: Fix for intent_inout args

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_66.f90
src/libasr/codegen/asr_to_llvm.cpp

Handle array item in `RealSignCopy`

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_c_cpp.h

towards https://github.com/lcompilers/lpython/issues/2288

C: Support nested functions

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/array_op.cpp
src/libasr/pass/nested_vars.cpp

fixes https://github.com/lfortran/lfortran/issues/2219

Refactor: Improvements

---

integration_tests/CMakeLists.txt
integration_tests/end_name_match.f90
src/lfortran/parser/semantics.h

Fixes: https://github.com/lfortran/lfortran/issues/2189

Case insensitive comparison for subroutine and program name checking

---

.github/workflows/CI.yml

Reverted: https://github.com/certik/scipy/commit/305f9fa2d45395e747e6add1592435a487eabeaf

CI: Test latest commit after reverting working commits

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/arrays_op_19.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/array_op.cpp
tests/reference/llvm-allocate_02-7f23768.json
tests/reference/llvm-allocate_02-7f23768.stdout
tests/reference/llvm-arrays_06-538e67d.json
tests/reference/llvm-arrays_06-538e67d.stdout
tests/reference/llvm-arrays_25-5b87ac7.json
tests/reference/llvm-arrays_25-5b87ac7.stdout
tests/reference/llvm-arrays_op_1-636d572.json
tests/reference/llvm-arrays_op_1-636d572.stdout
tests/reference/llvm-arrays_op_5-8426b5a.json
tests/reference/llvm-arrays_op_5-8426b5a.stdout
tests/reference/llvm-arrays_op_7-aeeda6d.json
tests/reference/llvm-arrays_op_7-aeeda6d.stdout
tests/reference/llvm-modules_36-53c9a79.json
tests/reference/llvm-modules_36-53c9a79.stdout
tests/reference/llvm-string_04-2d3483c.json
tests/reference/llvm-string_04-2d3483c.stdout
tests/reference/pass_array_op-modules_43-6930881.json
tests/reference/pass_array_op-modules_43-6930881.stdout

https://github.com/certik/fastGPT/pull/55#issuecomment-1684217628

Fix intrinsic applied for array slices and stored in array slice targets

---

.github/workflows/CI.yml

Converts `generate`:
* https://github.com/certik/fastGPT/commit/73ffdbc963bfeab4b1002916326fa133c004e159

CI fastGPT: convert more subroutines to functions

---

.github/workflows/CI.yml
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/llvm-string_04-2d3483c.json
tests/reference/llvm-string_04-2d3483c.stdout

towards https://github.com/lfortran/lfortran/issues/1953#issuecomment-1694403926

LLVM: Fix allocatable strings

---

src/libasr/codegen/asr_to_llvm.cpp
tests/reference/llvm-string_04-2d3483c.json
tests/reference/llvm-string_04-2d3483c.stdout

fixes https://github.com/lfortran/lfortran/pull/2254#discussion_r1306572792

LLVM: Use memset for allocatable strings

---

.github/workflows/CI.yml

towards https://github.com/lfortran/lfortran/pull/2254#discussion_r1306571610

CI: Rename job to 'Third party code compilation'

---

.github/workflows/CI.yml

Last issue we have is: https://github.com/lfortran/lfortran/issues/2198

CI: Remove manual mangling fixes, uncomment all tests

---

integration_tests/CMakeLists.txt
integration_tests/expr_16.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-parameter1-1a7ed3b.json
tests/reference/asr-parameter1-1a7ed3b.stdout

fixes https://github.com/lfortran/lfortran/issues/2279

Support attribute parameter specified later

---

integration_tests/CMakeLists.txt
integration_tests/nan_handling_01.f90
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/llvm-arrays_04_func-2aa342e.json
tests/reference/llvm-arrays_04_func-2aa342e.stdout
tests/reference/llvm-associate_04-97f4e70.json
tests/reference/llvm-associate_04-97f4e70.stdout
tests/reference/llvm-intrinsics_02-404e16e.json
tests/reference/llvm-intrinsics_02-404e16e.stdout
tests/reference/llvm-intrinsics_03-0771f1b.json
tests/reference/llvm-intrinsics_03-0771f1b.stdout
tests/reference/llvm-types_06-6f66d2c.json
tests/reference/llvm-types_06-6f66d2c.stdout

Fixes: https://github.com/lfortran/lfortran/pull/2268#issuecomment-1696854990

Perform ordered comparison for real numbers

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/array_05.f90
tests/errors/array_06.f90
tests/reference/asr-array_03-a79d86f.json
tests/reference/asr-array_03-a79d86f.stderr
tests/reference/asr-array_05-321b5d3.json
tests/reference/asr-array_05-321b5d3.stderr
tests/reference/asr-array_06-5f5f77a.json
tests/reference/asr-array_06-5f5f77a.stderr
tests/tests.toml

Throw error for the rank mismatch in array reference

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/arrays_op_20.f90
integration_tests/arrays_op_21.f90
src/libasr/asr_utils.h
src/libasr/pass/array_op.cpp
tests/reference/llvm-arrays_op_6-ae38631.json
tests/reference/llvm-arrays_op_6-ae38631.stdout

Closes https://github.com/lfortran/lfortran/issues/2253

Fix for functions returning allocatable arrays

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/arrays_op_22.f90
integration_tests/arrays_op_23.f90
src/libasr/asr_utils.h
src/libasr/pass/array_op.cpp
src/libasr/pass/pass_utils.cpp
tests/reference/llvm-allocate_02-7f23768.json
tests/reference/llvm-allocate_02-7f23768.stdout

Closes https://github.com/lfortran/lfortran/issues/2295

Fix issues with function call chaining

---

.github/workflows/CI.yml

Test both Debug and Release builds.

CI: Get fastGPT working with --fast

---

.github/workflows/CI.yml

Refer: https://github.com/lfortran/lfortran/pull/2285#issuecomment-1703164445

CI: Merge scipy build of special and minpack and test independently

---

integration_tests/CMakeLists.txt
integration_tests/file_09.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c

Towards: https://github.com/lfortran/lfortran/issues/2324

Support character array in read function

---

.github/workflows/CI.yml
src/libasr/codegen/asr_to_llvm.cpp

This is tested by fastGPT in Release mode, enabled at the CI now.

Handle PointerToDataArray in ArrayAll

---

.github/workflows/CI.yml

CI fastGPT: test minimal workarounds

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/file_11.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/comptime_eval.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
src/runtime/CMakeLists.txt
src/runtime/custom/lfortran_intrinsic_custom.f90

fixes https://github.com/lfortran/lfortran/issues/2311

Support newunit in open()

---

integration_tests/CMakeLists.txt
integration_tests/allocate_14.f90
src/libasr/pass/implied_do_loops.cpp

https://github.com/certik/fastGPT/pull/61#issuecomment-1705222526

Allocate LHS for the Array constant

---

.gitignore
src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/pickle.cpp
src/lfortran/pickle.h
src/lfortran/semantics/ast_to_asr.cpp
src/lfortran/tests/test_llvm.cpp
src/lfortran/tests/test_serialization.cpp
src/libasr/CMakeLists.txt
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/asr_to_wasm.cpp
src/libasr/pass/pass_manager.h
src/libasr/pickle.cpp
src/libasr/pickle.h
src/libasr/utils.h

Fixes: https://github.com/lfortran/lfortran/issues/2194

Print ASR after applying each pass using the `--verbose` option

---

integration_tests/CMakeLists.txt
integration_tests/file_10.f90
integration_tests/file_10_data.txt
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h

https://github.com/certik/fastGPT/tree/lf28run

Initial support for formatted FileRead()

---

src/libasr/pass/unique_symbols.cpp

mangle intrinsic function with hash of asr owner

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/flip_sign.cpp
src/libasr/pass/fma.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
src/libasr/utils.h
tests/reference/pass_flip_sign-expr_13-e24d940.json
tests/reference/pass_flip_sign-expr_13-e24d940.stdout
tests/reference/pass_flip_sign-flip_sign-16b288c.json
tests/reference/pass_flip_sign-flip_sign-16b288c.stdout

https://github.com/lcompilers/lpython/pull/2301

PASS: Update flip_sign to use Intrinsic function

---

src/lfortran/semantics/ast_to_asr.cpp
src/libasr/pass/pass_manager.h

Towards: https://github.com/lfortran/lfortran/issues/2350

Improvements to --dump-all-passes,

---

integration_tests/CMakeLists.txt
integration_tests/optional_03.f90
src/libasr/asr_utils.h
src/libasr/pass/transform_optional_argument_functions.cpp

Closes https://github.com/lfortran/lfortran/issues/2323

Handle derived types and arrays as optional arguments

---

integration_tests/CMakeLists.txt
integration_tests/file_12.f90

towards https://github.com/lfortran/lfortran/pull/2333#issuecomment-1706917295

TEST: Add fail test for iostat

---

src/runtime/CMakeLists.txt

Install the lfortran_intrinsic_custom module

---

.github/workflows/CI.yml
.github/workflows/Clean-Cache-CI.yml

Refer: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

CI: setup to clean cache for a pr once it is closed

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_69.f90
src/libasr/pass/intrinsic_function_registry.h
tests/errors/intrinsics1.f90
tests/reference/asr-intrinsics1-8ebce32.json
tests/reference/asr-intrinsics1-8ebce32.stderr
tests/tests.toml

Towards: https://github.com/lfortran/lfortran/issues/2208

Add Radix to IntrinsicScalarFunction

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_70.f90
integration_tests/template_array_03.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function_registry.h
tests/reference/asr-template_array_03-b7f9799.json
tests/reference/asr-template_array_03-b7f9799.stdout

Fixes #2343. Refer: https://github.com/lfortran/lfortran/pull/2346#discussion_r1315235434

Implement intrinsic `AINT`

---

src/libasr/pass/intrinsic_function.cpp

related https://github.com/lcompilers/lpython/pull/2315

Remove seemingly unneeded code

---

src/libasr/pass/unique_symbols.cpp

Fixes #2347.
```fortran
subroutine a()
integer :: x
logical qsmall
qsmall(x) = .NOT. (sum .GE. abstol .AND. x .GE. eps*sum)
end
```
> % lfortran a.f90 --show-asr --pass=unique_symbols --implicit-typing --all-mangling --mangle-underscore
<details>
<summary> ASR </summary>
```clojure
(TranslationUnit
(SymbolTable
1
{
a_:
(Function
(SymbolTable
2
{
qsmall_a_:
(Function
(SymbolTable
3
{
abstol_a_:
(Variable
3
abstol_a_
[]
Local
()
()
Default
(Real 4)
()
Source
Public
Required
.false.
),
eps_a_:
(Variable
3
eps_a_
[]
Local
()
()
Default
(Real 4)
()
Source
Public
Required
.false.
),
qsmall_return_var_name_a_:
(Variable
3
qsmall_return_var_name_a_
[]
ReturnVar
()
()
Default
(Logical 4)
()
Source
Public
Required
.false.
),
sum_a_:
(Variable
3
sum_a_
[]
Local
()
()
Default
(Real 4)
()
Source …
```

Append parent name for nested functions while mangling

---

.github/workflows/CI.yml

CI: Merge scipy build of special, minpack and fitpack and test independently

---

src/lfortran/semantics/ast_to_asr.cpp

Fixes: https://github.com/lfortran/lfortran/issues/2350

Do not remove the generated asr files

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_70.f90
integration_tests/intrinsics_73.f90
src/libasr/pass/intrinsic_function_registry.h

Fixes: https://github.com/lfortran/lfortran/issues/2409

Add intrinisc `sngl` conversion

---

.github/workflows/CI.yml
.gitignore
integration_tests/CMakeLists.txt
integration_tests/run_tests.py
run_tests.py
src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/fortran_evaluator.h
src/libasr/CMakeLists.txt
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/codegen/asr_to_fortran.h
tests/reference/fortran-expr5-3a279bb.json
tests/reference/fortran-expr5-3a279bb.stdout
tests/tests.toml

Towards: https://github.com/lfortran/lfortran/issues/2410

Initial ASR to Fortran implementation

---

integration_tests/CMakeLists.txt
integration_tests/expr_17.f90
src/libasr/codegen/asr_to_llvm.cpp

fixes https://github.com/lfortran/lfortran/issues/2436

LLVM: Fix fetching kind when type is pointer to array

---

pixi.toml

Run with:
pixi run build
pixi run test

Add initial pixi.toml

---

src/libasr/runtime/lfortran_intrinsics.c

This PR resolves all ```Invalid read/write```  issues encountered while running the ```lfortran_intrinsic.cpp``` file under `Valgrind`.
It is a very useful tool. Though it took some time to learn and understand its output, it pointed out a lot of bugs with regards to memory management.
The CI should not segfault anymore.
Checked integration tests and made sure the output is same as gfortran.

Resolve CI Failure in StringFormat backend

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_74.f90
src/libasr/codegen/asr_to_c_cpp.h

fixes https://github.com/lfortran/lfortran/issues/2459
related https://github.com/lcompilers/lpython/pull/2329

Matmul_01: C: Fix passing arr elements by ref to `random_number()`

---

grammar/AST.asdl
src/lfortran/parser/parser.cpp
src/lfortran/parser/parser.yy
src/lfortran/parser/semantics.h
src/lfortran/parser/tokenizer.re
tests/pragma2.f90
tests/reference/ast-pragma2-dd5bd9b.json
tests/reference/ast-pragma2-dd5bd9b.stdout
tests/tests.toml

Initial work to parse simd

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/legacy_array_sections_01.f90
src/bin/lfortran.cpp
src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/utils.h
tests/reference/llvm-legacy_array_sections_01-2515c0f.json
tests/reference/llvm-legacy_array_sections_01-2515c0f.stderr
tests/tests.toml

Introduce and implement `--legacy-array-sections`

---

integration_tests/CMakeLists.txt
integration_tests/arrays_33.f90
src/libasr/codegen/asr_to_llvm.cpp

For https://github.com/lfortran/lfortran/issues/2386#issuecomment-1727456250

Use LLVM values for dimensions in ``fill_array_details``

---

integration_tests/CMakeLists.txt
integration_tests/pass_array_by_data_07.f90
src/libasr/pass/pass_array_by_data.cpp

Towards, https://github.com/lfortran/lfortran/issues/2386#issuecomment-1725895676

Replace imported callback arguments in `pass_array_by_data` correctly

---

integration_tests/CMakeLists.txt
integration_tests/cmake_minimal_test_01.f90
src/lfortran/semantics/ast_common_visitor.h

Fix CMake test failure

---

integration_tests/CMakeLists.txt
integration_tests/arrays_34.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_utils.cpp
tests/reference/llvm-arrays_07-e8d0d0e.json
tests/reference/llvm-arrays_07-e8d0d0e.stdout
tests/reference/llvm-arrays_13-8ff7d44.json
tests/reference/llvm-arrays_13-8ff7d44.stdout

Closes https://github.com/lfortran/lfortran/issues/2472

Treat ``pointer`` arrays same as ``allocatables`` when it comes to allocation

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_28.f90
src/libasr/asr_utils.h
src/libasr/pass/array_op.cpp
src/libasr/pass/pass_utils.cpp
src/libasr/pass/subroutine_from_function.cpp

fixes https://github.com/lfortran/lfortran/issues/2437
related https://github.com/lcompilers/lpython/pull/2334

Dftatom: Fix assignment to array struct instance member

---

.github/workflows/CI.yml

towards https://github.com/lfortran/lfortran/issues/2386

CI: Dftatom: Use latest lf9 branch

---

integration_tests/CMakeLists.txt
integration_tests/write_05.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/print_arr.cpp
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
tests/reference/llvm-write3-49c0266.json
tests/reference/llvm-write3-49c0266.stderr

Fixes: https://github.com/lfortran/lfortran/issues/2491

feat: [LLVM] Implement writing an integer to the string

---

integration_tests/CMakeLists.txt
integration_tests/file_14.f90
src/libasr/codegen/asr_to_llvm.cpp

Fixes: https://github.com/lfortran/lfortran/issues/2462

[LLVM] Support pointer types in read function

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.cpp
src/libasr/pass/array_op.cpp
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/nested_vars.cpp
src/libasr/pass/pass_utils.cpp
tests/reference/asr-allocate_02-3c0d7c8.json
tests/reference/asr-allocate_02-3c0d7c8.stdout
tests/reference/asr-arrays_elemental_15-c7c15ca.json
tests/reference/asr-arrays_elemental_15-c7c15ca.stdout
tests/reference/asr-arrays_op_1-f8b9cb0.json
tests/reference/asr-arrays_op_1-f8b9cb0.stdout
tests/reference/asr-arrays_op_5-9ff5901.json
tests/reference/asr-arrays_op_5-9ff5901.stdout
tests/reference/asr-associate_05-4641244.json
tests/reference/asr-associate_05-4641244.stdout
tests/reference/asr-intrinsics_37-8df004d.json
tests/reference/asr-intrinsics_37-8df004d.stdout
tests/reference/asr-where_03-a34eed8.json
tests/reference/asr-where_03-a34eed8.stdout
tests/reference/asr-where_04-a7fce45.json
tests/reference/asr-where_04-a7fce45.stdout
tests/reference/pass_where-where_03-00685f9.json
tests/reference/pass_where-where_03-00685f9.stdout
tests/reference/pass_where-where_04-2ee4397.json
tests/reference/pass_where-where_04-2ee4397.stdout

Closes https://github.com/lfortran/lfortran/issues/2503

Implement ``ArrayBroadcast`` for ``BinOp`` nodes

---

run_tests.py
src/bin/lfortran.cpp
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/utils.h
tests/reference/asr_ignore_pragma-pragma2-ba96e35.json
tests/reference/asr_ignore_pragma-pragma2-ba96e35.stdout
tests/tests.toml

Fixes https://github.com/lfortran/lfortran/issues/2496

Introduce and implement `--ignore-pragma`

---

src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/pass/array_op.cpp
tests/reference/c-pragma2-a14de52.json
tests/reference/c-pragma2-a14de52.stdout
tests/tests.toml

Handle SIMD in generate_array_decl

---

integration_tests/CMakeLists.txt
integration_tests/ip_01.f90
src/lfortran/semantics/ast_common_visitor.h

Fix to_lower problem in visit_Num

---

integration_tests/CMakeLists.txt
integration_tests/shifta_01.f90
integration_tests/shifta_02.f90
src/lfortran/semantics/ast_common_visitor.h

Implement `shifta` using BinOp

---

integration_tests/CMakeLists.txt
integration_tests/equivalence_01.f90
integration_tests/equivalence_02.f90
integration_tests/equivalence_03.f90
integration_tests/equivalence_04.f90
integration_tests/equivalence_05.f90
integration_tests/equivalence_06.f90
integration_tests/equivalence_07.f90

Reference: https://github.com/lfortran/lfortran/issues/2523

Tests for `equivalence` added

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_79.f90
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function_registry.h

Implement intrinsic `Trailz`

---

integration_tests/CMakeLists.txt
src/libasr/pass/inline_function_calls.cpp
src/libasr/pass/pass_manager.h

https://github.com/lfortran/lfortran/issues/2063

Fix bugs in ``inline_function_calls`` ASR pass

---

integration_tests/CMakeLists.txt
integration_tests/min_01.f90

Reference: https://github.com/lfortran/lfortran/pull/2499#issuecomment-1743563739

Add tests for `min`, `min0`, `min1`, `amin0`, `amin1`, `dmin1`

---

.github/workflows/CI.yml
CMakeLists.txt
src/runtime/legacy/CMakeLists.txt

Fixes https://github.com/lfortran/lfortran/issues/2096

Add soname to runtime library

---

.github/workflows/CI.yml
ci/environment_linux_llvm16.yml
src/libasr/codegen/KaleidoscopeJIT.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/evaluator.cpp
src/libasr/codegen/llvm_utils.cpp

fixes https://github.com/lfortran/lfortran/issues/1507

Support building with LLVM 16

---

integration_tests/CMakeLists.txt
integration_tests/goto_gototarget_return_01.f90
src/libasr/codegen/asr_to_fortran.cpp

[ASR->Fortran] Minor fixes, implement goto, gototarget, return.

---

integration_tests/CMakeLists.txt
integration_tests/array_section_02.f90
src/libasr/pass/subroutine_from_function.cpp

Closes https://github.com/lfortran/lfortran/issues/2439

Handle ``ArraySection`` in variable dimension

---

integration_tests/CMakeLists.txt
integration_tests/string_25.f90
src/libasr/codegen/asr_to_fortran.cpp

~*Note: this should be reviewed and merged after #2593 is landed because we'll need the `StringConcat` function in this PR (I tested it locally, and all tests are passing).*~
Thank you!

[asr->fortran] implement visit_StringCompare & visit_StringChr

---

.github/workflows/CI.yml
ci/upload_tarball_to_release.sh

fixes https://github.com/lfortran/lfortran/issues/2590

CI: Support uploading tarball to release

---

.github/workflows/CI.yml

Dftatom update: https://github.com/czgdp1807/dftatom/commits/lf26

[dftatom] Enable more iterations for conv_lda

---

.github/workflows/CI.yml

dftatom commits https://github.com/certik/dftatom/compare/master...lf27.

dftatom: Run conv_rlda

---

.github/workflows/CI.yml

Reference: https://github.com/lfortran/lfortran/issues/2405#issuecomment-1750355871
- https://github.com/certik/scipy/commits/merge_specfun_minpack_fitpack_amos

CI: Merge scipy build of specfun, minpack, fitpack and amos and test independently

---

integration_tests/CMakeLists.txt
integration_tests/save_04.f90
src/libasr/codegen/asr_to_fortran.cpp

[ASR->Fortran] Add support for save

---

.github/workflows/CI.yml

Reference: https://github.com/lfortran/lfortran/pull/2565#pullrequestreview-1673649436
- https://github.com/certik/scipy/commits/merge_specfun_minpack_fitpack_amos_mach

CI: test scipy/special/mach 

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/derived_types_29.f90
src/libasr/codegen/asr_to_llvm.cpp

fixes https://github.com/lfortran/lfortran/issues/2561

Fix out args for struct mem

---

integration_tests/CMakeLists.txt
integration_tests/string_18.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h

Trim trailing whitespace before string comparision

---

src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/runtime/lfortran_intrinsics.c
tests/reference/llvm-init_values-b1d5491.json
tests/reference/llvm-init_values-b1d5491.stdout
tests/reference/llvm-modules_38-8886f9a.json
tests/reference/llvm-modules_38-8886f9a.stdout
tests/reference/llvm-string_01-deb8ed3.json
tests/reference/llvm-string_01-deb8ed3.stdout
tests/reference/llvm-string_02-c37e098.json
tests/reference/llvm-string_02-c37e098.stdout
tests/reference/llvm-string_03-2cd8fec.json
tests/reference/llvm-string_03-2cd8fec.stdout
tests/reference/llvm-string_04-2d3483c.json
tests/reference/llvm-string_04-2d3483c.stdout
tests/reference/llvm-string_10-ef0078f.json
tests/reference/llvm-string_10-ef0078f.stdout
tests/reference/llvm-string_11-e6c763f.json
tests/reference/llvm-string_11-e6c763f.stdout
tests/reference/run-write5-4a89b6b.json
tests/reference/run-write5-4a89b6b.stdout

Fixes: https://github.com/lfortran/lfortran/issues/2618, https://github.com/lfortran/lfortran/issues/2619, and https://github.com/lfortran/lfortran/issues/2620

Refactor: Fix memory leak in strings

---

integration_tests/CMakeLists.txt
integration_tests/functions_18.f90
src/libasr/pass/subroutine_from_function.cpp

fixes https://github.com/lfortran/lfortran/issues/2562

Fix alloc for func ret var in pass_sub_from_fn

---

.github/workflows/CI.yml

https://github.com/czgdp1807/dftatom/commits/lf34

Remove some workarounds in dftatom

---

integration_tests/CMakeLists.txt
integration_tests/entry_12.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/reference/asr-entry1-3075e81.json
tests/reference/asr-entry1-3075e81.stdout
tests/reference/asr-entry2-a9679e0.json
tests/reference/asr-entry2-a9679e0.stdout
tests/reference/asr-entry_02-b8ee2e2.json
tests/reference/asr-entry_02-b8ee2e2.stdout
tests/reference/asr-entry_05-f368f0e.json
tests/reference/asr-entry_05-f368f0e.stdout
tests/reference/asr-entry_06-b57385d.json
tests/reference/asr-entry_06-b57385d.stdout

Fixes #2639. Continuation of #2640

Handle statements after return in entry functions

---

.github/workflows/CI.yml
integration_tests/bin_op_real_01.f90
src/libasr/pass/array_op.cpp

Fixes: https://github.com/lfortran/lfortran/issues/2670

[ASR Pass] Allocate memory for a temporary variable in UnaryOp

---

.github/workflows/CI.yml

https://github.com/czgdp1807/dftatom/commits/lf40

Remove the final workarounds in dftatom

---

integration_tests/CMakeLists.txt
integration_tests/cycle_and_exit5.f90
src/libasr/codegen/asr_to_llvm.cpp

Reverts https://github.com/czgdp1807/dftatom/commit/a73ca412dce71542542b3c1ec3c128e44490e422

Fix ``cycle`` implementation in LLVM backend

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/character_02.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

Fixes: https://github.com/lfortran/lfortran/issues/2700

Refactor: Pass the constant value instead of a Var_t as an argument in the function call

---

integration_tests/CMakeLists.txt
integration_tests/allocate_15.f90
src/libasr/pass/array_op.cpp

Bug: Skip Binop operation on ArraySize node in array_op pass

---

integration_tests/CMakeLists.txt
integration_tests/where_06.f90
src/libasr/pass/where.cpp

Bug: Skip replace_Array in where pass

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_80.f90
src/libasr/pass/pass_array_by_data.cpp
tests/reference/llvm-modules_36-53c9a79.json
tests/reference/llvm-modules_36-53c9a79.stdout
tests/reference/llvm-sum_02-43f30ca.json
tests/reference/llvm-sum_02-43f30ca.stdout

fixes https://github.com/lfortran/lfortran/issues/2688

Fix bug in call parameter for intrinsic sum

---

integration_tests/CMakeLists.txt
integration_tests/equivalence_04.f90
integration_tests/equivalence_05.f90
integration_tests/equivalence_06.f90
integration_tests/equivalence_07.f90
integration_tests/equivalence_08.f90
src/lfortran/semantics/ast_body_visitor.cpp

Fixes https://github.com/lfortran/lfortran/pull/2673#issuecomment-1775177173

Handle equivalence in subroutine, function correctly

---

.gitignore
src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/semantics/ast_to_asr.cpp
src/libasr/pass/pass_manager.h
src/libasr/utils.h

towards https://github.com/lfortran/lfortran/pull/2709#issuecomment-1777679434

Support `--dump-all-passes-fortran` option

---

integration_tests/CMakeLists.txt
integration_tests/implicit_typing_02.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

fixes https://github.com/lfortran/lfortran/issues/2722

Fix bug in implicit typing for function declaration

---

integration_tests/CMakeLists.txt
integration_tests/file_17.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/print_arr.cpp
tests/reference/llvm-write3-49c0266.json
tests/reference/llvm-write3-49c0266.stdout

fixes https://github.com/lfortran/lfortran/issues/2720

Fix writing arrays to file

---

integration_tests/CMakeLists.txt
integration_tests/entry_13.f90
src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-entry1-3075e81.json
tests/reference/asr-entry1-3075e81.stdout
tests/reference/asr-entry2-a9679e0.json
tests/reference/asr-entry2-a9679e0.stdout
tests/reference/asr-entry_02-b8ee2e2.json
tests/reference/asr-entry_02-b8ee2e2.stdout
tests/reference/asr-entry_05-f368f0e.json
tests/reference/asr-entry_05-f368f0e.stdout
tests/reference/asr-entry_06-b57385d.json
tests/reference/asr-entry_06-b57385d.stdout

Fixes https://github.com/lfortran/lfortran/issues/2740. Fixes #2690.

Fix Incorrect handling of statements after return in entry function

---

src/libasr/codegen/asr_to_fortran.cpp

[fortran] use Enum's

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.cpp

Split UpdateArgsVisitor to ArgsVisitor and ArgsReplacer

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_81.f90
src/libasr/codegen/asr_to_llvm.cpp

Closes https://github.com/lfortran/lfortran/issues/2605

Fix `IfExp` implementation by using `CreateSelect`

---

integration_tests/intrinsics_19.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/intrinsic_function_registry.h
src/runtime/impure/lfortran_intrinsic_math.f90
tests/reference/asr-submodule_02-9152b7b.json
tests/reference/asr-submodule_02-9152b7b.stdout

Fixes: https://github.com/lfortran/lfortran/issues/2770

[ASR Pass] Implement `sqrt` and `dsqrt` in IntrinsicScalarFunction

---

src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/asr_utils.cpp
src/libasr/codegen/asr_to_c_cpp.h
tests/reference/asr-arrays_op_1-f8b9cb0.json
tests/reference/asr-arrays_op_1-f8b9cb0.stdout
tests/reference/asr-associate_05-4641244.json
tests/reference/asr-associate_05-4641244.stdout
tests/reference/asr-intrinsics_35-10733ec.json
tests/reference/asr-intrinsics_35-10733ec.stdout
tests/reference/asr-intrinsics_37-8df004d.json
tests/reference/asr-intrinsics_37-8df004d.stdout
tests/reference/asr-pragma2-604d549.json
tests/reference/asr-pragma2-604d549.stdout
tests/reference/asr-where_02-95cf592.json
tests/reference/asr-where_02-95cf592.stdout
tests/reference/asr-where_03-a34eed8.json
tests/reference/asr-where_03-a34eed8.stdout
tests/reference/asr_ignore_pragma-pragma2-ba96e35.json
tests/reference/asr_ignore_pragma-pragma2-ba96e35.stdout
tests/reference/c-pragma2-a14de52.json
tests/reference/c-pragma2-a14de52.stdout
tests/reference/pass_where-where_03-00685f9.json
tests/reference/pass_where-where_03-00685f9.stdout

fixes https://github.com/lfortran/lfortran/issues/2794

Fix constant simd vector code in C 

---

integration_tests/CMakeLists.txt
integration_tests/simd_01.f90

towards https://github.com/lfortran/lfortran/issues/2293#issuecomment-1793640946

TEST: Add simple simd array for C

---

.github/workflows/CI.yml

After #2800 gets merged, this will be good to merge too.
Ref: https://github.com/certik/scipy/commits/merge_special_minpack_minpack2_fitpack_integrate_01

CI: test scipy/integrate/quadpack 

---

src/libasr/pass/array_op.cpp
tests/array15.f90
tests/reference/llvm-allocate_02-7f23768.json
tests/reference/llvm-allocate_02-7f23768.stdout
tests/reference/llvm-arrays_25-5b87ac7.json
tests/reference/llvm-arrays_25-5b87ac7.stdout
tests/reference/llvm-arrays_op_7-aeeda6d.json
tests/reference/llvm-arrays_op_7-aeeda6d.stdout
tests/reference/pass_array_op-array15-079d0cd.json
tests/reference/pass_array_op-array15-079d0cd.stdout
tests/tests.toml

fixes https://github.com/lcompilers/lpython/issues/2403

Fix unused var created by `array_op`

---

src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/fortran_evaluator.h
src/lfortran/semantics/ast_to_asr.cpp
src/lfortran/tests/test_llvm.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/asr_to_llvm.h
src/libasr/codegen/asr_to_wasm.cpp
src/libasr/codegen/asr_to_wasm.h
src/libasr/pass/pass_manager.h

fixes https://github.com/lfortran/lfortran/issues/2744

Make dump passes to dump code and continue other execution

---

.gitignore

fixes https://github.com/lfortran/lfortran/issues/2831

GIT: Ignore generated file liblfortran_runtime.so.version

---

integration_tests/run_tests.py

fixes https://github.com/lfortran/lfortran/issues/2829

Fortran: Fix running normal integration tests

---

.github/workflows/CI.yml
src/bin/lfortran.cpp

fixes https://github.com/lfortran/lfortran/issues/2828

Fortran: Do not link with gfortran

---

CMakeLists.txt
src/libasr/runtime/lfortran_intrinsics.c
src/runtime/legacy/CMakeLists.txt

fixes https://github.com/lfortran/lfortran/issues/2568

CMake: Enable -Werror for lfortran_runtime libs

---

src/libasr/pass/pass_utils.h
src/libasr/pass/replace_symbolic.cpp

Addressing https://github.com/lcompilers/lpython/pull/2419#issuecomment-1807175641

Syncing some libasr changes from LPython

---

src/libasr/pass/instantiate_template.cpp
tests/reference/asr-template_error_05-85bce3c.json
tests/reference/asr-template_error_05-85bce3c.stderr

Fixes: https://github.com/lfortran/lfortran/issues/2852

improve the error message

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/c_utils.h
tests/reference/c-pragma2-a14de52.json
tests/reference/c-pragma2-a14de52.stdout
tests/reference/cpp-array1-d75d040.json
tests/reference/cpp-array1-d75d040.stdout
tests/reference/cpp-array2-9a93c4d.json
tests/reference/cpp-array2-9a93c4d.stdout
tests/reference/cpp-array3-a2f045b.json
tests/reference/cpp-array3-a2f045b.stdout
tests/reference/cpp-arrays_01-4fac8c3.json
tests/reference/cpp-arrays_01-4fac8c3.stdout
tests/reference/cpp-arrays_03_func-3a62608.json
tests/reference/cpp-arrays_03_func-3a62608.stdout
tests/reference/cpp-arrays_04_func-68b1437.json
tests/reference/cpp-arrays_04_func-68b1437.stdout
tests/reference/cpp-kokkos_program2-43a2cc6.json
tests/reference/cpp-kokkos_program2-43a2cc6.stdout

towards https://github.com/lfortran/lfortran/issues/2293
related https://github.com/lcompilers/lpython/pull/2424

SIMD: Support Associate in C

---

integration_tests/CMakeLists.txt
integration_tests/modules_53.f90
src/libasr/codegen/asr_to_llvm.cpp

Fixes https://github.com/lfortran/lfortran/issues/2871

Add support for array inside module

---

integration_tests/CMakeLists.txt
integration_tests/format_10.f90
src/libasr/runtime/lfortran_intrinsics.c

Fixes https://github.com/lfortran/lfortran/issues/2861

Minor fix to handle decimal formatting

---

src/libasr/runtime/lfortran_intrinsics.c

Fixes https://github.com/lfortran/lfortran/issues/2878
```console
(lf) ➜  lfortran git:(fmt4) ✗ gfortran integration_tests/format_10.f90 && ./a.out
3  1.00000000E+00  1.00000000E+00  1.00000000E+00
(lf) ➜  lfortran git:(fmt4) ✗ lfortran integration_tests/format_10.f90           
3  1.00000000E+00  1.00000000E+00  1.00000000E+00
```

Implement `*` and fixes to decimal formatting

---

integration_tests/CMakeLists.txt
integration_tests/save_07.f90
integration_tests/save_08.f90

Add test for `save` on arrays

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_83.f90
src/libasr/asr_utils.h

fixes https://github.com/lfortran/lfortran/issues/2885

Support `kind=` with function call value

---

integration_tests/CMakeLists.txt
integration_tests/modules_54.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

Convert name to lower case while adding generic procedures

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_84.f90
integration_tests/intrinsics_85.f90
src/libasr/pass/intrinsic_function_registry.h

Implement intrinsic `minexponent` and `maxexponent`

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/kind2.f90
tests/reference/asr-kind2-191347a.json
tests/reference/asr-kind2-191347a.stderr
tests/tests.toml

Throw error when `*` passed as kind while variable declartion

---

src/libasr/runtime/lfortran_intrinsics.c
tests/format2.f90
tests/reference/llvm-format2-ed47ddb.json
tests/reference/llvm-format2-ed47ddb.stdout
tests/tests.toml

Fixes: https://github.com/lfortran/lfortran/issues/2854

Printing support is not available for l3 format

---

integration_tests/CMakeLists.txt
integration_tests/string_27.f90
integration_tests/string_28.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-fn5-3d75eb7.json
tests/reference/asr-fn5-3d75eb7.stdout

Fixes #2936.
Tada, challenge 1 done :)

Use subargs while accessing element from character array

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_89.f90
src/libasr/pass/replace_symbolic.cpp

FIX: sin(0.5) print error

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/type_conflict1.f90
tests/reference/asr-type_conflict1-5097f3a.json
tests/reference/asr-type_conflict1-5097f3a.stderr
tests/tests.toml

Fixes: https://github.com/lfortran/lfortran/issues/2945

Error when parameter and target are used together

---

integration_tests/CMakeLists.txt
integration_tests/present_01.f90
src/libasr/pass/transform_optional_argument_functions.cpp

FIX: Handling of `present`

---

.github/workflows/CI.yml
.gitignore
CMakeLists.txt
ci/build_tmp.xsh
ci/create_source_tarball0.sh
ci/environment.yml
ci/environment_linux.yml
doc/man/CMakeLists.txt
doc/man/lfortran.md

CI: gen manpage for tarball

---

.github/workflows/CI.yml
CMakeLists.txt

fixes https://github.com/lfortran/lfortran/pull/2975#discussion_r1427606590

Provide CFLAGS at CI for err check lfortran_intrinsics.c

---

.github/workflows/CI.yml
doc/man/CMakeLists.txt

Fix-up for #2934 
Fix #2980 
It seems the CI doesn't test an out-ouf-source build (from the git source), so I try to changed that.

Fix out-of-source build

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_90.f90
src/libasr/pass/intrinsic_function_registry.h

FIX: Call to min intrinsic function fails for array arguments

---

src/bin/lfortran.cpp

More of #3001 
Useful for debugging the cpp backend etc.

Verbose include dirs

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_91.f90
src/runtime/pure/lfortran_intrinsic_string.f90
tests/reference/asr-string_11-0e4b62c.json
tests/reference/asr-string_11-0e4b62c.stdout
tests/reference/llvm-string_11-e6c763f.json
tests/reference/llvm-string_11-e6c763f.stdout

Fixes: #3004 
Fixes: #3008
Reference: https://github.com/lfortran/lfortran/pull/3007#issuecomment-1869627495

Fix implementation of index intrinsic and add optional `back` parameter

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_92.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_function_registry.h

Fixes: https://github.com/lfortran/lfortran/issues/3009

Add implementation for intrinsic `Anint`

---

integration_tests/CMakeLists.txt
integration_tests/parameter_06.f90
integration_tests/parameter_07.f90
src/lfortran/semantics/ast_common_visitor.h

FIX: Index is out of bounds

---

integration_tests/CMakeLists.txt
integration_tests/modules_55.f90
integration_tests/submodule_02.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asdl_cpp.py
src/libasr/asr_utils.h
tests/reference/asr-submodule_02-9152b7b.json
tests/reference/asr-submodule_02-9152b7b.stdout

https://github.com/lfortran/lfortran/pull/2866

Fixes for external symbols

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/derived_types_30.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
tests/reference/asr-derived_types_30-888fa15.json
tests/reference/asr-derived_types_30-888fa15.stdout
tests/tests.toml

Compiling ``stdlib/subprojects/test-drive/src/testdrive.F90``

---

integration_tests/CMakeLists.txt
integration_tests/complex_16.f90
src/lfortran/semantics/ast_body_visitor.cpp

FIX: Complex im, re is not supported yet for assignment

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_101.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_function_registry.h
src/runtime/pure/lfortran_intrinsic_string.f90
tests/reference/asr-fn5-3d75eb7.json
tests/reference/asr-fn5-3d75eb7.stdout
tests/reference/asr-fn6-a24010a.json
tests/reference/asr-fn6-a24010a.stdout

Implement intrinsic repeat

---

integration_tests/CMakeLists.txt
integration_tests/character_04.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-character_01-e8e453d.json
tests/reference/asr-character_01-e8e453d.stderr
tests/reference/asr-character_01-e8e453d.stdout
tests/tests.toml
tests/warnings/character_01.f90

Fixes: https://github.com/lfortran/lfortran/issues/2983
Fixes: https://github.com/lfortran/lfortran/issues/461

Warning when the LHS character len and the RHS character len are not equal

---

.github/workflows/CI.yml

Repository used: https://github.com/Pranavchiku/stdlib-fortran-lang
Branch: https://github.com/Pranavchiku/stdlib-fortran-lang/commits/lf14/
commit: https://github.com/Pranavchiku/stdlib-fortran-lang/commit/9e40e4d2f55e884bd4ce02b1e1a199bb11d1553f
Refer: https://github.com/lfortran/lfortran/issues/3000#issuecomment-1875882537

CI: test example of stdlib special functions gamma

---

src/lfortran/semantics/comptime_eval.h
src/libasr/pass/intrinsic_function_registry.h
src/runtime/impure/lfortran_intrinsic_math.f90

Fixes: https://github.com/lfortran/lfortran/issues/3019

Add gamma to IntrinsicScalarFunction

---

src/runtime/legacy/CMakeLists.txt

For https://github.com/lfortran/lfortran/issues/3033#issuecomment-1877856684

cmake: add libm to lfortran_runtime

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_102.f90
src/libasr/pass/intrinsic_function_registry.h

https://github.com/lcompilers/lc/pull/50

Support calling scalar intrinsics with ``allocatable`` inputs

---

integration_tests/CMakeLists.txt
integration_tests/tsunami.f90

Fixes #2884
Added tsunami tutorial as an integration test.

Added tsunami integration test 

---

integration_tests/CMakeLists.txt
integration_tests/arrays_35.f90
src/lfortran/semantics/ast_common_visitor.h

FIX: Type mismatch in array initializer r32 and i32

---

integration_tests/CMakeLists.txt
integration_tests/binop_01.f90
src/libasr/codegen/llvm_array_utils.cpp

FIX: operands to a binary operator are not of the same type!

---

integration_tests/CMakeLists.txt
integration_tests/write_06.f90
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/llvm-derived_types_32-4684b97.json
tests/reference/llvm-derived_types_32-4684b97.stdout

Fixing: https://github.com/lfortran/lfortran/issues/2840

Support char type for write(..)

---

integration_tests/warning_logicalstar.f90
src/lfortran/parser/parser.yy
src/lfortran/parser/semantics.h
tests/reference/ast-types_13-76138b5.json
tests/reference/ast-types_13-76138b5.stderr
tests/reference/ast_f90-types_13-ddae644.json
tests/reference/ast_f90-types_13-ddae644.stderr

Fixes #2105
Add a warning whenever a variable is declared using the logical*4 pattern.

Emit warning for logical* 4

---

integration_tests/CMakeLists.txt
integration_tests/dfloat_01.f90
src/lfortran/semantics/ast_common_visitor.h

ENH: support intrinsic `dfloat`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_108.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_function_registry.h
src/runtime/impure/lfortran_intrinsic_bit.f90
tests/reference/asr-modules_48-6cf0505.json
tests/reference/asr-modules_48-6cf0505.stdout

Towards: https://github.com/lfortran/lfortran/issues/3116

Implement `shiftr` 

---

.github/workflows/CI.yml
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
tests/reference/asr-fn5-3d75eb7.json
tests/reference/asr-fn5-3d75eb7.stdout
tests/reference/asr-string_19-d880475.json
tests/reference/asr-string_19-d880475.stdout

Compiling `test/array` to ASR

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_121.f90
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function_registry.h

Fixes: https://github.com/lfortran/lfortran/issues/3115

implement `leadz`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_122.f90
src/libasr/pass/intrinsic_function_registry.h

Fixes: https://github.com/lfortran/lfortran/issues/3143

Implement `rank`

---

.gitignore
build0.sh
ci/build_tmp.xsh
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h

towards https://github.com/lfortran/lfortran/issues/3129.

Python script for Intrinsic Functions verify_args()

---

integration_tests/intrinsics_126.f90

Tighten the accuracy for random number checks

---

integration_tests/CMakeLists.txt
integration_tests/elemental_03.f90

Requested at https://github.com/lfortran/lfortran/pull/3181#discussion_r1465078600

TST: Add test for optional argument in elemental function

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_129.f90
src/libasr/pass/array_op.cpp
src/libasr/pass/intrinsic_function_registry.h

FIX: abs for complex arrays

---

build0.sh
src/lfortran/parser/preprocessor.re
tests/preprocessor13.f90
tests/reference/asr_preprocess-preprocessor13-d951787.json
tests/reference/asr_preprocess-preprocessor13-d951787.stdout
tests/tests.toml

CPP: add `#elif` handling

---

src/lfortran/parser/preprocessor.re
tests/preprocessor14.f90
tests/reference/asr_preprocess-preprocessor14-07dfdb5.json
tests/reference/asr_preprocess-preprocessor14-07dfdb5.stdout
tests/tests.toml

Towards #3202.
There is a bug for the `DEC` case in the test, it returns 0, while it should be 1, for both `-` and `%`. The other two tests work.

CPP: implement %

---

src/lfortran/parser/preprocessor.h
src/lfortran/parser/preprocessor.re
tests/reference/asr_preprocess-preprocessor14-07dfdb5.json
tests/reference/asr_preprocess-preprocessor14-07dfdb5.stdout

CPP: fix function-like macro expansion

---

integration_tests/run_tests.py

towards https://github.com/lfortran/lfortran/issues/3211
fixes https://github.com/lfortran/lfortran/issues/3222
fixes https://github.com/lfortran/lfortran/issues/3221

Improve duplicate module names check

---

src/libasr/intrinsic_func_registry_util_gen.py

fixes https://github.com/lfortran/lfortran/issues/3159

Fix `Anint` and `Aint` args

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_130.f90
kishan.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h

Implemented `ishft` : https://gcc.gnu.org/onlinedocs/gfortran/ISHFT.html

Implemented `ishft`

---

src/lfortran/parser/preprocessor.re
tests/preprocessor16.f90
tests/reference/asr_preprocess-preprocessor16-b846504.json
tests/reference/asr_preprocess-preprocessor16-b846504.stdout
tests/tests.toml

fixes https://github.com/lfortran/lfortran/issues/3218
related https://github.com/lfortran/lfortran/pull/3240

CPP: Implement hex, oct, bin number

---

src/bin/lfortran.cpp
src/lfortran/utils.cpp
src/lfortran/utils.h
src/libasr/CMakeLists.txt

towards https://github.com/lfortran/lfortran/issues/3190

Install `dwarf_convert.py` and `dat_convert.py`

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/string_slice2.f90
tests/reference/asr-string_slice2-473fb60.json
tests/reference/asr-string_slice2-473fb60.stderr
tests/tests.toml

Fixes: https://github.com/lfortran/lfortran/issues/3196

Fixed string slicing

---

.github/workflows/CI.yml
integration_tests/modules_52_module1.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/asr_utils.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/where.cpp
src/runtime/impure/lfortran_intrinsic_math.f90
tests/reference/asr-modules_52-5261d38.json
tests/reference/asr-modules_52-5261d38.stdout

Reached ASR to LLVM after ASR passes.

[WIP] Compile ``test/array`` to LLVM

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_131.f90
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function_registry.h

Fixes: https://github.com/lfortran/lfortran/issues/2841

Add string support for intrinsic `max`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_132.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
tests/reference/asr-floor_01-9103fc5.json
tests/reference/asr-floor_01-9103fc5.stdout
tests/reference/asr-floor_02-5b70ee6.json
tests/reference/asr-floor_02-5b70ee6.stdout

Implemented Floor

---

integration_tests/intrinsics_19.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/pass/intrinsic_function_registry.h
src/runtime/impure/lfortran_intrinsic_math.f90
tests/reference/asr-external4-4e8bc7b.json
tests/reference/asr-external4-4e8bc7b.stdout

Towards: https://github.com/lfortran/lfortran/issues/3034

Redesign the `log` implementations

---

integration_tests/CMakeLists.txt
integration_tests/block_08.f90
src/libasr/codegen/asr_to_llvm.cpp

FIX: incorrect handling of memory allocation / freeing in blocks
