integration_tests/CMakeLists.txt
integration_tests/types_21.f90
src/libasr/pass/update_array_dim_intrinsic_calls.cpp

Fixes: https://github.com/lfortran/lfortran/issues/3151

Fix type mismatch in in pass

---

integration_tests/CMakeLists.txt
integration_tests/types_22.f90
src/lfortran/semantics/asr_implicit_cast_rules.h
src/lfortran/semantics/ast_common_visitor.h

Fixes: https://github.com/lfortran/lfortran/issues/3315

Handle Type Mismatch in Array Initialization

---

src/libasr/pass/intrinsic_function_registry.h
tests/reference/asr-shiftl1-0ff5448.json
tests/reference/asr-shiftl1-0ff5448.stdout
tests/shiftl1.f90
tests/tests.toml

Register missing `shiftl` intrinsic

---

integration_tests/intrinsics_133.f90
src/libasr/pass/intrinsic_function_registry.h

Implemented Ceiling Again

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_135.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h

Implemented Nint

---

.gitignore
integration_tests/CMakeLists.txt
integration_tests/pass_array_by_data_08.f90
src/libasr/pass/pass_array_by_data.cpp
tests/reference/llvm-arrays_03_func-98941b2.json
tests/reference/llvm-arrays_03_func-98941b2.stdout
tests/reference/llvm-arrays_04_func-2aa342e.json
tests/reference/llvm-arrays_04_func-2aa342e.stdout
tests/reference/llvm-arrays_08_func-85e526b.json
tests/reference/llvm-arrays_08_func-85e526b.stdout
tests/reference/llvm-arrays_25-5b87ac7.json
tests/reference/llvm-arrays_25-5b87ac7.stdout
tests/reference/llvm-arrays_op_5-8426b5a.json
tests/reference/llvm-arrays_op_5-8426b5a.stdout
tests/reference/llvm-arrays_op_7-aeeda6d.json
tests/reference/llvm-arrays_op_7-aeeda6d.stdout
tests/reference/llvm-modules_36-53c9a79.json
tests/reference/llvm-modules_36-53c9a79.stdout
tests/reference/llvm-sum_02-43f30ca.json
tests/reference/llvm-sum_02-43f30ca.stdout
tests/reference/pass_pass_array_by_data-modules_44-cd82150.json
tests/reference/pass_pass_array_by_data-modules_44-cd82150.stdout
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_37-1456cdb.json
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_37-1456cdb.stdout
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_39-906d6cb.json
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_39-906d6cb.stdout

Closes https://github.com/lfortran/lfortran/issues/3285

Update mangling scheme for generating functions in ``pass_array_by_data`` ASR pass

---

src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

See: https://github.com/lfortran/lfortran/pull/3261#discussion_r1480901123

Dev: Skip instantiating the function if the intrinsics contains compile time value

---

integration_tests/intrinsics_30.f90
src/lfortran/semantics/comptime_eval.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/runtime/impure/lfortran_intrinsic_math.f90
tests/reference/asr-intrinsics_30-93f854c.json
tests/reference/asr-intrinsics_30-93f854c.stdout

Redesign the `range` intrinsic implementation

---

integration_tests/intrinsics_132.f90
src/libasr/pass/intrinsic_functions.h

Implemented Floor in simpler manner

---

integration_tests/intrinsics_135.f90
src/libasr/pass/intrinsic_functions.h

Reimplemented a part of Nint intrinsic function

---

src/libasr/asr_utils.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_functions.h

towards https://github.com/lfortran/lfortran/issues/3328

Support more intrinsics in the python script

---

.github/workflows/CI.yml

Towards #3323.
Branch: https://github.com/Pranavchiku/stdlib-fortran-lang/commits/lf-linalg4/

CI: setup for `stdlib_linalg`

---

src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asdl_cpp.py
src/libasr/intrinsic_func_registry_util_gen.py

towards https://github.com/lfortran/lfortran/issues/3129

Simplify return in script

---

src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_functions.h

fixes https://github.com/lfortran/lfortran/issues/3325
closes https://github.com/lfortran/lfortran/issues/3129
closes https://github.com/lfortran/lfortran/issues/3328

Recover error messages in eval_*()

---

src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_functions.h
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h

Fixes https://github.com/lfortran/lfortran/issues/3373.
See: https://github.com/lfortran/lfortran/pull/3361#discussion_r1482504613

Dev: Implement `aimag` directly in ASR

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/arrays_40.f90
src/libasr/pass/pass_manager.h
tests/reference/llvm-boz_01-def9db5.json
tests/reference/llvm-boz_01-def9db5.stdout

https://github.com/lfortran/lfortran/issues/3382

Compiling and running ``stdlib/test/optval``

---

.github/workflows/CI.yml
src/libasr/asr_verify.cpp
src/libasr/pass/pass_array_by_data.cpp
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_37-1456cdb.json
tests/reference/pass_pass_array_by_data_transform_optional_argument_functions-modules_37-1456cdb.stdout

https://github.com/lfortran/lfortran/issues/3382

Test ``gauss`` in ``stdlib/test/quadrature`` 

---

src/libasr/pass/intrinsic_functions.h

Fixes https://github.com/lfortran/lfortran/issues/3247
Successor of my PR: https://github.com/lfortran/lfortran/pull/3341 (which can be closed now)

Bitshift used

---

src/bin/lfortran.cpp

https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9188#note_1482332
Related to #3208

lfortran: add --no-cpp option

---

integration_tests/CMakeLists.txt
integration_tests/functions_19.f90
src/libasr/CMakeLists.txt
src/libasr/pass/function_call_in_declaration.cpp
src/libasr/pass/pass_manager.h
src/libasr/pass/replace_function_call_in_declaration.h

Implement `function_call_in_declaration` pass

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_140.f90
src/lfortran/semantics/comptime_eval.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/runtime/pure/lfortran_intrinsic_kind.f90
tests/reference/asr-derived_type1-c109ce6.json
tests/reference/asr-derived_type1-c109ce6.stdout
tests/reference/asr-intrinsics_14-302666f.json
tests/reference/asr-intrinsics_14-302666f.stdout
tests/reference/asr-parameter_04-553ff5b.json
tests/reference/asr-parameter_04-553ff5b.stdout

Towards: https://github.com/lfortran/lfortran/issues/3169 and https://github.com/lfortran/lfortran/issues/3248

Implement `selected_int_kind`

---

.github/workflows/CI.yml
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/array_op.cpp
src/libasr/pass/subroutine_from_function.cpp
tests/reference/asr-arrays_06-9c8a08b.json
tests/reference/asr-arrays_06-9c8a08b.stdout
tests/reference/asr-arrays_op_1-f8b9cb0.json
tests/reference/asr-arrays_op_1-f8b9cb0.stdout
tests/reference/asr-functions_16-3e10090.json
tests/reference/asr-functions_16-3e10090.stdout
tests/reference/asr-implied_do_loops1-25d26db.json
tests/reference/asr-implied_do_loops1-25d26db.stdout
tests/reference/asr-implied_do_loops2-98464d0.json
tests/reference/asr-implied_do_loops2-98464d0.stdout
tests/reference/asr-implied_do_loops3-1dce8fd.json
tests/reference/asr-implied_do_loops3-1dce8fd.stdout
tests/reference/llvm-arrays_01_complex-c90dbdd.json
tests/reference/llvm-arrays_01_complex-c90dbdd.stdout
tests/reference/llvm-arrays_op_5-8426b5a.json
tests/reference/llvm-arrays_op_5-8426b5a.stdout

Closes https://github.com/lfortran/lfortran/issues/3323

Compile ``linalg_matrix_property_checks`` in ``stdlib``

---

integration_tests/CMakeLists.txt
integration_tests/associate_12.f90
integration_tests/associate_13.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/pass_utils.cpp

fixes https://github.com/lfortran/lfortran/issues/3414

Fix associate for real to complex pointer

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_142.f90
integration_tests/intrinsics_143.f90
integration_tests/intrinsics_144.f90
integration_tests/intrinsics_145.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_builder.h
src/libasr/pass/intrinsic_array_function_registry.h
src/runtime/impure/lfortran_intrinsic_math.f90

Implement intrinsic `dot_product`

---

integration_tests/CMakeLists.txt
integration_tests/complex_18.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h

fixes https://github.com/lfortran/lfortran/issues/3442

Support `complex()` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/lbound_01.f90
src/libasr/codegen/asr_to_llvm.cpp

Fixes #3294.
cc @HarshitaKalani

FIX: type mismatch in array `lbound`

---

.github/workflows/CI.yml
src/runtime/pure/lfortran_intrinsic_iso_fortran_env.f90
tests/reference/wat-cpu_time_02_wasm-fa2b15f.json
tests/reference/wat-cpu_time_02_wasm-fa2b15f.stdout

https://github.com/lfortran/lfortran/issues/3382
Closes https://github.com/lfortran/lfortran/issues/3000

Compile and run ``specialfunctions_gamma`` from ``stdlib``

---

integration_tests/CMakeLists.txt
integration_tests/complex_19.f90
src/lfortran/semantics/ast_common_visitor.h

fixes https://github.com/lfortran/lfortran/pull/3443#discussion_r1495327869, https://github.com/lfortran/lfortran/pull/3443#issuecomment-1953603681

Remove redundant check `create_Complex()`

---

.github/workflows/CI.yml
src/runtime/pure/lfortran_intrinsic_iso_fortran_env.f90
tests/reference/wat-cpu_time_02_wasm-fa2b15f.json
tests/reference/wat-cpu_time_02_wasm-fa2b15f.stdout

https://github.com/lfortran/lfortran/commit/07af3c505e5a7b68815de09cc3f4a68afecc11b1

Set ``real128`` to ``-1`` and workaround ``stdlib/specialfunctions_gamma`` accordingly

---

.github/workflows/CI.yml
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.cpp
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
src/runtime/pure/lfortran_intrinsic_ieee_arithmetic.f90
tests/reference/asr-template_03b-0778e50.json
tests/reference/asr-template_03b-0778e50.stdout
tests/reference/asr-template_04-f41dd3e.json
tests/reference/asr-template_04-f41dd3e.stdout
tests/reference/asr-template_array_05-ae2710a.json
tests/reference/asr-template_array_05-ae2710a.stdout
tests/reference/asr-template_matrix_01-65b17ae.json
tests/reference/asr-template_matrix_01-65b17ae.stdout

https://github.com/lfortran/lfortran/issues/3382
Closes https://github.com/lfortran/lfortran/issues/3046
Closes https://github.com/lfortran/lfortran/issues/3467

Compile ``stdlib/test/test_stdlib_math`` and ``diff`` and ``math_all_close`` examples

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_147.f90
integration_tests/intrinsics_148.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
tests/reference/asr-array_01_pack-6c829d9.json
tests/reference/asr-array_01_pack-6c829d9.stdout
tests/reference/asr-array_02_pack-233bae0.json
tests/reference/asr-array_02_pack-233bae0.stdout
tests/reference/asr-modules_43-d01691f.json
tests/reference/asr-modules_43-d01691f.stdout
tests/reference/pass_array_op-modules_43-6930881.json
tests/reference/pass_array_op-modules_43-6930881.stdout

DEV: implement intrinsic `pack`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_149.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h

DEV: implement intrinsic `unpack`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_150.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Implemented maskr

---

.github/workflows/CI.yml

CI: test `stdlib/linalg`

---

integration_tests/CMakeLists.txt
integration_tests/string_32.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_llvm.cpp

fixes https://github.com/lfortran/lfortran/issues/3501

Stdlib: Fix string concat overload

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/cmplx_01.f90
tests/reference/asr-array_transfer_01-3dca715.json
tests/reference/asr-array_transfer_01-3dca715.stderr
tests/reference/asr-cmplx_01-89b858d.json
tests/reference/asr-cmplx_01-89b858d.stderr
tests/reference/asr-complex_01-075c0b7.json
tests/reference/asr-complex_01-075c0b7.stderr
tests/tests.toml

Fixes: https://github.com/lfortran/lfortran/issues/3452

Throw error is the first arg of cmplx is absent

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_152.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/runtime/pure/lfortran_intrinsic_kind.f90
tests/reference/asr-derived_type1-c109ce6.json
tests/reference/asr-derived_type1-c109ce6.stdout
tests/reference/asr-intrinsics_14-302666f.json
tests/reference/asr-intrinsics_14-302666f.stdout
tests/reference/asr-parameter_04-553ff5b.json
tests/reference/asr-parameter_04-553ff5b.stdout

Fixes: https://github.com/lfortran/lfortran/issues/3429
Fixes: https://github.com/lfortran/lfortran/issues/2952
Fixes: https://github.com/lfortran/lfortran/issues/3284

Implement `selected_real_kind`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_152.f90
integration_tests/intrinsics_154.f90
src/libasr/asr_builder.h

fixes https://github.com/lfortran/lfortran/issues/3508

Stdlib: Fix bug in mod for integer kind `8`

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_fortran.cpp

Towards : https://github.com/lfortran/lfortran/issues/3416

Registers sin function

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_34.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

fixes https://github.com/lfortran/lfortran/issues/3526

Stdlib: Support use read

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_159.f90
src/libasr/asr_builder.h
src/libasr/pass/intrinsic_array_function_registry.h
tests/reference/asr-matrix_matmul_03-a99cdd1.json
tests/reference/asr-matrix_matmul_03-a99cdd1.stderr

ENH: Support complex type for `matmul`

---

integration_tests/intrinsics_159.f90

https://github.com/lfortran/lfortran/pull/3532#pullrequestreview-1901552728

test: update intrinsics_159 to use `dp`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_163.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Implemented Ishftc

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_134.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
tests/reference/asr-intrinsics_36-1cb3d03.json
tests/reference/asr-intrinsics_36-1cb3d03.stdout

Implement adjustl

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/string_34.f90
src/lfortran/semantics/ast_common_visitor.h

fixes https://github.com/lfortran/lfortran/issues/3546

Stdlib: Fix indices in string slice

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/string_35.f90
src/runtime/pure/lfortran_intrinsic_string.f90
tests/reference/llvm-string_11-e6c763f.json
tests/reference/llvm-string_11-e6c763f.stdout

fixes https://github.com/lfortran/lfortran/issues/3548

Stdlib: Fix index() for strings

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_165.f90
src/libasr/pass/pass_utils.cpp

FIX: Incorrect handling of result var in intrinsic `sum`

---

integration_tests/CMakeLists.txt
integration_tests/functions_21.f90
integration_tests/functions_22.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/pass/function_call_in_declaration.cpp
src/libasr/pass/pass_utils.h

FIX: Missing dependency in ASR

---

integration_tests/CMakeLists.txt
integration_tests/parameter_08.f90
integration_tests/parameter_09.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
tests/reference/asr-arrays_06-9c8a08b.json
tests/reference/asr-arrays_06-9c8a08b.stdout

Towards #3485. We can iteratively improve and add more tests if the direction looks good.
Fixes #3568.

ENH: handling compile time evaluation of elemental function

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_171.f90
src/libasr/asr_builder.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Towards: https://github.com/lfortran/lfortran/issues/3550

Implement `tolowercase`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_174.f90

Added tests for shape function

---

integration_tests/CMakeLists.txt
src/runtime/pure/lfortran_intrinsic_string.f90

fixes https://github.com/lfortran/lfortran/issues/3596

Fix `lgt`, `llt`, `lle`, `lge`

---

integration_tests/CMakeLists.txt
integration_tests/array_01_pack.f90
integration_tests/intrinsics_175.f90
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_function.cpp
tests/reference/asr-array_01_pack-6c829d9.json
tests/reference/asr-array_01_pack-6c829d9.stdout
tests/reference/asr-modules_43-d01691f.json
tests/reference/asr-modules_43-d01691f.stdout
tests/reference/pass_array_op-modules_43-6930881.json
tests/reference/pass_array_op-modules_43-6930881.stdout

ENH: assign correct dimension in `pack`

---

src/lfortran/parser/parser.yy
src/lfortran/parser/semantics.h
src/lfortran/tests/test_parse.cpp
tests/errors/end_function_name_not_match.f90
tests/reference/asr-implicit8-03c7a90.json
tests/reference/asr-implicit8-03c7a90.stderr
tests/reference/asr-implicit_typing3-c82e537.json
tests/reference/asr-implicit_typing3-c82e537.stderr
tests/reference/asr-template_error_01a-13d8554.json
tests/reference/asr-template_error_01a-13d8554.stderr
tests/reference/asr-template_error_02-a3d3b4c.json
tests/reference/asr-template_error_02-a3d3b4c.stderr
tests/reference/asr-template_error_04-16c03e5.json
tests/reference/asr-template_error_04-16c03e5.stderr
tests/reference/asr-template_error_05-85bce3c.json
tests/reference/asr-template_error_05-85bce3c.stderr
tests/reference/ast-end_function_name_not_match-92ee1a1.json
tests/reference/ast-end_function_name_not_match-92ee1a1.stderr
tests/tests.toml

fix: raise syntax error when function name doesn't match closing function name

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_177.f90
src/lfortran/semantics/comptime_eval.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/runtime/pure/lfortran_intrinsic_string.f90
tests/reference/asr-derived_types_04-da02dd9.json
tests/reference/asr-derived_types_04-da02dd9.stdout
tests/reference/asr-derived_types_06-847ca73.json
tests/reference/asr-derived_types_06-847ca73.stdout
tests/reference/asr-fn5-3d75eb7.json
tests/reference/asr-fn5-3d75eb7.stdout
tests/reference/asr-fn6-a24010a.json
tests/reference/asr-fn6-a24010a.stdout

Implement `adjustr()` as intrinsic registry function

---

src/libasr/asr_builder.h
src/libasr/pass/intrinsic_functions.h

ENH: define `CallIntrinsic` in asr builder and use it

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_182.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Implemented dshiftl(2)

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_183.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
tests/reference/asr-bits_05-1b98f97.json
tests/reference/asr-bits_05-1b98f97.stdout

cherry-picked work done by @shivimathur at #3571, resolved conflicts.

DEV: implement intrinsic `ibits`

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_builder.h
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/libasr/pass/pass_utils.cpp

enh: remove cast macro in asr builder

---

src/libasr/asr_builder.h
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_functions.h

removed compare macros from asr builder

---

integration_tests/intrinsics_191.f90

Requested at https://github.com/lfortran/lfortran/pull/3670#discussion_r1530310855

test: kind for complex(kind=8)

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_36.f90
src/libasr/pass/print_arr.cpp

fixes https://github.com/lfortran/lfortran/issues/3676

Fix derived io formatted write

---

ci/azure_install_macos.sh
ci/environment.yml
ci/environment_docs_linux.yml
ci/environment_linux.yml
ci/environment_linux_llvm.yml

Fixes https://github.com/lfortran/lfortran/issues/3687.

Pin nlohmann_json to the last working version

---

src/libasr/asr_builder.h
src/libasr/pass/intrinsic_functions.h

Refer: https://github.com/lfortran/lfortran/pull/3668#discussion_r1529165824

enh: Code cleanup for intrinsic functions

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_198.f90
src/libasr/pass/intrinsic_function.cpp

fix: allocating non-allocatable variables in intrinsic function for runtime dim

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_199.f90
src/libasr/pass/intrinsic_array_function_registry.h

fix: dim attribute for mask of rank 1 is incorrectly handled in intrinsic count

---

src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/casting_utils.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/array_op.cpp
src/libasr/pass/flip_sign.cpp
src/libasr/pass/intrinsic_function.cpp
src/libasr/pass/intrinsic_functions.h
src/libasr/pass/pass_utils.h
src/libasr/pass/promote_allocatable_to_nonallocatable.cpp
tests/reference/pass_flip_sign-expr_13-e24d940.json
tests/reference/pass_flip_sign-expr_13-e24d940.stdout
tests/reference/pass_flip_sign-flip_sign-16b288c.json
tests/reference/pass_flip_sign-flip_sign-16b288c.stdout

There are some changes which I have commented out. They should be uncommented in subsequent PRs.

Sync ``libasr`` with LC

---

integration_tests/CMakeLists.txt
integration_tests/arrays_41.f90
src/libasr/pass/update_array_dim_intrinsic_calls.cpp

enh: handling of Cast node while replacing arrray size in update array dim intrinsic call pass

---

integration_tests/template_array_03.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/ASR.asdl
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/casting_utils.cpp
src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/asr_to_wasm.cpp
src/libasr/codegen/c_utils.h
src/libasr/codegen/llvm_utils.cpp
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/inline_function_calls.cpp
src/libasr/pass/intrinsic_functions.h
tests/reference/asr-template_array_03-b7f9799.json
tests/reference/asr-template_array_03-b7f9799.stderr
tests/reference/asr-template_array_03-b7f9799.stdout
tests/reference/c-case_03-b50b4bf.json
tests/reference/c-case_03-b50b4bf.stdout
tests/reference/c-case_06-ecc9f3c.json
tests/reference/c-case_06-ecc9f3c.stdout

fixes https://github.com/lfortran/lfortran/issues/3374

Remove `const` ttype

---

src/libasr/pass/transform_optional_argument_functions.cpp

docs: document ASR pass `transform_optional_argument_functions` with example

---

.github/workflows/CI.yml

commit: https://github.com/czgdp1807/stdlib/commit/9bc606565ca2477435ba1c449f917a07d4bbc03f

CI: test LLVM compilation of `stdlib_stats_var`

---

integration_tests/intrinsics_87.f90
src/libasr/pass/intrinsic_functions.h

Fixes #3749
**when merging**: I request to squash the commits

fix: assign "m_type" for complex array argument in Abs correctly

---

integration_tests/CMakeLists.txt
integration_tests/arrays_43.f90
src/lfortran/semantics/ast_common_visitor.h

Fixes: https://github.com/lfortran/lfortran/issues/3729

Fix Incorrect handling of compile time compare operation

---

.github/workflows/CI.yml

Fixes https://github.com/lfortran/lfortran/issues/3755
https://github.com/czgdp1807/stdlib/commits/lf-stats-cov
https://github.com/czgdp1807/stdlib/commits/lf19

CI: test LLVM compilation of `stdlib_stats_cov`

---

.github/workflows/CI.yml

ci: test LLVM compilation of `stdlib_stats_median`

---

.github/workflows/CI.yml

ci: test LLVM compilation of `stdlib_stats_moment_mask`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_202.f90
src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-doloop_01-bb1c596.json
tests/reference/asr-doloop_01-bb1c596.stderr
tests/reference/asr-doloop_01-bb1c596.stdout
tests/tests.toml
tests/warnings/doloop_01.f90

Fixes: https://github.com/lfortran/lfortran/issues/3699
Fixes: https://github.com/lfortran/lfortran/issues/3485

Give warning for double type in loop start, end, step 

---

integration_tests/intrinsics_185.f90
src/libasr/pass/array_op.cpp
src/libasr/pass/intrinsic_functions.h

Fixes: https://github.com/lfortran/lfortran/issues/3477
Fixes: https://github.com/lfortran/lfortran/issues/3792

Fix handling of arryays in elemental intrinsic in array_op pass

---

src/libasr/asr_builder.h
src/libasr/pass/intrinsic_functions.h

Fixes: https://github.com/lfortran/lfortran/issues/3722

Refactor: Simplify implementation logic for modulo

---

src/bin/lfortran.cpp

towards https://github.com/lfortran/lfortran/pull/3842#issuecomment-2045612433.

ENH: Simple fixes

---

src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_functions.h
tests/errors/sqrt_neg.f90
tests/reference/asr-sqrt_neg-5a20839.json
tests/reference/asr-sqrt_neg-5a20839.stderr
tests/tests.toml

Add error message for negative argument of sqrt intrinsic function

---

src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/ASR.asdl
src/libasr/asr_verify.cpp
src/libasr/pass/for_all.cpp
tests/reference/asr-kokkos_program2-8391215.json
tests/reference/asr-kokkos_program2-8391215.stdout
tests/reference/asr-subroutine4-a425266.json
tests/reference/asr-subroutine4-a425266.stdout
tests/reference/asr-template_04-f41dd3e.json
tests/reference/asr-template_04-f41dd3e.stdout

feat: introduce `expr *shared`, `expr* local` in `DoConcurrent` node

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/atomic_01.f90
tests/errors/coarray_01.f90
tests/reference/asr-atomic_01-1c877f0.json
tests/reference/asr-atomic_01-1c877f0.stderr
tests/reference/asr-coarray_01-5f111e4.json
tests/reference/asr-coarray_01-5f111e4.stderr
tests/tests.toml

Towards: https://github.com/lfortran/lfortran/issues/492#issuecomment-2044374861

chore: throw error for coarray and atomic intrinsics

---

integration_tests/CMakeLists.txt
integration_tests/character_parameter_padding_trimming.f90
src/lfortran/semantics/ast_common_visitor.h
tests/character_parameter_padding_trimming.f90
tests/reference/asr-character_01-e8e453d.json
tests/reference/asr-character_01-e8e453d.stderr
tests/reference/asr-character_01-e8e453d.stdout
tests/reference/asr-character_parameter_padding_trimming-ea91653.json
tests/reference/asr-character_parameter_padding_trimming-ea91653.stderr
tests/reference/asr-character_parameter_padding_trimming-ea91653.stdout
tests/tests.toml
tests/warnings/character_01.f90

fix: pad/trim constant character string

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_213.f90
src/libasr/runtime/lfortran_intrinsics.c
src/runtime/impure/lfortran_intrinsic_math.f90
tests/reference/asr-matmul_01-7b0b0c2.json
tests/reference/asr-matmul_01-7b0b0c2.stdout

enh: support real(sp) in cpu_time

---

.github/workflows/CI.yml

Ref: https://github.com/lfortran/lfortran/pull/3926#issuecomment-2094112387

ci: update hash to remove test `test_loadtxt` file from `stdlib`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_217.f90
integration_tests/intrinsics_47.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/ASR.asdl
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
tests/reference/asr-intrinsics_47-bdbe527.json
tests/reference/asr-intrinsics_47-bdbe527.stdout

Fixes: https://github.com/lfortran/lfortran/issues/3826
Towards: https://github.com/lfortran/lfortran/issues/492

refactor: array intrinsic `all`

---

integration_tests/CMakeLists.txt
integration_tests/arrays_45.f90
integration_tests/arrays_46.f90
integration_tests/arrays_47.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_builder.h

enh: support assigning array dimension via module variables

---

src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_function_registry.h

Fix : https://github.com/lfortran/lfortran/issues/3970

Change ```static_cast<int>()``` to ```static_cast<int64_t>()```

---

src/lfortran/semantics/ast_common_visitor.h

Towards: https://github.com/lfortran/lfortran/pull/3979#discussion_r1592542386

Better way of fixing `len` function for intrinsic elemental function as input argument

---

integration_tests/CMakeLists.txt
integration_tests/format_14.f90
src/libasr/runtime/lfortran_intrinsics.c

enh: implement "T" format specifier

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_220.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

feat: implement `mergebits` intrinsic function

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_221.f90
integration_tests/parameter_08.f90
integration_tests/parameter_09.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_array_function_registry.h

Towards: https://github.com/lfortran/lfortran/issues/3203#issuecomment-2015804152

Add support for compile time evaluation of sum intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/file_20.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c

Fixes https://github.com/lfortran/lfortran/issues/3678

enh: support "unformatted" write

---

integration_tests/intrinsics_213.f90

Fix the numerical scheme. See
https://github.com/lfortran/lfortran/pull/3920/files#r1599179204.

Fix a test to run fast

---

integration_tests/intrinsics_172.f90
integration_tests/intrinsics_219.f90
src/libasr/pass/intrinsic_array_function_registry.h

Implement `eval_count`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_225.f90
integration_tests/intrinsics_226.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_array_function_registry.h

Implement array intrinsic `iany` and `iall`

---

integration_tests/CMakeLists.txt
integration_tests/parameter_10.f90
src/lfortran/semantics/ast_common_visitor.h

enh: support compile time evaluation of implied do loops

---

src/libasr/asr_utils.h
src/libasr/codegen/asr_to_wasm.cpp

Makes code execution faster and look cleaner.

Refactor: Change `if-else` to `switch` case

---

src/libasr/codegen/asr_to_fortran.cpp
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
tests/reference/asr-intrinsics_32-86443d8.json
tests/reference/asr-intrinsics_32-86443d8.stdout
tests/reference/asr-intrinsics_37-8df004d.json
tests/reference/asr-intrinsics_37-8df004d.stdout

Refactor: Move `merge` from 'intrinsic_array_functions' to 'intrinsic_elemental_function'

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_224.f90
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Towards: #492, https://github.com/lfortran/lfortran/pull/4017

Implement intrinsic `spacing`

---

doc/src/usage.md

docs: add information about 'backend' flag

---

a.f90
integration_tests/CMakeLists.txt
integration_tests/intrinsics_227.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h

Implement array intrinsic `norm2`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_35.f90
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_fortran.cpp
tests/reference/asr-intrinsics_35-10733ec.json
tests/reference/asr-intrinsics_35-10733ec.stdout
tests/reference/asr-intrinsics_47-bdbe527.json
tests/reference/asr-intrinsics_47-bdbe527.stdout

Register array intrinsics in fortran backend

---

integration_tests/CMakeLists.txt
integration_tests/parameter_11.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-arrays_06-9c8a08b.json
tests/reference/asr-arrays_06-9c8a08b.stdout
tests/reference/asr-implied_do_loops1-25d26db.json
tests/reference/asr-implied_do_loops1-25d26db.stdout
tests/reference/asr-implied_do_loops2-98464d0.json
tests/reference/asr-implied_do_loops2-98464d0.stdout
tests/reference/asr-implied_do_loops3-1dce8fd.json
tests/reference/asr-implied_do_loops3-1dce8fd.stdout
tests/reference/llvm-arrays_06-538e67d.json
tests/reference/llvm-arrays_06-538e67d.stdout

Fixes https://github.com/lfortran/lfortran/pull/4019#issuecomment-2118240991

chore: fix incorrect initial assignment to contains_loop_var

---

integration_tests/parameter_10.f90
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_functions.h

Towards: https://github.com/lfortran/lfortran/issues/3203

Refactor: Fix intrinsic function handling in extract_kind

---

integration_tests/intrinsics_149.f90
src/libasr/pass/intrinsic_array_function_registry.h

Towards: https://github.com/lfortran/lfortran/issues/4038

Rectify implementation logic for `unpack` intrinsic

---

integration_tests/intrinsics_151.f90
src/libasr/intrinsic_func_registry_util_gen.py

fix: support compile time reduction of kind argument

---

integration_tests/CMakeLists.txt
integration_tests/logical_casting_01.f90
run_tests.py
src/bin/lfortran.cpp
src/lfortran/semantics/ast_common_visitor.h
src/libasr/utils.h
tests/errors/type_casting_01.f90
tests/reference/asr-type_casting_01-4e8a892.json
tests/reference/asr-type_casting_01-4e8a892.stderr
tests/tests.toml

Towards: #4017 
Fixes: #4041
Also a little cleanup of the code.

enh: support type conversion from Integer to logical

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_230.f90
integration_tests/intrinsics_231.f90
src/lfortran/semantics/ast_common_visitor.h

Implement intrinsic `Dgamma`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_234.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_builder.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h

Implement `parity` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_232.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_array_function_registry.h

Implement `iparity` intrinsic function

---

integration_tests/CMakeLists.txt
integration_tests/parameter_13.f90

test: compile time example

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_239.f90
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Implement `erfc_scaled` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/arrays_48.f90
src/lfortran/semantics/ast_common_visitor.h

chore: setup is_argument correctly while processing dims

---

integration_tests/CMakeLists.txt
integration_tests/test_ieee_arithmetic.f90
src/lfortran/semantics/comptime_eval.h
src/runtime/pure/lfortran_intrinsic_ieee_arithmetic.f90

Towards: https://github.com/lfortran/lfortran/issues/3117#issuecomment-1946961539,  #4017

Implement ieee arithmetic functions

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/openmp1.f90
tests/reference/asr_openmp-openmp1-3056a3e.json
tests/reference/asr_openmp-openmp1-3056a3e.stdout
tests/tests.toml

feat: support reduction clause in omp pragma

---

integration_tests/CMakeLists.txt
integration_tests/modules_58.f90
integration_tests/modules_58_module.f90
src/libasr/asr_verify.cpp

closes #3968 , closes #3977 
I tried to bypass only the statements that would raise an error. @certik

Bypass verification on expr_type

---

integration_tests/CMakeLists.txt
integration_tests/openmp_02.f90
src/runtime/CMakeLists.txt
src/runtime/openmp/CMakeLists.txt
src/runtime/openmp/omp_lib.f90

feat: add support for `omp_lib`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_244.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_array_function_registry.h

Implement `cshift` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/openmp_03.f90
src/lfortran/parser/semantics.h
src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/string_utils.cpp
src/libasr/string_utils.h

Fixes : https://github.com/lfortran/lfortran/issues/4161

fix: parsing of shared variable in openmp pragma

---

integration_tests/intrinsics_134.f90
integration_tests/intrinsics_177.f90
src/libasr/intrinsic_func_registry_util_gen.py
tests/reference/asr-intrinsics_36-1cb3d03.json
tests/reference/asr-intrinsics_36-1cb3d03.stdout

Fix : https://github.com/lfortran/lfortran/issues/3980 for adjustl and adjustr.

Compile time handling of character len 

---

src/lfortran/fortran_evaluator.cpp
src/libasr/diagnostics.h

My first build attempt resulted in a few warnings being dumped on the console, these few patches removes them.

Get a warning-free build

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_245.f90
src/lfortran/semantics/ast_common_visitor.h
tests/errors/cmplx_02.f90
tests/errors/cmplx_03.f90
tests/reference/asr-cmplx_02-48bb125.json
tests/reference/asr-cmplx_02-48bb125.stderr
tests/reference/asr-cmplx_03-6426707.json
tests/reference/asr-cmplx_03-6426707.stderr
tests/tests.toml

fixes : https://github.com/lfortran/lfortran/issues/4049

fix : throw error for wrong syntax in cmplx intrinsic

---

integration_tests/intrinsics_244.f90
src/libasr/pass/intrinsic_array_function_registry.h

ref: rectified the change in argument post computation  error for `cshift` intrinsic

---

integration_tests/intrinsics_185.f90
integration_tests/intrinsics_186.f90

enh: update integration test for verify intrinsic

---

integration_tests/intrinsics_91.f90

Enh: Update integration test for `index` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_246.f90
integration_tests/intrinsics_247.f90

Fixes : https://github.com/lfortran/lfortran/issues/4174

test: add array tests for adjustl and adjustr

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/coarray_02.f90
tests/reference/asr-coarray_02-793f8b3.json
tests/reference/asr-coarray_02-793f8b3.stderr
tests/tests.toml

Throw error for leftover coarray function

---

integration_tests/intrinsics_246.f90
integration_tests/intrinsics_247.f90

Update integration tests for adjustl and adjustr

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_253.f90
integration_tests/intrinsics_254.f90

Add integration test for `erfc` and `derfc`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_255.f90
src/lfortran/semantics/ast_common_visitor.h
tests/errors/dint_args.f90
tests/errors/dnint_args.f90
tests/reference/asr-dint_args-0823aa1.json
tests/reference/asr-dint_args-0823aa1.stderr
tests/reference/asr-dnint_args-3d72f4b.json
tests/reference/asr-dnint_args-3d72f4b.stderr
tests/tests.toml

Fixes : https://github.com/lfortran/lfortran/issues/4190

refactor : Handle multiple arguments for intrinsics mapping

---

integration_tests/intrinsics_156.f90
integration_tests/intrinsics_157.f90
integration_tests/intrinsics_158.f90

test: update integration test for blt, ble and bge

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_260.f90
src/libasr/pass/intrinsic_array_function_registry.h

enh: support optional arg `mask` in `sum` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_259.f90

test: Update integration test for lgt, llt, lge, lle

---

integration_tests/intrinsics_168.f90
src/libasr/pass/intrinsic_functions.h
tests/errors/intrinsics_03.f90
tests/reference/asr-intrinsics_03-f6b3e89.json
tests/reference/asr-intrinsics_03-f6b3e89.stderr
tests/tests.toml

Throw error for neg `pos` and add test for `ibclr` intrinsic

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_fortran.cpp

fixes: https://github.com/lfortran/lfortran/issues/4106

fix: ```line_truncation``` issue in fortran backend

---

src/libasr/pass/intrinsic_array_function_registry.h

Towards: #4017
Towards: #4322
https://github.com/lfortran/lfortran/pull/4284#discussion_r1644399967

enh: support `mask` arg in `sum` intrinsic - 2

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_257.f90
src/libasr/pass/intrinsic_array_function_registry.h

Towards: #4017 
Fixes: https://github.com/lfortran/lfortran/issues/4336

Fix implementation logic for `product` and add support for `mask` arg 

---

integration_tests/intrinsics_268.f90
integration_tests/intrinsics_269.f90
integration_tests/intrinsics_270.f90

Addressing: https://github.com/lfortran/lfortran/pull/4351#discussion_r1649845423

Add compile time tests for asin, acos and atan intrinsic 

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_271.f90

Add integration test for `leadz` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_270.f90
integration_tests/intrinsics_271.f90
integration_tests/intrinsics_272.f90
src/libasr/pass/intrinsic_functions.h

Update integration test for `trailz` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_273.f90

Add tests for dprod intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_275.f90
integration_tests/intrinsics_276.f90
integration_tests/intrinsics_277.f90

test: add test for `or`, `and` and `xor`

---

src/libasr/asr_verify.cpp
src/libasr/pass/intrinsic_array_function_registry.h
src/libasr/pass/intrinsic_functions.h

asr verify check: ensure target variable with intent(in) isn't assigned

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_137.f90
integration_tests/intrinsics_140.f90
integration_tests/intrinsics_152.f90
integration_tests/intrinsics_181.f90
integration_tests/intrinsics_278.f90

Add tests for `tiny`, `huge`, `selected_real_kind`, `selected_int_kind`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_279.f90
integration_tests/intrinsics_280.f90
integration_tests/intrinsics_281.f90

Add tests for sinh, cosh and tanh intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_282.f90
integration_tests/intrinsics_30.f90
integration_tests/intrinsics_69.f90
tests/reference/asr-intrinsics_30-93f854c.json
tests/reference/asr-intrinsics_30-93f854c.stdout

Update test for radix, range and hypot

---

integration_tests/intrinsics_108.f90
integration_tests/intrinsics_123.f90
integration_tests/intrinsics_124.f90
integration_tests/intrinsics_136.f90

Update tests for shiftl, lshift and rshift intrinsic

---

.github/workflows/CI.yml

Towards: https://github.com/lfortran/lfortran/pull/4063, #4017

ci: remove dim in `sum` intrinsic in stdlib to make `real` work

---

integration_tests/intrinsics_150.f90
integration_tests/intrinsics_151.f90
src/libasr/pass/intrinsic_functions.h

Ref: rectified implementation of maskl intrinsic and add tests for maskl and maskr intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_283.f90
integration_tests/intrinsics_284.f90
integration_tests/intrinsics_286.f90

Update tests for asinh, acosh, atanh intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_288.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_array_function_registry.h

Fixes: https://github.com/lfortran/lfortran/issues/4408, https://github.com/lfortran/lfortran/issues/2433, https://github.com/lfortran/lfortran/issues/1315
Towards: #4017, #492

Implement `spread` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/do_loop_05.f90
src/libasr/pass/pass_utils.cpp

fix: incorrect handling of decrement variable in do loop

---

integration_tests/CMakeLists.txt
integration_tests/do_concurrent_02.f90
integration_tests/do_concurrent_03.f90
integration_tests/do_concurrent_04.f90
integration_tests/do_concurrent_05.f90
integration_tests/do_concurrent_06.f90
integration_tests/do_concurrent_07.f90
integration_tests/do_concurrent_08.f90
integration_tests/do_concurrent_09.f90
integration_tests/do_concurrent_10.f90
integration_tests/do_concurrent_11.f90
integration_tests/do_concurrent_12.f90
src/lfortran/semantics/ast_body_visitor.cpp

enh: do concurrent loop frontend to support local, shared, reduction

---

.github/workflows/CI.yml

Setup CI job for testing SNAP compilation.

chore (ci): setup CI job for testing SNAP compilation

---

integration_tests/CMakeLists.txt
integration_tests/complex_08.f90
integration_tests/intrinsics_208.f90
integration_tests/intrinsics_289.f90

test: add integration tests for `ishftc`, `bit_size`, `conjg`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_290.f90
integration_tests/intrinsics_291.f90

tests: add tests for `gamma` and `log10` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/cycle_and_exit6.f90
src/lfortran/parser/fixedform_tokenizer.cpp

add cycle statement to lex_body_statements in fixed form tokenizer

---

integration_tests/CMakeLists.txt
integration_tests/implicit_interface_17.f90
integration_tests/implicit_interface_17b.f90
src/lfortran/semantics/ast_common_visitor.h

enh: frontend to allow declaration of external function type after its initial declaration

---

integration_tests/CMakeLists.txt
integration_tests/pointer_01.f90
src/libasr/codegen/asr_to_llvm.cpp
tests/reference/llvm-allocate_03-495d621.json
tests/reference/llvm-allocate_03-495d621.stdout
tests/reference/llvm-arrays_25-5b87ac7.json
tests/reference/llvm-arrays_25-5b87ac7.stdout
tests/reference/llvm-arrays_op_4-df4e84d.json
tests/reference/llvm-arrays_op_4-df4e84d.stdout

fixes #4466 
This PR is an improved version of #4508 building upon the provided suggestion.

enh: point to array descriptor of pointer to array when allocating after nullifying it

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_293.f90
integration_tests/intrinsics_294.f90

tests: add tests for `log_gamma` and `dgamma` intrinsic

---

integration_tests/intrinsics_163.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_functions.h
tests/errors/ishftc_size.f90
tests/reference/asr-ishftc_size-1254b50.json
tests/reference/asr-ishftc_size-1254b50.stderr
tests/tests.toml

feat: add optional argument for ishftc intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/do_concurrent_13.f90
integration_tests/openmp_33.f90

test: add mandelbrot test with `openmp`

---

integration_tests/intrinsics_241.f90
src/libasr/pass/intrinsic_functions.h

correct return type for logical

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_296.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Implement `storage_size` intrinsic

---

integration_tests/intrinsics_122.f90
integration_tests/intrinsics_139.f90
integration_tests/intrinsics_173.f90
integration_tests/intrinsics_176.f90
src/libasr/pass/intrinsic_functions.h

Fixes: https://github.com/lfortran/lfortran/issues/4550

test: add and register

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_16.f90
integration_tests/intrinsics_295.f90
src/libasr/pass/intrinsic_functions.h

test: add integration test for `exp` 

---

src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/reference/asr-save3-025da43.json
tests/reference/asr-save3-025da43.stdout
tests/save3.f90
tests/tests.toml

enh: disable warning when global save attr is present

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_115.f90
integration_tests/intrinsics_127.f90
integration_tests/intrinsics_128.f90
integration_tests/intrinsics_135.f90
integration_tests/intrinsics_178.f90
integration_tests/intrinsics_187.f90
integration_tests/intrinsics_237.f90
integration_tests/intrinsics_297.f90

Add integration tests for intrinsic functions

---

integration_tests/bits_05.f90
integration_tests/intrinsics_46.f90
integration_tests/intrinsics_61.f90
src/libasr/pass/intrinsic_functions.h
tests/errors/ichar_01.f90
tests/reference/asr-bits_05-1b98f97.json
tests/reference/asr-bits_05-1b98f97.stdout
tests/reference/asr-ichar_01-a5284c8.json
tests/reference/asr-ichar_01-a5284c8.stderr
tests/reference/asr-intrinsics_46-0ef4d7a.json
tests/reference/asr-intrinsics_46-0ef4d7a.stdout
tests/tests.toml

Update integration tests

---

integration_tests/do_concurrent_07.f90
integration_tests/do_concurrent_10.f90
integration_tests/do_concurrent_11.f90
integration_tests/do_concurrent_12.f90
integration_tests/do_concurrent_13.f90
src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/do_concurrent1.f90
tests/reference/asr-do_concurrent1-74bde45.json
tests/reference/asr-do_concurrent1-74bde45.stderr
tests/tests.toml

enh: throw error when parallel loop variable is part of local expr

---

integration_tests/CMakeLists.txt
integration_tests/functions_24.f90

test: add integration test for char*1 function

---

integration_tests/intrinsics_163.f90
src/libasr/pass/intrinsic_functions.h
src/libasr/runtime/lfortran_intrinsics.c

feat: add runtime implementation of `ishftc` intrinsic

---

.github/workflows/CI.yml

Test SNAP compilation with `--fast`

chore (ci): test SNAP compilation with `--fast`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_300.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/array_op.cpp

fix: kind does not work for array args in compile time

---

src/libasr/pass/intrinsic_functions.h
tests/errors/modulo_01.f90
tests/reference/asr-modulo_01-b82bee9.json
tests/reference/asr-modulo_01-b82bee9.stderr
tests/tests.toml

Throw error if second arg of `modulo` is 0

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_304.f90
integration_tests/string_16.f90
src/libasr/intrinsic_func_registry_util_gen.py
tests/errors/sign_01.f90
tests/reference/asr-sign_01-62b270e.json
tests/reference/asr-sign_01-62b270e.stderr
tests/tests.toml

Throw error for different kind of args in `sign` and update integration test

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_153.f90
integration_tests/intrinsics_305.f90
integration_tests/intrinsics_306.f90
integration_tests/intrinsics_307.f90
integration_tests/intrinsics_308.f90
integration_tests/intrinsics_70.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_functions.h

fixes: #4608, #4607
towards: #3067

rectify bugs in intrinsics an update tests

---

src/libasr/pass/intrinsic_functions.h
tests/errors/dprod_01.f90
tests/errors/ifix_01.f90
tests/reference/asr-dprod_01-80a930c.json
tests/reference/asr-dprod_01-80a930c.stderr
tests/reference/asr-ifix_01-ed76fb2.json
tests/reference/asr-ifix_01-ed76fb2.stderr
tests/tests.toml

dev: throw error when arg of kind in ifix is not 4

---

integration_tests/file_09.f90
src/libasr/runtime/lfortran_intrinsics.c

fix: fix reading character array from file

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_310.f90
src/libasr/pass/intrinsic_functions.h

Fixes: https://github.com/lfortran/lfortran/issues/4622

Support kind = 1 and 2 for digits intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_309.f90
src/libasr/pass/intrinsic_array_function_registry.h

Fixes: https://github.com/lfortran/lfortran/issues/4614

Fix compile time evaluation for `pack` intrinsic

---

integration_tests/intrinsics_16.f90
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_functions.h

Fixes: https://github.com/lfortran/lfortran/issues/4542

enh: handle complex args in `aimag` with kind = 8

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_314.f90

test: add a test for `IntegerBOZConstant`

---

src/lfortran/tests/test_llvm.cpp

test: add test for array in interactive mode

---

integration_tests/CMakeLists.txt
integration_tests/subroutines_13.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_builder.h
src/libasr/pass/intrinsic_subroutine_registry.h
src/libasr/pass/intrinsic_subroutines.h
src/libasr/runtime/lfortran_intrinsics.c

feat: implement `get_command` intrinsic

---

Dockerfile
build_release.sh

Docker: build in Release mode

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_301.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_array_function_registry.h

Implement `findloc` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_302.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

Towards: https://github.com/lfortran/lfortran/issues/4593

Implement intrinsic `Is_contiguous`

---

src/bin/lfortran.cpp
src/libasr/codegen/evaluator.cpp
src/libasr/codegen/evaluator.h

feat: add support for executing `.ll` files directly

---

integration_tests/CMakeLists.txt
src/libasr/intrinsic_func_registry_util_gen.py

fixes integration_tests/intrinsics_16.f90

fix return_type of intrinsic functions

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_303.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_subroutine_registry.h
src/libasr/pass/intrinsic_subroutines.h
src/libasr/runtime/lfortran_intrinsics.c

feat: initial implementation of `random_seed`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_315.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

feat: implement `out_of_range` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_316.f90
src/libasr/pass/intrinsic_functions.h

Fixes: https://github.com/lfortran/lfortran/issues/4745

Arguments to min/max should have same type of elements

---

src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_subroutine_registry.h
src/libasr/pass/intrinsic_subroutines.h
src/runtime/builtin/lfortran_intrinsic_builtin.f90
tests/reference/asr-cmd_01-e172099.json
tests/reference/asr-cmd_01-e172099.stdout
tests/reference/asr-cmd_02-ba58262.json
tests/reference/asr-cmd_02-ba58262.stdout
tests/reference/asr-fn6-a24010a.json
tests/reference/asr-fn6-a24010a.stdout
tests/reference/asr-modules_48-6cf0505.json
tests/reference/asr-modules_48-6cf0505.stdout
tests/reference/asr-select_type_04-e8b402f.json
tests/reference/asr-select_type_04-e8b402f.stdout

Towards: https://github.com/lfortran/lfortran/issues/4593

Initial implementation of `execute_command_line`

---

doc/src/installation.md

I have written a short description of LLVM stacktracing. Let me know if there are any changes.

Add LLVM stacktraces to docs

---

src/lfortran/tests/CMakeLists.txt
src/lfortran/tests/test_ast.cpp
src/libasr/location.h

test: add `test_ast` to check location information of variable declaration

---

.gitignore
src/lfortran/tests/CMakeLists.txt

https://github.com/lfortran/lfortran/pull/4845#discussion_r1767535815

test: cleanup location test

---

src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/runtime/builtin/lfortran_intrinsic_builtin.f90
tests/reference/asr-cmd_01-e172099.json
tests/reference/asr-cmd_01-e172099.stdout
tests/reference/asr-fn6-a24010a.json
tests/reference/asr-fn6-a24010a.stdout
tests/reference/asr-modules_48-6cf0505.json
tests/reference/asr-modules_48-6cf0505.stdout
tests/reference/asr-select_type_04-e8b402f.json
tests/reference/asr-select_type_04-e8b402f.stdout

Remove old implementation of command_argument_count

---

src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/runtime/builtin/lfortran_intrinsic_builtin.f90
tests/reference/asr-cmd_01-e172099.json
tests/reference/asr-cmd_01-e172099.stdout
tests/reference/asr-fn6-a24010a.json
tests/reference/asr-fn6-a24010a.stdout
tests/reference/asr-modules_48-6cf0505.json
tests/reference/asr-modules_48-6cf0505.stdout
tests/reference/asr-select_type_04-e8b402f.json
tests/reference/asr-select_type_04-e8b402f.stdout

Implementing `move_alloc`

---

src/lfortran/tests/CMakeLists.txt

Towards #4808. See https://github.com/lfortran/lfortran/pull/4845#discussion_r1769594881

refactor: test `WITH_LSP`

---

src/libasr/pass/intrinsic_functions.h

Fixes https://github.com/lfortran/lfortran/issues/4842

Fixing debug build warnings

---

integration_tests/CMakeLists.txt
src/lfortran/semantics/ast_common_visitor.h

fix towards https://github.com/lfortran/lfortran/issues/4738#issuecomment-2326859441

Fix bug in reshape

---

src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/fortran_evaluator.h
src/lfortran/semantics/ast_to_asr.cpp
src/lfortran/semantics/ast_to_asr.h
src/lfortran/tests/test_ast.cpp
src/libasr/location.h

This PR applies code review done in https://github.com/lfortran/lfortran/pull/4851

refactor: duplicate code and apply code review for lsp

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_317.f90
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_subroutine_registry.h
src/libasr/pass/intrinsic_subroutines.h
src/libasr/runtime/lfortran_intrinsics.c
src/runtime/builtin/lfortran_intrinsic_builtin.f90
tests/reference/asr-cmd_01-e172099.json
tests/reference/asr-cmd_01-e172099.stdout
tests/reference/asr-dependency_test_03-86dce2a.json
tests/reference/asr-dependency_test_03-86dce2a.stdout
tests/reference/asr-fn6-a24010a.json
tests/reference/asr-fn6-a24010a.stdout
tests/reference/asr-modules_48-6cf0505.json
tests/reference/asr-modules_48-6cf0505.stdout
tests/reference/asr-select_type_04-e8b402f.json
tests/reference/asr-select_type_04-e8b402f.stdout

Implement get_command_argument

---

.github/workflows/CI.yml

CI: pin micromamba to version '1.5.10-0'

---

integration_tests/declaration_01.f90
src/lfortran/semantics/ast_common_visitor.h

Currently on *main* for a Fortran program like below:
```f90
program declaration_01
implicit none
integer, parameter :: xi = 2
real, parameter :: xr = 2.0
! real array initialized with integer constant value
real, parameter :: x_real_3(3) = xi
end program declaration_01
```
and on compiling it with LFortran I get:
```console
$ lfortran test.90
LCOMPILERS_ASSERT failed: /Users/gxyd/Documents/lfortran/src/libasr/asr.h
function down_cast(), line number 41 at 
is_a<T>(*f)
[1]    4748 abort      /Users/gxyd/Documents/lfortran/src/bin/lfortran
```
```console
$ lfortran test.f90 --show-asr
(TranslationUnit
(SymbolTable
1
{
declaration_01:
(Program
(SymbolTable
2
{
x_real_3:
(Variable
2
x_real_3
[]
Local
(ArrayConstant
12
[2.00000000e+00, 2.00000000e+00, 2.00000000e+00]
(Array
(Real 4) …
```

Cast during initialization like: `REAL :: x(2) = 1`

---

src/bin/lfortran.cpp

With this and https://github.com/dylon/lfortran-lsp/pull/1, we can now right click on code and `Go To Definition`
It works on vscode-extension. The fundamental problem with this is, when we do `go to definition` on vscode, the cursor takes us on the same line that is moves a column right. This is because our current implementation returns location of that node, instead we should lookup symbol table and return that symbol. That would take us to correct definition. That is from LFortran side we can improve.

feat: integrate `--lookup-name` feature with lsp

---

src/lfortran/semantics/comptime_eval.h
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_subroutine_registry.h
src/libasr/pass/intrinsic_subroutines.h
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
src/runtime/impure/lfortran_intrinsic_math.f90

Towards: https://github.com/lfortran/lfortran/issues/4593

Implement `srand`

---

src/libasr/pass/intrinsic_subroutines.h

Fixes: https://github.com/lfortran/lfortran/issues/4950

chore: add warning for srand

---

integration_tests/CMakeLists.txt
integration_tests/func_parameter_type_02.f90
tests/reference/asr-func_parameter_type_02-cef1ab3.json
tests/reference/asr-func_parameter_type_02-cef1ab3.stdout
tests/tests.toml

Closes #4948
This PR Addresses [Issue #4948](https://github.com/lfortran/lfortran/issues/4948) (moved MRE into integration tests)

test: MRE moved to integration_tests

---

src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_utils.h
tests/errors/func_arg_array.f90
tests/reference/asr-func_arg_array-609769c.json
tests/reference/asr-func_arg_array-609769c.stderr
tests/tests.toml

This PR Checks for array compatibility when passed in a function as an argument. 
(My Previous Branch was facing some conflicts so I have made this new PR with same changes as before and removed unnecessary changes as mention by @certik).

enh: array passed in function compatibility checking

---

src/libasr/codegen/KaleidoscopeJIT.h
src/libasr/codegen/evaluator.cpp

Fixes: https://github.com/lfortran/lfortran/issues/4882

[LLVM] Fix warnings for LLVM 17 build

---

integration_tests/CMakeLists.txt
integration_tests/legacy_array_sections_05.f90
src/libasr/pass/pass_manager.h

Fixes https://github.com/lfortran/lfortran/issues/4983

chore: use simplifier pass with --fast and reorder passes

---

.github/workflows/CI.yml
src/libasr/pass/pass_manager.h

With this SNAP fully works on branch `simplifier_pass`

ci: enable SNAP with --fast

---

integration_tests/CMakeLists.txt
integration_tests/logical_not_01.f90
src/libasr/pass/simplifier.cpp

enh: handle `LogicalNot`

---

.github/workflows/CI.yml
src/libasr/pass/inline_function_calls.cpp

Fixes: https://github.com/lfortran/lfortran/issues/4981

[ASR Pass] Skip inlining of interface functions

---

integration_tests/CMakeLists.txt
integration_tests/string_39.f90
integration_tests/string_40.f90
integration_tests/subroutines_14.f90
src/libasr/pass/simplifier.cpp

Fixes #4995, #4999, #5000, #5001

chore: do not link target if value is string section and not an array

---

integration_tests/CMakeLists.txt
integration_tests/binop_of_struct_instance_in_function_call.f90

this helps have the test case directly in *main* instead of *simplifier_pass* branch

test: add MRE for dftatom as integration test case

---

integration_tests/intrinsics_301.f90
src/libasr/pass/intrinsic_array_function_registry.h

Fixes #4679.
Still not Complete. I am keeping it in draft.

fix: optional arguments in findLoc()

---

src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/comptime_eval.h
src/libasr/asr_builder.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h
src/runtime/builtin/lfortran_intrinsic_builtin.f90
tests/reference/asr-boz_01-dedad59.json
tests/reference/asr-boz_01-dedad59.stdout
tests/reference/asr-int_01-72c2ff1.json
tests/reference/asr-int_01-72c2ff1.stdout
tests/reference/asr-int_01-9bf3eb9.json
tests/reference/asr-int_01-9bf3eb9.stdout
tests/reference/asr-int_02-e7de6a7.json
tests/reference/asr-int_02-e7de6a7.stdout
tests/reference/asr-select_type_04-e8b402f.json
tests/reference/asr-select_type_04-e8b402f.stdout

Towards: #4593
Fixed: #4526, #4186, #4092, #3953,

feat: implement intrinsic `int` and remove old implementation

---

integration_tests/intrinsics_298.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/intrinsic_array_function_registry.h

fix: Args in dot_product of different types (int - real - complex) 

---

.github/workflows/CI.yml

I've used the Fortran compiler flag *--realloc-lhs*

CI: update the CI job for fastGPT

---

.github/workflows/CI.yml

check to see if the CI job passes or not

CI: uncomment test without LLVM backend

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/int_01.f90
tests/reference/asr-int_01-9bf3eb9.json
tests/reference/asr-int_01-9bf3eb9.stderr
tests/reference/asr-kind_01-6c675be.json
tests/reference/asr-kind_01-6c675be.stderr

Fixing: https://github.com/lfortran/lfortran/pull/5029#discussion_r1798310567

Throw error for non scalar kind arg in int intrinsic

---

src/libasr/runtime/lfortran_intrinsics.c

Needed for conda-forge packaging:
https://github.com/conda-forge/lfortran-feedstock/pull/98

Fix include for Apple

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_322.f90
src/libasr/pass/intrinsic_functions.h
tests/reference/llvm-string_11-e6c763f.json
tests/reference/llvm-string_11-e6c763f.stdout

Fixed: https://github.com/lfortran/lfortran/issues/5050

fix: consider last index correctly in `index` intrinsic 

---

integration_tests/CMakeLists.txt
integration_tests/generic_interface_function_call_of_function_call.f90

This test case is extracted from *stdlib* and being used as an MRE here: https://github.com/lfortran/lfortran/issues/4761#issuecomment-2399113188

test: add MRE for function call of a function call for a generic interface

---

integration_tests/intrinsics_288.f90
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/pass/intrinsic_array_function_registry.h

Fixes #4801.
I have Added more tests in `intrinsics_288.f90` (which is integration test for spread function).

fix: Spread error for Scalar Source in Spread function

---

integration_tests/CMakeLists.txt
integration_tests/arrays_54.f90
src/libasr/pass/simplifier.cpp

https://github.com/lfortran/lfortran/issues/5092

Fixes issues with simplification of `RealBinOp`

---

integration_tests/intrinsics_276.f90
integration_tests/intrinsics_277.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_function_registry.h
src/libasr/pass/intrinsic_functions.h

feat: Implemented 'or' and 'xor' intrinsic functions

---

src/bin/lfortran.cpp
src/libasr/pass/pass_manager.h
src/libasr/utils.h

Add experimental-simplifer flag to alter between two list of ASR passes to be used

Add experimental-simplifer flag 

---

src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_utils.cpp

This PR ports the LLVM backend changes from *simplifier_pass* branch to *main*

port llvm backend changes from simplifier_pass branch

---

integration_tests/CMakeLists.txt

Uncomment working test

---

src/libasr/pass/implied_do_loops.cpp
src/libasr/pass/init_expr.cpp
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h

sync:`implied_do_loops`, `init_expr`, `pass_utils.h/.cpp` with simplifier

---

src/libasr/pass/inline_function_calls.cpp
src/libasr/pass/instantiate_template.cpp

sync: `inline_function_calls` and `instantitate_template` pass

---

src/libasr/pass/intrinsic_functions.h

I'll first check to see if the CI passes with this change or not.

undo commented out 'Abs' argument check

---

integration_tests/CMakeLists.txt
integration_tests/arrays_54.f90
integration_tests/arrays_55.f90
integration_tests/arrays_56.f90

Ports some of the integration tests from https://github.com/lfortran/lfortran/pull/4700 to *main*. There are two programs which are commented out in this PR.
Once this PR is merged into *main*, and the PR for *merge main into simplifier pass* is created, the two commented out test cases need to uncommented.

port test programs from simplifier_pass PR

---

src/libasr/pass/intrinsic_functions.h

syn: intrinsic_functions.h with main

---

src/libasr/pass/subroutine_from_function.cpp

We already have `subroutine_from_function_simplifier.cpp` in our *main* and *simplifier_pass*, which are used.

sync back 'subroutine_from_function.cpp' with main

---

integration_tests/CMakeLists.txt
integration_tests/procedure_decl_01_a.f90
integration_tests/procedure_decl_01_b.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_verify.cpp

Fixes #5142 
Here I didn't add test because this issue needs 2 separated files.

fix: m_type_declaration corrected for procedure declaration

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_fortran.cpp
tests/reference/fortran-complex_to_complex_cast_fortran_codegen-d2ad266.json
tests/reference/fortran-complex_to_complex_cast_fortran_codegen-d2ad266.stdout
tests/reference/fortran-int_to_int_cast_fortran_codegen-913a36c.json
tests/reference/fortran-int_to_int_cast_fortran_codegen-913a36c.stdout
tests/reference/fortran-real_to_integer_cast_fortran_codegen-d0b1495.json
tests/reference/fortran-real_to_integer_cast_fortran_codegen-d0b1495.stdout

Fixes https://github.com/lfortran/lfortran/issues/5221

enh: Fortran backend to visit `Print` arguments

---

integration_tests/CMakeLists.txt
integration_tests/array_concat.f90
src/lfortran/semantics/ast_body_visitor.cpp

fix: Array in ArrayInitializer is checked before dimension error

---

integration_tests/CMakeLists.txt
integration_tests/external_09.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/reference/asr-func_parameter_type_02-cef1ab3.json
tests/reference/asr-func_parameter_type_02-cef1ab3.stdout

chore: clear external_procedure after visiting subroutine

---

integration_tests/CMakeLists.txt
integration_tests/data_13.f90
src/lfortran/semantics/ast_common_visitor.h

Partially fixes the issue https://github.com/lfortran/lfortran/issues/4680 (see MRE present here: https://github.com/lfortran/lfortran/issues/4680#issuecomment-2304233569)

chore: expect variable value for implied do loop start, end, increment in data statement

---

integration_tests/CMakeLists.txt
integration_tests/implicit_typing_03.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asr_builder.h

enh: declare implicit variable logic to handle parameter value

---

.github/workflows/CI.yml

This PR does the following changes:
* Merges `Test LLVM WASM` to `Test LLVM` thus freeing up 2 jobs.

ci: merge `test_llvm_wasm` to `test_llvm` and test WASM for LLVM 10 and 19

---

integration_tests/CMakeLists.txt
integration_tests/arrays_reshape_18.f90
src/lfortran/semantics/ast_common_visitor.h

Fixes #5258. With this we can revert https://github.com/Pranavchiku/prima/commit/0d4240bc9094159260ff1d2334f1e8d4356b5782

enh: frontend to support keyword argument in array reshape

---

integration_tests/CMakeLists.txt
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/pass/simplifier.cpp

cc: @certik 
Closes https://github.com/lfortran/lfortran/issues/5201

DEV: Added simplification in `ArraySize` for type

---

integration_tests/CMakeLists.txt
integration_tests/procedure_06.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/transform_optional_argument_functions.cpp

Fixes #5141. I am not confident with the fix, may break a few CI tests. With this we can revert https://github.com/Pranavchiku/prima/commit/902950a8caf980910db4df4127dcca9356c9e241

enh: frontend to support procedure call

---

.vscode/launch.json
src/lfortran/semantics/ast_common_visitor.h
src/libasr/asdl_cpp.py
src/libasr/asr_utils.h
tests/errors/program_variable.f90
tests/reference/asr-program_variable-066cc64.json
tests/reference/asr-program_variable-066cc64.stderr
tests/tests.toml

Semantics: check that Var is either Variable or Function

---

integration_tests/CMakeLists.txt
integration_tests/where_13.f90
src/libasr/pass/where.cpp

fix: handling of `where` on elemental function with array argument

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_325.f90
src/libasr/pass/intrinsic_array_function_registry.h

enh: support integer(8) in spread intrinsic

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/data_implied_do1.f90
tests/errors/data_implied_do2.f90
tests/errors/data_implied_do3.f90
tests/reference/asr-data_implied_do1-87a7869.json
tests/reference/asr-data_implied_do1-87a7869.stderr
tests/reference/asr-data_implied_do2-fc94c6e.json
tests/reference/asr-data_implied_do2-fc94c6e.stderr
tests/reference/asr-data_implied_do3-831f843.json
tests/reference/asr-data_implied_do3-831f843.stderr
tests/tests.toml

fix: PR#5247 by applying review

---

src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/reference/llvm-modules_38-8886f9a.json
tests/reference/llvm-modules_38-8886f9a.stdout

ref: frontend to not create Enum_t instead add symbols in parent_scope

---

ci/environment.yml
ci/environment_docs_linux.yml
ci/environment_linux.yml
ci/environment_linux_llvm.yml

These versions are known to work. Install a specific cmake version, which should fix #5321.
Fixes #5321.

CI: set the packages to specific versions

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/array_size_01_cc.f90
tests/reference/run-array_size_01_cc-9335a32.json
tests/reference/run-array_size_01_cc-9335a32.stderr
tests/reference/run-array_size_01_cc-9335a32.stdout
tests/tests.toml

feat: error resilient intrinsic function

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/array_shape_01_cc.f90
tests/reference/run-array_shape_01_cc-098a6d5.json
tests/reference/run-array_shape_01_cc-098a6d5.stderr
tests/reference/run-array_shape_01_cc-098a6d5.stdout
tests/tests.toml

feat: error resilient array shape/dimension

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/arithmetic_if1_cc.f90
tests/errors/array_04_cc.f90
tests/errors/array_05_cc.f90
tests/errors/array_06_cc.f90
tests/errors/array_shape_01_cc.f90
tests/errors/array_size_01_cc.f90
tests/errors/array_size_02_cc.f90
tests/reference/asr-array_size_02-94fb4d3.json
tests/reference/asr-array_size_02-94fb4d3.stderr
tests/reference/run-arithmetic_if1_cc-87bcd45.json
tests/reference/run-array_04_cc-c986e51.json
tests/reference/run-array_05_cc-4c5cdb4.json
tests/reference/run-array_06_cc-e5490ba.json
tests/reference/run-array_shape_01_cc-098a6d5.json
tests/reference/run-array_size_01_cc-9335a32.json
tests/reference/run-array_size_02_cc-c7cec87.json
tests/reference/run-array_size_02_cc-c7cec87.stderr
tests/reference/run-array_size_02_cc-c7cec87.stdout
tests/tests.toml

feat: error resilient dim in size intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/arrays_57.f90
src/libasr/asr_utils.h

enh: make_array_size_t_util to support IntrinsicArrayFunction

---

src/bin/lfortran.cpp
src/lfortran/fortran_evaluator.cpp
src/lfortran/parser/preprocessor.h
src/lfortran/parser/preprocessor.re
tests/errors/cpp_err1.f90
tests/errors/cpp_err2.f90
tests/errors/cpp_err3.f90
tests/errors/cpp_err4.f90
tests/errors/cpp_err5.f90
tests/errors/cpp_err6.f90
tests/reference/asr_preprocess-cpp_err1-3303e2d.json
tests/reference/asr_preprocess-cpp_err1-3303e2d.stderr
tests/reference/asr_preprocess-cpp_err2-aa1ccd3.json
tests/reference/asr_preprocess-cpp_err2-aa1ccd3.stderr
tests/reference/asr_preprocess-cpp_err3-a7ea818.json
tests/reference/asr_preprocess-cpp_err3-a7ea818.stderr
tests/reference/asr_preprocess-cpp_err4-9f3b813.json
tests/reference/asr_preprocess-cpp_err4-9f3b813.stderr
tests/reference/asr_preprocess-cpp_err5-38d12de.json
tests/reference/asr_preprocess-cpp_err5-38d12de.stderr
tests/reference/asr_preprocess-cpp_err6-47462f4.json
tests/reference/asr_preprocess-cpp_err6-47462f4.stderr
tests/tests.toml

Location information was added. Test several of them.
Later the preprocessor can be upgraded to be error resilient.

Make the preprocessor return regular error messages

---

tests/fixedform_doloop3.f
tests/reference/ast-fixedform_doloop3-d579f3c.json
tests/reference/ast-fixedform_doloop3-d579f3c.stdout

Fixes https://github.com/lfortran/lfortran/issues/5341 (considering that issue is valid)

use correct way of initialization in test case

---

src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
tests/errors/continue_compilation_2.f90
tests/reference/run-continue_compilation_2-3499257.json
tests/reference/run-continue_compilation_2-3499257.stderr
tests/reference/run-continue_compilation_2-3499257.stdout
tests/tests.toml

Towards: https://github.com/lfortran/lfortran/issues/5036

feat: error resilient errors

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/array_size_04.f90
tests/errors/array_size_05_cc.f90
tests/reference/asr-array_size_04-dcfa313.json
tests/reference/asr-array_size_05-bc7d72f.json
tests/reference/run-array_size_05_cc-98734df.json
tests/reference/run-array_size_05_cc-98734df.stderr
tests/reference/run-array_size_05_cc-98734df.stdout
tests/tests.toml

feat: error resilient kind parameter for intrinsics

---

integration_tests/CMakeLists.txt
integration_tests/arrays_58.f90
src/libasr/pass/intrinsic_function.cpp

enh: intrinsic function pass to allocate temporary of intrinsic Transpose

---

integration_tests/intrinsics_326.f90

Resolves https://github.com/lfortran/lfortran/pull/5376#discussion_r1840239737

test: initialize subd_test in intrinsics_326 correctly

---

.github/workflows/CI.yml
ci/environment_docs_linux.yml
ci/environment_linux.yml
ci/environment_linux_llvm.yml

Follow up on #5322.
Fixes #5395.

CI: Set specific version of cmake

---

src/lfortran/semantics/ast_symboltable_visitor.cpp

Addresses https://github.com/lfortran/lfortran/pull/5329#discussion_r1842730907

chore: fix comment punctuations

---

src/lfortran/semantics/ast_common_visitor.h

Ref: append errors in diagnostics for `ast_common_visitor` file and removed Semantic Errors

---

src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-subroutine2-2e9b84b.json
tests/reference/asr-subroutine2-2e9b84b.stderr

Ref: removed all throw semantic errors from `ast_common_visitor` file

---

src/lfortran/semantics/ast_symboltable_visitor.cpp

Enh: refactor semantic errors in ast_symboltable_visitor file

---

src/lfortran/semantics/asr_implicit_cast_rules.h
src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/lfortran/semantics/comptime_eval.h
src/libasr/asr_utils.h
src/libasr/pass/instantiate_template.cpp
tests/reference/asr-kind_float_of_int-4b9cf53.json
tests/reference/asr-kind_float_of_int-4b9cf53.stderr
tests/reference/asr-kind_string_of_int-ed0ec70.json
tests/reference/asr-kind_string_of_int-ed0ec70.stderr

Enh: refactor semantic errors in all the files

---

tests/errors/continue_compilation_2.f90
tests/reference/run-continue_compilation_2-3499257.json
tests/reference/run-continue_compilation_2-3499257.stderr

feat: add more error tests with continue compilation flag

---

integration_tests/CMakeLists.txt

Fix a cmake warning

---

src/lfortran/semantics/ast_body_visitor.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/lfortran/semantics/semantic_exception.h
src/libasr/semantic_exception.h

ref: remove semantic error class

---

integration_tests/CMakeLists.txt
integration_tests/modules_59.f90
src/libasr/asr_utils.h

Chore : Add implementation to duplicate generic procedure

---

integration_tests/CMakeLists.txt
integration_tests/functions_25.f90

Already works just added a test.
https://github.com/lfortran/lfortran/issues/4761#issuecomment-2421723196

TEST: Added regression test for `stdlib` MRE

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_328.f90
src/libasr/pass/function_call_in_declaration.cpp

Closes https://github.com/lfortran/lfortran/issues/5007

DEV: Fix function_call_in_declaration to visit nested Functions

---

src/libasr/lsp.cpp
tests/reference/lookup_name-function_call1-c233951.json
tests/reference/lookup_name-function_call1-c233951.stdout
tests/reference/lookup_name-lookup_name1-9a3abcc.json
tests/reference/lookup_name-lookup_name1-9a3abcc.stdout

Refer https://github.com/lfortran/lfortran/issues/5420

enh: `--lookup-name` to return symbol name

---

tests/errors/continue_compilation_1.f90
tests/errors/matrix_matmul_03.f90
tests/errors/matrix_matmul_04.f90
tests/errors/matrix_matmul_05.f90
tests/errors/matrix_matmul_06.f90
tests/errors/merge_bits_run.f90
tests/reference/asr-matrix_matmul_03-a99cdd1.json
tests/reference/asr-matrix_matmul_04-90da47c.json
tests/reference/asr-matrix_matmul_05-c57a23d.json
tests/reference/asr-matrix_matmul_06-d802f54.json
tests/reference/asr-merge_bits_run-9579699.json
tests/reference/run-continue_compilation_1-08988e5.json
tests/reference/run-continue_compilation_1-08988e5.stderr
tests/reference/run-continue_compilation_1-08988e5.stdout
tests/tests.toml

feat: add error tests with continue-compilation flag

---

build1.bat
build1.sh
build_release.sh

Use `ninja` for generating build files and `ccache` for caching compilation.

build: use `ninja` for build

---

integration_tests/CMakeLists.txt
integration_tests/parameter_15.f90
src/lfortran/semantics/ast_common_visitor.h

Fixes: https://github.com/lfortran/lfortran/issues/5478

fix: Handle type casting when assigning to parameter

---

integration_tests/CMakeLists.txt
integration_tests/fortran_02.f90
src/libasr/codegen/asr_to_fortran.cpp

Towards [fortran_backend](https://github.com/lfortran/lfortran/issues/5260)
This PR aims to write doconcurrent visitor for fortran backend

Enh: Fortran-Backend: DoConcurrentLoop Visitor

---

integration_tests/CMakeLists.txt
integration_tests/openmp_40.f90
src/libasr/pass/openmp.cpp

Towards #4900
Intended towards correctly calculating total number of iterations in Multiple Headed DoConcurrentLoop.

feat: Multiple Headed DoConcurrentLoop Total Iterations

---

integration_tests/inquire_01.f90
src/libasr/codegen/asr_to_llvm.cpp

Allow for allocatable file names in file inquire

---

integration_tests/CMakeLists.txt
integration_tests/read_01.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h

feat: support list directed input for `character`, `integer` and `real`

---

integration_tests/CMakeLists.txt
integration_tests/array_indices_array_section.f90
src/libasr/pass/array_op.cpp
src/libasr/pass/array_op_simplifier.cpp
src/libasr/pass/simplifier.cpp

Remove ``NO_EXPERIMENTAL_SIMPLIFIER`` from ``integration_tests/array_indices_array_section.f90``

---

integration_tests/CMakeLists.txt
integration_tests/line_continuation_04.f90
src/lfortran/parser/parser.cpp

Fixes https://github.com/lfortran/lfortran/issues/4770

fix: in a string with '&' and '!' together isn't a comment

---

integration_tests/CMakeLists.txt
integration_tests/procedure_07.f90
src/libasr/pass/pass_array_by_data.cpp
src/libasr/pass/transform_optional_argument_functions.cpp

fix: Support type declared procedure in `pass_array_by_data`

---

grammar/AST.asdl
src/lfortran/parser/semantics.h
src/libasr/ASR.asdl
src/libasr/asr_lookup_name.h
tests/collect_occurence4.f90
tests/reference/rename_symbol-collect_occurence4-9f1ef3e.json
tests/reference/rename_symbol-collect_occurence4-9f1ef3e.stdout
tests/tests.toml

Towards https://github.com/lfortran/lfortran/issues/5558

feat: propagate location information of `Module`, `SubModule` and `Subroutine`

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_159.f90
src/libasr/asr_builder.h
src/libasr/asr_utils.h
src/libasr/asr_verify.cpp
src/libasr/pass/array_op_simplifier.cpp
src/libasr/pass/implied_do_loops.cpp
src/libasr/pass/simplifier.cpp

Remove ``NO_EXPERIMENTAL_SIMPLIFIER`` from ``intrinsics_159.f90`` and ``array_indices_array_item.f90``

---

integration_tests/CMakeLists.txt
integration_tests/fortuno_01.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/codegen/asr_to_llvm.cpp

Fixes: https://github.com/lfortran/lfortran/issues/5515

enh: support StructInstanceMember in SelectType

---

.github/workflows/CI.yml

Branch: https://github.com/Pranavchiku/prima/tree/lf13
commit: https://github.com/Pranavchiku/prima/commit/b3f5b55c94b3b0b2568fe9af97a8e34a48cac7b4

ci: setup prima

---

src/bin/lfortran.cpp

Now, there are two ways to specify the linker and their path:
- Using `--linker` and `--linker-path` options
- Using environment variable `LFORTRAN_LINKER` and `LFORTRAN_LINKER_PATH`
Usage:
```console
$ lfortran x.f90 --linker=gcc
$ lfortran x.f90 --linker-path=/usr/bin
$ lfortran x.f90 --linker=gcc --linker-path=/usr/bin
```
```console
$ export LFORTRAN_LINKER=gcc
$ export LFORTRAN_LINKER_PATH=/usr/bin/
$ lfortran x.f90
```
Towards: https://github.com/lfortran/lfortran/issues/5526

fix: Add two new options `--linker` and `--linker-path`

---

integration_tests/modules_56.f90

Update modules_56.f90 and remove the CI error

---

integration_tests/CMakeLists.txt
integration_tests/read_02.f90
integration_tests/read_02_data.txt
src/libasr/runtime/lfortran_intrinsics.c

fixes #5576 and https://github.com/lfortran/lfortran/issues/5545#issuecomment-2513454447.

fix: use a temporary buffer with `fgets()` for formatted read

---

CMakeLists.txt
ci/test_cpp_version.xsh
src/bin/CMakeLists.txt

Keep this option off by default for speed of compilation

Add WITH_BENCHMARKS cmake option

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/continue_compilation_2.f90
tests/reference/asr-continue_compilation_2-a6145a1.json
tests/reference/asr-continue_compilation_2-a6145a1.stderr

fix: resolved failing of continue compilation flag for error files for different kinds

---

integration_tests/CMakeLists.txt
integration_tests/subroutines_15.f90
src/libasr/pass/transform_optional_argument_functions.cpp

Change accessing optional arguments which are out of bounds

---

doc/src/usage.md

Added all the valid standard options. fixes issue #4773  .

Added valid standard options

---

src/lfortran/semantics/ast_symboltable_visitor.cpp
tests/errors/continue_compilation_2.f90
tests/reference/asr-continue_compilation_2-a6145a1.json
tests/reference/asr-continue_compilation_2-a6145a1.stderr

fix: skipped errors for common1.f90 file provided continue-compilation flag

---

integration_tests/procedure_07.f90
integration_tests/procedure_08.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/pass_array_by_data.cpp
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
src/libasr/pass/transform_optional_argument_functions.cpp

fix: Added `m_type_declaration` info and use function ptr directly 

---

src/libasr/asr_utils.h
src/libasr/pass/array_op_simplifier.cpp

Addresses reviews in https://github.com/lfortran/lfortran/pull/5670#pullrequestreview-2500631859
Should be quick to go in. Rest of the changes please feel free to open issue for it. I will look at those later.

DEV: Improvise refactoring of code in ``array_op_simplifier.cpp``

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_mlir.cpp

[MLIR] Handle and fix Print and FileWrite node

---

integration_tests/CMakeLists.txt
integration_tests/print_arr_07.f90
src/lfortran/fortran_evaluator.cpp
src/libasr/codegen/asr_to_mlir.cpp

feat: [MLIR] Add basic fixed array support

---

integration_tests/CMakeLists.txt
integration_tests/procedure_09_a.f90
integration_tests/procedure_09_b.f90
src/libasr/pass/transform_optional_argument_functions.cpp

Fix: Add `FunctionType` info in transform_optional_argument pass

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_fortran.cpp

Fixes #4113 . Please have a look.

fortran backend: implieddoLoop support added

---

.github/workflows/CI.yml

https://github.com/lfortran/lfortran/issues/5717

CI: Test dftatom with ``--experimental-simplifier --fast``

---

run_tests.py
src/lfortran/parser/parser.cpp
tests/errors/program_without_line_cc.f90
tests/reference/asr-program_without_line_cc-78281a4.json
tests/reference/asr-program_without_line_cc-78281a4.stderr
tests/reference/asr-program_without_line_cc-78281a4.stdout
tests/tests.toml

fix: program without line generates ast with continue compilation flag

---

integration_tests/CMakeLists.txt
integration_tests/string_42.f90
src/lfortran/semantics/ast_body_visitor.cpp

Fix : Read from allocatable string

---

src/lfortran/tests/test_cmake_integration.sh
src/lfortran/tests/test_cmake_integration/CMakeLists.txt
src/lfortran/tests/test_cmake_integration/hello.f90

test: add minimal cmake integration testing

---

run_tests.py
src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-program_without_line_cc-b84ba02.json
tests/reference/asr-program_without_line_cc-b84ba02.stderr
tests/reference/asr-program_without_line_cc-b84ba02.stdout
tests/tests.toml

fix: asr generates with cc flag for program without line files

---

.github/workflows/CI.yml

commit: https://github.com/Pranavchiku/prima/commit/6e61b35d4530ebc7e4ed3c5cc1c1594f25b4570b#diff-5ac3fadf8e555686a6645d153e95a4e53fdb95508a916ceb4b053bf11b375786R193
branch: https://github.com/Pranavchiku/prima/tree/lf20

CI: test PRIMA on CI

---

integration_tests/CMakeLists.txt
integration_tests/procedure_12.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

Fix: Support for self-referencing procedure declaration

---

integration_tests/CMakeLists.txt
integration_tests/procedure_11.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

fix: visit procedure declaration after visiting func/subrout in `ast_symboltable_visitor`

---

src/libasr/codegen/asr_to_mlir.cpp

Fixes: https://github.com/lfortran/lfortran/issues/5693

[MLIR] Add '\0' to StringAttr to fix printing the garbage value

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_mlir.cpp

Fixes: https://github.com/lfortran/lfortran/issues/5726

[MLIR] Support ArrayBound visitor

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_mlir.cpp

[MLIR] Support more visitors

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_mlir.cpp

[MLIR] Support WhileLoop

---

src/libasr/asdl_cpp.py

rem: setting loc information while deserialzing to zero

---

integration_tests/procedure_10.f90
integration_tests/procedure_11.f90
src/libasr/asr_utils.h

fix: allow procedure pointer initialisation with Var

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_333.f90
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/pass/implied_do_loops.cpp
src/libasr/pass/pass_utils.cpp

After there is a bug in ASR to LLVM pass. I will see what's causing the issue.

DEV: Fixes for implied_do_loops pass

---

.github/workflows/CI.yml

https://github.com/lfortran/lfortran/issues/5717

CI: Compile PRIMA with `--experimental-simplifier`

---

src/libasr/lsp.cpp
tests/reference/lookup_name-function_call1-c233951.json
tests/reference/lookup_name-function_call1-c233951.stdout
tests/reference/lookup_name-lookup_name1-9a3abcc.json
tests/reference/lookup_name-lookup_name1-9a3abcc.stdout
tests/reference/lookup_name-lookup_name2-458b8c9.json
tests/reference/lookup_name-lookup_name2-458b8c9.stdout

enh: output of `--lookup-name` by appending filename

---

src/lfortran/parser/semantics.h
tests/errors/continue_compilation_3.f90
tests/reference/asr-continue_compilation_3-435a232.json
tests/reference/asr-continue_compilation_3-435a232.stderr

fix: incorrect_pragma generates ast and asr with cc flag

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_mlir.cpp

[MLIR] Visit Modules in the TranslationUnit scope

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_mlir.cpp

[MLIR] Add support for more nodes

---

src/lfortran/parser/semantics.h
tests/errors/continue_compilation_2.f90
tests/reference/asr-continue_compilation_2-a6145a1.json
tests/reference/asr-continue_compilation_2-a6145a1.stderr

fix: unsupported kind error generates ast and asr with cc flag

---

integration_tests/CMakeLists.txt
integration_tests/string_43.f90
src/lfortran/semantics/ast_common_visitor.h

Fixes: https://github.com/lfortran/lfortran/issues/5845

enh: handle character array for string concat

---

integration_tests/CMakeLists.txt
integration_tests/string_44.f90
src/lfortran/semantics/ast_body_visitor.cpp

Fixes: https://github.com/lfortran/lfortran/issues/5838

Handle allocatable strings for select case

---

integration_tests/CMakeLists.txt
src/libasr/codegen/asr_to_mlir.cpp

[MLIR] Handle PointerToDataArray array as arg to a FunctionCall

---

integration_tests/CMakeLists.txt
integration_tests/openmp_42.f90
integration_tests/openmp_43.f90
src/lfortran/semantics/ast_body_visitor.cpp

Towards #5871 
Refer [comment](https://github.com/lfortran/lfortran/issues/5871#issuecomment-2565649784)
MRE 
```fortran
program openmp_43
use omp_lib
! declare variables as required
integer :: ny, nx, nz  , i,j
integer :: iy, ix, iz
ny=3
nx=4
nz=5
do j=1,2
do i =1,3
!$omp parallel do collapse(2) private(iy, ix, iz)
do iy = 1, ny
do ix = 1, nx
do iz = 1, nz
print *,"iy->", iy,"ix->", ix,"iz->", iz
end do
end do
end do
!$omp end parallel do
end do
end do
end program
```
On Main branch 
We get this 
```console
(DoLoop
()
((Var 2 j)
(IntegerConstant 1 (Integer 4) Decimal)
(IntegerConstant 2 (Integer 4) Decimal)
())
[(DoLoop
()
((Var 2 i)
(IntegerConstant 1 (Integer 4) Decimal)
(IntegerConstant 3 (Integer 4) Decimal)
())
[(DoConcurrentLoop
[((Var 2 iy)
(IntegerConstant 1 (Integer 4) Decimal) …
```

Handle Nesting level of Pragma directive for Collapse clause

---

doc/src/installation.md

docs: include dependency for source tarball installation and fix `cd` command

---

.github/workflows/CI.yml

With this for `bobyqa_example_1`, LFortran gives exact same output as GFortran.

CI: Update CI for PRIMA

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_336.f90
src/libasr/codegen/asr_to_fortran.cpp

Fixes: https://github.com/lfortran/lfortran/issues/2529

Add test for to check array `mask` arg of `any` intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/polymorphic_arguments_01.f90
integration_tests/polymorphic_arguments_02.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/asr_utils.h
tests/reference/asr-polymorphic_arguments_02-bb6f3e2.json
tests/reference/asr-polymorphic_arguments_02-bb6f3e2.stdout
tests/tests.toml

enh: add support for passing argument of any type to a polymorphic function parameter

---

integration_tests/CMakeLists.txt
integration_tests/pass_array_by_data_10.f90
src/libasr/pass/pass_array_by_data.cpp

fix: handling of nested pass array by data functions

---

.github/workflows/CI.yml

This just tests the following commit: https://github.com/libprima/prima/commit/811948c319aa8f05e6cfb2faedc0334124d77670.

CI: update PRIMA to test more thoroughly

---

.github/workflows/CI.yml
ci/environment_linux.yml
ci/test_cpp_version.xsh
ci/test_without_llvm_backend.xsh
environment_linux.yml
integration_tests/CMakeLists.txt
integration_tests/format_04.f90

We have a hard dependency on `libunwind` for LLVM > 11.

ci: resolve failures

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_342.f90
src/libasr/intrinsic_func_registry_util_gen.py
src/libasr/pass/intrinsic_array_function_registry.h

Towards: https://github.com/lfortran/lfortran/issues/5938
There's one more issue to be handled.

fix: handle allocatable arrays with spread

---

integration_tests/matrix_02_matmul.f90
tests/reference/asr-matrix_02_matmul-d389302.json
tests/reference/asr-matrix_02_matmul-d389302.stdout

Fixes #6019 
Initialize the variables to fixed values

fix: Initialize variable to values in test matrix_02_matmul

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_343.f90
src/libasr/pass/simplifier.cpp

Closes https://github.com/lfortran/lfortran/issues/5912

Fix ``cshift`` for 1D case

---

integration_tests/CMakeLists.txt

tests: add `NOFAST` label for test `pass_array_by_data_05.f90`

---

integration_tests/run_tests.py

fix: integration test runner

---

integration_tests/CMakeLists.txt
integration_tests/arrays_05_size.f90

Fixes #5060 
Just added test to close the issue as things are running well in main.

test : Add test for external integer with kind 8 used as array size 

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/continue_compilation_1.f90
tests/reference/asr-continue_compilation_1-04b6d40.json
tests/reference/asr-continue_compilation_1-04b6d40.stderr

fix: throw error for non-scalar in selected_int_kind, selected_real_kind, selected_char_kind

---

.github/workflows/CI.yml
integration_tests/functions_30.f90
src/libasr/pass/simplifier.cpp

fix: Create temporary for scalar function with lhs array variable is one of its argument

---

src/libasr/pass/simplifier.cpp

Towards #6084. Sample PR to show how we can proceed towards cleaning up all macros from simplifier pass.

rem: macro `transform_stmts_impl` from simplifier pass

---

.github/workflows/CI.yml

This is only for test if everything works fine or not for `cleaned_branch` after removing workarounds.

ci: test PRIMA workaround `cleaned_branch`

---

src/libasr/pass/simplifier.cpp

Towards #6084 
- Remove the macro of `call_create_and_allocate_temporary_variable` from simplifier pass and update the related call of macro in the simplifier pass.

rem: macro `call_create_and_allocate_temporary_variable` from simplifier pass

---

src/libasr/codegen/asr_to_llvm.cpp

Based on https://github.com/lfortran/lfortran/pull/6091#pullrequestreview-2571009987

enh : Create function for loading deep copy of array size

---

src/libasr/pass/simplifier.cpp

Towards #6084 
- Removes following macros:
1. `BEGIN_VAR_CHECK`
2. `END_VAR_CHECK`
3. `is_current_expr_linked_to_target`
4. `check_if_ASR_owner_is_module`
5. `check_if_ASR_owner_is_enum`
6. `check_if_ASR_owner_is_struct`

refactor: remove macros and created function

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-continue_compilation_1-04b6d40.json
tests/reference/asr-continue_compilation_1-04b6d40.stderr

Apply suggestion from the #6107

improve error message in If for expression not logical

---

src/libasr/pass/simplifier.cpp

Towards #6084 
- Removes following macros:
1. `replace_expr_with_temporary_variable`
2. `force_replace_current_expr_for_array`
3. `force_replace_current_expr_for_struct`
4. `force_replace_current_expr_for_scalar`
5. `replace_current_expr`
6. `generate_associate_for_array_section`
7. `check_for_var_if_array`
8. `check_if_linked_to_target`

refactor: use function instead of macros

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_347.f90
src/libasr/pass/print_arr.cpp

Fixes: https://github.com/lfortran/lfortran/issues/6126

fix: handle dims correctly in print_arr pass

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_346.f90
src/lfortran/semantics/ast_common_visitor.h

Towards: https://github.com/lfortran/lfortran/issues/5143#issue-2609982523
Fixes the second program.

Handle null string correctly 

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_350.f90
src/libasr/pass/simplifier.cpp

fix: allocating to temporary created for spread intrinsic

---

src/libasr/pass/simplifier.cpp

Fixes: #6084 
- Removes macro `is_current_expr_linked_to_target_then_return` and used function instead of that.

rem: macro `is_current_expr_linked_to_target_then_return` from simplifier pass

---

integration_tests/intrinsics_39.f90
src/libasr/pass/intrinsic_subroutines.h
src/libasr/runtime/lfortran_intrinsics.c
src/libasr/runtime/lfortran_intrinsics.h
tests/reference/asr-intrinsics_39-f721e16.json

Towards: https://github.com/lfortran/lfortran/issues/6192

enh: support `values` in date_and_time intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_40.f90
src/libasr/pass/pass_array_by_data.cpp

feat: add support for Struct procedure Variables in `pass_array_by_data`

---

src/libasr/asr_scopes.h
src/libasr/pass/function_call_in_declaration.cpp

Based on comment https://github.com/lfortran/lfortran/pull/6235#discussion_r1945303607

enh : Add method to find global scope of any scope in SymbolTable

---

integration_tests/derived_types_40.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/pass_array_by_data.cpp

With this and https://github.com/Pranavchiku/prima/commits/test_uobyqa-1 `test_uobyqa-1` works well with LFortran

fix: create load when associate value is Struct procedure Member

---

integration_tests/arrays_10_size.f90
src/libasr/pass/function_call_in_declaration.cpp

enh: Support ExternalSymbols in function_call_in_declaration pass

---

integration_tests/arrays_10_size.f90
src/libasr/pass/function_call_in_declaration.cpp

Removes https://github.com/Pranavchiku/prima/commit/e79ec797d7806977c9e679972d665493d1b4c93a

enh: support negative vars in `function_call_in declaration`

---

.github/workflows/CI.yml

With #6272, this is updated PRIMA branch.

ci: update PRIMA CI (Removed Workarounds)

---

.github/workflows/CI.yml

CI: Update for compiling Numerical Methods Fortran

---

.github/workflows/CI.yml

We are able to run only one test on CI for linux: `test_uobyqa.f90`

ci: test if prima linux tests works

---

integration_tests/sign_from_value.f90
tests/reference/asr-sign_from_value-b974070.json
tests/reference/asr-sign_from_value-b974070.stdout
tests/reference/pass_sign_from_value-sign_from_value-ba1c944.json
tests/reference/pass_sign_from_value-sign_from_value-ba1c944.stdout

Adding removed test from this PR #6306

Test : Revert removed test ( Adding it back )

---

integration_tests/CMakeLists.txt

https://github.com/lfortran/lfortran/issues/6333

TEST: Remove NOFAST from `integration_tests/CMakeLists.txt`

---

integration_tests/CMakeLists.txt

https://github.com/lfortran/lfortran/issues/6333

TEST: Remove NOFAST tags from integration_tests/CMakeLists.txt

---

integration_tests/CMakeLists.txt

https://github.com/lfortran/lfortran/issues/6333

TEST: Remove NOFAST tags from ``integration_tests/CMakeLists.txt``

---

.github/workflows/CI.yml

That way we can ensure that the downloaded file is correct.
Towards #6318.

CI: print the SHA256 of model.dat to check it

---

.github/workflows/CI.yml

Removes : https://github.com/Pranavchiku/prima/commit/c838496e349bb6db6e5d67a9737ef49683614c7f

ci: remove PRIMA workarounds

---

integration_tests/array_section_04.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/array_passed_in_function_call.cpp

enh: Support FunctionCall in descriptor temporary pass

---

integration_tests/legacy_array_sections_02.f90

Addresses https://github.com/lfortran/lfortran/pull/6404#pullrequestreview-2640950082, test for commit https://github.com/lfortran/lfortran/pull/6404/commits/d43d1b7dbad5e0a592f57d3a255752a1cf8d1962.

test: add test for correct dimensions of `legacy_array_sections`

---

.github/workflows/CI.yml
Dockerfile
integration_tests/CMakeLists.txt
integration_tests/intrinsics_367.f90
src/libasr/runtime/lfortran_intrinsics.c

fix: `get_environment_variable` to return asked variable

---

.github/workflows/CI.yml

ci: switch OS for prima tests

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/nullify_05.f90
src/libasr/codegen/asr_to_fortran.cpp
src/libasr/codegen/asr_to_llvm.cpp

Fixes #6440 and remove workaround from PRIMA.

Fix: Handle external symbol in nullify and update prima CI

---

src/lfortran/semantics/ast_common_visitor.h
tests/errors/continue_compilation_1.f90
tests/reference/asr-continue_compilation_1-04b6d40.json
tests/reference/asr-continue_compilation_1-04b6d40.stderr

throw error when shape argument in reshape in not fixed size array

---

integration_tests/CMakeLists.txt
integration_tests/data_15.f90
src/libasr/pass/pass_utils.cpp
src/libasr/pass/pass_utils.h
tests/reference/llvm-implicit_interface_04-9b6786e.json
tests/reference/llvm-implicit_interface_04-9b6786e.stdout
tests/reference/pass_init_expr-array13-db4fb0f.json
tests/reference/pass_init_expr-array13-db4fb0f.stdout

fixes https://github.com/lfortran/lfortran/issues/5532

[LAPACK] Support multi-dim array in `DATA` statement

---

src/bin/lfortran_lsp_language_server.cpp
src/bin/lfortran_lsp_language_server.h

Uses LFortran to highlight symbol occurrences.

Adds support for highlighting symbols with lfortran

---

src/bin/lfortran_lsp_language_server.cpp

Changes:
* BUGFIX: Renames symbols across files
* BUGFIX: Only highlights symbol occurrences within the same file
Root cause: I did not realize that `LCompilers::LFortran::OccurenceCollector` returned references to the symbol from all files.

Fixes a bug that treated all symbol occurrences as being within the same file

---

integration_tests/intrinsics_309.f90
src/lfortran/semantics/ast_common_visitor.h

Towards #6309
Fixes MRE at https://github.com/lfortran/lfortran/issues/6309#issuecomment-2659025725

enh: support initial bool support in implied do loop values visitor

---

integration_tests/CMakeLists.txt
src/libasr/pass/transform_optional_argument_functions.cpp

fixes: https://github.com/lfortran/lfortran/issues/6599

Fix argument insertion to include non-optional arguments

---

src/libasr/compiler_tester/tester.py

tests: remove test references before updating

---

integration_tests/intrinsics_148.f90
src/lfortran/semantics/asr_implicit_cast_rules.h

fixes: https://github.com/lfortran/lfortran/issues/6636

fix: handle typecasting correctly

---

integration_tests/transfer_01.f90
src/lfortran/semantics/ast_common_visitor.h

fix: handle real type correctly in compiletime `transfer`

---

integration_tests/CMakeLists.txt
integration_tests/bindc_05.f90
integration_tests/bindc_05c.c
src/libasr/pass/subroutine_from_function.cpp

Handle type(C_PTR) return type from Bind(C) FunctionCalls

---

integration_tests/CMakeLists.txt
integration_tests/class_15.f90
src/lfortran/semantics/ast_common_visitor.h
tests/errors/continue_compilation_1.f90
tests/reference/asr-continue_compilation_1-04b6d40.json
tests/reference/asr-continue_compilation_1-04b6d40.stderr

fixes: https://github.com/lfortran/lfortran/issues/6750

fix: handle optional keyword args correctly for class procedure

---

ci/test.sh
src/bin/language_server_interface.cpp
src/bin/language_server_interface.h
src/bin/lfortran_lsp_language_server.cpp
src/bin/lfortran_lsp_language_server.h
src/server/base_lsp_language_server.cpp
src/server/base_lsp_language_server.h
src/server/communication_protocol.cpp
src/server/communication_protocol.h
src/server/generator/llanguage_server/cxx/lsp_language_server_header_generator.py
src/server/generator/llanguage_server/cxx/lsp_language_server_source_generator.py
src/server/language_server.cpp
src/server/language_server.h
src/server/logger.cpp
src/server/logger.h
src/server/lsp_message_stream.cpp
src/server/lsp_message_stream.h
src/server/lsp_text_document.cpp
src/server/lsp_text_document.h
src/server/queue.hpp
src/server/tests/src/llanguage_test_client/lsp_test_client.py
src/server/thread_pool.cpp
src/server/thread_pool.h
tests/server/src/lfortran_language_server/lfortran_lsp_test_client.py
tests/server/tests/conftest.py

Changes:
* Improves logging with UTC timestamps and additional attributes
* Adds test client trace log file
* Auto-scales the request and worker thread pools
* Fixes several minor issues

Addresses timeout issues and improves debuggability

---

src/lfortran/parser/preprocessor.re
tests/preprocessor19.f90
tests/reference/asr_preprocess-preprocessor19-6d76e11.json
tests/reference/asr_preprocess-preprocessor19-6d76e11.stdout
tests/tests.toml

fix: match regex when macro is with empty body

---

integration_tests/CMakeLists.txt
integration_tests/implied_do_loops9.f90
src/lfortran/semantics/ast_common_visitor.h

fix : Handle the use of FixedSizedArray for ImpliedDoLoop on the bases its m-type

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_376.f90
src/libasr/pass/nested_vars.cpp
src/libasr/pass/transform_optional_argument_functions.cpp

towards: https://github.com/lfortran/lfortran/issues/6773

fix: handle present in nested functions correctly

---

src/libasr/pass/transform_optional_argument_functions.cpp

https://github.com/lfortran/lfortran/pull/6995#issuecomment-2802653085

Revert 6988

---

src/server/CMakeLists.txt
src/server/base_lsp_language_server.cpp
src/server/base_lsp_language_server.h
src/server/parallel_lsp_language_server.cpp
src/server/parallel_lsp_language_server.h
src/server/process_usage.cpp
src/server/process_usage.h
src/server/queue.hpp
src/server/thread_pool.cpp
src/server/thread_pool.h

Adds the following stats:
* Sample timestamp (for time series analysis)
* CPU utilization (percentage overall)
* Memory usage (in bytes)
* Incoming and outgoing message queue stats (name, size, total messages seen)
* Request and worker thread pool stats (name, number of available threads, number of threads actively executing tasks, number of tasks pending execution, and total number of executed tasks)

Expands the telementry data with useful stats

---

.github/workflows/CI.yml
src/libasr/pass/intrinsic_array_function_registry.h

With #7003  Towards #2524 
It works without any workarounds except removing 128 bits type variable. Also all 5 tests are passing but there is a bug in 5th test, so it is taking long to compile. For now I have commented last test.

CI: setup CI for fortran-primes code

---

.github/workflows/CI.yml

ci: bump to latest commit for stdlib test with less workarounds

---

src/lfortran/parser/preprocessor.re
tests/errors/unterminated_if_01.f90
tests/errors/unterminated_ifdef_01.f90
tests/errors/unterminated_ifndef_01.f90
tests/reference/asr_preprocess-unterminated_if_01-6989548.json
tests/reference/asr_preprocess-unterminated_if_01-6989548.stderr
tests/reference/asr_preprocess-unterminated_ifdef_01-f746dbf.json
tests/reference/asr_preprocess-unterminated_ifdef_01-f746dbf.stderr
tests/reference/asr_preprocess-unterminated_ifndef_01-1761667.json
tests/reference/asr_preprocess-unterminated_ifndef_01-1761667.stderr
tests/tests.toml

Fixes https://github.com/lfortran/lfortran/issues/7032

raise error in C preprocessor for an unterminated directive

---

build1.sh

Do not install LFortran when building it

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt
integration_tests/run_tests.py
src/bin/lfortran.cpp
src/bin/lfortran_accessor.cpp
src/bin/lfortran_accessor.h
src/lfortran/fortran_evaluator.cpp
src/lfortran/fortran_evaluator.h
src/lfortran/fortran_kernel.cpp
src/lfortran/semantics/ast_common_visitor.h
src/lfortran/semantics/ast_symboltable_visitor.cpp
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h

feat: mark modules as external if global procedures are present and no program is present

---

integration_tests/CMakeLists.txt
integration_tests/no_explicit_return_type_01.f90
src/lfortran/semantics/ast_symboltable_visitor.cpp

fix: extract return type of implicitly declared functions with simple attributes

---

ci/test_third_party_codes.sh

ci: bump to latest commit for stdlib

---

integration_tests/read_03.f90

Towards: https://github.com/lfortran/lfortran/pull/7057#issuecomment-2830436506

test: update test read_03.f90 to test just the actual new feature added

---

.github/workflows/CI.yml
integration_tests/CMakeLists.txt

enh: integration tests for separate compilation with `llvm_goc` label

---

integration_tests/intrinsics_130.f90
src/libasr/pass/intrinsic_functions.h

fix: handle different kinds in `ishft` intrinsic

---

integration_tests/case_01.f90
src/libasr/pass/pass_utils.cpp
tests/reference/asr-case_01-b59db9c.json
tests/reference/asr-case_01-b59db9c.stdout
tests/reference/ast-case_01-929583e.json
tests/reference/ast-case_01-929583e.stdout
tests/reference/ast_f90-case_01-dcc012a.json
tests/reference/ast_f90-case_01-dcc012a.stdout
tests/reference/c-case_01-2ff47e6.json
tests/reference/c-case_01-2ff47e6.stdout
tests/reference/cpp-case_01-49038b7.json
tests/reference/cpp-case_01-49038b7.stdout
tests/reference/julia-case_01-cbdd0aa.json
tests/reference/julia-case_01-cbdd0aa.stdout
tests/reference/llvm-case_01-09dad75.json
tests/reference/llvm-case_01-09dad75.stdout

fix: handle different kind in `select case` expr

---

integration_tests/file_26.f90
src/libasr/codegen/asr_to_llvm.cpp

fix: handle `PointerToDataArray` in `fileRead`

---

integration_tests/array_04_transfer.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/pass/array_struct_temporary.cpp

Towards #7186. 
MRE works but give wrong answer.

fix: Handle different kinds in `ArraySection` inside intrinsic

---

integration_tests/CMakeLists.txt
integration_tests/class_17.f90
src/lfortran/semantics/ast_body_visitor.cpp

Towards: #7185 .
There is an open PR: https://github.com/lfortran/lfortran/pull/7189, which intends to fix the same issue as this PR, the only upside is that this PR uses a simpler logic and has more test cases in this PR.
I've shamelessly taken idea for test cases from the PR: https://github.com/lfortran/lfortran/pull/7189 itself.

fix: refactor nopass assignment logic

---

src/libasr/dwarf_convert.py

Provide a proper absolute path

---

integration_tests/CMakeLists.txt
integration_tests/cond_03.f90
src/lfortran/semantics/ast_common_visitor.h

Handle the case of LHS and RHS being pointers in less than condition

---

src/lfortran/parser/preprocessor.re
tests/preprocessor21.f90
tests/preprocessor22.f90
tests/reference/asr_preprocess-cpp_err5-38d12de.json
tests/reference/asr_preprocess-cpp_err5-38d12de.stderr
tests/reference/asr_preprocess-preprocessor21-aded728.json
tests/reference/asr_preprocess-preprocessor21-aded728.stdout
tests/reference/asr_preprocess-preprocessor22-17078cd.json
tests/reference/asr_preprocess-preprocessor22-17078cd.stdout
tests/tests.toml

Fixes https://github.com/lfortran/lfortran/issues/7257

fix: allow BITOR and BITAND operator in b-factor

---

ci/test_third_party_codes.sh
integration_tests/CMakeLists.txt
integration_tests/separate_compilation_07.f90
integration_tests/separate_compilation_07a.f90
integration_tests/separate_compilation_07b.f90
integration_tests/separate_compilation_07c.c
integration_tests/separate_compilation_08.f90
integration_tests/separate_compilation_08a.f90
integration_tests/separate_compilation_08b.f90
src/libasr/asr_scopes.cpp
src/libasr/pass/intrinsic_array_function_registry.h
tests/reference/llvm-modules_36-53c9a79.json
tests/reference/llvm-modules_36-53c9a79.stdout

Towards https://github.com/lfortran/lfortran/issues/7163

ci: enable POT3D and SNAP with separate compilation

---

ci/test_third_party_codes.sh

Reverts lfortran/lfortran#7273
Unblocking the CI.

Revert "fix: [fortran_mpi] use MPI wrappers from lfortran/fortran_mpi"

---

integration_tests/CMakeLists.txt
integration_tests/nested_struct_proc_01.f90
src/lfortran/semantics/ast_common_visitor.h
tests/reference/asr-nested_struct_proc_01-3b9017b.json
tests/reference/asr-nested_struct_proc_01-3b9017b.stdout
tests/tests.toml

Fix: Handle FunctionCall to ClassProcedures for Generics 

---

ci/test_third_party_codes.sh

Towards https://github.com/lfortran/lfortran/issues/7328

ci: setup fastGPT with separate compilation

---

ci/test_third_party_codes.sh

Towards: https://github.com/lfortran/lfortran/issues/6020

CI: test numeric-method-fortran with --std=f23

---

integration_tests/CMakeLists.txt
integration_tests/intrinsics_379.f90
src/libasr/pass/intrinsic_subroutines.h

Fixes #7431. I'm not convinced with the fix, there are a lot of bugs in `get_command_argument` we need to correctly fix it.

ref: logic to handle optional arguments in `get_intrinsic_subroutine`

---

integration_tests/CMakeLists.txt
integration_tests/class_27.f90
src/libasr/codegen/asr_to_llvm.cpp

fix: allow struct to class association if struct is extended type

---

.github/workflows/CI.yml

Attempts to resolve: https://github.com/lfortran/lfortran/pull/7488#discussion_r2113446869

CI: club LSP tests with our existing CI tests of macOS / Linux

---

integration_tests/CMakeLists.txt
integration_tests/string_55.f90

Test : Add test that used to fail `llvm_wasm`

---

integration_tests/allocate_01.f90
tests/reference/asr-allocate_01-f3446f6.json
tests/reference/asr-allocate_01-f3446f6.stdout

Addresses https://github.com/lfortran/lfortran/pull/7505#pullrequestreview-2880581565

test: add test for allocate

---

integration_tests/CMakeLists.txt
integration_tests/format_34.f90
tests/reference/run-format_34-81f4937.json
tests/reference/run-format_34-81f4937.stdout
tests/tests.toml

closes: https://github.com/lfortran/lfortran/issues/6674

Add more tests related to formatting

---

integration_tests/CMakeLists.txt
integration_tests/format_33.f90
src/libasr/runtime/lfortran_intrinsics.c

fixes: https://github.com/lfortran/lfortran/issues/7401

implement backspace logic correctly

---

integration_tests/CMakeLists.txt
integration_tests/class_31.f90
integration_tests/class_32.f90
integration_tests/class_35.f90
src/libasr/codegen/asr_to_llvm.cpp

feat: add support for class to class variable assignment

---

integration_tests/CMakeLists.txt
integration_tests/hashmap_struct_01.f90

chore: Added integration test for hashmap struct

---

src/libasr/codegen/asr_to_c.cpp
src/libasr/codegen/asr_to_c_cpp.h
src/libasr/codegen/asr_to_julia.cpp
src/libasr/pass/unique_symbols.cpp
src/libasr/pickle.cpp

use `m_intrinsic` to check module is intrinsic or not

---

ci/test_third_party_codes.sh

With this PR we set `splpak` at CI: https://github.com/Pranavchiku/splpak/tree/lf-1

ci: setup `splpak`

---

integration_tests/class_21.f90
src/libasr/codegen/asr_to_llvm.cpp

fix: handle class pointer passed/returned in function

---

integration_tests/CMakeLists.txt
integration_tests/transfer_03.f90
integration_tests/transfer_04.f90
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/codegen/llvm_array_utils.cpp
src/libasr/pass/pass_array_by_data.cpp

fix: inconsistent casting bugs in LLVM IR generation

---

ci/test_third_party_codes.sh

ci: enable testing more examples for stdlib string_type with separate compilation

---

ci/test_third_party_codes.sh

Towards #6840 
After #7711, this will be good to merge.

ci: test toml-f, jonquil build

---

integration_tests/CMakeLists.txt
integration_tests/arrays_92.f90
src/libasr/pass/array_struct_temporary.cpp

fix: replace Var with ArrayConstant value with appropriate type

---

src/bin/language_server_interface.cpp

Fixes https://github.com/lfortran/lfortran/pull/7658/files#r2140462425.

Better help message

---

integration_tests/CMakeLists.txt
integration_tests/select_label_01.f90
src/lfortran/semantics/ast_body_visitor.cpp
src/libasr/ASR.asdl
src/libasr/pass/select_case.cpp
tests/reference/asr-assign_to1-a6b7599.json
tests/reference/asr-assign_to1-a6b7599.stdout
tests/reference/asr-assign_to2-127a642.json
tests/reference/asr-assign_to2-127a642.stdout
tests/reference/asr-case_01-b59db9c.json
tests/reference/asr-case_01-b59db9c.stdout
tests/reference/asr-case_02-8557909.json
tests/reference/asr-case_02-8557909.stdout
tests/reference/asr-case_03-e03f722.json
tests/reference/asr-case_03-e03f722.stdout
tests/reference/asr-case_05-8f778ac.json
tests/reference/asr-case_05-8f778ac.stdout
tests/reference/asr-case_06-f84222d.json
tests/reference/asr-case_06-f84222d.stdout
tests/reference/asr-common_05-f767179.json
tests/reference/asr-common_05-f767179.stdout
tests/reference/asr-fixed_form_goto_select-a0c3483.json
tests/reference/asr-fixed_form_goto_select-a0c3483.stdout
tests/reference/asr-goto_04-2487215.json
tests/reference/asr-goto_04-2487215.stdout
tests/reference/pass_dead_code_removal-case_06-e7f007f.json
tests/reference/pass_dead_code_removal-case_06-e7f007f.stdout

feat: introduce and implement label in `Select`

---

integration_tests/CMakeLists.txt
integration_tests/derived_types_65.f90

test: add test for printing derived types

---

integration_tests/CMakeLists.txt
integration_tests/arrays_93.f90
src/libasr/pass/function_call_in_declaration.cpp

fix: creating helper function while having function call in declaration with logical not

---

integration_tests/iso_c_binding_01.f90
src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
tests/reference/asr-c_ptr_02-fce1b0e.json
tests/reference/asr-c_ptr_02-fce1b0e.stdout

feat: introduce `c_intptr_t` in `iso_c_binding`

---

integration_tests/CMakeLists.txt
integration_tests/arrays_94.f90
src/libasr/pass/function_call_in_declaration.cpp

fix: creating helper function while having function call in declaration with logical binop

---

integration_tests/CMakeLists.txt
integration_tests/hashmap_derived_pointer_associated.f90

chore: Added a test to check associated of a dervied type pointer member

---

integration_tests/operator_overloading_12.f90
src/lfortran/semantics/ast_common_visitor.h
src/libasr/ASR.asdl
src/libasr/asr_utils.cpp
src/libasr/asr_utils.h
src/libasr/codegen/asr_to_llvm.cpp
src/libasr/pass/array_struct_temporary.cpp
tests/reference/asr-operator_overloading_12-b71f657.json
tests/reference/asr-operator_overloading_12-b71f657.stdout
tests/tests.toml

feat: implemented OverloadedBoolOp

---

integration_tests/CMakeLists.txt
integration_tests/separate_compilation_14.f90
integration_tests/separate_compilation_14a.f90
integration_tests/separate_compilation_15.f90
integration_tests/separate_compilation_15a.f90
src/libasr/codegen/asr_to_llvm.cpp

feat: introduce `common` linkage for global vars in separate compilation

---

check_binary_file_in_git_history.py

Fix the CI when test in main https://github.com/lfortran/lfortran/actions/runs/15966006639/job/45026467488

CI : Minor fix - make sure to use checkout command when there's a commit history difference (avoid indexing out of range)

---

integration_tests/CMakeLists.txt
integration_tests/operator_overloading_17.f90
src/libasr/asr_utils.cpp

fix: compare types properly while checking for op overloading

---

src/libasr/codegen/asr_to_llvm.cpp

Gep refactor

---

integration_tests/operator_overloading_17.f90
src/libasr/pass/pass_array_by_data.cpp

enh: check associate block also while removing symbol in pass_array_by_data

---

src/libasr/codegen/asr_to_llvm.cpp

chore: gep to gep2

---

doc/src/asr/asr_nodes/statement_nodes/allocate.md
integration_tests/CMakeLists.txt
integration_tests/allocate_25.f90
src/lfortran/semantics/ast_body_visitor.cpp
tests/reference/asr-allocate_02-3c0d7c8.json
tests/reference/asr-allocate_02-3c0d7c8.stdout
tests/reference/asr-functions_16-3e10090.json
tests/reference/asr-functions_16-3e10090.stdout

fixes: https://github.com/lfortran/lfortran/issues/8109

fix: handle assignment when allocate is provided with source keyword

---

integration_tests/CMakeLists.txt
integration_tests/nested_14.f90
src/libasr/pass/nested_vars.cpp

fix: visit Array Type of Variable for replacing nested var

---

ci/test_third_party_codes.sh

CI: setup FPM at CI

---

src/libasr/runtime/lfortran_intrinsics.c

refactor: some of the string runtime functions

---

src/lfortran/semantics/ast_body_visitor.cpp
tests/errors/continue_compilation_2.f90
tests/reference/asr-continue_compilation_2-a6145a1.json
tests/reference/asr-continue_compilation_2-a6145a1.stderr

fixes: https://github.com/lfortran/lfortran/issues/8317

error: throw error for incompatible ranks of arrays

---

src/bin/lfortran_command_line_parser.cpp
src/libasr/utils.h

Towards https://github.com/lfortran/lfortran/issues/7068

feat: add a new flag `--new-classes`

---

ci/test_third_party_codes.sh

ci: test jonquil for FPM

---

integration_tests/CMakeLists.txt
integration_tests/select_rank_01.f90
src/lfortran/semantics/ast_body_visitor.cpp

enh: initial implementation of `select rank`
