lfortran/lfortran

- CONTRIBUTING.md
- doc/nb/developer_tutorial.ipynb
- doc/src/CONTRIBUTING.md
- doc/src/index.md
- doc/src/installation.md
This `PR` updates the docs to point to the `LFortran` `GitHub` Repository.
> Doc: Point docs to GitHub

- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/codegen/llvm_array_utils.h
It seems, with recent changes in #8 , a parameter of `SimpleCMODescriptor::fill_array_details()` is unused.
While building `LFortran`, I am receiving an `unused parameter warning`. This `PR` temporarily fixes the warning.
CC: @czgdp1807
> LLVM: Temporarily comment out unused parameter

- src/bin/lfortran.cpp
For now you need to pass the -c option and manually link with a runtime compiled to the target. You can use -v to get the linker command line.
Runtime cross compilation and automatic selection based on target is coming soon.
> Passes `-target` to the cc linker

- src/bin/lfortran.cpp
This is a first step to make linking more robust. The current configuration yielded an error when trying to integrate with meson tests. A next step would be to introduce a handling with several arguments (e.g. https://github.com/DaanDeMeyer/reproc).
> Small linker fix

- .pre-commit-config.yaml
The trailing whitespace is used as a newline.
> Skip md files for trailing whitespace fix

- src/bin/lfortran.cpp
- src/lfortran/tests/test_error_rendering.cpp
- src/libasr/diagnostics.cpp
- src/libasr/diagnostics.h
- src/libasr/utils.h
For now do "human" (default) and "short" (one line errors).
Example:
```console
$ lfortran --show-asr tests/errors/type_mismatch1.f90 --error-format=short
tests/errors/type_mismatch1.f90:4:1 semantic error: Type mismatch in assignment, the types must be compatible
$ lfortran --show-asr tests/errors/type_mismatch1.f90 --error-format=human
semantic error: Type mismatch in assignment, the types must be compatible
--> tests/errors/type_mismatch1.f90:4:1
|
4 | x = "x"
| ^   ^^^ type mismatch (integer and character)
Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```
> Implement other error formats

- src/libasr/asr_utils.h
- src/runtime/impure/lfortran_intrinsics.c
This `PR` fixes the following compiler warnings:
At **CI**:
```bash
/lfortran/lfortran-0.16.0-212-g34f250421/src/libasr/asr_utils.h:1435:44: warning: ‘end_int’ may be used uninitialized in this function [-Wmaybe-uninitialized]
1435 |                                    end_int - start_int + 1,
```
```bash
/lfortran/lfortran-0.16.0-212-g34f250421/src/libasr/asr_utils.h:1435:44: warning: ‘start_int’ may be used uninitialized in this function [-Wmaybe-uninitialized]
1435 |                                    end_int - start_int + 1,
```
**Locally** as well as **CI**:
```bash
lfortran/src/runtime/impure/lfortran_intrinsics.c:655:22: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
655 |     sprintf(res, "%lld", num); …
```
> Fix Compiler Warnings

- src/runtime/legacy/CMakeLists.txt
Ignore the following error.
```
$ LFORTRAN_KOKKOS_DIR=/home/test/install-prefix /home/test/install-prefix/bin/lfortran --backend=cpp ~/test.f90
a.out.tmp.o.tmp.cpp:8:10: fatal error: lfortran_intrinsics.h: No such file or directory
8 | #include <lfortran_intrinsics.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
The command 'g++ -std=c++17 -I/home/test/install-prefix/include -I/home/test/install-prefix/bin/../share/lfortran/lib/impure -o a.out.tmp.o -c a.out.tmp.o.tmp.cpp' failed.
```
> backend-cpp: install lfortran_intrinsics.h

- src/runtime/impure/lfortran_intrinsics.c
.../lfortran/src/runtime/impure/lfortran_intrinsics.c:655:25: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
sprintf(res, "%ld", num);
~~~   ^~~
%lld
> Fix a compiler warning

- .github/workflows/CI.yml
So that Windows starts first, then macOS, then linux.
> CI: sort matrix from the slowest to the fastest

- src/libasr/codegen/asr_to_llvm.cpp
Fixes https://gitlab.com/lfortran/lfortran/-/issues/748.
> LLVM: reset goto label mapping for each procedure

- src/libasr/codegen/wasm_to_wat.cpp
- src/libasr/codegen/wasm_to_wat.h
- src/libasr/codegen/wasm_utils.cpp
- src/libasr/wasm_instructions.txt
The previous `PR` #49 fails with `segmentation fault` for `integration_tests/arrays_01.f90` during `wat` generation.
This `PR` fixes the bug and adds support for `wat` generation for basic arrays.
> WAT: Arrays Fix

- CMakeLists.txt
Fix bug with cmake calling build0.sh
Ensures that build0.sh is called with bash AND from the right directory.
This now allows for out-of-source builds.
Also removes the need to call `./build0.sh` in envs with bash
before calling cmake.
---
You could technically now remove all the calls to `./build0.sh`.
On a separate note, you might want to rename the calls to `python` --> `python3` in the scripts to make lfortran buildable from envs (other than anaconda) that do not have the alias setup.
> Out-of-source builds

- src/bin/lfortran.cpp
- src/libasr/utils.h
If set, it will save the object code into .o files. Otherwise (default)
it will create an empty file, and only generate the final binary when
compiling the main program.
Fixes: https://gitlab.com/lfortran/lfortran/-/issues/749
> Add a --generate-object-code compiler option

- integration_tests/CMakeLists.txt
- src/libasr/codegen/asr_to_wasm.cpp
This `PR` adds support for `real` and `logical` type `1D-arrays`.
CC: @czgdp1807
> WASM: Support Real and Logical types with Arrays

- .github/workflows/CI.yml
- integration_tests/CMakeLists.txt
- src/bin/lfortran.cpp
This `PR` adds support for `wasm` `integration_tests` testing at the `CI`.
> CI: Support integration tests testing for WASM

- cmake/UserOverride.cmake
This PR removes `-march=native` hard coding. 
On the one hand, `-march=native` does not work with Clang on M1 Macs. 
Additionally,  this option makes "Release" binaries not very portable to older CPUs (e.g. for conda-forge or other package managers).
I think this should only ever be set by a user that wants maximum performance.
> remove march=native hard coding

- .github/workflows/CI.yml
m2-bison installs m2-bash, which overrides the default bash shell on
Windows. You need to install m2-filesystem to properly
initialise the m2-bash environment.
> bug(build): fixes Windows bash env initialisation

- src/libasr/pass/pass_array_by_data.cpp
In C++ I think one cannot modify the map which is iterated over by
erasing elements from it, as it can invalidate the iterator. So we first
store the items to erase and then we erase it in the second step. This
fixes the segfault encountered at:
https://gitlab.com/lfortran/lfortran/-/issues/762
> Fix an invalid iterator

- src/lfortran/parser/fixedform_tokenizer.h
- src/lfortran/parser/parser.cpp
- src/lfortran/parser/parser.h
- tests/errors/fixed_form_1.f
- tests/errors/fixed_form_2.f
- tests/errors/fixed_form_3.f
- tests/errors/fixed_form_4.f
- tests/errors/fixed_form_5.f
- tests/reference/ast-fixed_form_1-3be6d43.json
- tests/reference/ast-fixed_form_1-3be6d43.stderr
- tests/reference/ast-fixed_form_2-1350599.json
- tests/reference/ast-fixed_form_2-1350599.stderr
- tests/reference/ast-fixed_form_3-53e9045.json
- tests/reference/ast-fixed_form_3-53e9045.stderr
- tests/reference/ast-fixed_form_4-656a640.json
- tests/reference/ast-fixed_form_4-656a640.stderr
- tests/reference/ast-fixed_form_5-f25edd8.json
- tests/reference/ast-fixed_form_5-f25edd8.stderr
- tests/tests.toml
> More robust error messages for fixed-form

- integration_tests/CMakeLists.txt
- integration_tests/expr_08.f90
- integration_tests/expr_09.f90
- src/libasr/codegen/asr_to_wasm.cpp
- src/libasr/codegen/wasm_assembler.h
- src/libasr/codegen/wasm_to_wat.h
- tests/reference/wat-expr_08-74f99b7.json
- tests/reference/wat-expr_08-74f99b7.stderr
- tests/reference/wat-expr_08-74f99b7.stdout
- tests/reference/wat-expr_09-fa1b124.json
- tests/reference/wat-expr_09-fa1b124.stdout
- tests/tests.toml
This `PR` adds support for `pow` when `exponent = 2` in the `wasm` backend.
> WASM: Initial implementation of x**2

- integration_tests/expr_08.f90
- src/libasr/codegen/asr_to_wasm.cpp
- tests/reference/wat-abs_01-0c0b4df.json
- tests/reference/wat-abs_01-0c0b4df.stdout
- tests/reference/wat-abs_03-5d62cca.json
- tests/reference/wat-abs_03-5d62cca.stdout
- tests/reference/wat-expr_08-74f99b7.json
- tests/reference/wat-expr_08-74f99b7.stdout
- tests/reference/wat-types_15-abe4006.json
- tests/reference/wat-types_15-abe4006.stdout
- tests/reference/wat-wasm_floats-c84c674.json
- tests/reference/wat-wasm_floats-c84c674.stdout
This `PR` adds support for using the `compile-time` value of a function in the `WebAssembly` Backend.
> WASM: Use compile-time function value

- integration_tests/CMakeLists.txt
- integration_tests/arrays_16_func.f90
- src/libasr/codegen/asr_to_llvm.cpp
Test added (fails in main, works now).
Co-authored-by: Gagandeep Singh <gdp.1807@gmail.com>
Closes https://github.com/lfortran/lfortran/pull/141
> LLVM: Determine if it is an argument correctly

- src/libasr/codegen/asr_to_wasm.cpp
This `PR` adds support of using `bind(c)` in the `wasm` backend to import functions from `JavaScript`.
More details at https://gitlab.com/lfortran/lfortran/-/issues/761
> WASM: Support bind C for array passing to JavaScript

- README.md
We have archived the old gitlab repository: https://gitlab.com/lfortran/lfortran
And we migrated issues to github. From now on we will open new issues at
github.
> Update README with regards to issues

- .github/workflows/CI.yml
- ci/upload_lfortran_wasm.sh
- ci/wasm_builds_update_json.py
This `PR` attempts to fix the currently failing `CI`. It also brings support for uploading the built `lfortran.js` and `lfortran.wasm` to https://github.com/lfortran/wasm_builds
> CI: Fix CI and upload to wasm_builds

- ci/upload_lfortran_wasm.sh
This `PR` fixes the location of `data.json` (currently being saved to `/docs/dev/`) to be saved to `/docs/`. This `PR` also adds support to the `CI` to store the `latest_commit` as well inside `/docs/dev/latest_commit`.
> CI: Fix upload to wasm_builds

- ci/upload_lfortran_wasm.sh
We recently faced an outage at `dev.lfortran.org` due to appending to (instead of overwriting) the `latest_commit` at `wasm_builds` repository. This `PR` fixes the `CI` to (hopefully) overwrite the file.
More details at: https://github.com/lfortran/lcompilers_frontend/issues/32
The erroneous `CI` logic was written by me  and I sincerely apologize for the inconvenience caused.
> CI: Fix: Overwrite the latest_commit file

- src/libasr/codegen/wasm_to_wat.cpp
- src/libasr/codegen/wasm_to_wat.h
During `wasm` to `wat` conversion, we were skipping the first `eight` bytes of wasm (as they contain the magic number and wasm version). This `PR` fixes checking/verifying those `eight` bytes.
> WAT: verify preamble

- src/lfortran/fortran_evaluator.cpp
- src/libasr/codegen/wasm_to_wat.cpp
- src/libasr/codegen/wasm_to_wat.h
This `PR` tries to refactor the `wasm_to_wat.cpp` to be similar to the other `asr_to_backend.cpp` files. It also tries to add error handling functionalities in the `wasm_to_wat` backend.
> WAT: wasm_to_wat error handling

- integration_tests/CMakeLists.txt
This `PR` enables `wasm` backend for supporting tests in `integration_tests/CMakeLists.txt`.
> WASM: Enable supporting integration_tests

- src/libasr/codegen/asr_to_wasm.cpp
- src/libasr/codegen/asr_to_wasm.h
- src/libasr/codegen/wasm_assembler.h
- src/libasr/codegen/wasm_to_wat.cpp
- src/libasr/codegen/wasm_to_wat.h
- src/libasr/codegen/wasm_utils.cpp
- src/libasr/codegen/wasm_utils.h
This `PR` improves the formatting of `wasm` backend related source code files. 
It uses the following style settings in `vscode`:
```bash
"C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 80 }", 
"C_Cpp.clang_format_style": "{ BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 80 }"
```
> WASM, WAT: Improve code formatting

- integration_tests/CMakeLists.txt
- integration_tests/cpu_time_02_wasm.f90
- src/libasr/codegen/wasm_assembler.h
- tests/reference/wat-cpu_time_02_wasm-fa2b15f.json
- tests/reference/wat-cpu_time_02_wasm-fa2b15f.stderr
- tests/reference/wat-cpu_time_02_wasm-fa2b15f.stdout
- tests/tests.toml
towards #555, #540 
Corresponding `PR` at `lcompilers_frontend`: https://github.com/lfortran/lcompilers_frontend/pull/36
> WASM: Add support for cpu_time

- .gitignore
- build_to_wasm.sh
- ci/upload_lfortran_wasm.sh
- src/bin/CMakeLists.txt
- src/lfortran/utils.cpp
towards #540 
This `PR` adds support of `preloading` the `runtime` library with `lfortran.js` and `lfortran.wasm`.
Corresponding `PR` at `lcompilers_frontend`: https://github.com/lfortran/lcompilers_frontend/pull/37
> WASM: Support runtime library

- integration_tests/data_01.f90
- src/lfortran/semantics/ast_common_visitor.h
This PR generates ASR for `scipy/odr/odrpack/d_mprec.f`:
```
% lfortran --implicit-typing --fixed-form --show-asr scipy/odr/odrpack/d_mprec.f --show-stacktrace 
(TranslationUnit (SymbolTable 1 {dmprec: (Function (SymbolTable 2 {b: (Variable 2 b Local () (RealConstant 2.000000 (Real 8 [])) Default (Real 8 []) Source Public Required .false.), dmprec: (Variable 2 dmprec ReturnVar () () Default (Real 8 []) Source Public Required .false.), td: (Variable 2 td Local () (IntegerConstant 53 (Integer 4 [])) Default (Integer 4 []) Source Public Required .false.), ts: (Variable 2 ts Local () (IntegerConstant 24 (Integer 4 [])) Default (Integer 4 []) Source Public Required .false.)}) dmprec [] [] [(= (Var 2 dmprec) (RealBinOp (Var 2 b) Pow (Cast (IntegerBinOp (IntegerConstant 1 (Integer 4 [])) Sub …
```
> Fix Data Attr Initialization

- .github/dependabot.yml
This will open PRs whenever there is an update on the GitHub Actions used by lfortran. It will run all your CI checks to ensure that nothing in your CI pipeline has broken.
I think you will have to enable dependabot alerts under the `Security` tab (need to have admin rights for that).
> feat: add dependabot for GitHub Actions

- src/bin/lfortran.cpp
> fix: throw error when infile does not exist (#740)

- src/libasr/codegen/asr_to_cpp.cpp
- tests/reference/cpp-array1-d75d040.json
- tests/reference/cpp-array1-d75d040.stdout
- tests/reference/cpp-array2-9a93c4d.json
- tests/reference/cpp-array2-9a93c4d.stdout
Implement new `trim_dims` to avoid array name collisions.
> Fix: avoid n-d array name collisions (#747)

- run_tests.py
@lucifer1004 We didn't catch something in the review, some tests weren't running anymore. I think doing `rm tests/reference/*`, then again running `./run_tests.py -u` and observing if there are deletions or changes should help for this.
> Testing infrastructure refactoring fix

- src/libasr/compiler_tester/tester.py
Currently, `-t bits` will not include `integration_tests/bits_01.f90` since it does not match `bits` from the beginning. We should use `re.search` instead of `re.match`.
> [test] Use `re.search` instead of `re.match` in tests

- src/libasr/runtime/lfortran_intrinsics.c
cc @czgdp1807 
https://github.com/lcompilers/lpython/pull/1051#discussion_r987731423
I haven't added a test for this because LFortran does not generate an ASR node for `StringSection` in Fortran frontend.
> Fix lfortran_str_slice

- src/libasr/asr_verify.cpp
> Verify: check that SubroutineCall points to a fn

- .github/workflows/CI.yml
- ci/environment_linux_llvm15.yml
- environment_linux.yml
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
Add a CI test and update the code to compile. We support all LLVM 11 - 15. For LLVM 11 everything works. For LLVM 14 and 15 only integration tests pass (we test at the CI), but interactivity does not work and reference tests don't pass, because each LLVM version outputs slightly different LLVM IR code.
I think a good way to move forward is to keep the latest LLVM version always working for everything and just keep updating our tests. And for older versions keep as much working as possible, but reference tests will not work.
> Enable LLVM 15 support

- share/lfortran/nb/Demo1.ipynb
- share/lfortran/nb/Operators Control Flow.ipynb
- share/lfortran/nb/Variables.ipynb
- src/lfortran/tests/test_llvm.cpp
- src/libasr/codegen/KaleidoscopeJIT.h
- src/libasr/codegen/evaluator.cpp
- src/libasr/codegen/evaluator.h
What works:
* ctest
* integration_tests
* ./run_tests.py (the LLVM tests only pass with LLVM 11, since other LLVM versions produce slightly different LLVM IR)
* Basic interactivity on all platforms (Jupyter)
Changes:
* LLVM does not allow any duplicate symbols, so we disabled those tests
* There are some additional failures on Windows, so we disabled those tests; basic small subset of interactivity still works even on Windows, so we still test that, including Jupyter notebooks.
What we need to fix in subsequent PRs:
* All platforms: Cannot redefine a function or a variable in interactive mode: #918
* Windows: Some missing symbols: https://github.com/lfortran/lfortran/issues/915
* Windows: Some other failures (possibly related to the above): https://github.com/lfortran/lfortran/issues/913 …
> Update JIT to work with LLVM 10 - 15

- src/lfortran/tests/test_llvm.cpp
Skip on Windows for now due to #913.
> Enable the sin(0.5) test on Linux/macOS

- ci/create_source_tarball0.sh
The file is 8.3MB large, so this is a good saving.
> Remove parser.output from the source tarball

- src/libasr/runtime/lfortran_intrinsics.c
macOS before 11.12 do not have it declared. Windows also does not have it, so for now we disable it.
> Disable clock_gettime() on macOS

- integration_tests/arrays_13.f90
- src/libasr/asr_utils.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/codegen/llvm_array_utils.h
- tests/reference/llvm-array2-4254183.json
- tests/reference/llvm-array2-4254183.stdout
- tests/reference/llvm-array2_derived-ecff8f2.json
- tests/reference/llvm-array2_derived-ecff8f2.stdout
- tests/reference/llvm-arrays_01_logical-f19a63d.json
- tests/reference/llvm-arrays_01_logical-f19a63d.stdout
- tests/reference/llvm-arrays_13-8ff7d44.json
https://github.com/lfortran/lfortran/issues/900
> Removing `getPointerElementType` usage in LLVM backend

- doc/src/intrinsics/numeric/conjg.md
- closes #934 
Solution described in https://github.com/lfortran/lfortran/issues/934#issue-1416042128
> Docs: fix conjg example

- src/bin/tpl/whereami/whereami.cpp
it mostly adds support to OpenBSD
I tried to keep the local modifications (`NOMINMAX` definition in `_WIN32`,  `sys/limits.h` include removal and explicit `PATH_MAX` definition).
> update whereami to ba364cd54fd431c76c045393b6522b4bff547f50 (2022-02-18)

- integration_tests/CMakeLists.txt
- integration_tests/arrays_18_func.f90
- src/libasr/codegen/asr_to_llvm.cpp
Closes https://github.com/lfortran/lfortran/issues/944
Closes https://github.com/lfortran/lfortran/pull/945
Before LLVM 15 we used to directly query LLVM type to check whether an array variable is a data only array (i.e., just a pointer to data) or a descriptor array (i.e., a struct of data pointer, and dimensional information). Since LLVM 15 we are not supposed to do that. In https://github.com/lfortran/lfortran/commit/cf481fd69d4b6cd781eb0734997599421ceacc1b, data only arrays also passed the `arr_descr->is_array(...)` check but they shouldn't. In this PR we make sure that we only call `arr_descr->convert_to_argument(...)` only for descriptor arrays. See the updated if check for the same.
`minpack` (commit - 8217d0822a1ec01d71d0aa006a6ffe3134fcbd13) compilation status using this PR is, …
> Fix argument conversion for data only arrays

- src/bin/lfortran.cpp
- src/lfortran/tests/test_llvm.cpp
- src/libasr/utils.h
- src/libasr/utils2.cpp
- add OpenBSD platform to have proper `lfortran --version` output
```
LFortran version: 0.18.0-b58397ba-dirty
Platform: OpenBSD
Default target: amd64-unknown-openbsd7.2
```
- disable "FortranEvaluator 10 trig functions" test on OpenBSD as it fails with JIT error
```
JIT session error: Symbols not found: [ _lfortran_cacos, _lfortran_cacosh, _lfortran_caimag, _lfortran_casin, _lfortran_casinh, _lfortran_catan, _lfortran_catanh, _lfortran_ccos, _lfortran_ccosh, _lfortran_cexp, _lfortran_clog, _lfortran_cpu_time, _lfortran_csin, _lfortran_csinh, _lfortran_csqrt, _lfortran_ctan, _lfortran_ctanh, _lfortran_dacos, _lfortran_dacosh, _lfortran_dasin, _lfortran_dasinh, _lfortran_datan, _lfortran_datan2, _lfortran_datanh, _lfortran_dcos, _lfortran_dcosh, _lfortran_derf, _lfortran_derfc, …
```
> proper OpenBSD support

- src/bin/lfortran.cpp
When reworking the [Implement -I and -J (CompilerOptions edition)](https://github.com/lfortran/lfortran/pull/901) to become [Implement -I and -J (PassOptions edition)](https://github.com/lfortran/lfortran/pull/930) I forgot to copy changes to save_mod_files in lfortran.cpp. The result is that you can load from -J but not save to it.
You can use the example code in those PRs to see that my_module.mod is indeed not saved to `-J mods/`.
> Save mod files to -J

- integration_tests/CMakeLists.txt
- integration_tests/arrays_19.f90
- src/libasr/pass/update_array_dim_intrinsic_calls.cpp
Closes https://github.com/lfortran/lfortran/issues/955
> Replace `ArrayBound` correctly with dimension for arrays passed as data pointers

- integration_tests/CMakeLists.txt
- integration_tests/types_17.f90
- src/lfortran/semantics/ast_common_visitor.h
it permits to properly parse variable declaration like `character(len=n,kind=c_char), pointer :: sptr`.
found while trying to build `fpm`. it failed to build [src/fpm_strings.f90](https://github.com/fortran-lang/fpm/blob/6c51ebb5d844b9e7ff070b4b629ed2d5d973d8b2/src/fpm_strings.f90#L171-L179) (it still fail, but on the next error):
```fortran
function f_string_cptr_n(cptr, n) result(s)
type(c_ptr), intent(in), value :: cptr
integer(kind=c_size_t), intent(in) :: n
character(len=n,kind=c_char) :: s
character(len=n,kind=c_char), pointer :: sptr
call c_f_pointer(cptr, sptr)
s = sptr
end function
```
with:
```
semantic error: fptr is not a pointer.
--> ./src/fpm_strings.f90:177:28
|
177 |     call c_f_pointer(cptr, sptr)
|                            ^^^^ 
```
> do not ignore pointer attribute on character

- src/bin/lfortran.cpp
This was inserted by mistake when testing on macOS where gcc is a front for clang. Cross compilation with gcc uses a different binary for the target architecture.
I will reopen the cross compilation PR after this is merged.
> Gcc doesn't use --target

- src/bin/CMakeLists.txt
- src/lfortran/tests/CMakeLists.txt
See https://github.com/lfortran/lfortran/issues/509 .
The patch from @semarie for OpenBSD is also fine for FreeBSD.
> Fix Symbols not found for FreeBSD (idem OpenBSD)

- src/bin/lfortran.cpp
I remember doing this when implementing -I and -J but it didn't make to the final pull request. The error is that when on the REPL lfortran can't find the builtin functions like sin(), cos(), etc.
> REPL doesn't initialize runtime_library_dir

- src/bin/lfortran.cpp
It seems in https://github.com/lfortran/lfortran/pull/930, the `runtime_library_dir` was incorporated into the `compiler_options`. With that change, for `EMSCRIPTEN_KEEPALIVE` functions, the `runtime_library_dir` was not being initialized. This `PR` (hopefully) fixes it.
> Build to WASM: Initialize compiler_options.runtime_library_dir

- GOVERNANCE.md
I was reading through the governance doc and thought this should be changed since development has been completely shifted to GitHub from GitLab.
> [Trivial] Rename MR to PR in governance doc

- integration_tests/implied_do_loops1.f90
- integration_tests/implied_do_loops2.f90
- integration_tests/implied_do_loops3.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/reference/asr-implied_do_loops1-f5adada.json
- tests/reference/asr-implied_do_loops1-f5adada.stdout
- tests/reference/asr-implied_do_loops2-edb5843.json
- tests/reference/asr-implied_do_loops2-edb5843.stdout
- tests/reference/asr-implied_do_loops3-2a10d65.json
- tests/reference/asr-implied_do_loops3-2a10d65.stdout
- tests/tests.toml
This PR solves  [#981 (comment) ](https://github.com/lfortran/lfortran/issues/981#issuecomment-1304725752), AST->ASR passes for ImpliedDoLoop works.
> Fixes in `ImpliedDoLoop`.

- src/libasr/codegen/asr_to_llvm.cpp
Tests pass on my system so safe to conclude that the removed code isn't needed anyways. The problematic part was everything inside a single `if` check which was going to be true anyways as we don't handle the intrinsics in the old fashioned way (which is by catching them and processing the args accordingly).
> Remove dead code from ``convert_call_args``

- src/libasr/codegen/asr_to_llvm.cpp
The error message looks like this:
```
warning: unit in write() is not implemented yet, using stdout for now
--> /Users/ondrej/repos/lfortran/minpack/examples/example_hybrd1.f90:39:12
|
39 |     write (nwrite, 1000) fnorm, info !, (x(j), j=1, n)
|            ^^^^^^ using stdout for now
Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```
> Warning instead of an error for unit in write

- src/libasr/asdl_cpp.py
- src/libasr/asr_utils.h
Found in https://github.com/lfortran/lfortran/pull/1045#discussion_r1034093434
Earlier I was using `current_expr_copy` as a state of the class `BaseExprReplacer`. I did this to avoid re-definition errors of `current_expr_copy` by C++ compilers. This caused loss of original expressions once we moved deeper into the expression tree. However now I use local variables and declare always new ones by suffixing `current_expr_copy` with `_[counter]`. **This avoids re-definition errors by C++ compiler and allows replacement of expressions having very deep trees in ASR.**
> Fix expression replacer for multi-layer replacements of expressions

- integration_tests/modules_15.f90
- integration_tests/modules_15b.f90
- integration_tests/modules_15c.c
- integration_tests/modules_15c.h
- tests/reference/asr-modules_15b-5be0f8a.json
- tests/reference/asr-modules_15b-5be0f8a.stdout
It turns out this feature is already implemented, but it has not been tested. This adds tests for integer, single and double precision real arrays.
> Add a test for A(*) style arrays in bind(c)

- integration_tests/expr_11.f90
- src/libasr/codegen/asr_to_c_cpp.h
- src/libasr/codegen/asr_to_julia.cpp
- tests/reference/c-expr_11-8e5ae80.json
- tests/reference/c-expr_11-8e5ae80.stdout
- tests/reference/julia-expr_11-ab53b8f.json
- tests/reference/julia-expr_11-ab53b8f.stdout
- tests/tests.toml
> Do not reset precedence when cast does not add parentheses

- integration_tests/CMakeLists.txt
- integration_tests/arrays_20.f90
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-arrays_20-cb6ba8f.json
- tests/reference/asr-arrays_20-cb6ba8f.stdout
- tests/tests.toml
Fixes: https://github.com/lfortran/lfortran/issues/1065
> Use m_vartype (ArrayInitializer) to get the initializer type.

- src/libasr/codegen/asr_to_llvm.cpp
Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1355
> Changes for printing of ``i8`` and ``i16`` integers in LLVM

- src/libasr/asr_utils.h
- src/libasr/codegen/asr_to_c.cpp
- src/libasr/codegen/asr_to_c_cpp.h
- src/libasr/codegen/asr_to_llvm.cpp
Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1382
> Changes for supporting data only array members for BindC structs

- .github/workflows/CI.yml
This uses the scipy24 branch of Minpack at https://github.com/certik/minpack, it currently has a few commits as a workaround, and each such commit has a link to the LFortran issue that we need to fix. The workarounds are very small.
> CI: test Minpack with every commit

- integration_tests/intrinsics_34.f90
- src/lfortran/semantics/comptime_eval.h
- tests/reference/asr-intrinsics_34-daa20c0.json
- tests/reference/asr-intrinsics_34-daa20c0.stdout
Fixes #1122.
With this, we get [`minpack/example_lmdif1`](https://github.com/certik/minpack/blob/scipy21/examples/example_lmdif1.f90) aligned with GFortran by every bit.
Clean PR for #1176.
> Fix `sqrt(epsilon(1._dp))`

- .github/workflows/CI.yml
The workaround due to https://github.com/lfortran/lfortran/issues/1181 has been removed.
> CI: Remove one workaround from Minpack

- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/ASR.asdl
- src/libasr/pass/instantiate_template.cpp
- tests/reference/asr-template_nested-3a03184.json
- tests/reference/asr-template_nested-3a03184.stdout
- tests/reference/asr-template_travel-f827c57.json
- tests/reference/asr-template_travel-f827c57.stdout
#1199: unify `instantiate_Function`
Removed functionalities unique to LPython from the template instantiation in libasr.
> Synchronizing libasr's template instantiation with LPython

- .github/workflows/CI.yml
The following examples now work:
* example_hybrd
* example_hybrd1
* example_lmdif1
The following example compiles and runs, but gives incorrect results:
* example_lmder1
The following examples requires many patches (in the scipy26 branch in certik/minpack) to even compile and run (too many things were commented out to give correct results, but it is a start):
* example_primes
> Minpack: all examples now compile

- run_tests.py
This is not the full fix, as it can still fail if the other process is still writing the mod file and we are already reading it. The robust solution is to name the mod file uniquely per test and use it. That requires more extensive modification.
Also currently the mod files are saved in the current directory, which is not clean. The mod files should be stored in `tests/output`.
Towards #1218.
> CI: Only compile if the mod file does not exist

- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-template_error-8ad11a2.json
- tests/reference/asr-template_error-8ad11a2.stderr
Building on #1168, changing the error message for functions in templates to be more legible.
> Improving error message for templates

- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/comptime_eval.h
- src/libasr/ASR.asdl
- src/libasr/codegen/asr_to_julia.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/runtime/impure/lfortran_intrinsic_math.f90
- tests/reference/julia-arrays_02-849d7b0.json
- tests/reference/julia-arrays_02-849d7b0.stdout
Construct IntrinsicFunctionSqrt in the frontend, implement in LLVM and Julia backends. All integration tests pass. Reference tests updated.
This change allows Minpack to reproduce exactly the same results as GFortran.
Fixes #1224.
> ASR: Add IntrinsicFunctionSqrt

- .github/workflows/CI.yml
- ci/build.xsh
- ci/test.xsh
This should make the tests hopefully robust at the CI. The parallel race conditions are still there and need to be fixed eventually.
Towards #1218 and #1229.
> CI: run run_tests in serial

- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/errors/private1.f90
- tests/reference/asr-private1-d595bcb.json
- tests/reference/asr-private1-d595bcb.stderr
- tests/tests.toml
Fixes #1239.
As of now, I made a check for only `Variable_t`.
> Add provision to disallow importing private variables.

- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/errors/private2.f90
- tests/reference/asr-private2-2935bf3.json
- tests/reference/asr-private2-2935bf3.stderr
- tests/tests.toml
> Disallow access to private variables `use foo, only:y`

- .gitattributes
- src/lfortran/parser/fixedform_tokenizer.cpp
- src/lfortran/parser/parser.cpp
- tests/fixed_form/crlf1.f
- tests/reference/ast-crlf1-0461359.json
- tests/reference/ast-crlf1-0461359.stdout
- tests/tests.toml
We remove CR in the fixed-form prescanner, and in the fixed-form tokenizer we only handle LF, not CR. This seems to robustly parse fixed-form input source code with CRLF.
Fixes #1252.
> Fixed-form tokenizer: handle CR properly

- src/libasr/asr_verify.cpp
- tests/block2.f90
- tests/reference/asr-block2-2b330cc.json
- tests/reference/asr-block2-2b330cc.stdout
- tests/tests.toml
Fixes #1259.
Bam! With this PR LFortran can now compile `minpack.f90` of modern minpack to ASR.
> Add provision to visit "stmt" in "BlockCall_t"

- integration_tests/CMakeLists.txt
- integration_tests/modules_26.f90
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/llvm-callback_05-c86f2cc.json
- tests/reference/llvm-callback_05-c86f2cc.stdout
- tests/reference/llvm-recursion_03-3285725.json
- tests/reference/llvm-recursion_03-3285725.stdout
Fixes https://github.com/lfortran/lfortran/issues/1266.
> Add provision to use two different functions with same name and different arguments.

- integration_tests/CMakeLists.txt
- integration_tests/block_05.f90
- src/libasr/codegen/asr_to_llvm.cpp
Fixes #1293.
With this PR [modern_minpack/minpack.f90](https://github.com/fortran-lang/minpack/blob/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/src/minpack.f90) compiles to LLVM.
> Support `exit` statements for `Block_t`

- src/bin/lfortran.cpp
Thanks to #1333 we can test this PR as follows on Apple M1:
```console
$ lfortran -g integration_tests/array_section_01.f90 -o x
$ lldb x
(lldb) target create "x"
Current executable set to '/Users/ondrej/repos/lfortran/lfortran/x' (arm64).
(lldb) run
Process 90808 launched: '/Users/ondrej/repos/lfortran/lfortran/x' (arm64)
Process 90808 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x10000004c)
frame #0: 0x0000000100003e70 x`vecfcn(__1_k=19, fvec=0) at array_section_01.f90:6:5
3   	    integer :: n
4   	    real :: fvec(n)
5   	
-> 6   	    fvec(2:n) = 0.0
7   	    print *, fvec
8   	
9   	end subroutine vecfcn
Target 0: (x) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, …
```
> LLVM: Enable debugging information

- integration_tests/CMakeLists.txt
- integration_tests/block_06.f90
- src/libasr/codegen/asr_to_wasm.cpp
This PR implements initial support for `visit_BlockCall` in the `wasm` backend.
- Varaibles and statements inside a block are supported (their support is yet to be verfied by adding a test case)
- For variables declared inside the block scope, we are declaring them as local variables of the function (thus they are now available throughout the whole function scope).
- GoTo and GoToTarget are not yet supported
Related: https://github.com/lcompilers/lpython/pull/1548
> WASM: Initial support for BlockCall

- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/libasr/asr_scopes.h
- src/libasr/pass/array_op.cpp
- src/libasr/pass/pass_utils.cpp
add_symbol: symbol did not exist before
overwrite_symbol: symbol existed before
add_or_overwrite_symbol: symbol might or might not exist before
The most clean approach is using `add_symbol` or `overwrite_symbol`, and they enforce the convention with an assert statement.
Only use add_or_overwrite_symbol() as the last resort and document why the symbol can be overwritten in the same symbol table, but only sometimes. Often times this signals a bug in our code, we should have created a unique symbol name first.
> Distinguish between adding and overwriting symbols

- integration_tests/CMakeLists.txt
- integration_tests/write_01.f90
- src/libasr/pass/print_arr.cpp
- tests/reference/llvm-write3-49c0266.json
- tests/reference/llvm-write3-49c0266.stderr
Fixes #1369.
With this PR, LFortran now compiles `minpack/test/test_hybrd.f90` to LLVM!
> Add provision to do `FileWrite` over arrays using do_loops

- src/libasr/stacktrace.h
ref: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
https://github.com/lfortran/lfortran/issues/1373
> Add missing <cstdint> header to stacktrace.h

- ci/upload_docs.sh
```bash
(base) lfortran$ export t="heads/refs/ci/git/flow/br/name" 
(base) lfortran$ echo ${t##*/}                            
name
```
When `git-flow` style branch names are used, the `branch_name` in `ci/upload_docs.sh` stores only the last part of the branch name. This PR fixes it to use the whole branch name.
> CI: Minor improvement

- integration_tests/CMakeLists.txt
- integration_tests/block_07.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/ASR.asdl
- src/libasr/codegen/asr_to_llvm.cpp
Fixes #1402.
With this PR, LFortran's output for [example_lmdif1.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_lmdif1.f90) aligns with GFortran.
> Introduce `ExitBlock()` as an ASR node 

- integration_tests/do_loop_02.f90
The "j" loop was looping over all integers, wrapping around to negative integers and continuing to zero. It took over a second to run. Now it behaves as intended and runs immediately.
> do_loop_02: Fix infinite loop

- integration_tests/CMakeLists.txt
- integration_tests/complex_12.f90
- integration_tests/complex_13.f90
- integration_tests/complex_14.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/asr-complex_07-8d914e3.json
- tests/reference/asr-complex_07-8d914e3.stdout
- tests/reference/asr-sole_intrinsic-ee625f4.json
- tests/reference/asr-sole_intrinsic-ee625f4.stdout
Fixes #1416.
Credits: @sloorush, Addition, and Continuation to PR: #1028.
> Implement `visit_ComplexConstructor_t` for runtime arguments

- integration_tests/CMakeLists.txt
- integration_tests/nested_07.f90
- integration_tests/nested_08.f90
- src/libasr/codegen/asr_to_llvm.cpp
Fixes [#1150(comment)](https://github.com/lfortran/lfortran/issues/1150#issuecomment-1472535222).
Example in #1150 works perfect, but not in `example_lmder1`
> Fix handling of nested_globals in ASR to LLVM conversion

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_49.f90
- src/libasr/pass/intrinsic_function_registry.h
Closes https://github.com/lfortran/lfortran/issues/1452
This pull request is to fix issue #1452 which is an incorrect call to intrinsic functions in llvm. A small change to instantiate_functions in intrinsic_function_registry.h is all that is needed to fix the issue.
> Fixed c_func_name for complex argument type

- .github/workflows/CI.yml
This uses main branch of https://github.com/Pranavchiku/modern_minpack.git, it currently has a few commits as a workaround, and each such commit has a link to the LFortran issue that we need to fix. The workarounds are very small.
> CI: test modern_minpack with every commit

- integration_tests/modules_35.f90
- tests/reference/asr-modules_35-2a0333c.json
- tests/reference/asr-modules_35-2a0333c.stdout
- tests/reference/pass_implied_do_loops-modules_35-fde962b.json
- tests/reference/pass_implied_do_loops-modules_35-fde962b.stdout
See, https://github.com/lfortran/lfortran/actions/runs/4587462208/jobs/8100987850?pr=1480
> Add allocate statement in ``integration_tests/modules_35.f90`` for safety

- ci/build_tmp.xsh
- ci/environment.yml
Coming from - https://github.com/lfortran/lfortran/pull/1532#issuecomment-1502057502 and https://github.com/lfortran/lfortran/pull/1532#issuecomment-1501988353
I investigated. `nbconvert=7.3.1` names the generated file as `Demo1_out.nbconvert.ipynb` and `nbconvert<7.3.1` names it as `Demo1_out.ipynb`. `nbconvert 7.3.1` is getting installed on the CI but the build script is written according to `nbconvert < 7.3.1`.
See,
```zsh
(lf_nbconvert) 22:32:54:~/lfortran_project/lfortran/share/lfortran/nb % jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=360 --output Demo1_out.ipynb Demo1.ipynb
[NbConvertApp] Converting notebook Demo1.ipynb to notebook
Starting xeus-fortran kernel...
If you want to connect to this kernel from an other client, you can use the …
```
> Always use fixed ``nbconvert`` version in CI

- .github/workflows/CI.yml
It temporarily fixes the failing CI in main branch https://github.com/lfortran/lfortran/actions/runs/4673006168. A robust approach could/would be to debug what causes the github CI to fail when using node versions other than `14.18.2`.
Related https://github.com/lcompilers/lpython/pull/1699.
Also https://github.com/emscripten-core/emsdk/pull/829#issuecomment-1504472139.
> CI: Install and use specific node version

- .github/workflows/CI.yml
Just two workarounds needed:
* https://github.com/Pranavchiku/modern_minpack/commit/b3618f9a1c1bff8c3b1d259a84214886b8099cf3
* https://github.com/Pranavchiku/modern_minpack/commit/c0e0e6583b41573f54278469d6d58061fe6ea04b
> CI Minpack: use clean commits for workarounds

- integration_tests/CMakeLists.txt
- integration_tests/declaration_01.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/codegen/asr_to_llvm.cpp
> Add provision to get compile time value of Cast(ArrayConstant[]) while declaring variables

- doc/src/asr/asr_nodes/expression_nodes/Var.md
- doc/src/asr/asr_nodes/symbol_nodes/Variable.md
- doc/src/asr/asr_nodes/symbol_nodes/symbol_nodes.md
- integration_tests/CMakeLists.txt
- integration_tests/procedure_01.f90
- src/libasr/asr_verify.cpp
Towards #1247.
This PR adds tests and documentation, but the implementation itself requires `type_declaration`, which we will add in the next PR.
We documented the ASR design of this feature in the doc directory and we improved the documentation overall as well.
In future PRs:
* Add `type_declaration` to Variable (already documented in this PR)
* Get basic usage of `procedure(fn) :: x` in function arguments working (requires `type_declaration`)
* Add a test for calling the `procedure(fn) :: f` function using keyword arguments like `f(a=5)` (requires `type_declaration`)
* Add a test for procedure pointers: `procedure(fn), pointer :: f; f => my_fn; call f(a=5)`
* Even later: Implement Lambda functions, as expressions, possibly unify with Function
> Implementation of `procedure(fn) :: x` (I)

- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-functions_16-f863e4a.json
- tests/reference/asr-functions_16-f863e4a.stdout
Populate `type_declaration` for Function. Tests updated.
> Implementation of `procedure(fn) :: x` (III)

- integration_tests/CMakeLists.txt
- src/libasr/codegen/asr_to_llvm.cpp
This PR gets the basic `procedure(fn) :: x` working. Test is enabled. More tests and fixes are needed, but the basic implementation is done.
> Implementation of `procedure(fn) :: x` (V)

- integration_tests/CMakeLists.txt
- integration_tests/nested_11.f90
- src/libasr/pass/nested_vars.cpp
Closes https://github.com/lfortran/lfortran/issues/1596
> Use correct ``ExternalSymbol`` for nested variables in a given scope 

- integration_tests/CMakeLists.txt
- integration_tests/procedure_03.f90
- src/libasr/ASR.asdl
- src/libasr/asr_utils.h
- tests/reference/asr-implicit_interface5-4e61259.json
- tests/reference/asr-implicit_interface5-4e61259.stdout
- tests/reference/asr-implicit_typing2-4e0bae9.json
- tests/reference/asr-implicit_typing2-4e0bae9.stdout
- tests/reference/asr-modules_15b-5be0f8a.json
- tests/reference/asr-modules_15b-5be0f8a.stdout
- tests/reference/asr-redeclaration1-0adcc00.json
- tests/reference/asr-redeclaration1-0adcc00.stdout
- tests/reference/asr-template_array_03-81d3ec4.json
- tests/reference/asr-template_array_03-81d3ec4.stdout
The following file
```fortran
module minpack_module
use iso_fortran_env, only: wp => real64
implicit none
abstract interface
subroutine func(n, x, fvec, iflag)
!! user-supplied subroutine for [[hybrd]], [[hybrd1]], and [[fdjac1]]
import :: wp
implicit none
integer, intent(in) :: n !! the number of variables.
real(wp), intent(in) :: x(n) !! independent variable vector
real(wp), intent(out) :: fvec(n) !! value of function at `x`
integer, intent(inout) :: iflag !! set to <0 to terminate execution
end subroutine func
end interface
contains
subroutine hybrd(fcn)
implicit none
procedure(func) :: fcn
end subroutine 
end module
```
now seems to produce the correct ASR:
```console
$ lfortran --show-asr a.f90         
(TranslationUnit (SymbolTable 1 {iso_fortran_env: (IntrinsicModule …
```
> Initial FunctionParam implementation

- integration_tests/CMakeLists.txt
- integration_tests/sum_02.f90
- src/libasr/pass/intrinsic_function.cpp
- src/libasr/pass/intrinsic_function_registry.h
The last commit makes the error better. Apply this to upstream minpack plus our commit d778fdb067233c859f153e0799186387ea7d7ea4:
```diff
--- a/examples/example_hybrd.f90
+++ b/examples/example_hybrd.f90
@@ -59,8 +59,8 @@ program example_hybrd
if (abs(fnorm - 1.1926358347598092E-008_wp) > 1e-16) error stop
if ((abs(nfev - 14)) > 1e-16) error stop
if ((abs(info - 1)) > 1e-16) error stop
-    print *, "sum(x) = ", sum2(x)
-    if(abs(sum2(x) - (-5.7297012139802952_wp)) >  1e-16) error stop
+    print *, "sum(x) = ", sum(x)
+    if(abs(sum(x) - (-5.7297012139802952_wp)) >  1e-16) error stop
contains
@@ -96,13 +96,4 @@ contains
end subroutine fcn
-    real(wp) function sum2(x) result(r)
-    real(wp), intent(in) :: x(:)
-    integer :: i
-    r = 0
-    do i = 1, size(x)
-        r = r + x(i) …
```
> Add a test for the abs(sum(x) - y) issue

- .github/workflows/CI.yml
We now test Minpack directly from upstream, with the following commit applied:
https://github.com/Pranavchiku/modern_minpack/commit/fcde66ca86348eb0c4012dbdf0f4d8dba61261d8
Which adds checks into the examples of the type:
if (abs(fnorm - 1.1926358347598092E-008_wp) > 1e-16) error stop
if ((abs(info - 1)) > 1e-16) error stop
print *, "sum(x) = ", sum(x)
if (abs(sum(x) - (-5.7297012139802952_wp)) >  1e-16) error stop
To ensure correct results, and it uses the intrinsic abs() and sum() and it works.
> CI: Test modern Minpack with intrinsic sum

- run_tests.py
- src/bin/lfortran.cpp
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/utils.h
- tests/print3.f90
- tests/reference/asr-print3-5f4fc26.json
- tests/reference/asr-print3-5f4fc26.stdout
- tests/tests.toml
> Compiler option to print leading space for `print *`

- .github/workflows/CI.yml
Fixes the following warnings
```
ld: warning: dylib (/Users/runner/work/lfortran/lfortran/src/runtime/liblfortran_runtime.dylib) was built for newer macOS version (12.6) than being linked (12.0)
```
> CI: Fix macos warnings

- integration_tests/CMakeLists.txt
- integration_tests/modules_51.f90
- src/lfortran/semantics/ast_common_visitor.h
> Allow declaration of variables with nullptr vartype in module when `--implicit-typing` is enabled

- CMakeLists.txt
> CMake: support LLVM as a single shared library

- integration_tests/CMakeLists.txt
- integration_tests/statement_01.f90
- integration_tests/statement_02.f90
- integration_tests/statement_03.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-statement_01-00eefc8.json
- tests/reference/asr-statement_01-00eefc8.stdout
- tests/reference/asr-statement_02-daaef34.json
- tests/reference/asr-statement_02-daaef34.stdout
- tests/reference/asr-statement_03-99c9cd3.json
- tests/reference/asr-statement_03-99c9cd3.stdout
- tests/tests.toml
Fixes #1793. Fixes #1796.
With this LFortran compile `scipy/stats/statlib` to ASR.
Fixes #1797.
> Bug fixes for `statement` functions

- src/lfortran/semantics/ast_body_visitor.cpp
- tests/allow_implicit_interface4.f90
- tests/reference/asr-allow_implicit_interface4-4615450.json
- tests/reference/asr-allow_implicit_interface4-4615450.stdout
- tests/tests.toml
Fixes #1441.
With this LFortran now compiles all of `scipy/scipy/integrate/quadpack` to ASR.
> Add provision to update args of subroutine call when `--implicit-interface` is enabled

- integration_tests/CMakeLists.txt
- integration_tests/external_02.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes #1801.
With this and #1800 PR LFortran compile 61/64 files of `scipy/special/cdflib` to ASR, the remaining 3 are `save` , `visit_DataImpliedDo`.
> handle `implicit none` in external variable declaration

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_52.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/runtime/pure/lfortran_intrinsic_math2.f90
- tests/fixed_form/intrinsic_implicit.f
- tests/reference/asr-external3-2aafcb3.json
- tests/reference/asr-external3-2aafcb3.stdout
- tests/reference/asr-fn5-3d75eb7.json
- tests/reference/asr-fn5-3d75eb7.stdout
- tests/reference/asr-intrinsic_implicit-77de888.json
- tests/reference/asr-intrinsic_implicit-77de888.stdout
- tests/reference/asr-string_19-d880475.json
- tests/reference/asr-string_19-d880475.stdout
- tests/reference/asr-template_triple-54fa485.json
- tests/reference/asr-template_triple-54fa485.stdout
- tests/reference/pass_flip_sign-expr_13-e24d940.json
- tests/reference/pass_flip_sign-expr_13-e24d940.stdout
- tests/reference/pass_flip_sign-flip_sign-16b288c.json
- tests/reference/pass_flip_sign-flip_sign-16b288c.stdout
- tests/tests.toml
This is simple working fix for the min0 and max0 intrinsic functions.
The following now works and produces the correct ASR.
```fortran
program intrinsics_52
integer :: a, b, c, d, e, f
a = 2
b = -3
c = 5
d = 10
e = 20
f = -30
if (max0(10,20) /= 20) error stop
if (max0(3,5,4) /= 5) error stop
if (max0(a,b) /= a) error stop
if (max0(a,b,c) /= c) error stop
if (max0(d,e,f,a,b,c) /= e) error stop
if (min0(10,20) /= 10) error stop
if (min0(3,5,4) /= 3) error stop
if (min0(a,b) /= b) error stop
if (min0(c,b,a) /= b) error stop
if (min0(d,e,f,a,b,c) /= f) error stop
end
```
> Implement multi-argument min0 and max0 using lfortran_intrinsic

- CMakeLists.txt
Right now, cmake will just happily continue even if running `./build0.sh` fails, this patch fixes that.
> cmake: fail if build0.sh fails

- integration_tests/format_04.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/runtime/lfortran_intrinsics.c
This PR builds up on #1829 and implement Strings, newlines and positional edits using ```StringFormat```.
@certik Please review my latest commit. If its alright then I'll continue adding other formatting types.
The following produces the expected output:
```fortran
program format_04
print *, "ok", "b"
print '(a,a)', "ok", "b"
print '("Success!",/,10X,A6,"World!")',"Hello 123"
end program
```
Output:
```console
ok b
okb
Success!
Hello World!
```
> Implement Strings, newlines and positional edits using StringFormat

- integration_tests/CMakeLists.txt
- integration_tests/data_08.f90
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-implicit4-704272e.json
- tests/reference/asr-implicit4-704272e.stdout
> Add provision to check `array->m_type` in data stmt

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_52.f90
- integration_tests/intrinsics_54.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/pass/intrinsic_function_registry.h
- tests/reference/asr-intrinsic_implicit-77de888.json
- tests/reference/asr-intrinsic_implicit-77de888.stdout
Will fix #1739
Work in Progress
The ```max0``` and ```min0``` Fortran functions can accept any arbitrary number of arguments.
@czgdp1807 Can you please review this and guide me with the implementation of the  ```instantiate_Max()``` function? How would I write that?
> Implementation of max0() using IntrinsicFunction

- integration_tests/CMakeLists.txt
- integration_tests/character_01.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes #693. Fixes #768.
With this PR we get `scipy/odr/odrpack` compiled to ASR.
> Allow `character :: a*4, b(2) * 5`

- integration_tests/CMakeLists.txt
- integration_tests/common_10.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Fixes #1910.
With this and #1909 we get `scipy/sparse/linalg/_eigen/arpack` compiled to ASR.
> Allow to cast if target is `StructInstanceMember`

- integration_tests/CMakeLists.txt
- integration_tests/common_11.f90
- src/lfortran/semantics/ast_common_visitor.h
> Add provision to handle `ArrayItem` while populating `COMMON` block variables

- .github/workflows/CI.yml
- src/libasr/asr_utils.h
- src/libasr/asr_verify.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/array_op.cpp
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/pass_array_by_data.cpp
Closes https://github.com/lfortran/lfortran/issues/1932
`main.f90` in `fastGPT` generates LLVM with LFortran. I will add the test for the same in `CI.yml` with `lf3` branch.
> Generate LLVM from ``fastGPT``

- integration_tests/CMakeLists.txt
- integration_tests/implicit_argument_casting_01.f90
- integration_tests/run_tests.py
- run_tests.py
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/asr_utils.cpp
- src/libasr/asr_utils.h
- src/libasr/pass/array_op.cpp
- src/libasr/pass/global_stmts_program.cpp
- src/libasr/pass/instantiate_template.cpp
- src/libasr/pass/intrinsic_function.cpp
- src/libasr/pass/nested_vars.cpp
- src/libasr/pass/pass_utils.cpp
- src/libasr/pass/subroutine_from_function.cpp
- src/libasr/pass/transform_optional_argument_functions.cpp
- tests/reference/asr-implicit_argument_casting_01-2274b4b.json
- tests/reference/asr-implicit_argument_casting_01-2274b4b.stdout
- tests/tests.toml
Fixes #1926.
With this, we get `scipy/linalg` compile to ASR once again.
> Implement `--implicit-argument-casting`

- integration_tests/CMakeLists.txt
- integration_tests/entry_05.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- tests/reference/asr-entry_05-f368f0e.json
- tests/reference/asr-entry_05-f368f0e.stdout
- tests/tests.toml
Fixes #1869. Fixes #1913.
This will work for updating nodes of statement functions, but I am not sure about updating the types of variables. The correct fix will be to store AST nodes and redeclare it for entry functions.
> Add provision to update duplicated nodes of entry function correctly

- src/libasr/asr_verify.cpp
- src/libasr/serialization.cpp
Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/2155
> Avoid verifying ``IntrinsicFunction`` if ``check_external`` is ``False``

- integration_tests/CMakeLists.txt
[1942#pullrequestreview](https://github.com/lfortran/lfortran/pull/1942#pullrequestreview-1520393946)
> Add `gfortranImpilicitArgument` flag in integration tests

- src/libasr/codegen/asr_to_llvm.cpp
To catch errors earlier.
Towards #1977.
> LLVM: Add an assert statement

- integration_tests/CMakeLists.txt
- integration_tests/entry_08.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Fixes #1986. 
With this and #1984 we get `scipy/special/cdflib` compile to LLVM
> Avoid visiting statements after return in entry function

- .github/workflows/CI.yml
Now when we can compile to a binary, we do not need to test ASR, as it is implicitly tested now as well. The `ldd` line prints the shared libraries, so that we can check that they got linked correctly.
> CI: simplify the fastGPT test, add ldd

- src/libasr/codegen/asr_to_llvm.cpp
```zsh
(fastgpt) 21:10:02:~/lfortran_project/fastGPT % FC=lfortran cmake -DFASTGPT_BLAS=OpenBLAS .
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is unknown
-- Detecting Fortran compiler ABI info
-- …
```
> Fix for allocatable array in ``ArrayAll``

- integration_tests/format_05.f90
- src/libasr/runtime/lfortran_intrinsics.c
The formatting of f8.3 is not correct, but at least it prints the right number now.
> Initial support for f8.3 format

- src/libasr/codegen/asr_to_llvm.cpp
This is hard to test currently, but once we support formatted writing into a string, we will be able to test it.
Fixes #2019.
> Fix printing a struct member

- src/libasr/runtime/lfortran_intrinsics.c
> Fix a bug in _lfortran_read_array_int8

- .github/workflows/CI.yml
The results agree with GFortran. There is just one change with regards to correct results:
diff --git a/gpt2.f90 b/gpt2.f90
index e04fec5..b3dbdd3 100644
--- a/gpt2.f90
+++ b/gpt2.f90
@@ -274,7 +274,7 @@ end if
!print *, "It fails below:"
do j = 1, n_layer
i = j
-    !i = 1
+    i = 1
!    print *, i ! Never gets printed
call transformer_block(n_seq, n_seq_x, n_embd, x, &
mlp_fc_w(:,:,i), mlp_fc_b(:,i), &
Without it LFortran has a bug while passing `A(:,i)` as an argument, only `i=1` works, higher `i` fail.
> CI: test full fastGPT run

- src/bin/lfortran.cpp
We now can do `lfortran -E main.f -o main.cpp`. I came across this while implementing compiler detection on cmake.
> Save preprocessed source to file

- integration_tests/CMakeLists.txt
- integration_tests/cpp_pre_01.f90
- src/lfortran/fortran_evaluator.cpp
- src/lfortran/utils.cpp
- src/lfortran/utils.h
fixes https://github.com/lfortran/lfortran/issues/1945
```fortran
$ cat examples/expr2.f90 
! File test.f90
program test
#ifdef SOMETHING
#endif // This should work
#define square(a) /* This should be ignored as well */ a * a
integer :: a = 10
print*, square(a)
end program test
```
```
$ gfortran examples/expr2.f90 -cpp 
$ ./a.out 
100
```
```
$ lfortran examples/expr2.f90 --cpp
100
```
> CPP Preprocessor remove cpp comments

- .github/workflows/CI.yml
The SciPy package takes a very long time to build (20+ minutes), so we move this test up, so that it starts sooner, to reduce the total CI test time.
> CI: move the scipy test up to run sooner

- integration_tests/CMakeLists.txt
- integration_tests/minpack_03.f90
Fixes: https://github.com/lfortran/lfortran/issues/1563
> Test added for Type *getType() const { return VTy; }

- src/bin/lfortran.cpp
At the moment we only use the file extension .f, in the future as problems arise we can add more heuristics like what values appear on the first 5 columns.
~~Is there any reason this has not been done yet?~~
~~Ok, six tests fail, if those are the only reasons I'm wiling to work on them.~~
> Add flag --fixed-form-infer

- .github/workflows/CI.yml
It seems a few hours back `conda` used to install node `v18`. It currently installs node `v20`. It seems there are some changes to WASI API interface in node `v20`. For the moment, in this PR, we are using a fixed node `v18` at the CI. For the longer term, I think we can try supporting all major node versions for the generated `wasm` binary and related `js` script.
> CI: Use fixed node v18.13.0

- .github/workflows/CI.yml
Now we only have `nan` handling and segmentation fault left #2198.
> CI: use latest commit to test Scipy

- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
- tests/errors/array_03.f90
- tests/errors/array_04.f90
- tests/reference/asr-array_03-a79d86f.json
- tests/reference/asr-array_03-a79d86f.stderr
- tests/reference/asr-array_04-5864f91.json
- tests/reference/asr-array_04-5864f91.stderr
- tests/tests.toml
Closes #2197 
This adds an error message for indexing a non-array variable or type member.
> Better error message for nonarray indexing

- .github/workflows/CI.yml
This tests two new commits to fastGPT:
* https://github.com/certik/fastGPT/commit/3fe851aae07338a20d55cef344b097b2b2d3ae98
* https://github.com/certik/fastGPT/commit/1b3501f75399f350a2cac51a89d9024493a2c34f
> CI: remove several slice workarounds in fastGPT

- .github/workflows/CI.yml
This PR converts some subroutines back to functions, but not all yet:
* https://github.com/certik/fastGPT/commit/5a289cec91938d7754c123797c65457ddc3d571a
> CI fastGPT: convert some subroutines to functions

- src/bin/lfortran.cpp
Also make it shorter to fit in an 80 column terminal.
> Fix a typo in a help string

- .github/workflows/CI.yml
This converts the `gpt2` subroutine to a function, but it modifies the output array so that it works with LFortran:
* https://github.com/certik/fastGPT/commit/71fc5a89233873e5606fff8d6e16d3905f36ee42
It is not clear to me yet what exactly the bug is, but the above commit works, which brings `fastGPT` closer to `main`, so it's a step in the right direction.
> CI fastGPT: turn gpt2 into a function

- integration_tests/CMakeLists.txt
- integration_tests/mangle_underscore_01.f90
- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/libasr/CMakeLists.txt
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/pass_manager.h
- src/libasr/pass/unique_symbols.cpp
- src/libasr/pass/unique_symbols.h
- src/libasr/utils.h
Thanks @Smit-create for implementation! When I use `--all-mangling --mangle-underscore` flags to compile the file, I now don't need `_` fixes.
PS: I just copied entire pass from `lpython` and added `--mangle-underscore` flag to explicitly specify `_` mangling.
> Use `unique_symbols` pass from lpython

- integration_tests/CMakeLists.txt
- integration_tests/format_07.f90
- src/libasr/pass/print_arr.cpp
Fixes https://github.com/lfortran/lfortran/pull/2193#issuecomment-1694506731
This PR allows to print arrays while using format statements.
The following gives same output for GFortran and LFortran
```fortran
program format_07
implicit none
integer, parameter :: dp=kind(0d0)
real(dp) :: x(3)
real :: z(3)
integer :: y(4)
x = [1._dp,1._dp,1._dp]
y = [117,123,124,126]
z = [1.0,2.0,3.0]
10 format(3d12.5)
20 format(4i10)
30 format(3d12.5)
print 10, x
print 20, y
print 30, z
end program
```
```console
0.10000D+01 0.10000D+01 0.10000D+01
117       123       124       126
0.10000D+01 0.20000D+01 0.30000D+01
```
> Print arrays with StringFormat

- integration_tests/CMakeLists.txt
From https://github.com/lfortran/lfortran/issues/597,
>CI: Testing NodeJS version compare fix/make-robust
The statement string(COMPARE GREATER_EQUAL "${WASM_EXEC_VERSION}" "v16.0.0" IS_NODE_ABOVE_16) in integration_tests/CMakeLists.txt can/might return wrong/undesired result when the node version is between (around) v2.0.0 to <= v9.x.x
This PR fixes the above.
> CMake: Fix node version compare

- .github/workflows/CI.yml
Continuation of #2268. Okay, so the latest branch `scipy/special8` has all tests working, now the only fix left to do is #2198
> CI: use exact version in environment.yml, check the halting nan test

- integration_tests/format_04.f90
- src/libasr/runtime/lfortran_intrinsics.c
Fixes https://github.com/lfortran/lfortran/issues/2274
This now gives the same output as ```gfortran```:
```fortran
program format_04
real :: a,b,c
integer :: f
a = 123.456
b = 123.45678
c = 12.34
f = 12345
print '(i0)', f, -f
print '(d0.0,1x,d0.1,1x,d0.2)',a,b,c
print '(d0.0,1x,d0.1,1x,d0.2)',-a,-b,-c
print '("Hello")'
end program
```
```console
12345
-12345
0.123456001D+3 0.1D+3 0.12D+2
-0.123456001D+3 -0.1D+3 -0.12D+2
Hello
```
> Improvements to integer and decimal formatting

- integration_tests/format_06.f90
- integration_tests/format_07.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/pass/print_arr.cpp
```write``` statements will now be able to print arrays correctly and use labels to find ```format``` statements below them.
See the added tests in ```format_06.f90``` and ```format_07.f90``` for example, they now give the same output as ```gfortran```.
> Implement array support and format label for WRITE statements

- integration_tests/CMakeLists.txt
- integration_tests/precision_01.f90
- integration_tests/precision_02.f90
- src/lfortran/semantics/asr_implicit_cast_rules.h
- tests/reference/asr-div_to_mul-3aaf3c0.json
- tests/reference/asr-div_to_mul-3aaf3c0.stdout
- tests/reference/asr-intrinsics_03-ef06d46.json
- tests/reference/asr-intrinsics_03-ef06d46.stdout
- tests/reference/asr-intrinsics_04-524ec3a.json
- tests/reference/asr-intrinsics_04-524ec3a.stdout
- tests/reference/asr-intrinsics_37-8df004d.json
- tests/reference/asr-intrinsics_37-8df004d.stdout
- tests/reference/llvm-intrinsics_03-0771f1b.json
- tests/reference/llvm-intrinsics_03-0771f1b.stdout
- tests/reference/pass_div_to_mul-div_to_mul-d0027c6.json
- tests/reference/pass_div_to_mul-div_to_mul-d0027c6.stdout
> Use kind as tiebreaker when two types have same priority 

- src/libasr/pass/print_arr.cpp
Fixes broken CI: https://github.com/lfortran/lfortran/actions/runs/6029177336/job/16358089914
> check if` x.m_values` is not nullpointer before accessing its value

- .github/workflows/CI.yml
The only patch left is:
```diff
% git diff origin/main scipy/special/specfun/specfun.f
diff --git a/scipy/special/specfun/specfun.f b/scipy/special/specfun/specfun.f
index b30997331..5025de738 100644
--- a/scipy/special/specfun/specfun.f
+++ b/scipy/special/specfun/specfun.f
@@ -4382,7 +4382,7 @@ C             (2) DVLA for computing Dv(x) for large |x|
C       ====================================================
C
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
-        DIMENSION DV(0:*),DP(0:*)
+        DIMENSION DV(0:100),DP(0:100)
XA=DABS(X)
VH=V
V=V+DSIGN(1.0D0,V)
@@ -7978,7 +7978,7 @@ C       ==================================================
C
IMPLICIT DOUBLE PRECISION (A-B,D-H,O-Y)
IMPLICIT COMPLEX*16 (C,Z)
-        DIMENSION CPB(0:*),CPD(0:*)
+        DIMENSION CPB(0:100),CPD(0:100) …
```
> CI: bump to latest commit of scipy

- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/unique_symbols.cpp
- src/libasr/utils.h
Refer: https://github.com/lfortran/lfortran/pull/2263#issuecomment-1701441308
> Add a compiler option to enable mangling of bindc abi type functions

- .github/workflows/CI.yml
These are the only workarounds left in [gpt2.f90](https://github.com/certik/fastGPT/blob/63d279d800ab316f4143a681d4cd46486e4d7f26/gpt2.f90):
```diff
diff --git a/gpt2.f90 b/gpt2.f90
index 28406a5..a57876e 100644
--- a/gpt2.f90
+++ b/gpt2.f90
@@ -21,7 +21,7 @@ type :: model_t
ln2_b(:,:), ln2_g(:,:), &
lnf_b(:), lnf_g(:)
integer, allocatable :: decoder_idx(:), vocab_idx(:), byte_encoder(:)
-    integer(1), allocatable :: decoder_txt(:), vocab_txt(:)
+    character, allocatable :: decoder_txt(:), vocab_txt(:)
integer :: model_file_version
end type
@@ -93,13 +93,9 @@ end function
function ffn(x, fc_w, fc_b, proj_w, proj_b) result(y)
real(sp), intent(in) :: x(:,:), fc_w(:,:), fc_b(:), proj_w(:,:), proj_b(:)
real(sp) :: y(size(x,1),size(x,2))
-real(sp) :: yy(size(x,1),size(x,2))
-real(sp) :: …
```
> CI fastGPT: remove several workarounds

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/string_binop.f90
- tests/reference/asr-string_binop-415f1fa.json
- tests/reference/asr-string_binop-415f1fa.stderr
- tests/tests.toml
Fixes #2303 
```fortran
print *, "a" + "b"
end
```
```console
(lf) sarthak@pop-os:~/lfortran$ lfortran tests/errors/string_binop.f90 
semantic error: Binary numeric operators cannot be used on strings
--> tests/errors/string_binop.f90:1:10
|
1 | print *, "a" + "b"
|          ^^^^^^^^^ help: use '//' for string concatenation
Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
> Fix: Throw an error for numeric binop on strings

- integration_tests/reserved_02.f90
- tests/reference/ast_f90-reserved_02-a00a6f2.json
- tests/reference/ast_f90-reserved_02-a00a6f2.stdout
Otherwise it fails in fast mode, probably LLVM optimizes some things out.
> reserved_02.f90: initialize the variable

- integration_tests/CMakeLists.txt
- src/libasr/pass/pass_manager.h
This pass doesn't work in all cases yet. Now many tests work with `--fast`, as well as fastGPT.
Many `--fast` tests were enabled, and I created an issue https://github.com/lfortran/lfortran/issues/2315 to enable the rest.
Fixes #2313.
> Disable inlining functions for --fast

- src/libasr/runtime/lfortran_intrinsics.c
See https://github.com/conda-forge/lfortran-feedstock/pull/41 for the failure.
> Do not use clock_gettime for Intel macOS

- integration_tests/CMakeLists.txt
- integration_tests/format_08.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/runtime/lfortran_intrinsics.c
Fixes https://github.com/lfortran/lfortran/issues/2320 and https://github.com/lfortran/lfortran/issues/2321
```fortran
program test_print
implicit none
character(:), allocatable :: a
a = "xx"
print "(a)", a
end program
```
```console
xx
```
```fortran
program test_print
implicit none
integer :: a(10)
a = 1
print "(1000(i6))", a
end program
```
```console
1     1     1     1     1     1     1     1     1     1
```
> Compute args for StringFormat and fix format segfault

- integration_tests/format_04.f90
- src/libasr/runtime/lfortran_intrinsics.c
Fixes https://github.com/lfortran/lfortran/issues/2325
```fortran
PROGRAM TEST
DOUBLE PRECISION :: R,S,T
R = 12345678
S = 23.5678
T = 0.345678
PRINT '( F13.3,1X,F9.6,1X, F0.2 )', R, S, T
PRINT '( F13.3,1X,F9.6,1X, F0.2 )', -R, -S, -T
END 
```
```console
12345678.000 23.567800 .35
-12345678.000 ********* -.35
```
I might have missed some corner cases, let me know if this is working as expected with fastGPT
> Implement 'F' formatting for float values

- .github/workflows/CI.yml
- integration_tests/file_10.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/runtime/lfortran_intrinsics.c
- src/libasr/runtime/lfortran_intrinsics.h
This PR gets the chat program in the lf33run branch at fastgpt (https://github.com/certik/fastGPT/tree/lf33run) to run. It currently works for first 2 prompts but segfaults on the exact third run. Also, note that in the lf33run branch, to make it work with LFortran, we replaced a local array allocated on stack with an allocatable array allocated on heap.
> Support iostat in read()

- integration_tests/format_04.f90
- integration_tests/format_08.f90
- src/libasr/runtime/lfortran_intrinsics.c
Before i was splitting the format statement into comma separated values. That was not an efficient implementation as it does not work for many cases like ```(aai6)```.
Now i have implemented a parser for the format statements. This way it will be easily maintainable in the future too.
Example from ```scipy```:
```fortran
WRITE(*,9000)
9000 FORMAT(/' Adjust D1MACH by uncommenting data statements'/
*' appropriate for your machine.')
```
```console
Adjust D1MACH by uncommenting data statements
appropriate for your machine.
```
> Implement a parser for IO Format

- integration_tests/CMakeLists.txt
- integration_tests/file_13.f90
- src/lfortran/semantics/ast_body_visitor.cpp
This PR solves the following issue:
```
integration_tests % cat file_13.f90     
program file_13
implicit none
integer :: num
open(UNIT=1, file="file_01_data.txt", form="formatted", access="stream", status="old")
read(1, *) num
close(1)
print *, num
if (num /= 10130) error stop
end program
integration_tests % cat file_01_data.txt
10130
c
4.20
9223372036854775804
integration_tests % gfortran file_13.f90
integration_tests % ./a.out 
10130
integration_tests % lfortran_in_main file_13.f90
semantic error: `newunit` or `unit` must be specified either in argument or keyword arguments.
--> file_13.f90:6:5
|
6 |     open(UNIT=1, file="file_01_data.txt", form="formatted", access="stream", status="old")
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> Fix open keyword args case

- integration_tests/intrinsics_17.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/pass/intrinsic_function_registry.h
Fixes https://github.com/lfortran/lfortran/issues/2378
```datan2()``` is an archaic form of ```atan2``` that works only on ```real(8)``` kind.
```fortran
program main
real*8 :: x
x = datan2(0d0,-1.d0)
print*, "x = ", x
end program
```
```console
x =  3.14159265358979312e+00
```
Implemented as an intrinsic function. Implemented a namespace ```BinarayInstrinsicFunction```  (taken from ```UnaryInstinsicFunction```) as well, since I thought it would be useful in the future.
> Implement datan2()

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_71.f90
- src/libasr/pass/intrinsic_array_function_registry.h
This PR fixes the following issue:
```bash
$ cat integration_tests/intrinsics_71.f90      
program intrinsics_71
implicit none
integer :: result_value
result_value = routine(3)
print *, result_value
if (result_value /= 600) error stop
contains
function routine(p) result(r)
integer, intent(in) :: p
integer :: a(1, p)
integer :: b(p, 1)
integer :: c(1, 1)
integer :: r
a(1, 1) = 10
a(1, 2) = 10
a(1, 3) = 10
b(1, 1) = 20
b(2, 1) = 20
b(3, 1) = 20
c = matmul(a, b)
r = c(1, 1)
end function routine
end program
$ gfortran integration_tests/intrinsics_71.f90
$ ./a.out 
600
$ lfortran_in_main integration_tests/intrinsics_71.f90 
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.
ASR verify pass error: ASR verify: Var::m_v `p` cannot point outside of its …
```
> Fix intrinsic function dependency on external symbol in dims

- integration_tests/CMakeLists.txt
- integration_tests/array_unbounded_01.f90
- integration_tests/array_unbounded_02.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/ASR.asdl
- src/libasr/asr_utils.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/codegen/llvm_array_utils.h
- src/libasr/codegen/llvm_utils.cpp
Fixes https://github.com/lfortran/lfortran/issues/2198. I manually checked scipy build for specfun, now we can remove the one last patch that we had :). With this PR, we get specfun working perfectly without any patches.
> Introduce and implement `UnboundedPointerToData`

- .github/workflows/CI.yml
With this we get `scipy/special/specfun` tested without any patch. We are using https://github.com/certik/scipy/commits/merge_special_minpack3, it has only 3 commits those are `exact version in environment file`, `Specfun: use our own library`, `Minpack: use our own library`, no extra patches.
> CI: bump specfun, minpack to latest commit of scipy, remove all patches

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_72.f90
- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/intrinsics_02.f90
- tests/reference/asr-intrinsics_02-eb20326.json
- tests/reference/asr-intrinsics_02-eb20326.stderr
- tests/tests.toml
Function reference for ```datan2``` is not working in main because it is not registered in the ```comptime_eval_map```.
That is now fixed with this PR. A real-time test for ```datan2``` has been registered as well.
```fortran
program main
real(8) :: x, y, datan2
x = 2.0D0
y = 3.0D0
print *, datan2(x,y)
end program
```
```console
(lf) ~$ lfortran --implicit-interface integration_tests/intrinsics_72.f90 
5.88002603547567504e-01
```
>  https://github.com/lfortran/lfortran/issues/2345#issuecomment-1711656575 These get resolved when I comment out real*8 datan2
This will not be required anymore.
> Fix function reference and create real-time test for `datan2`

- .github/workflows/CI.yml
Once https://github.com/lfortran/lfortran/pull/2395 gets merged, we can merge this too.
With this we get scipy/interpolate/fitpack tested without any patch. We are using https://github.com/certik/scipy/commits/merge_specfun_minpack_fitpack3, it has only 4 commits, and those are "exact version in environment file", "Specfun: use our own library", "Minpack: use our own library" and "Fitpack: use our own library" and no extra patches.
> CI: bump specfun, minpack, fitpack to latest commit of scipy, remove all patches

- integration_tests/CMakeLists.txt
- integration_tests/interface_14.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/libasr/asdl_cpp.py
- src/libasr/asr_utils.h
- src/libasr/pass/pass_array_by_data.cpp
- src/libasr/pass/pass_utils.h
Fixes the issue https://github.com/lfortran/lfortran/issues/2386#issuecomment-1720501673.
Related https://github.com/lcompilers/lpython/pull/2326.
> Fixes reference to derived_type_symbol in Function that has interface as argument

- integration_tests/CMakeLists.txt
- integration_tests/format_09.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/print_arr.cpp
Fixes https://github.com/lfortran/lfortran/issues/2344
This PR allows us to use arrays in between arguments of print statements and print them with the correct formatting.
Before, we made a new print statement for every element for the array.
Now we have all of them, along with the other arguments, in a single ```StringFormat``` expr in their correct places.
The following produces the same output for lfortran and gfortran:
```fortran
program format_09
implicit none
integer :: a(5),b(5),c(10)
integer, parameter :: dp=kind(0d0)
real(dp) :: d(3)
a = [117,123,124,126,129]
b = [1,2,3,4,5]
c = 1
d = [1._dp,1._dp,1._dp]
print '(6(i6))', c
print 10, "hello", a ,"world", b
10  format(a,i10,i4,i5,i6,i7)
print 20, 'String:', 3.1415926d0, &
'Integer:', 42, &
'Array:', d
20 …
```
> Handle arrays for StringFormat correctly

- integration_tests/CMakeLists.txt
- integration_tests/interface_15.f90
- src/libasr/asr_utils.h
- src/libasr/pass/pass_array_by_data.cpp
fixes https://github.com/lfortran/lfortran/issues/2435
> Dftatom: Fix reference to derived_type when duplicating symbol

- integration_tests/CMakeLists.txt
- integration_tests/implied_do_loops4.f90
- src/libasr/pass/implied_do_loops.cpp
With this we get `scipy/optimize/lbfgsb_src` compiled to LLVM.
We currently have support for implied do loops represented as `[(i, i=1,3)]`, so to get `print *, (i,i=1,3)` working I replaced it as `print *, [(i, i=1,3)]`.
> Hack to get I/O operations via implied do loops working

- integration_tests/CMakeLists.txt
- integration_tests/format_09.f90
- integration_tests/write_04.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/print_arr.cpp
- src/libasr/runtime/lfortran_intrinsics.c
- tests/reference/asr-arrays_23-a731033.json
- tests/reference/asr-arrays_23-a731033.stdout
- tests/reference/asr-derived_types_04-da02dd9.json
- tests/reference/asr-derived_types_04-da02dd9.stdout
- tests/reference/asr-derived_types_06-847ca73.json
- tests/reference/asr-derived_types_06-847ca73.stdout
- tests/reference/asr-fn5-3d75eb7.json
- tests/reference/asr-fn5-3d75eb7.stdout
- tests/reference/asr-fn6-a24010a.json
- tests/reference/asr-fn6-a24010a.stdout
- tests/reference/asr-intrinsics_open_close_read_write-a696eca.json
- tests/reference/asr-intrinsics_open_close_read_write-a696eca.stdout
- tests/reference/run-write4-329d906.json
- tests/reference/run-write4-329d906.stdout
- tests/reference/run-write5-4a89b6b.json
- tests/reference/run-write5-4a89b6b.stdout
- tests/write5.f90
Fixes https://github.com/lfortran/lfortran/issues/2413
```fortran
program test
implicit none
write(*,'("Hello ")',advance='NO')
write(*,'("world!")')
end program
```
```console
(lf) ➜  lfortran git:(advance) ✗ lfortran examples/temp.f90 
Hello world!
```
> Implement formatting for Write statement and fix "advance" bug

- src/libasr/codegen/asr_to_c_cpp.h
Towards #2293.
The `matmul_01` example now compiles via the C backend:
```
lfortran --backend=c matmul_01.f90
```
But there are warnings (the generated code for Associate is not completely correct yet) and the code segfaults when running (at the very least due to incorrect ArraySection handling by this PR).
> C: Initial implementation of ReAlloc and Associate

- src/libasr/pass/array_op.cpp
fixes https://github.com/lfortran/lfortran/issues/2454
> PASS: Fix unused variable warning in array_op

- integration_tests/run_tests.py
Fixes: https://github.com/lfortran/lfortran/issues/2482
> Set `-DCMAKE_Fortran_FLAGS` to use `-g` option for Fortran backend

- src/bin/lfortran.cpp
This allows lfortran to work with cmake when it passes `-fPIC` to it. We should probably only support `-fPIC` as a no-op (by checking the `f_flags` vector and ensuring only `PIC` is passed, otherwise give an error), since I think by default we generate position independent code.
> Support the -fPIC flag (ignoring it for now)

- integration_tests/CMakeLists.txt
- integration_tests/legacy_array_sections_02.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Fixes: https://github.com/lfortran/lfortran/issues/2481
> Handle a 1D array from 2D array in legacy-array-sections

- integration_tests/CMakeLists.txt
- integration_tests/optional_04.f90
- src/libasr/pass/transform_optional_argument_functions.cpp
Fixes #2463.
Code gets compiled and give a junk value in return, that is why I have not added any test yet
```fortran
module m
contains
subroutine sub( a )
integer, intent(in), optional :: a(10)
call sub2( a(5) )
end subroutine
subroutine sub2( a )
integer, intent(in), optional :: a
if ( present(a) ) print *, a
end subroutine
end module
use m
call sub()
end
```
> LFortran
```console
% lfortran a.f90              
-1470529752
```
> GFortran
```console
% gfortran a.f90&& ./a.out
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x1028e5b07
#1  0x1028e4b53
#2  0x1a891ea23
#3  0x1029d8597
zsh: segmentation fault  ./a.out
```
> Handle nested optional arguments

- .github/workflows/CI.yml
> CI: use CMake system to build SciPy

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_78.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/comptime_eval.h
- src/libasr/pass/intrinsic_function_registry.h
I was trying to see how far we are to compile https://github.com/perazz/fortran-primes/tree/main which requires intrinsic `mod`.
> Implement intrinsic `mod`

- src/bin/lfortran.cpp
- src/libasr/dwarf_convert.py
- src/libasr/runtime/lfortran_intrinsics.c
Fixes: https://github.com/lfortran/lfortran/issues/2535
> Support runtime stacktrace to work in arbitrary directories

- src/libasr/codegen/asr_to_llvm.cpp
- tests/errors/runtime_stacktrace_01.f90
- tests/reference/run_dbg-runtime_stacktrace_01-dcc746e.json
- tests/reference/run_dbg-runtime_stacktrace_01-dcc746e.stderr
Fixes: https://github.com/lfortran/lfortran/issues/2537
> [LLVM] Print stack trace in `stop` only for non-zero exit code

- integration_tests/CMakeLists.txt
- integration_tests/fortran_primes_01.f90
- src/lfortran/semantics/ast_common_visitor.h
Towards #2545.
A test needs to be added.
> Use std::stoll instead of std::stoi

- src/lfortran/semantics/ast_common_visitor.h
instead of populating it for every function call
> Refactor: Initialize double_precision_intrinsics only once

- integration_tests/CMakeLists.txt
Fixes: https://github.com/lfortran/lfortran/issues/2570
> Throw error for unsupported backend in CMakeLists

- CMakeLists.txt
- ci/environment.yml
- cmake/FindStaticZSTD.cmake
> Find the zstd library properly

- tests/errors/template_error_08.f90
- tests/reference/asr-template_error_08-b380a57.json
There was a duplicate module name, now it should be fixed.
Towards #2606.
> Rename the module in tests

- integration_tests/format_04.f90
- src/libasr/runtime/lfortran_intrinsics.c
Fixes https://github.com/lfortran/lfortran/issues/2554 and https://github.com/lfortran/lfortran/issues/2547
Precision of double should be correct upto atleast 10 places now.There is a small loss of precision in printing double somewhere, maybe when we receive it in the runtime library, but I'll try to find it. Though in my experience, even Fortran does not print high precision real values correctly.
```fortran
program expr2
implicit none
real(8) :: x_1, x_2
x_1 = -25658.418788050920
x_2 = 8.9919751917477697E-004
print '("x_1=", F20.12, " x_2=", E10.2)', x_1, x_2
print *, x_1, x_2
end program
```
```console
(lf) ➜  lfortran git:(fmtfix) ✗ lfortran examples/temp.f90           
x_1= -25658.418788050920 x_2=  0.90E-3
-2.56584187880509198e+04 8.99197519174776971e-04
(lf) ➜  lfortran …
```
> Implement 'ES' Real Formatting and Fix Double Precision

- integration_tests/CMakeLists.txt
confirmed both the generated code and test codes are the same for each case.
> [tests] enable some expr & data tests

- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/runtime/lfortran_intrinsics.c
Fixes #2621 
Fixed all memory leaks in all format related integration tests, and ensured that the output is correct by comparing with gfortran.
```console
(lf) ➜  lfortran git:(memleak) ✗ valgrind --leak-check=yes ./format_04.out          
==334439== Memcheck, a memory error detector
==334439== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==334439== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==334439== Command: ./format_04.out
==334439== 
ok b
okb
Success!
Hello World!
danc  in themoon
ab  cdef  ghi  jkl  qwerty 12
123     00456
012345  ***
0.12D+03  -0.123457D+03  0.12D+02  *******
-1.23D+02   12.34568D+01 -1.23D+01   1.23D+02
-0.01E+04   0.001235E+05 -1.23E+01   1.23E+02
1  2  3  4  5  6  7  8  9 10 11 12
1  2  3  4 hello
5  6  7  8 hello
9 10 …
```
> Fix all memory leaks in string formatting and print

- .github/workflows/CI.yml
I just noticed that this workaround was also fixed by https://github.com/lfortran/lfortran/pull/2624.
> CI: Remove another workaround in dftatom

- .github/workflows/CI.yml
The branch `lf31` is based out of the latest `lf30_convrlda` at https://github.com/czgdp1807/dftatom.
> Remove another workaround for array

- integration_tests/CMakeLists.txt
- integration_tests/write_03.f90
Declare all variables, set them.
Workaround the bug in https://github.com/lfortran/lfortran/issues/2646.
> Fix the write_03 test

- src/libasr/pass/print_arr.cpp
- tests/reference/run-write4-329d906.json
- tests/reference/run-write4-329d906.stdout
- tests/reference/run-write5-4a89b6b.json
- tests/reference/run-write5-4a89b6b.stdout
Fixes https://github.com/lfortran/lfortran/issues/2651
```fortran
program expr2
implicit none
write(*,"(a)",advance="no") "hi:"
write(*,"(a)",advance="no") "bye"
end program
```
```console
(lf) ➜  lfortran git:(adv2) ✗ lfortran examples/temp.f90
hi:bye%
(lf) ➜  lfortran git:(adv2) ✗ gfortran examples/temp.f90 && ./a.out
hi:bye%                                                       
```
> Fix m_sep and m_end for FileWrite in print_arr.cpp

- .github/workflows/CI.yml
towards https://github.com/lfortran/lfortran/issues/1953
The `test_chat` works for all the `14` items available, but we test only the first `3` because
- they were the ones that were initially tested (before the workaround)
- the CI completes quickly
> CI: fastGPT: Test the chat with no workarounds

- src/libasr/pass/implied_do_loops.cpp
- src/libasr/pass/insert_deallocate.cpp
- tests/reference/llvm-allocate_01-573b1f6.json
- tests/reference/llvm-allocate_01-573b1f6.stdout
- tests/reference/llvm-allocate_02-7f23768.json
- tests/reference/llvm-allocate_02-7f23768.stdout
- tests/reference/llvm-arrays_op_6-ae38631.json
- tests/reference/llvm-arrays_op_6-ae38631.stdout
Closes https://github.com/lfortran/lfortran/issues/2627
Some final deallocates were missing which are now showing up in updated reference tests.
> Fix ``insert_deallocate`` ASR pass

- src/lfortran/fortran_evaluator.cpp
- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/codegen/asr_to_fortran.h
With this PR in, the failure in https://github.com/lfortran/lfortran/pull/2663 can be debugged as follows:
```console
$ lfortran --show-fortran intrinsics_61.f90 
code generation error: Cast IntegerToInteger: Unsupported Kind 1
Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
and the full stacktrace can be seen by:
```console
$ lfortran --show-fortran intrinsics_61.f90 --show-stacktrace
File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2289
return emit_fortran(arg_file, compiler_options);
File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 794
LCompilers::Result<std::string> src = fe.get_fortran(input, lm, diagnostics);
File …
```
> Handle exceptions in ASR->Fortran properly

- .github/workflows/CI.yml
This makes the diff against the latest master in dftatom simpler.
The diff is here: https://github.com/certik/dftatom/compare/master...czgdp1807:dftatom:lf38
> CI dftatom: merge lf38 with master

- integration_tests/CMakeLists.txt
- integration_tests/doloop_11.f90
- src/libasr/codegen/asr_to_wasm.cpp
- src/libasr/pass/pass_utils.cpp
fixes https://github.com/lfortran/lfortran/issues/2699
The test at https://github.com/lfortran/lfortran/issues/2699#issue-1957268190 now works:
```console
$ cat examples/expr2.f90 
program cycle_and_exit5
implicit none
integer :: i, j
integer(8) :: s
s = 0
do i = 1, 10
if( 3*(i/3) == i ) exit
do j = 1, 20
s = s + i + j
end do
print *, i, j
if( 2*(i/2) == i ) cycle
s = 2*s
end do
print *, s
if( s/= 710 ) error stop
end program cycle_and_exit5
$ gfortran examples/expr2.f90 
$ ./a.out 
1          21
2          21
710
$ lfortran_in_main examples/expr2.f90 
1 20
2 20
710
$ lfortran_in_main examples/expr2.f90 --use-loop-variable-after-loop
1 2
2 2
710
$ lfortran examples/expr2.f90                               
1 20
2 20
710
$ lfortran examples/expr2.f90 --use-loop-variable-after-loop 
1 21
2 …
```
> Fix value of iterator after do loop completion

- .github/workflows/CI.yml
Reference: https://github.com/certik/scipy/commits/merge_specfun_minpack_fitpack_amos_mach_02
> CI: Merge scipy build of specfun, minpack, fitpack, amos and mach with no patches!

- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/lfortran/pickle.cpp
- src/lfortran/pickle.h
- src/libasr/asdl_cpp.py
- src/libasr/pickle.cpp
- src/libasr/pickle.h
- src/libasr/utils.h
This PR supports a `--no-loc` flag which enables the user to skip the location information in the generated AST/R Json format.
```console
$ lfortran examples/expr2.f90 --show-asr --json --no-loc
{
"node": "TranslationUnit",
"fields": {
"symtab": {
"node": "SymbolTable1",
"fields": {
"expr2": {
"node": "Program",
"fields": {
"symtab": {
"node": "SymbolTable2",
"fields": {
"x": {
"node": "Variable",
"fields": {
"parent_symtab": 2,
"name": "x",
"dependencies": [],
"intent": "Local",
"symbolic_value": [],
"value": [],
"storage": "Default",
"type": {
"node": "Integer",
"fields": {
"kind": 4
}
},
"type_declaration": [],
"abi": "Source",
"access": "Public",
"presence": "Required",
"value_attr": false
}
}
}
},
"name": "expr2",
"dependencies": [],
"body": [
{
"node": "Assignment",
"fields": { …
```
> Support --no-loc to skip location info in Json

- .github/workflows/CI.yml
Refer: https://github.com/lfortran/lfortran/pull/2673#issuecomment-1780556534
This PR tests https://github.com/certik/scipy/commits/merge_specfun_minpack_fitpack_amos_mach_03, commit: https://github.com/certik/scipy/commit/f7cbdacbd5c5cf807579729d59d3830f2aa9c4a2
TODO:
> CI: change branch to test amos, mach without any patch

- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/lfortran/parser/preprocessor.re
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/lfortran/semantics/ast_to_asr.cpp
- src/lfortran/tests/test_llvm.cpp
- src/libasr/codegen/asr_to_c.cpp
- src/libasr/codegen/asr_to_c_cpp.h
- src/libasr/codegen/asr_to_cpp.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/asr_to_wasm.cpp
- src/libasr/pass/pass_manager.h
- src/libasr/utils.h
fixes https://github.com/lfortran/lfortran/issues/2738
> Move pass options inside compiler options

- .github/workflows/CI.yml
With this we have 6 / 18 packages ( 1/3rd of SciPy ) compiled and being tested at our CI. More specifically, entire `scipy.special.*` that includes `amos`, `cdflib`, `specfun`, `mach`, also, `minpack`, `fitpack` works with LFortran with no modification.
> CI: test `scipy/special/cdflib`

- .github/workflows/CI.yml
Branch: https://github.com/certik/scipy/commits/merge_special_minpack_fitpack_02
@HarshitaKalani can you please verify the commits once?
> CI: Bump SciPy to latest commit

- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/lfortran/fortran_evaluator.h
towards https://github.com/lfortran/lfortran/issues/2744.
Now it can only be used as `lfortran main.f90 --dump-all-passes-fortran` which is the same as how `--dump-all-passes` used to work previously before PR https://github.com/lfortran/lfortran/pull/2733 was merged.
> Remove extra supports for --dump-all-passes-fortran

- .github/workflows/CI.yml
Well `minpack2` was a fallen fruit which we didn't pick. Now we have it ( 7 / 18 )
Branch: https://github.com/certik/scipy/commits/merge_special_minpack_minpack2_fitpack_01
> CI: test `scipy/optimize/minpack2`

- .github/workflows/CI.yml
Ah, I am not sure how much is this needed but if we are compiling it and tests pass why not test it at CI. Subroutines defined in `d1mach.f` and `xerror.f` are highly likely to be used in `odepack`, `quadpack`.
> CI: test `scipy/integrate/mach`

- integration_tests/CMakeLists.txt
- integration_tests/matmul_02.f90
> Add a matmul_02 test

- src/libasr/runtime/lfortran_intrinsics.c
Fixes: https://github.com/lfortran/lfortran/issues/2776
> Bug: Fix the `unit_file_bin` not being initialized

- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.cpp
- tests/external_03.f90
- tests/reference/asr-allow_implicit_interface3-7ef92cc.json
- tests/reference/asr-allow_implicit_interface3-7ef92cc.stdout
- tests/reference/asr-external3-2aafcb3.json
- tests/reference/asr-external3-2aafcb3.stdout
- tests/reference/asr-external4-4e8bc7b.json
- tests/reference/asr-external4-4e8bc7b.stdout
- tests/reference/asr-external_01-6754623.json
- tests/reference/asr-external_01-6754623.stdout
- tests/reference/asr-external_03-fe60427.json
- tests/reference/asr-external_03-fe60427.stdout
- tests/tests.toml
With this we get correct ASR for https://github.com/lfortran/lfortran/issues/1977#issuecomment-1791095925, however the error still persists.  On debugging, I found that `llvm_symtab_fn_arg` consists hash corresponding to  `f` present in symbol table of `a`, and then when we encounter `call a(f)` in body of `b`, `f` is part of symbol table belonging to `b` and thus it throws error. 
One way to fix this is, whenever we add hash of an external function into  `llvm_symtab_fn_arg`, lookup all the symtabs where it is present and add their hash as well. Although, we do not have any information to check if `is_external(f)`.
Another way that comes to my mind is to make all external functions part of module `__lcompilers_external_functions_module`, this way we have a global module accessible to …
> Add provision to `visit_FunctionCall` in `update_call_args`

- integration_tests/CMakeLists.txt
- integration_tests/template_03.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/reference/asr-template_03-6afb845.json
- tests/reference/asr-template_03-6afb845.stdout
- tests/tests.toml
I got the program mentioned in https://github.com/lfortran/lfortran/issues/2771 to work with different types real and integer.
```
subroutine f()
...
instantiate axpy_tmpl(real, integer, real, real, operator(+), operator(*))
...
end subroutine
```
> Handle template binary operations with different types 

- integration_tests/CMakeLists.txt
- integration_tests/external_07.f90
- integration_tests/external_08.f90
- src/libasr/codegen/asr_to_llvm.cpp
- tests/external_04.f90
- tests/reference/llvm-external_03-c3442bb.json
- tests/reference/llvm-external_03-c3442bb.stdout
- tests/reference/llvm-external_04-30bc1c7.json
- tests/reference/llvm-external_04-30bc1c7.stdout
- tests/tests.toml
Fixes #1977. Fixes #2748. Fixes #2427
> Handle external interface in `convert_call_args`

- src/bin/lfortran.cpp
There seems to be some issue with the GLibc: `clock_gettime@GLIBC_2.17`.
So, we need to switch to clang linking for Fortran backend.
> Link binary executables for the Fortran backend using clang

- integration_tests/CMakeLists.txt
- integration_tests/data_11.f90
Fixes: https://github.com/lfortran/lfortran/issues/1991
> Add test for the number of values and variables match in DATA

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_82.f90
- src/libasr/pass/intrinsic_function_registry.h
Fixes: https://github.com/lfortran/lfortran/issues/2242
> Add array support in `tan`, `cosh`, `sinh`, `tanh` 

- integration_tests/CMakeLists.txt
- integration_tests/matmul_01.f90
- integration_tests/matmul_02.f90
- src/libasr/codegen/asr_to_c_cpp.h
- tests/reference/asr-matmul_01-7b0b0c2.json
- tests/reference/asr-matmul_01-7b0b0c2.stdout
The memory fix is taken from https://github.com/lfortran/lfortran/pull/2865.
> SIMD: C: Fix memory issue and enable matmul_01

- integration_tests/CMakeLists.txt
- integration_tests/transfer_01.f90
- integration_tests/transfer_02.f90
- src/libasr/codegen/asr_to_llvm.cpp
Fixes #2875. I am not sure if this is correct approach. For 
```fortran
program main
implicit none
integer :: i = 123456
real :: r
real :: result
result = transfer(i, r)
print *, result
end program main
```
> LFortran
```console
% lfortran a.f90 
1.23456000e+05
```
> GFortran
```console
% gfortran a.f90 && ./a.out
1.72998703E-40
```
I feel output of GFortran is incorrect.
> [LLVM] Initial implementation for BitCast

- integration_tests/CMakeLists.txt
- integration_tests/matmul_01.f90
- src/libasr/codegen/asr_to_c.cpp
- src/libasr/codegen/asr_to_c_cpp.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/pass_utils.cpp
- tests/reference/asr-matmul_01-7b0b0c2.json
- tests/reference/asr-matmul_01-7b0b0c2.stdout
Fixes: https://github.com/lfortran/lfortran/issues/2886
Fixes: https://github.com/lfortran/lfortran/issues/2887
> [ASR Pass] FMA: Create an IntrinsicScalarFunction for SIMDArray

- integration_tests/CMakeLists.txt
- integration_tests/class_12.f90
- integration_tests/class_13.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/asr_utils.cpp
- src/libasr/asr_utils.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/array_op.cpp
- src/libasr/pass/instantiate_template.cpp
- src/libasr/pass/intrinsic_function.cpp
- src/libasr/pass/nested_vars.cpp
- src/libasr/pass/pass_utils.cpp
- src/libasr/pass/promote_allocatable_to_nonallocatable.cpp
- src/libasr/pass/subroutine_from_function.cpp
- src/libasr/pass/transform_optional_argument_functions.cpp
fixes https://github.com/lfortran/lfortran/issues/2898
> Fix subroutine with nopass attribute

- integration_tests/CMakeLists.txt
- integration_tests/legacy_array_sections_03.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
Fixes #2753
TODO:
With this PR, we correctly parse `print *, ddot_sl(a(1,0))` as `print *, ddot_sl(a(1,0:))` with `--legacy-array-sections` but it   throws code generation error while generating llvm. This is because of another issue that needs to be fixed to create a proper test for this PR.
```fortran
DOUBLE PRECISION FUNCTION ddot_sl(dx)
DOUBLE PRECISION dx(*)
END
SUBROUTINE slsqpb (la, n, a)
INTEGER la, n
external ddot_sl
DOUBLE PRECISION a(la,n+1), ddot_sl
print *, ddot_sl(a(1,0)) ! passed an array section
END
```
> Apply legacy array sections on arguments of function call

- .gitignore
Fixes the problem of 
```console
% git status
On branch main
Your branch is up to date with 'origin/main'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
inst/
nothing added to commit but untracked files present (use "git add" to track)
```
> chore: add `inst/` to gitignore

- integration_tests/CMakeLists.txt
- integration_tests/template_lapack_01.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/libasr/pass/instantiate_template.cpp
- tests/reference/asr-template_lapack_01-0d30f43.json
- tests/reference/asr-template_lapack_01-0d30f43.stdout
- tests/tests.toml
Addressing #2267. However, the example described in the issue didn't implement the specific subroutines `sgemm`, etc.
> Lapack example with generics

- CMakeLists.txt
- src/runtime/legacy/CMakeLists.txt
Fix #2974 
CMake picks up `CXXFLAGS` automatically, so I am not sure what the point of 487ff2ec48 was.
> Fix cxxflags

- src/libasr/codegen/asr_to_fortran.cpp
- tests/char1.f90
- tests/reference/fortran-char1-046b501.json
- tests/reference/fortran-char1-046b501.stdout
- tests/tests.toml
> ENH: handling of `char(xx)` as a variable symbolic value

- src/bin/lfortran.cpp
> print link line for verbose

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_91.f90
- integration_tests/intrinsics_94.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
- src/libasr/pass/intrinsic_function_registry.h
Closes #3011, towards #3000
With this PR we can remove comments for `hypot` 
```diff
diff --git a/src/stdlib_specialfunctions_gamma.fypp b/src/stdlib_specialfunctions_gamma.fypp
index 29af406..e8ae0e0 100644
--- a/src/stdlib_specialfunctions_gamma.fypp
+++ b/src/stdlib_specialfunctions_gamma.fypp
@@ -470,7 +470,7 @@ contains
end if
-!        d = hypot(z2 % re, z2 % im)
+        d = hypot(z2 % re, z2 % im)
z1 = z2
m = 0
```
> ENH: Implement intrinsic hypot

- src/libasr/codegen/asr_to_llvm.cpp
Taken from https://github.com/lcompilers/lc/pull/43
> Create dimension descriptor while copying arrays only when needed

- .github/workflows/CI.yml
Fix up for #2934, I think `lfortran.1` should be part of the tarball that gets uploaded.
> CI: add lfortran.1 to tarball

- .github/workflows/CI.yml
Towards #3000
Branch: https://github.com/Pranavchiku/stdlib-fortran-lang/commits/lf-special-function-gamma-2/
Commit: https://github.com/Pranavchiku/stdlib-fortran-lang/commit/6b1c348d02576739df10c755cdcee2520ec18fe6
> ci: update stdlib branch to remove workaround for gamma

- integration_tests/CMakeLists.txt
- integration_tests/expr_18.f90
- src/lfortran/semantics/asr_implicit_cast_rules.h
- tests/reference/asr-allocate_01-f3446f6.json
- tests/reference/asr-allocate_01-f3446f6.stdout
- tests/reference/asr-arrays_01_complex-2513a51.json
- tests/reference/asr-arrays_01_complex-2513a51.stdout
- tests/reference/asr-associate_02-ca5c9ec.json
- tests/reference/asr-associate_02-ca5c9ec.stdout
- tests/reference/asr-complex_div_test-21dab13.json
- tests/reference/asr-complex_div_test-21dab13.stdout
- tests/reference/asr-complex_mul_test-562260f.json
- tests/reference/asr-complex_mul_test-562260f.stdout
- tests/reference/asr-complex_sub_test-f54ef56.json
- tests/reference/asr-complex_sub_test-f54ef56.stdout
- tests/reference/asr-implicit10-23a5156.json
- tests/reference/asr-implicit10-23a5156.stdout
- tests/reference/asr-implicit10-f531a25.json
- tests/reference/asr-implicit10-f531a25.stdout
- tests/reference/asr-implicit11-95f56fd.json
- tests/reference/asr-implicit11-95f56fd.stdout
- tests/reference/asr-implicit12-1826599.json
- tests/reference/asr-implicit12-1826599.stdout
- tests/reference/asr-implicit9-b56b139.json
- tests/reference/asr-implicit9-b56b139.stdout
fixes https://github.com/lfortran/lfortran/issues/3096
```bash
(lf2) % cat integration_tests/expr_18.f90 
program main
complex, parameter :: x = 123
print *, x
if (abs(x - (123, 0)) > 1e-5) error stop
end program
(lf2) % gfortran integration_tests/expr_18.f90 
(lf2) % ./a.out 
(123.000000,0.00000000)
(lf2) % lfortran_in_main integration_tests/expr_18.f90 
File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/bin/lfortran.cpp", line 2340
err = compile_to_object_file(arg_file, tmp_o, false,
File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/bin/lfortran.cpp", line 907
result = fe.get_asr2(input, lm, diagnostics);
File "/Users/ubaid/Desktop/OpenSource/lfortran_in_main/src/lfortran/fortran_evaluator.cpp", line 253
Result<ASR::TranslationUnit_t*> …
```
> Stdlib: Fix initialization for complex parameter

- .github/workflows/CI.yml
LFortran Output:
```bash
+ ./example/ascii/example_ascii_reverse
!dlroW ,olleH
+ ./example/ascii/example_ascii_to_lower
hello!
+ ./example/ascii/example_ascii_to_sentence
Hello!
'Enquoted'
1st
+ ./example/ascii/example_ascii_to_title
Hello There!
'Enquoted'
1st
+ ./example/ascii/example_ascii_to_upper
HELLO!
```
GFortran Output:
```bash
+ ./example/ascii/example_ascii_reverse
!dlroW ,olleH
+ ./example/ascii/example_ascii_to_lower
hello!
+ ./example/ascii/example_ascii_to_sentence
Hello!
'Enquoted'
1st
+ ./example/ascii/example_ascii_to_title
Hello There!
'Enquoted'
1st
+ ./example/ascii/example_ascii_to_upper
HELLO!
```
> Stdlib: LFortran compiles ascii

- integration_tests/CMakeLists.txt
- integration_tests/expr_18.f90
- integration_tests/expr_19.f90
- src/lfortran/semantics/asr_implicit_cast_rules.h
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-complex_07-71c3c47.json
- tests/reference/asr-complex_07-71c3c47.stdout
- tests/reference/asr-complex_dp-ec165b1.json
- tests/reference/asr-complex_dp-ec165b1.stdout
- tests/reference/llvm-complex_dp-7286fd2.json
- tests/reference/llvm-complex_dp-7286fd2.stdout
Also update the error message.
fixes https://github.com/lfortran/lfortran/issues/3098
> Fix complex parameter initialization

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_105.f90
- integration_tests/intrinsics_62.f90
- src/libasr/pass/intrinsic_array_function_registry.h
- tests/reference/asr-intrinsics_27-11ba39d.json
- tests/reference/asr-intrinsics_27-11ba39d.stdout
Fixes: https://github.com/lfortran/lfortran/issues/3081
> Fix `shape` intrinsic for scalar arg

- doc/src/installation.md
I tried to build `lfortran` in WSL2 and for the most part it went well.
There are a few places in the documentation that need to be updated.
- In addition to zlib, you need zstd, otherwise cmake will complain that it can't find the dependencies.
Maybe this could be added to conda's environment configuration as well? Just like:
https://github.com/lfortran/lfortran/blob/60dac4092ece5ed0b49d1d8b727a67ce78864352/ci/environment.yml#L22
- `lfortran` now generates an executable with the same name as the source file
- Do we need to add `-DWITH_RUNTIME_STACKTRACE=yes` to the default cmake flags?
Otherwise `./run_tests.py` will throw an error when executing `runtime_stacktrace_01.f90 * run_dbg`
Or skip the related tests if the WITH_RUNTIME_STACKTRACE flag is not set …
> doc: Update Windows build instructions

- integration_tests/intrinsics_109.f90
- integration_tests/intrinsics_110.f90
- integration_tests/intrinsics_111.f90
- integration_tests/intrinsics_112.f90
- integration_tests/intrinsics_113.f90
- integration_tests/intrinsics_114.f90
- integration_tests/intrinsics_115.f90
- integration_tests/intrinsics_116.f90
- integration_tests/intrinsics_117.f90
- integration_tests/intrinsics_118.f90
- integration_tests/intrinsics_119.f90
This PR improves intrinsic tests added in: https://github.com/lfortran/lfortran/pull/3123
> Improve intrinsic tests

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_123.f90
- integration_tests/intrinsics_125.f90
- integration_tests/intrinsics_126.f90
- integration_tests/intrinsics_74.f90
- src/lfortran/semantics/comptime_eval.h
- src/libasr/runtime/lfortran_intrinsics.c
- src/runtime/impure/lfortran_intrinsic_math.f90
fixes https://github.com/lfortran/lfortran/issues/3128
> Fix `random_number()`

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_127.f90
- src/libasr/pass/intrinsic_function_registry.h
Fixes: https://github.com/lfortran/lfortran/issues/3170
As per the documentation of ifix: https://gcc.gnu.org/onlinedocs/gcc-3.4.6/g77/IFix-Intrinsic.html
> Implemented ifix

- integration_tests/CMakeLists.txt
- integration_tests/elemental_02.f90
- src/libasr/pass/array_op.cpp
Fixes #3180, towards #3046.
With this PR we get `example_math_is_close` working with LFortran.
> FIX: optional argument handling for elemental funtion

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_128.f90
- src/libasr/pass/intrinsic_function_registry.h
> Implemented Idint

- .github/workflows/CI.yml
- src/bin/lfortran.cpp
> lfortran: compile capital F files as well

- src/lfortran/semantics/comptime_eval.h
> Refactor: remove old compile time implementations

- src/bin/lfortran.cpp
- src/lfortran/utils.cpp
- src/lfortran/utils.h
fixes https://github.com/lfortran/lfortran/issues/3242.
> Support calling `get_executable_path()` only once

- .github/workflows/CI.yml
- integration_tests/intrinsics_03.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/comptime_eval.h
- src/libasr/pass/unique_symbols.cpp
- src/runtime/impure/lfortran_intrinsic_math.f90
- src/runtime/pure/lfortran_intrinsic_math2.f90
- tests/reference/asr-intrinsics_03-ef06d46.json
- tests/reference/asr-intrinsics_03-ef06d46.stdout
- tests/reference/llvm-intrinsics_03-0771f1b.json
- tests/reference/llvm-intrinsics_03-0771f1b.stdout
- tests/reference/pass_flip_sign-expr_13-e24d940.json
- tests/reference/pass_flip_sign-expr_13-e24d940.stdout
- tests/reference/pass_flip_sign-flip_sign-16b288c.json
- tests/reference/pass_flip_sign-flip_sign-16b288c.stdout
Towards: https://github.com/lfortran/lfortran/issues/3034
> Refactor: Remove old `abs` runtime implementations

- integration_tests/CMakeLists.txt
- integration_tests/arrays_38.f90
- src/libasr/asr_verify.cpp
Fixes #3264, towards #3046.
With this PR we get `example_linspace_int16` working.
> ASR Verify: visit function signature

- integration_tests/CMakeLists.txt
- integration_tests/complex_17.f90
- src/libasr/pass/array_op.cpp
- src/libasr/pass/pass_utils.cpp
Fixes #3275, towards #3046.
With this we get `example_linspace_complex` working. Also, with https://github.com/pranavchiku/stdlib-fortran-lang/tree/lf-math7 and this PR we get `example_logspace_*` working.
> ENH: Handle complex constructor over array

- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/pass/intrinsic_function_registry.h
- tests/errors/substring_endidx.f90
- tests/errors/substring_startidx.f90
- tests/errors/substring_stride.f90
- tests/reference/asr-allocate_04-68facec.json
- tests/reference/asr-allocate_04-68facec.stdout
- tests/reference/asr-arrays_23-a731033.json
- tests/reference/asr-arrays_23-a731033.stdout
- tests/reference/asr-modules_48-6cf0505.json
- tests/reference/asr-modules_48-6cf0505.stdout
- tests/reference/asr-string_04-2ebc0e6.json
- tests/reference/asr-string_04-2ebc0e6.stdout
- tests/reference/asr-string_10-eb8bca7.json
- tests/reference/asr-string_10-eb8bca7.stdout
- tests/reference/asr-string_12-e72e066.json
- tests/reference/asr-string_12-e72e066.stdout
- tests/reference/asr-substring_endidx-0f7e2c9.json
- tests/reference/asr-substring_endidx-0f7e2c9.stderr
- tests/reference/asr-substring_startidx-5fb6d57.json
- tests/reference/asr-substring_startidx-5fb6d57.stderr
- tests/reference/asr-substring_stride-27c1b9d.json
- tests/reference/asr-substring_stride-27c1b9d.stderr
- tests/tests.toml
> assign "value" for IntegerBinOp node in StringSection when adjusting for 0-based indexing

- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/comptime_eval.h
- src/libasr/codegen/asr_to_wasm.cpp
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/unused_functions.cpp
- src/runtime/impure/lfortran_intrinsic_math.f90
- src/runtime/pure/lfortran_intrinsic_math2.f90
- tests/reference/asr-implicit11-95f56fd.json
- tests/reference/asr-implicit11-95f56fd.stdout
- tests/reference/asr-implicit_typing4-c338b90.json
- tests/reference/asr-implicit_typing4-c338b90.stdout
- tests/reference/asr-sole_intrinsic-3e826bd.json
- tests/reference/asr-sole_intrinsic-3e826bd.stdout
- tests/reference/pass_flip_sign-expr_13-e24d940.json
- tests/reference/pass_flip_sign-expr_13-e24d940.stdout
- tests/reference/pass_flip_sign-flip_sign-16b288c.json
- tests/reference/pass_flip_sign-flip_sign-16b288c.stdout
Towards: https://github.com/lfortran/lfortran/issues/3034
> Refactor: Remove old `aimag` runtime implementations

- src/bin/lfortran.cpp
- src/libasr/utils.h
Fix #3281
This PR hand through all `-l`, `-L`, `-W` and the `--shared` flag, the ordering changes a bit, but good enough for now I guess.
> lfortran: improve handling of linker flags

- src/lfortran/parser/tokenizer.re
- tests/reference/asr-preprocess_01-20f7efb.json
- tests/reference/asr-preprocess_01-20f7efb.stderr
- tests/reference/asr-preprocess_01-20f7efb.stdout
- tests/tests.toml
- tests/warnings/preprocess_01.f90
fixes https://github.com/lfortran/lfortran/issues/3259
> Emit warning for CPP defines if `--cpp` is not present

- src/bin/lfortran.cpp
> lfortran: add dummy optimization level option

- integration_tests/CMakeLists.txt
- integration_tests/modules_56.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
Fixes #3054, towards #3046.
Continuation of #3056.
After this PR, most of examples align with GFortran, I will setup checks like `if (xx) error stop` and then set it up at CI.
> Fix: using lfortran intrinsic module inside module

- src/bin/lfortran.cpp
Related to #3208 
There was a bug in `-L` parsing, `-Ldir file` was turned into `-Ldir -Lfile` instead of keeping `-Ldir file`.
> lfortran: another linker fix

- .github/workflows/CI.yml
This PR updates branch and commit of `stdlb-special-function-gamma` that has `error stop` conditions on examples to ensure alignment with GFortran. All examples align correctly.
Towards #3000.
Branch: https://github.com/pranavchiku/stdlib-fortran-lang/tree/lf-special-function-gamma-3
Commit: https://github.com/Pranavchiku/stdlib-fortran-lang/commit/f15a3a107f399b2e00b46ad5ee805d94aca2b404
> CI: update test stdlib special function 

- src/lfortran/semantics/comptime_eval.h
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
- src/runtime/impure/lfortran_intrinsic_math.f90
- tests/reference/asr-intrinsics_08-9988b1f.json
- tests/reference/asr-intrinsics_08-9988b1f.stdout
- tests/reference/asr-intrinsics_09-2af35ec.json
- tests/reference/asr-intrinsics_09-2af35ec.stdout
- tests/reference/asr-intrinsics_34-c5cfc20.json
- tests/reference/asr-intrinsics_34-c5cfc20.stdout
> Redesign the `epsilon` and `tiny` intrinsics implementations

- .github/workflows/CI.yml
Fixes: https://github.com/lfortran/lfortran/issues/3357
> [stdlib] Use source directory as module path directory

- run_tests.py
- src/bin/lfortran.cpp
- tests/preprocessor17.F90
- tests/reference/asr-preprocessor17-f2d76bb.json
- tests/reference/asr-preprocessor17-f2d76bb.stdout
- tests/tests.toml
Fix #3349
Closes #3228 
Related #3208
> lfortran: add option to infer cpp for F files

- integration_tests/CMakeLists.txt
- integration_tests/functions_20.f90
- src/libasr/gen_pass.py
- src/libasr/pass/function_call_in_declaration.cpp
Fixes https://github.com/lfortran/lfortran/pull/3407#issuecomment-1945387833, towards #3323.
With this PR we can remove https://github.com/Pranavchiku/stdlib-fortran-lang/commit/c9b4090da37dd3aae824d433aa5fc6e689207f0b
> ENH: support `IntegerBinOp` in pass `function_call_in_declaration`

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/compare_01.f90
- tests/reference/asr-compare_01-c98905f.json
- tests/reference/asr-compare_01-c98905f.stderr
- tests/tests.toml
Fixes: https://github.com/lfortran/lfortran/issues/3444
> Throw error for comparison of different types of operands

- src/libasr/codegen/asr_to_c_cpp.h
- src/libasr/codegen/asr_to_fortran.cpp
change `s` to `fortran_code`, as that's self explanatory
> rename public variable for Fortran codegen string

- .github/workflows/CI.yml
- integration_tests/CMakeLists.txt
- integration_tests/string_36.f90
- src/libasr/runtime/lfortran_intrinsics.c
This PR fixes the following issue:
```console
% cat integration_tests/string_36.f90 
program string_36
implicit none
character(len=5) :: hello
hello = "hello"
hello(4:3) = ""
print *, hello
if (hello /= "hello") error stop
end program
% gfortran integration_tests/string_36.f90 
% ./a.out 
hello
% lfortran_in_main integration_tests/string_36.f90 
ERROR STOP
```
> Stdlib: Fix assign to string slice

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_170.f90
- src/libasr/asr_builder.h
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
Fixes: #3496
```
/lfortran (exponent)$ lfortran b.f90
123
234
345
456
567
678
789
8910
91011
Binary file "/home/lfortran/src/bin/lfortran", in _start()
File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
File "/home/lfortran/src/bin/lfortran.cpp", line 2394, in ??
return main_app(argc, argv);
File "/home/lfortran/src/bin/lfortran.cpp", line 2355, in main_app(int, char**)
err = compile_to_object_file(arg_file, tmp_o, false,
File "/home/lfortran/src/bin/lfortran.cpp", line 949, in ??
res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
File "/home/lfortran/src/lfortran/fortran_evaluator.cpp", line 360, in …
```
> Implemented Exponent

- integration_tests/CMakeLists.txt
- integration_tests/functions_23.f90
- src/libasr/pass/function_call_in_declaration.cpp
> ENH: handle duplicate argindices and refactor `function_call_in_declaration` pass

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_178.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
> Implemented rrspacing

- integration_tests/intrinsics_178.f90
> Used lowercase for function call in rrspacing

- integration_tests/CMakeLists.txt
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/ASR.asdl
- src/libasr/CMakeLists.txt
- src/libasr/asr_builder.h
- src/libasr/codegen/asr_to_c_cpp.h
- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/pass/intrinsic_subroutine.cpp
- src/libasr/pass/intrinsic_subroutine_registry.h
- src/libasr/pass/intrinsic_subroutines.h
- src/libasr/pass/pass_manager.h
- src/libasr/pass/pass_utils.cpp
- src/libasr/pass/pass_utils.h
- src/libasr/pass/replace_intrinsic_subroutine.h
- src/libasr/runtime/lfortran_intrinsics.c
- src/libasr/runtime/lfortran_intrinsics.h
- tests/reference/asr-intrinsics_29-d4080f2.json
- tests/reference/asr-intrinsics_29-d4080f2.stdout
- tests/reference/asr-matmul_01-7b0b0c2.json
- tests/reference/asr-matmul_01-7b0b0c2.stdout
Closes #2591 
ASR Definition
> | IntrinsicImpureSubroutine(int intrinsic_id, expr* args, int overload_id)
> feat: Introduce and implement `IntrinsicImpureSubroutine`

- .github/workflows/CI.yml
- integration_tests/array_02_pack.f90
- integration_tests/intrinsics_65.f90
- src/libasr/asr_utils.h
- src/libasr/asr_verify.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/pass/array_op.cpp
- src/libasr/pass/function_call_in_declaration.cpp
- src/libasr/pass/intrinsic_array_function_registry.h
- src/libasr/pass/intrinsic_functions.h
- src/libasr/pass/pass_array_by_data.cpp
- src/libasr/pass/pass_utils.cpp
- src/libasr/pass/pass_utils.h
- tests/reference/asr-array_02_pack-233bae0.json
- tests/reference/asr-array_02_pack-233bae0.stdout
Work in Progress. Will continue on Monday and Tuesday next week.
> Compile and run ``test_corr::test_sp`` in ``stdlib/test/stats``

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_190.f90
- integration_tests/intrinsics_191.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/intrinsic_func_registry_util_gen.py
> fix: Kind for CMPLX and ArrayConstructor doesn't work

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_108.f90
- integration_tests/intrinsics_132.f90
- integration_tests/intrinsics_133.f90
- integration_tests/intrinsics_185.f90
- integration_tests/intrinsics_194.f90
- integration_tests/intrinsics_195.f90
- integration_tests/intrinsics_46.f90
- integration_tests/intrinsics_58.f90
- integration_tests/intrinsics_70.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
- src/libasr/pass/intrinsic_functions.h
- tests/reference/asr-intrinsics_46-0ef4d7a.json
- tests/reference/asr-intrinsics_46-0ef4d7a.stdout
> enh: support `compiletime_broadcast_elemental_intrinsic` for multiple arguments

- src/libasr/pass/intrinsic_functions.h
> enh: removed cast macros from intrinsic_function file

- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/runtime/lfortran_intrinsics.c
and get back stdin read working.
```console
% lfortran examples/chat_01.f90 
Please enter your name:
Joe
---------WELCOME TO CHAT_01---------
Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat
Enter your choice:
1
Hi Joe
Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat
Enter your choice:
2
Hello Joe
Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat
Enter your choice:
3
Good Morning Joe
Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat
Enter your choice:
4
Happy Birthday Joe!
Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the …
```
> Remove unneeded visit expr

- src/libasr/stacktrace.cpp
@certik I only got the error when enabled `MACH_O`, not otherwise. Therefore hiding it inside that macro.
> stacktrace.cpp: add limits.h for PATH_MAX

- src/libasr/pass/nested_vars.cpp
- src/libasr/pass/promote_allocatable_to_nonallocatable.cpp
- src/libasr/pass/transform_optional_argument_functions.cpp
Minor refactoring, which I probably should've already done in https://github.com/lfortran/lfortran/pull/3711
> refactor: use existing function to determine nopass value in function calls

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_200.f90
- src/libasr/pass/intrinsic_array_function_registry.h
- src/libasr/pass/intrinsic_function.cpp
- tests/reference/asr-array_01_pack-6c829d9.json
- tests/reference/asr-array_01_pack-6c829d9.stdout
Fixes #3752. Towards LLVM compilation of `stdlib_stats_median`
> chore: handle allocatable types for intrinsic pack

- .github/workflows/CI.yml
With efforts of @HarshitaKalani, we get `stdlib_stats_mean` compiled to LLVM. As she has no push access to `lf19` branch, I cherry-picked commits and opening PR on her behalf, all credits for the work goes to her.
> CI: test LLVM compilation of `stdlib_stats_mean`

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_201.f90
- src/libasr/pass/intrinsic_array_function_registry.h
Fixes #3765. With this, #3762 and #3759 we get `stdlib_stats_median` compiled to LLVM.
> fix: intrinsic sum, any calls existing function with incorrect signature

- .github/workflows/CI.yml
With this we get all of `stdlib_stats` compiled to LLVM.
> ci: test LLVM compilation of `stdlib_stats_moment_scalar`

- integration_tests/CMakeLists.txt
- integration_tests/dealloc_01.f90
- integration_tests/dealloc_02.f90
- src/libasr/runtime/lfortran_intrinsics.c
The workaround leaks memory, so I think we should not commit this, and rather implement a proper fix.
> Add tests for deallocation bug, and a workaround

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_206.f90
- src/libasr/codegen/asr_to_fortran.cpp
> enh: add support for `poppar` intrinsic in `fortran` backend

- integration_tests/intrinsics_139.f90
- src/libasr/pass/intrinsic_functions.h
Fix: https://github.com/lfortran/lfortran/issues/3837
> fix: compile time evaluation for modulo

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/specific_type_intrinsic.f90
- tests/reference/asr-specific_type_intrinsic-60c666c.json
- tests/reference/asr-specific_type_intrinsic-60c666c.stderr
- tests/tests.toml
Fixes: https://github.com/lfortran/lfortran/issues/3849
> Refactor: Throw error if specific type intrinsics are called with wrong type arguments

- src/bin/lfortran.cpp
Currently we support:
* `--std=f23`: enable all Fortran 2023 options that we currently support, disable all style warnings; the goal is strict standard conformance
* `--std=legacy`: all f23 options and also legacy F77 style features
* `--std=lf` (the default, the same as no option): the default LFortran behavior which deviates from the strict standard conformance
Fixes #1677.
> Implement --std=f23/legacy/lf option

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_210.f90
- integration_tests/lcompilers_test_module.f90
This PR aims to add in house `lcompilers_test_module` that provides api `lcompilers_test( actual, expected, tol )`.
With this module we can simple remove those `if( abs( actual - expected ) - 1e-10 ) error stop` statements.
1. integration tests
```cmake
RUN(NAME intrinsics_210 LABELS gfortran llvm llvm_wasm EXTRAFILES lcompilers_test_module.f90) # bessel_jn
```
2. tests
```toml
[[test]]
filename = "../integration_tests/intrinsics_210.f90"
asr = true
extrafiles = "../integration_tests/lcompilers_test_module.f90"
```
---
I am open to discussion if we need this or not.
> feat: add `lcompilers_test_module`

- src/libasr/pass/intrinsic_array_function_registry.h
- tests/reference/asr-intrinsics_35-10733ec.json
- tests/reference/asr-intrinsics_35-10733ec.stdout
- tests/reference/asr-intrinsics_47-bdbe527.json
- tests/reference/asr-intrinsics_47-bdbe527.stdout
- tests/reference/llvm-modules_36-53c9a79.json
- tests/reference/llvm-modules_36-53c9a79.stdout
Fixes: https://github.com/lfortran/lfortran/issues/3966
> Enh: Modularize the code for intrinsic `any` and `all`

- integration_tests/derived_types_36.f90
- integration_tests/file_15.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/asr_utils.h
- tests/errors/iostat_constant_integer.f90
- tests/errors/iostat_non_scalar_value.f90
- tests/reference/asr-iostat_constant_integer-4f6f5d4.json
- tests/reference/asr-iostat_constant_integer-4f6f5d4.stderr
- tests/reference/asr-iostat_non_scalar_value-7d45a6f.json
- tests/reference/asr-iostat_non_scalar_value-7d45a6f.stderr
- tests/tests.toml
"variable" is as defined in the 2023 FORTRAN documentation as (R907)
Fixes #3947
> fix: allow "variable" as "iostat" and "iomsg" value

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_219.f90
- src/lfortran/semantics/ast_common_visitor.h
Towards: https://github.com/lfortran/lfortran/issues/3860#issuecomment-2051719754
> Fix: handle initialisation of Intrinsic elemental functions to compile time constant

- integration_tests/intrinsics_104.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes: https://github.com/lfortran/lfortran/issues/3860
> Fix: fix `len` function for intrinsic elemental function as input argument

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_218.f90
- src/lfortran/semantics/comptime_eval.h
- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
- src/runtime/pure/lfortran_intrinsic_string.f90
- tests/reference/asr-derived_types_04-da02dd9.json
- tests/reference/asr-derived_types_04-da02dd9.stdout
- tests/reference/asr-derived_types_06-847ca73.json
- tests/reference/asr-derived_types_06-847ca73.stdout
- tests/reference/asr-fn5-3d75eb7.json
- tests/reference/asr-fn5-3d75eb7.stdout
- tests/reference/asr-fn6-a24010a.json
- tests/reference/asr-fn6-a24010a.stdout
- tests/reference/asr-intrinsics_33-816caef.json
- tests/reference/asr-intrinsics_33-816caef.stdout
> feat: implement intrinsic `new_line` and remove old runtime code

- integration_tests/CMakeLists.txt
- integration_tests/polymorphic_argument.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Simple fix to ensure that when resolving symbol we use "to_lower" in SelectType.
I'm naming the file as `polymorphic_arg`, as I intend to used the test file to include test cases for issues like https://github.com/lfortran/lfortran/issues/3677 (which I've been working on)
I wonder if we there is a good reason to keep everything in the user-provided case (and not convert it to lower case, maybe while parsing itself), is the reason that it will make the parser slow?
> fix: use "to_lower" when resolving symbol in SelectType

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_223.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
> Implement intrinsic `nearest`

- integration_tests/CMakeLists.txt
- integration_tests/bindc_03.f90
- integration_tests/bindc_03c.c
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
- src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
- tests/reference/asr-array12-cb81afc.json
- tests/reference/asr-array12-cb81afc.stdout
- tests/reference/asr-c_ptr_02-fce1b0e.json
- tests/reference/asr-c_ptr_02-fce1b0e.stdout
- tests/reference/asr-modules_15b-09f8335.json
- tests/reference/asr-modules_15b-09f8335.stdout
- tests/reference/asr-string1-f6332d9.json
- tests/reference/asr-string1-f6332d9.stdout
- tests/reference/asr-string2-3425046.json
- tests/reference/asr-string2-3425046.stdout
Fixes #3989. Fixes #3992. Fixes #3991.
With this PR we get the toy example compiled with LFortran
```console
% lfortran -c libgompinterop.f90 && lfortran d.f90 -L/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/ -lomp -Wl,-rpath,/Users/pranavchiku/repos/llvm-project/openmp/build/runtime/src/
Max threads:  8
Hello from thread  3
Hello from thread  1
Hello from thread  2
Hello from thread  0
Hello from thread  4
Hello from thread  6
Hello from thread  7
Hello from thread  5
```
> enh: add support for `c_funptr` and `c_funloc`

- src/libasr/runtime/lfortran_intrinsics.h
fixes https://github.com/lfortran/lfortran/issues/4047
> C: Fix name to `_lfortran_d_cpu_time()` in header file

- src/lfortran/tests/test_llvm.cpp
- src/libasr/codegen/asr_to_llvm.cpp
Fixes the following problem:
```bash
❯ lf
Interactive Fortran. Experimental prototype, not ready for end users.
LFortran version: 0.0.0
* Use Ctrl-D to exit
* Use Enter to submit
* Use Alt-Enter or Ctrl-N to make a new line
- Editing (Keys: Left, Right, Home, End, Backspace, Delete)
- History (Keys: Up, Down)
>>> integer :: i(10)                                                                                                1,17  ]
>>> print *, i                                                                                                      1,11  ]
Binary file "/home/vipul/Workspace/others/lfortran/src/bin/lfortran", in _start()
Binary file "/lib64/libc.so.6", in __libc_start_main_alias_2()
Binary file …
```
> Fix array symbol duplication in interactive mode

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_230.f90
- src/libasr/codegen/asr_to_fortran.cpp
I've also shifted the intrinsic Inquiry functions from elemental functions.
Towards: https://github.com/lfortran/lfortran/pull/4054#discussion_r1611988947, #4017
> Deregister features from fortran backend which are not in use yet (for which no tests exist)

- integration_tests/CMakeLists.txt
- integration_tests/integer_bin_op_dim_external_module.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
fixes #4013 
```fortran
subroutine a(cs)
use xx
real, dimension(nx - 1), intent(in) :: cs
end subroutine
```
is transformed to:
```fortran
pure integer function __lcompilers_get_nx()
use xx
get_nx = nx
end function
subroutine a(cs)
use xx
interface
pure integer function __lcompilers_get_nx()
end function
end interface
real, dimension(__lcompilers_get_nx() - 1), intent(in) :: cs
end subroutine
```
```fortran
module xx
integer :: nx = 4
end module xx
subroutine a(cs)
use xx
integer, dimension(nx - 1), intent(in) :: cs
print *, cs
end subroutine
program main
integer, dimension(4) :: cs
cs = [1, 2, 3, 4]
call a(cs)
end program
```
```console
1 2 3 
```
> Handle `IntegerBinOp_t` when setting array dimension through a module variable

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_236.f90
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_functions.h
- tests/reference/asr-bits_02-e48c6d3.json
- tests/reference/asr-bits_02-e48c6d3.stdout
Fixes: https://github.com/lfortran/lfortran/issues/3999
Towards: #4017
> fix return_type of bit_size intrinsic

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_238.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes: https://github.com/lfortran/lfortran/issues/4070
> fix: population of optional args in intrinsics while compile time evalution of implied do loops

- integration_tests/CMakeLists.txt
- integration_tests/modules_57.f90
- src/libasr/codegen/asr_to_llvm.cpp
fixes #4115. fixes #4120.
The implementation is complete in itself, but due to #4120 it currently prints a zero value even when an initial value is available.
```fortran
module test_complex_module
complex :: c = (3.0, 4.0)
end module test_complex_module
program test_complex_program
use test_complex_module
print *, c
end program test_complex_program
```
```console
(0.000000,0.000000)
```
> feat: add support for global `COMPLEX` variables

- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/pass/intrinsic_function_registry.h
Towards: #4017 
With this, we do not explicitly need to register intrinsic functions in asr to fortran backend. It is handled automatically.
> refactor: generalise fortran backend for all intrinsic functions

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_242.f90
- src/libasr/pass/intrinsic_functions.h
- tests/errors/nint_overflow.f90
- tests/reference/asr-nint_overflow-bf5738b.json
- tests/reference/asr-nint_overflow-bf5738b.stderr
- tests/tests.toml
Fixes : https://github.com/lfortran/lfortran/issues/4079
> Throw an error if result of ```NINT``` overflows its kind 

- src/libasr/compiler_tester/tester.py
- tests/tests.toml
There were duplicate tests which when run in parallel overwrote the JSON or output and then failed. This PR adds checks into the runner for duplicate tests, so this will not happen again. It then removes all duplicates. I checked the affected issues below and indeed I can see these duplicate tests reported there.
Fixes #3619, #3707, #3736, #3985.
> Fix a test runner

- integration_tests/CMakeLists.txt
- integration_tests/global_array_01.f90
- src/libasr/codegen/asr_to_llvm.cpp
fixes #3897 
The chief cause of the issue was `init_value` being a `nullptr` due to the use of `llvm::dyn_cast` to convert `tmp` of type `llvm::Value*` to `llvm::Constant*`. `tmp` is not a constant value here and so the cast returns a `nullptr` according to the definition of `llvm::dyn_cast<T>(U)`. `init_value` being a `nullptr` caused the initialization of the variable using a `zeroinitializer`, hence leading to the issue.
```llvm
@arr = global [4 x i32] zeroinitializer
```
To fix the issue we initialize the global `array` variable manually using the `m_value` of the variable.
```fortran
module test
implicit none
integer(4), dimension(2) :: arr = [105, 109]
end module test
program a
use test, only: arr
implicit none
integer :: i
i = 1
print *, arr(i)
end program a
```
```console
(base) …
```
> fix: add support for initializing global `array` variables

- src/lfortran/tests/test_llvm.cpp
- src/libasr/asr_scopes.cpp
- src/libasr/asr_verify.cpp
- src/libasr/codegen/KaleidoscopeJIT.h
- src/libasr/codegen/evaluator.cpp
Reference lcompilers/lpython#2706
This PR is required by #4006
> Fix ASR verify pass error while using Interactive

- integration_tests/intrinsics_74.f90
Now it is robust and should work for any random number.
Fixes #4167.
> Fix the intrinsics_74.f90 test

- .github/workflows/CI.yml
- src/libasr/codegen/KaleidoscopeJIT.h
- src/libasr/codegen/evaluator.cpp
There are two issues that we need to fix with subsequent commits:
* New pass manager
* Symbol lookup
Maybe a few more things. Currently `--show-llvm` or compiling via the LLVM 17 backend does not work.
> Fixes to build with LLVM 17

- integration_tests/CMakeLists.txt
- integration_tests/openmp_01.f90
- src/bin/lfortran.cpp
- src/libasr/CMakeLists.txt
- src/libasr/gen_pass.py
- src/libasr/pass/openmp.cpp
- src/libasr/pass/pass_manager.h
- src/libasr/pass/replace_openmp.h
- src/libasr/utils.h
Towards #4137, #3777.
With current status of pass we transform
```fortran
subroutine omp_func(n)
implicit none
integer, intent(in) :: n
integer :: i
!$omp parallel private(i) shared(n)
!$omp do
do i = 1, n
print *, "xyz"
end do
!$omp end do
!$omp end parallel
print *, "n = ", n
end subroutine
program openmp
integer, parameter :: n = 100
call omp_func(n)
print *, "Done for n = ", n
end program
```
TO
```fortran
module thread_data_module
use, intrinsic :: iso_c_binding
type, bind(C) :: thread_data
integer(c_int) :: n
end type thread_data
end module thread_data_module
subroutine omp_func(n)
use iso_c_binding
use thread_data_module
implicit none
integer(c_int), intent(in) :: n
integer :: i
type(thread_data), target :: data
type(c_ptr) :: tdata
data%n = n
tdata = c_loc(data)
print *, "n = ", n …
```
> feat: first step of `openmp` pass

- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/lfortran/fortran_evaluator.h
- src/lfortran/tests/test_llvm.cpp
- src/libasr/codegen/evaluator.cpp
- src/libasr/pass/global_stmts.cpp
> Support logical values when using interactive

- .github/workflows/CI.yml
Towards: https://github.com/lfortran/lfortran/pull/3635
> ci: update hash to workaround achar(0)

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_230.f90
- integration_tests/intrinsics_237.f90
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_functions.h
- tests/reference/asr-intrinsics_46-0ef4d7a.json
- tests/reference/asr-intrinsics_46-0ef4d7a.stdout
Towards: #4017 
Fixes: https://github.com/lfortran/lfortran/issues/4059
> Support array type return_type for elemental intrinsics

- .github/workflows/CI.yml
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_utils.cpp
- src/libasr/codegen/llvm_utils.h
Now the simplest example works with LLVM 17:
```
$ lfortran examples/expr2.f90
25
$ lfortran examples/expr2.f90 --show-llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"
@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [5 x i8] c"%d%s\00", align 1
define i32 @main(i32 %0, ptr %1) {
.entry:
call void @_lpython_call_initial_functions(i32 %0, ptr %1)
%x = alloca i32, align 4
store i32 25, ptr %x, align 4
%2 = load i32, ptr %x, align 4
call void (ptr, ...) @_lfortran_printf(ptr @2, i32 %2, ptr @1)
ret i32 0
}
declare void @_lpython_call_initial_functions(i32, ptr)
declare void @_lfortran_printf(ptr, ...)
```
One can see that now the pointers are not typed, just represented as …
> Start implementing opaque pointers

- src/libasr/codegen/asr_to_llvm.cpp
Now we need to change the other 162 occurences. Sometimes it is as simple as
this PR. Some other times it requires to pass throug the type via the function
hierarchy in the ASR->LLVM backend.
> ASR->LLVM: change CreateLoad to CreateLoad2

- integration_tests/CMakeLists.txt
- integration_tests/use_01.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
fixes #4165 
```fortran
MODULE one
IMPLICIT NONE
INTEGER :: nx = 1
END MODULE one
MODULE two
USE one, ONLY: nx
IMPLICIT NONE
END MODULE two
PROGRAM test
USE two
USE one, ONLY: nx
PRINT *, nx
END PROGRAM test
```
```console
1
```
> fix: erase symbol from old symbol table when importing from a new module

- integration_tests/CMakeLists.txt
- integration_tests/implied_do_loops5.f90
- src/lfortran/semantics/ast_common_visitor.h
fixes #4202 
```fortran
MODULE solvar_module
REAL, DIMENSION(10) :: fixup_counter
END MODULE
PROGRAM test
USE solvar_module
IMPLICIT NONE
INTEGER :: n
PRINT *, (fixup_counter(n),n=1,4)
END PROGRAM test
```
```console
0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 
```
> fix: check if a `Var_t` expression is a `Variable_t` before down casting

- integration_tests/CMakeLists.txt
- integration_tests/generic_name_02.f90
- src/libasr/codegen/asr_to_llvm.cpp
> Fix: add type check for struct before downcasting

- integration_tests/intrinsics_185.f90
- integration_tests/intrinsics_189.f90
- src/libasr/pass/intrinsic_functions.h
Fixes: https://github.com/lfortran/lfortran/issues/4226
Towards: #4017
> Update test for `scan` intrinsic and handle kind = 8 for `verify` and `scan` intrinsic

- integration_tests/CMakeLists.txt
- integration_tests/bindc_04.f90
- integration_tests/bindc_04c.c
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-array12-cb81afc.json
- tests/reference/asr-array12-cb81afc.stdout
- tests/reference/asr-string1-f6332d9.json
- tests/reference/asr-string1-f6332d9.stdout
- tests/reference/asr-string2-3425046.json
- tests/reference/asr-string2-3425046.stdout
Towards #4031, #3777.
The example compiles and works but somehow the output diverges looks like when we do `c_f_pointer(...)` it does not return correct fortran pointer:
```console
% gfortran ./integration_tests/bindc_04.f90 ./integration_tests/bindc_04c.c&& ./a.out
0.00000000       1.00000000       2.00000000       3.00000000       4.00000000    
% gcc -c ./integration_tests/bindc_04c.c -o a_c.o && lfortran -c ./integration_tests/bindc_04.f90 && lfortran bindc_04.o a_c.o
2.52007390e+26 1.40129846e-45 5.62639831e-23 7.00649232e-45 3.37928510e-36 
```
> fix: incorrect variable abi type

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_249.f90
- integration_tests/intrinsics_250.f90
- src/libasr/pass/pass_utils.h
Fixes: https://github.com/lfortran/lfortran/issues/4239
Fixes: https://github.com/lfortran/lfortran/issues/4062
Towards: #4017
> Fix: add type check for `ArrayPhysicalCast` before downcasting 

- integration_tests/CMakeLists.txt
- integration_tests/bindc_04.f90
- integration_tests/bindc_04c.c
- integration_tests/openmp_bindc_03.f90
- src/libasr/codegen/asr_to_llvm.cpp
Fixes #4232. Fixes #4031. Towards #3777.
> chore: hack to load `cptr` in `visit_CPtrToPointer` if it is `StructInstanceMember`

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_251.f90
- integration_tests/intrinsics_252.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes: https://github.com/lfortran/lfortran/issues/4264
Towards: #4017
> fix: array handling for `derf` and add test for `erf` and `derf`

- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_utils.cpp
- src/libasr/codegen/llvm_utils.h
Rename function `getStruct` back to `getStructType`. This mistake was caught while working on #4269.
> refactor (revert): rename function `getStruct` back to `getStructType`

- src/libasr/runtime/lfortran_intrinsics.c
I just made a fresh build and on my Mac machine and got these warnings.
```
/Users/anurag/Library/projects/open_source/lfortran/src/libasr/runtime/lfortran_intrinsics.c:2452:29: warning: format specifies type 'long *' but the argument has type 'int64_t *' (aka 'long long *') [-Wformat]
(void)!scanf(INT64, p);
~~~~~  ^
/Users/anurag/Library/projects/open_source/lfortran/src/libasr/runtime/lfortran_intrinsics.c:2466:37: warning: format specifies type 'long *' but the argument has type 'int64_t *' (aka 'long long *') [-Wformat]
(void)!fscanf(filep, INT64, p);
~~~~~  ^
```
> Warning free build on Mac M1

- .github/workflows/CI.yml
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/codegen/llvm_array_utils.h
- src/libasr/codegen/llvm_utils.cpp
- src/libasr/codegen/llvm_utils.h
Extend the work done in https://github.com/lfortran/lfortran/pull/4206 to have the output LLVM IR as opaque pointers instead of typed pointers, see:
* https://releases.llvm.org/17.0.1/docs/ReleaseNotes.html#changes-to-the-llvm-ir
* https://releases.llvm.org/17.0.1/docs/OpaquePointers.html
> use opaque pointers instead of typed pointers

- integration_tests/CMakeLists.txt
- integration_tests/where_07.f90
- src/libasr/pass/where.cpp
fixes #4238 
```fortran
PROGRAM test_program
IMPLICIT NONE
LOGICAL(4), DIMENSION(4) :: l
l = [.TRUE., .FALSE., .TRUE., .FALSE.]
WHERE (l .neqv. .TRUE.)
l = .TRUE.
END WHERE
print *, l
END PROGRAM test_program
```
```console
True True True True 
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
T T T T
```
> feat: add support for element-wise operations on logical arrays using the `WHERE` statement

- integration_tests/intrinsics_166.f90
- integration_tests/intrinsics_167.f90
- integration_tests/intrinsics_168.f90
- src/libasr/pass/intrinsic_functions.h
> Support kind mismatch in `ibclr`, `btest` and `ibset` and add tests

- .github/workflows/CI.yml
- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_258.f90
Fixes: https://github.com/lfortran/lfortran/issues/3809
> ci: uncomment `abs(X-mean)**2` as is working now

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_232.f90
- integration_tests/intrinsics_256.f90
- integration_tests/intrinsics_257.f90
- integration_tests/intrinsics_260.f90
- integration_tests/intrinsics_263.f90
- src/libasr/pass/intrinsic_array_function_registry.h
> enh: support mask for compile time evaluation of `iparity`, `minval` and `maxval`

- integration_tests/CMakeLists.txt
- integration_tests/where_08.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- tests/errors/incorrect_array_type_where_01.f90
- tests/errors/incorrect_array_type_where_02.f90
- tests/errors/incorrect_type_where_01.f90
- tests/errors/incorrect_type_where_02.f90
- tests/errors/incorrect_type_where_03.f90
- tests/errors/incorrect_type_where_04.f90
- tests/reference/asr-incorrect_array_type_where_01-b613ee3.json
- tests/reference/asr-incorrect_array_type_where_01-b613ee3.stderr
- tests/reference/asr-incorrect_array_type_where_02-b821d8c.json
- tests/reference/asr-incorrect_array_type_where_02-b821d8c.stderr
- tests/reference/asr-incorrect_type_where_01-8974c02.json
- tests/reference/asr-incorrect_type_where_01-8974c02.stderr
- tests/reference/asr-incorrect_type_where_02-1746f84.json
- tests/reference/asr-incorrect_type_where_02-1746f84.stderr
- tests/reference/asr-incorrect_type_where_03-a95b1f2.json
- tests/reference/asr-incorrect_type_where_03-a95b1f2.stderr
- tests/reference/asr-incorrect_type_where_04-f7dffdb.json
- tests/reference/asr-incorrect_type_where_04-f7dffdb.stderr
- tests/tests.toml
fixes #4316 
```fortran
program name
implicit none
logical :: a(5)
integer  :: b(5)
a = [.true., .false., .true., .false., .true.]
where(a) b = 12121
print *, b
end program name
```
is transformed to
```fortran
program name
implicit none
integer(4) :: __1_k
logical(4), dimension(5) :: __libasr__created__var__0__array_constant_
logical(4), dimension(5) :: a
integer(4), dimension(5) :: b
__1_k = lbound(__libasr__created__var__0__array_constant_, 1)
__libasr__created__var__0__array_constant_(__1_k) = .true.
__1_k = __1_k + 1
__libasr__created__var__0__array_constant_(__1_k) = .false.
__1_k = __1_k + 1
__libasr__created__var__0__array_constant_(__1_k) = .true.
__1_k = __1_k + 1
__libasr__created__var__0__array_constant_(__1_k) = .false.
__1_k = __1_k + 1 …
```
> fix: handle lone `logical` array in `WHERE` clause

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_04.f90
- integration_tests/intrinsics_264.f90
- integration_tests/intrinsics_265.f90
- integration_tests/intrinsics_266.f90
- integration_tests/intrinsics_267.f90
- tests/reference/asr-intrinsics_04-524ec3a.json
- tests/reference/asr-intrinsics_04-524ec3a.stdout
Towards: #4017 , https://github.com/lfortran/lfortran/issues/3067
> Add integration test for `sin`, `cos`, `tan`, `dsin`, `dcos`, `dtan`

- integration_tests/CMakeLists.txt
- integration_tests/where_09.f90
- src/libasr/pass/where.cpp
Fixes #4318. Continuation of #4323.
> chore: duplicate expr before using in `where` pass to avoid automatic updation via reference

- integration_tests/where_08.f90
- src/lfortran/semantics/ast_body_visitor.cpp
#4320 had missed handling this, leading to some errors in compiling SNAP. This PR fixes it.
> fix: handle `allocatable` logical array inside `WHERE` clause

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_138.f90
- integration_tests/intrinsics_274.f90
- integration_tests/intrinsics_93.f90
- src/lfortran/semantics/ast_common_visitor.h
> Fix: support array type arg in inquiry functions and update tests for `precision` and `epsilon`

- integration_tests/CMakeLists.txt
- integration_tests/where_10.f90
- src/libasr/pass/where.cpp
resolves #4317 
The `array_op` pass converts every array section assignment statement into it's own `DO` loop and uses the loop variable for the assignment. This caused an issue with handling array section assignments inside the `WHERE` clause, as here we need the main `DO` loop variable for both condition check and assignment due to the array shapes being same. 
We add native support for handling `ArraySection_t` in the `where` pass to handle this.
```fortran
where (first_array(1, :) == zero)
first_array(1, :) = 2.0
end where
```
is converted to
```fortran
first_array(1, __1_k) = 2.00000000e+00
do __1_k = lbound(first_array(1, lbound(first_array, 2):ubound(first_array, 2)), 1), ubound(first_array(1,&
lbound(first_array, 2):ubound(first_array, 2)), 1), 1
if (first_array(1, __1_k) == zero) …
```
> feat: add support for handling `ArraySection_t` inside `WHERE` clause

- integration_tests/intrinsics_214.f90
- integration_tests/intrinsics_215.f90
- integration_tests/intrinsics_216.f90
> Add compile time and runtime tests for scalar for sind, cosd and tand intrinsic

- integration_tests/CMakeLists.txt
- integration_tests/openmp_31.f90
- src/libasr/pass/openmp.cpp
Towards #4388, #3777.
With this the example in #4388 compiles but it gives all `0.00`, I think a small piece is missing.
> fix: minor bug when creation of module lead to asr verify failure in openmp

- integration_tests/openmp_06.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Towards #4388, #3777. With this we get ASR correct. In openmp ASR pass, the trouble is do loop has its own statement, it translates it correctly but deletes do loop. We need to write `transform_stmts_do_loop`, I know how to fix it and made progress over it.
> enh: frontend to handle variants of `omp parallel do`

- integration_tests/CMakeLists.txt
- integration_tests/openmp_32.f90
- src/libasr/pass/openmp.cpp
Fixes #4388. Towads #3777. With this PR we get it working.
> Serial
```console
% gfortran b.f90 && ./a.out 
Done steps  =           100
Done steps  =           200
Done steps  =           300
Done steps  =           400
Done steps  =           500
Done steps  =           600
Done steps  =           700
Done steps  =           800
Done steps  =           900
Done steps  =          1000
8.1156792211894978E-023   3.5746070221702888E-022   5.2919810042527039E-023   1.2024036703484373E-022
% lfortran b.f90 
style suggestion: Use '==' instead of '.eq.'
--> b.f90:161:36
|
161 |         if ( mod( tsteps, nprint ) .eq. 0 ) print *, 'Done steps  =  ', tsteps
|                                    ^^^^ help: write this as '=='
Note: Please report unclear, confusing or incorrect messages as bugs at …
```
> enh: openmp pass to handle pragma inside do loop

- .github/workflows/CI.yml
This upload does not work, so we disable it for now.
First workaround for https://github.com/lfortran/lfortran/issues/4431.
> CI: disable WASM upload

- integration_tests/CMakeLists.txt
- integration_tests/where_11.f90
- src/libasr/pass/array_op.cpp
- src/libasr/pass/where.cpp
Fixes #4318 
I noticed that there could be some duplicated node for `intrinsicsElementalFunction` (nodes with same pointer address). They're mainly made by `where` asr_pass, which is great as we can memorize their result and just whenever we encounter them again we can simply get their result without doing all this work.
***
**Why is that related to the issue with intrinsics call inside where ?**
The reason is that after `where` pass did it work it left us with 3 duplicated `intrinsicsElementalFunction`. Whenever you visit a single one of them and you get any of the internal nodes tweaked or replaced, the others get affected as well which results in error in the great helper phase `asr_verify` as one of the node has done its replace phase correctly but the others changed and now they …
> enh : Memorize Duplicate `intrinsicsElementalFunction` + `intrinsicsArrayFunction`

- integration_tests/CMakeLists.txt
- integration_tests/compiler_version_01.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
I am firstly sorry for duplicating efforts, I didn't checkout https://github.com/lfortran/lfortran/pull/4422. I think this approach is cleaner and fits with our design of implementing intrinsic. I am not sure if there is any further cleaning possible in this PR, I would appreciate any feedback.
> feat: implement intrinsic `compiler_version`

- .github/workflows/CI.yml
This reverts commit 283d90efbb41a63894425371cfaf519268948e1b.
Fixes #4431.
> Revert "CI: disable WASM upload"

- integration_tests/CMakeLists.txt
- integration_tests/derived_types_37.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/pass/pass_utils.cpp
- tests/errors/derived_type_06.f90
- tests/reference/run-derived_type_06-2623a81.json
- tests/reference/run-derived_type_06-2623a81.stderr
- tests/tests.toml
fixes #4348 
Mainly, This fix does the following :
- sets  whole node type of `structInstanceMember` resulting from `visit_nameutils()` to array, if an array is found in the node (it could be buried in the hierarchy). This makes the node detectable by `array_op` pass so it create array reference around it (`arrayItem`).
- It triggers an error if more than on than array found in the hierarchy of `structInstanceMember` (`Two or more part references with non-zero rank must not be specified.`) . though `visit_nameutils()` tends to detect that error but it doesn't. (**It needs some refactoring**).
- When we create array reference in `array_op` pass, we start looking up for the node that's of an array type then we wrap an array item around it.
- Once we finished the work on `array_op` we set …
> Implied loop on structinstancemember

- integration_tests/CMakeLists.txt
- integration_tests/implicit_interface_15.f90
- integration_tests/implicit_interface_15b.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes #4445.
PS: It is yet to register test for this PR. How shall I register it?
This is how I test it:
```console
% lfortran -c --generate-object-code ./integration_tests/implicit_interface_15b.f90
% lfortran -c --generate-object-code --implicit-interface ./integration_tests/implicit_interface_15.f90
% lfortran implicit_interface_15.o implicit_interface_15b.o                                            
x
1.00000000e+01
```
> chore: set physical cast of argument correctly while creating implicit interface

- integration_tests/CMakeLists.txt
- integration_tests/global_array_pointer_01.f90
- src/libasr/codegen/asr_to_llvm.cpp
fixes #4464 
The problem is the exact same as the one here https://github.com/lfortran/lfortran/pull/4111/files.
We needed to initialize to global array variable then we chose to memorize the data for such arrays,  and once we call `visit_program`   while creating LLVM IR the memorized data would be used to initialize the arrays inside the main function of the LLVM IR.
> Fix : Memorize Pointer arrays for later initialization

- src/bin/glfortran
Assume `lfortran` is available in PATH because we can't guess its location from the relative path.
> Fix glfortran script when it's not installed

- integration_tests/CMakeLists.txt
- integration_tests/parameter_14.f90
- src/lfortran/semantics/ast_common_visitor.h
As discussed with @Pranavchiku in #4473, this PR Fixes #4471.
The current `determine_type` function in `ast_common_visitor.h` uses `compiler_options.po.default_integer_kind` in order to determine the `a_kind` value which is passed on to create the ASR variable type. This means that the Real values are also affected by this flag which is visible in the MRE from #4471.
> make RealType independent of -fdefault-integer-8

- doc/src/installation.md
When building from git source, I noticed that there are some packages that are not listed in the current documentation but are required.
I also noticed that builds fail if the gcc and gxx installed on the system are out of date, so I added the latest gcc and gxx from conda-forge.
> fix: Update installation.md in doc

- integration_tests/CMakeLists.txt
- integration_tests/where_12.f90
- src/libasr/pass/where.cpp
fixes #4510 
The fix creates nested do loops based on number of dimensions of the addressed array in the where statement.
fortran code of this initial code https://github.com/lfortran/lfortran/issues/4510#issue-2407913875 after **where** pass  :
```Fortran
do __1_k = lbound(arr, 1), ubound(arr, 1), 1
do __2_k = lbound(arr, 2), ubound(arr, 2), 1
do __3_k = lbound(arr, 3), ubound(arr, 3), 1
if (arr(__1_k, __2_k, __3_k) == 0) then
arr(__1_k, __2_k, __3_k) = 555
end if
end do
end do
end do
```
_code snippet of nested do loop, not full code._
> fix : Nested array ref in where

- integration_tests/CMakeLists.txt
- integration_tests/string_38.f90
- src/libasr/codegen/asr_to_llvm.cpp
Chore: Change expected integer parameter type lfortran_str_slice depending on passed compiler option `-fdefault-integer-8`
Fixes #4453. I am unsure if this is the best solution as it is not quite so elegant.
> fix fdefault-integer-8 verification error for string slices

- integration_tests/CMakeLists.txt
- integration_tests/while_03.f90
- src/lfortran/parser/fixedform_tokenizer.cpp
Fixes #4492. The do while lexing function did not lex the body statements inside, instead it would tokenize each line until a `doend` label was reached which does not allow for nested loops inside of do-while loops. This PR aims to fix that.
> lex body statements inside do while loops

- tests/errors/int_01.f90
- tests/reference/asr-int_01-9bf3eb9.json
- tests/reference/asr-int_01-9bf3eb9.stderr
- tests/tests.toml
Adding this to make sure that the error persists even with the new implementation of `int` intrinsic.
Ref: https://github.com/lfortran/lfortran/issues/4539#issuecomment-2256116600
Towards: #4017
> Add test for non-scalar kind arg for `int` intrinsic

- src/lfortran/parser/fixedform_tokenizer.cpp
Fixes #4494. This is based on the changes @Pranavchiku recommended and results in the same output as the non-fixed-form tokenizer for the same MRE noted in the issue.
> Add character*1 to fixedform tokenizer

- integration_tests/CMakeLists.txt
- integration_tests/print_arr_06.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/runtime/lfortran_intrinsics.c
- tests/reference/llvm-derived_types_32-4684b97.json
- tests/reference/llvm-derived_types_32-4684b97.stdout
- tests/reference/llvm-format2-ed47ddb.json
- tests/reference/llvm-format2-ed47ddb.stdout
towards https://github.com/lfortran/lfortran/issues/2543, https://github.com/lfortran/lfortran/issues/4523
***
**Description** : 
This PR enhances the backend to support printing arrays directly out of its pointer.
This PR utilizes `compute_fmt_specifier_and_args()` so it embeds type integers as passed args to `string_format_intrinsic()`;We use flag `add_type_as_int` to do that.
To print arrays using its pointer in the backend use `--skip-pass=print_arr`
We embed types as integers to be passed to `string_format_intrinsic()` function in c to be able to know what are the types, This would make use able to identify types mismatch to avoid segfaults and to know if we have an array pointer so we can loop on it.
***
**Next To Do**
- In order to only pass strings to `printf()` in c with case …
> enh : Support array printing in backend

- integration_tests/intrinsics_131.f90
- integration_tests/intrinsics_88.f90
- src/libasr/pass/intrinsic_functions.h
- tests/errors/intrinsics12.f90
- tests/errors/intrinsics13.f90
- tests/reference/asr-intrinsics12-16f1580.json
- tests/reference/asr-intrinsics12-16f1580.stderr
- tests/reference/asr-intrinsics13-349f6ac.json
- tests/reference/asr-intrinsics13-349f6ac.stderr
- tests/reference/asr-max_01-b3ef694.json
- tests/reference/asr-max_01-b3ef694.stderr
- tests/reference/asr-max_01-b3ef694.stdout
- tests/reference/asr-max_02-ddd1334.json
- tests/reference/asr-max_02-ddd1334.stderr
- tests/reference/asr-max_02-ddd1334.stdout
- tests/reference/asr-min_01-aefbe8a.json
- tests/reference/asr-min_01-aefbe8a.stderr
- tests/reference/asr-min_01-aefbe8a.stdout
- tests/reference/asr-min_02-81ef3b7.json
- tests/reference/asr-min_02-81ef3b7.stderr
- tests/reference/asr-min_02-81ef3b7.stdout
- tests/tests.toml
> Support different kind of args in min/max and update tests

- integration_tests/intrinsics_141.f90
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
> Correct type handling in `scale` intrinsic and update tests

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_298.f90
- src/libasr/pass/intrinsic_array_function_registry.h
> chore: support different kind of args in DotProduct and add test 

- integration_tests/derived_types_37.f90
- src/libasr/pass/array_op.cpp
- src/libasr/pass/pass_utils.cpp
Fixes #4579 
The problem occurs because we create a do loop with wrong bounds. 
instead of creating a bound for such expression `type%arr%num`, We should create a bound on `arr`.
Instead of fetching the array expression from `structInstaceMember` hierarchy inside `create_array_ref()` function, We create a designated function to do so in pass `array_op` so we can build a correct do loop by setting `result_var` to the fetched array.
> enh : Implied allocatable array assignment in StructIntanceMember

- src/libasr/pass/intrinsic_functions.h
- tests/errors/idint_real4.f90
- tests/reference/asr-idint_real4-b5321a5.json
- tests/reference/asr-idint_real4-b5321a5.stderr
- tests/tests.toml
> Throw error for single precision argument of `Idint` intrinsic 

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/intrinsics14.f90
- tests/errors/intrinsics15.f90
- tests/reference/asr-intrinsics14-5a6d04e.json
- tests/reference/asr-intrinsics14-5a6d04e.stderr
- tests/reference/asr-intrinsics15-76ae493.json
- tests/reference/asr-intrinsics15-76ae493.stderr
- tests/tests.toml
Fixes: https://github.com/lfortran/lfortran/issues/4584
> Throw error when first arg to `scale`/`set_exponent` intrinsic is integer array

- src/bin/lfortran.cpp
See https://gitlab.kitware.com/cmake/cmake/-/issues/26145#note_1554135
> lfortran: hand verbose option through to linker

- integration_tests/CMakeLists.txt
- integration_tests/equivalence_09.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes #4442. 
I removed the if-else cases for the number of args and added a for loop over the args instead, however note that for me this currently only works for args<=2. When there are 3 equivalence statements using commas i receive an assertfailure, but that is out of the scope of this PR.
> update equivalence for 2 args

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/kind_01.f90
- tests/reference/asr-kind_01-6c675be.json
- tests/reference/asr-kind_01-6c675be.stderr
- tests/tests.toml
fixes: https://github.com/lfortran/lfortran/issues/4539
> Throw error if `kind` arg in intrinsics is non-scalar

- src/libasr/ASR.asdl
- src/libasr/asdl_cpp.py
- src/libasr/asr_utils.cpp
- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/pass/intrinsic_subroutine.cpp
- src/libasr/pass/intrinsic_subroutine_registry.h
- src/libasr/pickle.cpp
- tests/reference/asr-intrinsics_29-d4080f2.json
- tests/reference/asr-intrinsics_29-d4080f2.stdout
- tests/reference/asr-matmul_01-7b0b0c2.json
- tests/reference/asr-matmul_01-7b0b0c2.stdout
> fix: printing incorrect name of `IntrinsicImpureSubroutine` in ASR

- .github/workflows/upload_docker_build.yml
- Dockerfile
fixes https://github.com/lfortran/lfortran/issues/2478
This PR adds a docker file to support building a docker image for `lfortran`. The built docker image is currently uploaded here https://hub.docker.com/repository/docker/ubaidsh/lfortran-build/general. 
It also adds a new workflow to auto-build and upload docker builds for every merge commit in `main`. The built images are uploaded to github packages. We currently overwrite the same image on every push.
First install docker https://docs.docker.com/engine/install/.
- run the image interactively `docker run -it ubaidsh/lfortran-build`
- one can find `lfortran` in `/app/bin/lfortran`
- run `docker build -t lfortran-build .` from the root directory of `lfortran` project
> Add `dockerfile` to support building docker image 

- integration_tests/CMakeLists.txt
- integration_tests/struct_type_01.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
> fix: struct type out of symbol error by duplicating it inside symbol table whenever required

- integration_tests/CMakeLists.txt
- integration_tests/pointer_02.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/codegen/llvm_array_utils.h
fixes #4635 
-We treat array of `pointer` as the same as `allocatable` when it comes to creating the ex `array { float*, i32,%dimension_descriptor*, i1, i32 }` and the dimension_descriptor `%dimension_descriptor = type { i32, i32, i32 }`.
- These LLVM structs get created by using alloca which creates an LLVM struct on the stack.
- We use `alloca` in the main function, so that object stay in the memory in the livetime of the running program
- But when we `nullify()`, We get disattached from that object.
- whenever we try to allocate again in a function, we would create an object in the stack that eventually would get freed
- That's why we couldn't produce it unless there's some function calls
***
**How fix Works**
- access the size of the struct (array, dimension_descriptor) by using GEP …
> Fix (nullify) : use malloc instead of allocation on stack 

- CMakeLists.txt
- src/bin/lfortran.cpp
- src/libasr/CMakeLists.txt
- src/libasr/stacktrace.cpp
- src/libasr/stacktrace.h
Since stacktraces on Ubuntu are very slow, LLVM stacktraces are being implemented to speed up the Ubuntu implementation,a s well as create a platform independent stacktracer.
More discussion in : #4236
> Add basic llvm stacktrace support

- integration_tests/CMakeLists.txt
- src/libasr/asr_builder.h
- src/libasr/pass/intrinsic_array_function_registry.h
We transform `int(matrix_b, kind=4)(i)` to `int(matrix_b(i), kind=4)`.
We are now able to test `intrinsics_142.f90`, `intrinsics_143.f90` and `intrinsics_298.f90`.
> fix: do casting on resultant `ArrayItem` instead of the complete array for intrinsic `DotProduct`

- src/libasr/pass/simplifier.cpp
I think once we merge this small change, the `simplifier_pass` branch will become compatible to be merge with `main` again
> simplifier pass: use `get_intrinsic_subroutine_name` for IntrinsicImpureSubroutine's

- src/libasr/stacktrace.cpp
We register `loc_abort_callback_print_stack` as the callback for `SIGABRT`. ([reference](https://github.com/Vipul-Cariappa/lfortran/blob/4c23d088213c4c18ee833253dc607216543dcf9e/src/libasr/stacktrace.cpp#L592-L593)).
Then we end up calling `abort` again while handling the `SIGABRT` signal.
I faced a similar problem while working with LPython, you can see the PR at https://github.com/lcompilers/lpython/pull/2626
> Prevent calling `abort` while handling the `SIGABRT` signal

- src/lfortran/semantics/asr_implicit_cast_rules.h
- tests/cast_node_m_value.f90
- tests/reference/asr-cast_node_m_value-8b7098f.json
- tests/reference/asr-cast_node_m_value-8b7098f.stdout
Following the changes in https://github.com/lfortran/lfortran/pull/4778, this probably got missed. I noticed this while trying to see, which ASR nodes have non-nullptr `m_symbolic_value`, while `m_value` is nullptr, and I noticed this case.
Also, I made all the variables as parameters, ensuring that the m_value is set  at compile-time.
> ASR: assign m_value to ComplexToComplex Cast node

- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-arrays_reshape_14-913f34e.json
- tests/reference/asr-arrays_reshape_14-913f34e.stdout
- tests/reference/asr-implied_do_loops2-98464d0.json
- tests/reference/asr-implied_do_loops2-98464d0.stdout
- tests/reference/asr-matrix_01_transpose-fb3276a.json
- tests/reference/asr-matrix_01_transpose-fb3276a.stdout
I made a similar PR against the *simplifier pass* branch, where it causes segmentation fault on a few of the cases on Linux (but not on macOS).
Let me know if there are more extra test cases needed for this.
> ASR: fix ArrayReshape ttype

- src/bin/lfortran.cpp
- src/lfortran/tests/ir.ll
- src/lfortran/tests/test_llvm.cpp
- src/libasr/codegen/evaluator.cpp
- src/libasr/codegen/evaluator.h
resolves #4790 
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/ir.ll
./examples/ir.ll:15:9: error: stored value and pointer type do not match
store i64 1, i32* %a1, align 4
^
Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start
File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2624, in main
return main_app(argc, argv);
File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2599, in main_app(int, char**)
err = …
```
> enh: add support for reporting errors during LLVM IR execution

- integration_tests/CMakeLists.txt
- integration_tests/openmp_01.f90
- integration_tests/openmp_34.f90
Thread IDs are now shown to confirm active threads and ensure even distribution of iterations. The output will display "xyz" printed 10 times, with each thread ID appearing twice, indicating that the 10 iterations are evenly distributed among 5 threads.
```shell
(lf2) aditya-trivedi@Observer:~/thats_me/Main_Repo$ ./lfortran/src/bin/lfortran --openmp --link-with-gcc ./lfortran/integration_tests/openmp_01.f90 -o a --openmp-lib-dir=${CONDA_PREFIX}/lib && ./a
0
xyz
2
xyz
2
3
xyz
3
xyz
1
xyz
1
xyz
4
xyz
xyz
0
xyz
4
xyz
n =     10
Done for n =     10
```
> enh: Refine OpenMP Test to Confirm Thread Load Balancing

- src/lfortran/parser/fixedform_tokenizer.cpp
- tests/fixedform_module.f
- tests/reference/ast-fixedform_module-3f800f0.json
- tests/reference/ast-fixedform_module-3f800f0.stdout
- tests/tests.toml
This will take us a little forward in the direction of being able to [compile POT3D](https://github.com/lfortran/lfortran/issues/2862).
> parser: allow MODULE statement in fixed form parser

- integration_tests/CMakeLists.txt
Seems like `associate_13.f90` succeeds now on both macOS and Linux. Probably, after making changes in `reshape` recently.
> simplifier pass: uncomment passing test case

- integration_tests/CMakeLists.txt
I didn't notice that on *main*, we only have compilation of *gfortran* label. So, this shouldn't be a problem anyways.
> uncomment passing tests

- src/libasr/asr_verify.cpp
Fixes https://github.com/lfortran/lfortran/issues/4738#issuecomment-2355830539
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran/integration_tests$ lfortran -c modules_58_module.f90
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran/integration_tests$ lfortran modules_58.f90
Size of nx1    555
Size of nx2    1000
555
```
> fix: do ASR verification conditionally for `ExternalSymbol` in `ArraySize`

- integration_tests/CMakeLists.txt
- src/libasr/pass/simplifier.cpp
We convert variable initilization to assignment in all of the scopes where the variable is present. E.g; below is the output of *simplifier pass* branch for `subroutines_12.f90`:
```f90
! Fortran code after applying the pass: simplifier
program subroutines_12
implicit none
integer(4), save :: nang ! initialized in `subroutines_12.f90` as `nang = 2`, but un-initialized now
call my_subroutine()
contains
subroutine my_subroutine()
integer(4), dimension(nang) :: fxhv
nang = 2 ! initilized here in this scope, where it's used
end subroutine my_subroutine
end program subroutines_12
```
```f90
! Fortran code after applying the pass: simplifier
program subroutines_12
implicit none
integer(4), save :: nang ! in `subroutines_12.f90` it's nang = 2 at initialization
nang = 2 ! convert to assignment in …
```
> simplifier pass: convert initialization to assignment in the same scope as initialization

- integration_tests/CMakeLists.txt
- integration_tests/legacy_array_sections_04.f90
- integration_tests/legacy_array_sections_04b.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_builder.h
Towards https://github.com/lfortran/lfortran/issues/4251. With this PR we get a segfault on that example, the reason is passing `afb` as  `afb( * ) ` and this leads to some array physical type problems. Thus I changed it to `afb( 4 )`, this is also not working with main.
> enh: support passing an ArrayItem first and then an Array in `--legacy-array-sections`

- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
- tests/function_call1.f90
- tests/reference/asr-function_call1-0b992da.json
- tests/reference/asr-function_call1-0b992da.stdout
- tests/tests.toml
Fixes #4759.
It still fails with `--show-llvm`
> feat: duplicate return type before setting in function call

- src/libasr/utils2.cpp
This handles several failure modes explicitly, and fixes a bug for empty files.
This should fix https://github.com/lfortran/lfortran/issues/4859.
> Add several fixes to read_file()

- src/bin/lfortran.cpp
Towards #4808
With this PR we can now show symbols inside `module`, `program`,`function`, `subroutine`. Previously symbols present inside scope of `TranslationUnit` were shown.
Previous:
With this PR:
> enh: lsp document symbols to collect nested symbols as well

- src/libasr/asr_utils.cpp
- src/libasr/asr_utils.h
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
- src/runtime/builtin/lfortran_intrinsic_builtin.f90
- tests/reference/asr-cmd_01-e172099.json
- tests/reference/asr-cmd_01-e172099.stdout
- tests/reference/asr-fn6-a24010a.json
- tests/reference/asr-fn6-a24010a.stdout
- tests/reference/asr-modules_48-6cf0505.json
- tests/reference/asr-modules_48-6cf0505.stdout
- tests/reference/asr-select_type_04-e8b402f.json
- tests/reference/asr-select_type_04-e8b402f.stdout
Reverts lfortran/lfortran#4863
> Revert "Remove old implementation of command_argument_count"

- src/libasr/asr_builder.h
> refactor: improve `ttype` exception message in ASR builder

- integration_tests/CMakeLists.txt
- integration_tests/openmp_35.f90
Added case of using multiple reduction with double precision data type
Output:-
```shell
(lf) aditya-trivedi@Observer:~/thats_me/main/lfortran$ ./src/bin/lfortran --openmp --link-with-gcc ./integration_tests/openmp_35.f90 --cpp -o a --openmp-lib-dir=${CONDA_PREFIX}/lib  && ./a
Total count:     1.60000000000000000e+01
Sum of v1:     1.36000000000000000e+02
Product result for v2:     2.09227898880000000e+13
Difference result for v3:     -1.36000000000000000e+02
```
> Enh:-Added Integration OpenMp test

- src/lfortran/semantics/comptime_eval.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
- src/libasr/runtime/lfortran_intrinsics.c
- src/runtime/builtin/lfortran_intrinsic_builtin.f90
- tests/reference/asr-cmd_01-e172099.json
- tests/reference/asr-cmd_01-e172099.stdout
- tests/reference/asr-fn6-a24010a.json
- tests/reference/asr-fn6-a24010a.stdout
- tests/reference/asr-modules_48-6cf0505.json
- tests/reference/asr-modules_48-6cf0505.stdout
- tests/reference/asr-select_type_04-e8b402f.json
- tests/reference/asr-select_type_04-e8b402f.stdout
Towards: https://github.com/lfortran/lfortran/issues/4593
> remove old implementation of command_argument_count

- src/lfortran/semantics/asr_lookup_name.cpp
- src/libasr/asdl_cpp.py
With this PR we are now almost done with `lookup-name` feature. We can now get information about the node where our cursor is pointing. There will be bugs which we need to handle by overriding this default visitor and thereby I have not removed `asr_lookup_name.cpp` file.
> feat: add a `DefaultLookupNameVisitor` that is created automatically

- integration_tests/CMakeLists.txt
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/codegen/llvm_array_utils.h
As a side effect, `current_select_type_block_type` now refers to the underlying type instead of the pointer, since we need that information later on.
> LLVM17: Fix select_type_05

- .github/workflows/CI.yml
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/evaluator.cpp
- src/libasr/codegen/llvm_array_utils.cpp
- src/libasr/codegen/llvm_utils.cpp
- src/libasr/codegen/llvm_utils.h
There were three issues
- llvm::CGFT_AssemblyFile moved to llvm::CodeGenFileType::AssemblyFile
- Vectorize.h, Host.h is removed
- All pointer types are removed (e.g., getInt8Ty)
> [LLVM] Fixes to build with LLVM 18,

- integration_tests/CMakeLists.txt
- src/libasr/pass/simplifier.cpp
- src/libasr/pass/where.cpp
```fortran
program main
call where_03
contains
subroutine where_03
implicit none
real a(4)
a = [1.0, 2.0, 1.0, 4.0]
where(a == 1.0) a = a * 3.0
end subroutine
end program
```
is transformed to
```fortran
! Fortran code after applying the pass: simplifier
program main
implicit none
call where_03()
contains
subroutine where_03()
real(4), dimension(4) :: __libasr_created__array_broadcast_
real(4), dimension(4) :: a
a = [1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00]
where (a == 1.00000000e+00)
__libasr_created__array_broadcast_ = 3.00000000e+00
a = a*__libasr_created__array_broadcast_
end where
print *, a
end subroutine where_03
end program main
```
> fix: replace `ArrayBroadcast` in `where` pass

- .github/workflows/CI.yml
- src/libasr/codegen/asr_to_llvm.cpp
Fixes: https://github.com/lfortran/lfortran/issues/4982
> [LLVM] Specify type for Load in StringCompare

- .github/workflows/CI.yml
Currently, when we create a PR against *simplifier_pass* branch, this leads to two CI checks, which always remain on *Expected — Waiting for status to be report..* (see example screenshot below):
Example PR where this happens: https://github.com/lfortran/lfortran/pull/5009
With this we introduce two dummy CI jobs (one for macOS and other for Linux), which do nothing at all (so they will always pass)
This solution followed after certik's comment here: https://github.com/lfortran/lfortran/pull/5004#issuecomment-2397002183
> CI: introduce dummy CI jobs to resolve "expected check" error

- src/runtime/builtin/lfortran_intrinsic_builtin.f90
- tests/reference/asr-select_type_04-e8b402f.json
- tests/reference/asr-select_type_04-e8b402f.stdout
> Remove old implementation of `len` intrinsic from old runtime lib

- integration_tests/CMakeLists.txt
- integration_tests/test_call_arg_structinstance_member.f90
this tests to make sure that when a StructInstanceMember is passed as an argument to a subroutine call (with intent(out)), then the changes are indeed made to the StructInstanceMember directly
Initially reported here https://github.com/lfortran/lfortran/issues/4761#issuecomment-2401815359
> test: add MRE for dftatom as integration test case

- .github/workflows/CI.yml
- src/libasr/pass/simplifier.cpp
This probably completely helps us compile dftatom on *simplifier_pass* branch, (excluding ofcourse the fast test cases, which I haven't checked)
> chore: don't create temporary for StructInstanceMember when present as call argument

- src/lfortran/semantics/comptime_eval.h
- src/runtime/builtin/lfortran_intrinsic_builtin.f90
- tests/reference/asr-select_type_04-e8b402f.json
- tests/reference/asr-select_type_04-e8b402f.stdout
> Remove unused interface for is_iostat_end and is_iostat_eor from old runtime lib

- .github/workflows/CI.yml
- check_binary_file_in_git_history.py
closes https://github.com/lfortran/lfortran/issues/5018
I don't know if it should be a dedicated job to test for binary files. Anyways, I tried to not interrupt the flow of the CI and did a checkout back to latest commit when the test succeeds. maybe we can call github action `checkout@v4` again right after running the test.
> CI : Add test for checking if there's a pushed binary file in git commit history

- integration_tests/CMakeLists.txt
- integration_tests/where_03.f90
- integration_tests/where_04.f90
- integration_tests/where_07.f90
- integration_tests/where_10.f90
- src/libasr/asdl_cpp.py
- src/libasr/pass/array_op.cpp
- src/libasr/pass/intrinsic_functions.h
- src/libasr/pass/where.cpp
- tests/reference/asr-where_03-a34eed8.json
- tests/reference/asr-where_04-a7fce45.json
- tests/reference/pass_where-where_01-94e4416.json
- tests/reference/pass_where-where_01-94e4416.stdout
- tests/reference/pass_where-where_02-1839d96.json
- tests/reference/pass_where-where_02-1839d96.stdout
- tests/reference/pass_where-where_03-00685f9.json
- tests/reference/pass_where-where_03-00685f9.stdout
- tests/reference/pass_where-where_04-2ee4397.json
- tests/reference/pass_where-where_04-2ee4397.stdout
Cherry-pick commits from https://github.com/lfortran/lfortran/pull/3748 (i.e. array_op_refac branch), specific to `where` tests
Changes done after cherry-picking the commits:
- disabled `integration_tests/where_04` for now, as it failed with the CI
* as the current *main* also has it disabled, so that's alright for now
- update reference tests
- fixed CI job *Check Release build*'s failure
> cherry-pick 'where' tests fix from array_op_refac branch

- src/libasr/pass/simplifier.cpp
We need to add an MRE present here: https://github.com/lfortran/lfortran/issues/4761#issuecomment-2416936436 to the *main* branch, once the tests on this PR succeed.
> chore: replace intrinsic elemental function with temporary when return type is StructType

- integration_tests/CMakeLists.txt
- integration_tests/elemental_function_overloaded_compare.f90
this tests to make sure that elemental function which overloads a comparison operator works correctly
There is a scope of improvement in the test-case in future, as it probably wouldn't compile and run currently if the program is extended to include the implementation of different functions in all ways
> tests: add MRE extracted from stdlib

- .github/workflows/CI.yml
- integration_tests/CMakeLists.txt
- integration_tests/elemental_function_scalar_array_arg.f90
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-template_03b-0778e50.json
- tests/reference/asr-template_03b-0778e50.stdout
- tests/reference/asr-template_04-f41dd3e.json
- tests/reference/asr-template_04-f41dd3e.stdout
If atleast one of the argument is an array, we should create the return type accordingly
This PR is ideally to be created against *main* and not *simplifier_pass*, but I'll like to do that just before *simplifier_pass* is ready to be merged.
> chore: fix return type of elemental function (could be of generic procedure)

- integration_tests/CMakeLists.txt
- src/libasr/codegen/asr_to_wasm.cpp
The following tests fail when running integration tests. 
```
The following tests FAILED:
38 - if_02 (SEGFAULT)
146 - complex_sub_test (SEGFAULT)
193 - template_add_01b (SEGFAULT)
212 - template_lapack_01 (Failed)
Errors while running CTest
```
Once these are done, the PR is ready.
> Fix array op tests for WASM

- .github/workflows/CI.yml
Refer: https://github.com/emscripten-core/emsdk/commit/53249b91e7ce47253502efdf3ee1900757d7f700#diff-ae070fbd66c55f7bf108994c0a42ffe69eee7319b5bf0f47bef0fcdbd8b496b3R180
> ci: use `node-18.20.3-64bit` for emsdk installation

- .github/workflows/CI.yml
- src/libasr/pass/simplifier.cpp
For an assignment like `c = transpose(c)` we need to create a temporary variable for `transpose(c)`.
This helps us get rid of the last workaround in *stdlib*
> chore: Temporary for transpose intrinsic array function

- integration_tests/nbody.f90
- src/lfortran/mod_to_asr.cpp
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/libasr/asr_builder.h
- src/libasr/asr_utils.h
- src/libasr/pass/arr_slice.cpp
- src/libasr/pass/array_op.cpp
- src/libasr/pass/global_stmts.cpp
- src/libasr/pass/inline_function_calls.cpp
- src/libasr/pass/instantiate_template.cpp
- src/libasr/pass/pass_compare.cpp
- src/libasr/pass/pass_list_expr.cpp
- src/libasr/pass/pass_utils.cpp
- src/libasr/pass/replace_symbolic.cpp
- src/libasr/pass/select_case.cpp
- src/libasr/pass/simplifier.cpp
- src/libasr/pass/while_else.cpp
This PR introduces the below changes:
1. undo the workaround in nbody.f90, as that workaround isn't needed anymore
2. use `ASR::make_Variable_t` instead of `ASRUtils::make_Variable_t_util`, as there isn't any difference between the two anymore (initially there was)
> Undo changes which aren't needed any more in simplifier_pass

- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/errors/duplicate_module_procedures.f90
- tests/reference/asr-duplicate_module_procedures-3eaed23.json
- tests/reference/asr-duplicate_module_procedures-3eaed23.stderr
- tests/tests.toml
This PR addresses an issue where duplicate symbols in the `add_generic_procedures()` function were not being properly caught and reported, potentially leading to incorrect compilation results. The problem occurred while pushing symbols into the `Vec<ASR::symbol_t*>` structure in `ast_symboltable_visitor.cpp`.
fixes: #4222 
Added logic to detect and report duplicate symbols in `add_generic_procedures()`.
Verified with test cases that the system now correctly handles and reports duplicates.
> Raise error for duplicate functions in interface

- integration_tests/CMakeLists.txt
- src/libasr/asr_utils.cpp
- src/libasr/asr_utils.h
Because of use of `static` variable, `make_FunctionCall_t_util` always uses the default value set for it, we need to make it an `external` variable instead, that's one solution.
Other solution to the problem could be use to setter and getter for `use_experimental_simplifier` variable.
> use 'external' variable instead of 'static' variable

- .github/workflows/CI.yml
- src/libasr/asr_verify.cpp
- src/libasr/asr_verify.h
- src/libasr/pass/implied_do_loops.cpp
- src/libasr/pass/init_expr.cpp
- src/libasr/pass/pass_manager.h
This will ensure that there is only a single place to enable/disable experimental simplifier pass, instead of use `pass_options.experimental_simplifier` at some places and `ASRUtils::use_experimental_simplifier` at others.
Also, toggling experimental_simplififer in hard-coded manner will produce expected results, once `ASRUtils::use_experimental_simplifier` is set to true/false, it will be used as that value throughout our codebase.
> chore: use `ASRUtils::use_experimental_simplifier` for enabling/disabling experimental simplifier

- integration_tests/CMakeLists.txt
These all pass in the simplifier PR #5182, so they should pass in `main` also.
> Enable all intrinsics for simplifier

- src/bin/lfortran.cpp
- src/libasr/codegen/evaluator.cpp
- src/libasr/codegen/evaluator.h
This will now print:
```console
$ lfortran --version
LFortran version: 0.41.0-147-g0588e0f67-dirty
Platform: Linux
LLVM: 11.1.0
Default target: x86_64-unknown-linux-gnu
```
> Print LLVM version in `--version`

- src/lfortran/semantics/ast_body_visitor.cpp
Towards [bug fix](https://github.com/lfortran/lfortran/pull/5011#discussion_r1821262606)
in continuation of #5011
> chore: use int instead of unsigned int in comparison operation

- integration_tests/intrinsics_78.f90
- src/libasr/asr_builder.h
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_functions.h
In continuation of :- #4645 
Basically , the logic is extended to promote lower kind in case of real.
Also , some refactoring changes are made like removeing ```create_type``` function which was added to create type with given kind but the workaround achieved by a earlier function ```set_kind_to_ttype_t```.
> Mod refactoring changes and extended logic to real

- integration_tests/procedure_decl_01_b.f90
In continuation of #5208.
Just added `call calcfc()` to justify change of `asr_verify.cpp`.
> test: added subroutine call in procedure declaration test

- integration_tests/assign_allocatable_array_of_struct_instances.f90
- src/libasr/pass/implied_do_loops.cpp
The issue really appeared (the test failed) when I started utilizing the string descriptor built on top of this PR #4918; So I needed to do this minor fix.
> Fix array constructor function

- integration_tests/format_14.f90
- src/libasr/runtime/lfortran_intrinsics.c
Fixes https://github.com/lfortran/lfortran/issues/5224.
Since this would anyway be eventually needed for compilation of POT3D third party package, I picked it up.
> enh: implement "TL/TR" format specifiers

- src/lfortran/parser/fixedform_tokenizer.cpp
- tests/fixed_form_interface.f
- tests/reference/ast-fixed_form_interface-a8dfdb0.json
- tests/reference/ast-fixed_form_interface-a8dfdb0.stdout
Fixes https://github.com/lfortran/lfortran/issues/5220
> chore: tokenize 'do concurrent' in fixed-form program

- src/lfortran/parser/fixedform_tokenizer.cpp
- tests/fixed_form_interface.f
- tests/reference/ast-fixed_form_interface-a8dfdb0.json
- tests/reference/ast-fixed_form_interface-a8dfdb0.stdout
Fixes https://github.com/lfortran/lfortran/issues/5234
> chore: tokenize 'FLUSH' in fixedform

- .github/workflows/CI.yml
Fixes https://github.com/lfortran/lfortran/issues/5231
some of third party packages in it need a specific version i.e. either macOS or ubuntu, this PR makes sure that the OS is used as a variable, where the different third party can decide whether something needs to be run with 'macOS' or 'ubuntu' or both
before this commit, 'Test fpm', 'Test fastGPT ( ubuntu-latest )' or 'Test fastGPT ( macos-latest )' weren't being run under 'Test LLVM' CI job as 'matrix.os' was always empty
Below are the third party packages, which are now tested twice for each OS (ubuntu and macOS), and for each LLVM version (earlier they are were tested on only ubuntu):
* Test Legacy Minpack (SciPy)
* Test Modern Minpack (Fortran-Lang)
* Test Modern Minpack (check results)
* Test dftatom
* Test stdlib
* Test SNAP …
> CI: fix bug with fastGPT ubuntu & fpm in Test LLVM CI job

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_323.f90
- src/libasr/asr_builder.h
Foxes #5243
With this PR and https://github.com/Pranavchiku/numerical-methods-fortran/commits/lf1/, we compile https://github.com/lfortran/lfortran/issues/4703 fully, 1 workaround ( https://github.com/lfortran/lfortran/issues/5245 ), 2 commented tests ( which will be easy to fix )
> enh: r2r logic to avoid unnecessary cast node

- src/lfortran/semantics/ast_body_visitor.cpp
- tests/errors/array_04_cc.f90
- tests/reference/run-array_04_cc-c986e51.json
- tests/reference/run-array_04_cc-c986e51.stderr
- tests/reference/run-array_04_cc-c986e51.stdout
- tests/tests.toml
Toward :- #5036 
I am not sure that should we handle this error file.
Error message for this file is thrown through asr_utils and so , didn't break the semantic error into diagnostic and semantic abort and instead used catch for semantic error
```
File "/mnt/d/lfortran2/lfortran/src/libasr/asr_utils.h", line 4752, in LCompilers::ASR::expr_t* LCompilers::ASRUtils::get_bound<LCompilers::LFortran::SemanticError>(LCompilers::ASR::expr_t*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Allocator&)
throw SemanticError(msg, arr_expr->base.loc);
semantic error: Type member a is not an array so it cannot be indexed.
--> try.f90:8:1
|
8 | b%a(:) = 1
| ^^^^^^
Note: Please report unclear, confusing or incorrect messages as bugs at …
```
> Error resilient array_04

- src/bin/lfortran.cpp
- tests/reference/run-array_02_cc-634bad3.json
- tests/reference/run-array_04_cc-c986e51.json
- tests/reference/run-array_05_cc-4c5cdb4.json
- tests/reference/run-array_06_cc-e5490ba.json
- tests/reference/run-array_07-de10142.json
- tests/reference/run-assign_01-f454e20.json
Fixes #5248
We now return non-zero code with `--show-llvm`, `--show-fortran`, `--show-asr`, binary generation and execution when `--continue-compilation` is on and there are error messages.
> fix: return non-zero exit code with `--continue-compilation`

- src/lfortran/parser/parser.cpp
- src/lfortran/parser/parser.yy
- src/lfortran/semantics/ast_body_visitor.cpp
- tests/parser/enum_decl_without_start_program.f90
- tests/reference/ast-enum_decl_without_start_program-9ae6425.json
- tests/reference/ast-enum_decl_without_start_program-9ae6425.stdout
- tests/tests.toml
This makes it also work without the program statement present. There was also a bug in being case sensitive in recognize "end program", so I fixed it, together with other places that used `strcmp()` instead of `to_lower()`.
Fixes #5270.
> Allow enum in interactive mode

- src/lfortran/parser/parser.yy
- tests/parser/parameter_without_start_program.f90
- tests/reference/ast-parameter_without_start_program-a99ac57.json
- tests/reference/ast-parameter_without_start_program-a99ac57.stdout
- tests/tests.toml
This also makes it work without the program statement.
Fixes #5269.
> Parser: allow parameter in interactive mode

- integration_tests/CMakeLists.txt
- integration_tests/intent_02.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Fixes #5249 
The ASR goes from this :
```clj
(Allocate
[((StructInstanceMember
(Var 6 s1)
6 1_tt_ssss
(Allocatable
(Character 1 -2 () DescriptorString)
)
()
)
[]
(IntegerConstant 10 (Integer 4) Decimal)
())]
()
()
()
)
(SubroutineCall
6 sub1
()
[((Var 6 s1))]
()
)
(ImplicitDeallocate
[(Var 6 allocatable_str)]
)
(SubroutineCall
6 sub2
()
[((Var 6 allocatable_str))]
()
)
(ImplicitDeallocate
[(Var 6 allocatable_str)]
)]
),
```
To this :
```clj
(Allocate
[((StructInstanceMember
(Var 6 s1)
6 1_tt_ssss
(Allocatable
(Character 1 -2 () DescriptorString)
)
()
)
[]
(IntegerConstant 10 (Integer 4) Decimal)
())]
()
()
()
)
(ImplicitDeallocate
[(StructInstanceMember
(Var 6 s1)
6 1_tt_ssss
(Allocatable
(Character 1 -2 () DescriptorString)
)
()
)]
)
(SubroutineCall
6 sub1
()
[((Var 6 s1))]
()
) …
```
> Fix : intent out with allocatable internal members of passed structType argument

- src/bin/lfortran.cpp
Converts the response to a specified but missing input file from an `LCompilersException` to a message on `std::cerr` and a non-zero return code, both modeled on clang's response.  This addresses issue #5286 (which is a duplicate of issue #3796)
> Reduce severity of missing input file

- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-program_variable-066cc64.json
- tests/reference/asr-program_variable-066cc64.stderr
Show a secondary label with the declaration location.
Follow up for #5291.
Before:
After:
> Improve the error message for Program as a Var

- src/libasr/codegen/asr_to_llvm.cpp
- tests/errors/array_03.f90
- tests/errors/array_03_cc.f90
- tests/reference/asr-array_03-a79d86f.json
- tests/reference/run-array_03_cc-e368d39.json
- tests/reference/run-array_03_cc-e368d39.stderr
- tests/reference/run-array_03_cc-e368d39.stdout
- tests/tests.toml
Toward :- #5036 
```
program array_03
implicit none
integer :: a(:)
a(:,:) = 1
end program
```
Handled error in array_03 and the changes brought segmentation fault which were handled in asr_to_llvm.cpp file.
> Error resilient array-03

- src/lfortran/parser/parser.cpp
- tests/common2.f
- tests/fixed_form_line_limit.f
- tests/reference/asr-common2-64c97b2.json
- tests/reference/ast-common2-1811464.json
- tests/reference/ast-fixed_form_line_limit-0a3f0f0.json
- tests/reference/ast-fixed_form_line_limit-0a3f0f0.stdout
- tests/tests.toml
This changes the fixed-form parser to completely ignore inputs beyond  column 72, which addresses issue #678.  This PR also adjusts an existing fixed-form test (common2) to conform to the 72 column restriction, and adds a new test case to ensure c72 behavior. 
Note that this PR leaves the string-parsing behavior discussed in issue #5305 unchanged: those issues will be addressed in another PR.   Ideas for future improvement include:
* add a command-line option to adjust the fixed-form line length
* warn when input is being discarded (a la GCC -Wall).
* consider the 2018 limit of 132 characters for free-form lines (removed in 2023).
> Enforce 72-column limit on fixed-form inputs

- src/lfortran/parser/parser.cpp
- tests/fixed_form_line_limit.f
- tests/reference/ast-fixed_form_line_limit-0a3f0f0.json
- tests/reference/ast-fixed_form_line_limit-0a3f0f0.stdout
This PR addresses a fixed-form failure where the first 72 columns are spaces, but there is non-blank text afterwards, such as in the second line of this snippet:
```fortran
CHARACTER CVTN01*1                                                00760402
00770402
```
This is now correctly categorized as a blank line (=> comment).  Testing has been updated to cover this case.
This closes #5311.
> Treat spaces in first 72 columns as a comment

- integration_tests/CMakeLists.txt
- integration_tests/save_09.f90
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/llvm-arrays_op_4-df4e84d.json
- tests/reference/llvm-arrays_op_4-df4e84d.stdout
- tests/reference/llvm-associate_02-558b0e6.json
- tests/reference/llvm-associate_02-558b0e6.stdout
- tests/reference/llvm-associate_03-68dfbc7.json
- tests/reference/llvm-associate_03-68dfbc7.stdout
- tests/reference/llvm-bindc3-d064ff7.json
- tests/reference/llvm-bindc3-d064ff7.stdout
- tests/reference/llvm-callback_02-41bc7d7.json
- tests/reference/llvm-callback_02-41bc7d7.stdout
- tests/reference/llvm-callback_05-c86f2cc.json
- tests/reference/llvm-callback_05-c86f2cc.stdout
- tests/reference/llvm-implicit_interface_04-9b6786e.json
- tests/reference/llvm-implicit_interface_04-9b6786e.stdout
- tests/reference/llvm-int_dp-9b89d9f.json
- tests/reference/llvm-int_dp-9b89d9f.stdout
- tests/reference/llvm-int_dp_param-f284039.json
- tests/reference/llvm-int_dp_param-f284039.stdout
- tests/reference/llvm-intrinsics_02-404e16e.json
- tests/reference/llvm-intrinsics_02-404e16e.stdout
- tests/reference/llvm-intrinsics_03-0771f1b.json
- tests/reference/llvm-intrinsics_03-0771f1b.stdout
- tests/reference/llvm-real_dp_param-bac42bc.json
- tests/reference/llvm-real_dp_param-bac42bc.stdout
- tests/reference/llvm-return_03-3f7087d.json
- tests/reference/llvm-return_03-3f7087d.stdout
Fixes #5308.
This is the second part of the fix after https://github.com/lfortran/lfortran/pull/5316.
This finishes the basic implementation for integer/real/logical scalar variables. See the issue https://github.com/lfortran/lfortran/issues/5319 to implement this for the rest of the types.
> Fix integer/real/logical save variables

- src/lfortran/parser/parser.yy
- tests/data3.f90
- tests/reference/asr-data3-0afaffe.json
- tests/reference/asr-data3-0afaffe.stdout
- tests/tests.toml
Trying to run the FCVS_95 validation suite in #480, I found that some `DATA` statement constructs were not supported in LFortran, such as positive signed integers and complex:
```f90
data ivon06,ivon07,ivon08,ivon09,ivon10 /+3,+76,+587,+9999,+21111/
data axva,axvb /(-234.23, 3), (+2, -3.0)/
```
While I was working on fixing those, I noted that the `data_stmt_repeat` grammar rule was too permissive in some cases, and that the `data_stmt_constant` was not supporting _scalar-constant-subobject_, so I tried to fix those as well.  Added a new test as well.
> Adjust DATA statement parsing

- .github/workflows/CI.yml
Several changes were made:
* Use the upstream master unmodified
* In LLVM 10-19 only test one test, not the full testsuite
* In 3rd party tests only test simplifier without `--fast`.
> CI: speedup dftatom tests

- .github/workflows/CI.yml
Given:
* The simplifier is tested with LLVM in other tests
* We only changed the backend in LLVM to use WASM
And assuming:
* No bugs in LLVM
We do not need to test simplifier with llvm_wasm, because it should not trigger any bugs. If it does, those would be LLVM bugs, or integration bugs, but those are rare. For now the main thing is to ensure the simplifier pass works and it works with all the other passes and with LLVM. We already test that. We do not need to test every combination of the simplifier and other options.
Once simplifier becomes ready, then we can start testing it with all combinations. Until then we just need to ensure it works with one set of options, not all.
> CI: do not run simplifier for llvm_wasm tests

- integration_tests/CMakeLists.txt
- integration_tests/fortran_01.f90
- integration_tests/openmp_40.f90
- src/libasr/codegen/asr_to_fortran.cpp
Towards [ Fortran Backend](https://github.com/lfortran/lfortran/issues/5260)
Starting with minimal fix
> enh: Fortran backend to support openmp dump

- integration_tests/CMakeLists.txt
- integration_tests/array_op_07.f90
- src/libasr/pass/array_op.cpp
Fix :- #5285
Earlier , we were not visiting arguments of Array Function which can be an IntrinsicElementalFunction and thus , this PR tries to incorporate this thing in array_op.
> Fix: Handling maxval array function with comparision operator

- src/lfortran/parser/parser.yy
- src/lfortran/parser/semantics.h
- tests/errors/init1.f90
- tests/reference/ast-init1-a99a704.json
- tests/reference/ast-init1-a99a704.stderr
- tests/tests.toml
The parser conflict changes are non-essential.
Add an error test for "integer x = 1".
Depends on #5362, must be merged first.
Fixes #3945.
> Rework the declaration parsing

- src/libasr/pass/simplifier.cpp
Fixes https://github.com/lfortran/lfortran/issues/5199
The following is the Fortran code generated by this PR,
```fortran
! Fortran code after applying the pass: simplifier
program main
implicit none
integer(4) :: __1__libasr_index_
integer(4), dimension(1) :: __libasr__created__var__0__array_constructor_
integer(4), dimension(4) :: __libasr_created__array_reshape_array
integer(4), dimension(:), allocatable :: __libasr_created__intrinsic_array_function_Shape
integer(4), dimension(2) :: __libasr_created__intrinsic_array_function_Shape1
integer(4), dimension(1) :: __libasr_created_string_format
integer(4), dimension(2, 2) :: arr
integer(4) :: dim
dim = 1
__libasr_created__array_reshape_array = [1, 2, 3, 4]
__libasr_created__intrinsic_array_function_Shape1 = Shape(arr)
arr = …
```
> Fix temporary creation for ArraySize argument

- integration_tests/arrays_57.f90
- src/libasr/asr_utils.h
Fixes #5334 
Here I haven't changed logic, just reordered checking of arg type as it may be case like `func(abs(A(:,1:2))` where ArraySection is detected after `IntrinsicElementFunction` check.
> enh: reordered checking of arg type in `make_ArraySize_util`

- integration_tests/CMakeLists.txt
- integration_tests/save_10.f90
- integration_tests/save_11.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/init_expr.cpp
- src/libasr/pass/simplifier.cpp
Towards #5319.
The fix doesn't work for `structTypes` yet. but it should be easy after this PR to do so.
I don't like the workarounds in `init_expr` and `simplifier` pass to make this feature work. They simplify things for the backend, but that's the way I found it would work.
Things that gets done in `program` instead of locally in the function or while creating the module (like allocating an array desc) are getting a lot. maybe we need to look into that matter to simplify things further. maybe use lambda functions to preserve these actions so it get applied one by one without caring about preserving the arguments and calling the needed function.
> Initalize save variables in program for arrays and complex

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_327.f90
- src/libasr/pass/simplifier.cpp
I'll first want to see if the tests pass or not. The idea is to make the test case being added here: https://github.com/lfortran/lfortran/pull/5349 to pass with `--experimental-simplifier`.
Currently, I've commented out the test case because it doesn't work without *experimental-simplifier*.
> enh: set_allocation_size for transpose intrinsic array function

- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/runtime/lfortran_intrinsics.c
- tests/reference/asr-modules_48-6cf0505.json
- tests/reference/asr-modules_48-6cf0505.stdout
- tests/reference/asr-string_17-29e01e3.json
- tests/reference/asr-string_17-29e01e3.stdout
Instead of relaying on runtime C's `strlen` to return the size of the string by iterating over the consecutive characters till it reaches the null character, We simply use the size if the string we have is of physical type stringDescriptor `{char_ptr, size, capacity}`
> Enh : Utilize stringDescriptor size for `len()`

- integration_tests/CMakeLists.txt
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/libasr/codegen/asr_to_fortran.cpp
- tests/reference/fortran-enum_01-3bcfd6d.json
- tests/reference/fortran-enum_01-3bcfd6d.stdout
- tests/reference/llvm-modules_38-8886f9a.json
- tests/reference/llvm-modules_38-8886f9a.stdout
- tests/tests.toml
Fixes #5314. This is the same design mentioned at #5314 but due to https://github.com/lfortran/lfortran/issues/5314#issuecomment-2466649139 we cannot pull enum variable. This asks us to create an `EnumeratorLink` node, doing precisely the same thing as `ExternalSymbol` but we need to write exact same code and handler for `EnumeratorLink` as we do for `ExternalSymbol` so I think using `ExternalSymbol` is a way here to avoid duplication.
> revert: creating `Enum_t` node and link variables via `ExternalSymbol`

- src/lfortran/semantics/ast_body_visitor.cpp
Pull Request aims to convert all SemanticAbort in ast_body_visitor file into diag.add + SemanticAbort.
With this PR , all SemanticErrors are covered for this file.
> refactor: `ast_body_visitor` to throw `SemanticAbort()` instead at every place

- build1.bat
- build1.sh
- build_release.sh
- build_to_wasm.sh
This option creates a json file called `compile_commands.json` containing the exact compiler calls for all translation units of the project. The file is required for using the `clangd` LSP. Please see https://clang.llvm.org/docs/JSONCompilationDatabase.html.
> build: add `CMAKE_EXPORT_COMPILE_COMMANDS` option to build script for working with `clangd` LSP

- integration_tests/fortran_01.f90
- src/libasr/codegen/asr_to_fortran.cpp
In continuation of #5278
And Towards #5260
Generates proper fortran code for ptr = c_loc(x)
> enh: Fortran Backend : Handling C_loc

- src/lfortran/parser/parser.yy
Now we have just one error recovery at the statement level, which is easier to mmaintain and it is able to print AST, since we simply skip the statement.
This provides an improvement over the initial implementation in https://github.com/lfortran/lfortran/pull/4774. The test introduced there still works.
> Parser: error at the statement level

- environment_linux.yml
Currently, we've a failure in *main* for the run here: https://github.com/lfortran/lfortran/actions/runs/11966322550/job/33361766770.
Ondřej in a message here: https://lfortran.zulipchat.com/#narrow/channel/197339-General/topic/CI.20failure.20in.20main/near/483842225, mentioned that:
> Use the same version that we use at the CI
This PR fixes the version of `cmake` to 3.29.1
> CI: fix version of cmake to use

- integration_tests/CMakeLists.txt
- integration_tests/where_14.f90
- src/libasr/pass/where.cpp
- tests/reference/pass_where-where_03-00685f9.json
- tests/reference/pass_where-where_03-00685f9.stdout
Fixes #5433
It changes the ASR for the example `where (xbdi == 0) ssq = max(0, ssq - xbdi)` from 
```Clojure
(IntegerBinOp
(ArrayItem
(Var 3 ssq)
[(()
(Var 3 __1_k)
())]
(Integer 4)
RowMajor
()
)
Sub
(ArrayItem
(Var 3 xbdi)
[(()
(Var 3 __1_k)
())]
(Integer 4)
RowMajor
()
)
(Array
(Integer 4)
[((IntegerConstant 1 (Integer 4) Decimal)
(ArraySize
(Var 3 a)
()
(Integer 4)
()
))]
PointerToDataArray
)
()
)
```
To
```Clojure
(IntegerBinOp
(ArrayItem
(Var 3 ssq)
[(()
(Var 3 __1_k)
())]
(Integer 4)
RowMajor
()
)
Sub
(ArrayItem
(Var 3 xbdi)
[(()
(Var 3 __1_k)
())]
(Integer 4)
RowMajor
()
)
(Integer 4)  ;; HERE IS THE CHANGE
()
)
```
> Modify return type for `BinOp` after `where` pass itemize the array

- src/libasr/pass/insert_deallocate.cpp
- tests/finalize_01.f90
- tests/reference/pass_insert_deallocate-finalize_01-3efebdd.json
- tests/reference/pass_insert_deallocate-finalize_01-3efebdd.stdout
- insert `implicitDeallcoate` node in `program`, `function`, `block`, `if`, `doWhile`, `do` bodies.
- create a stack to hold the current implicit node that needs to be inserted by if,doWhile, do visitors, nested functions.
- Create visitors for if, doWhile, do to look up for insider returns or exits.
- Create some functions for redundant usage.
- make sure avoid unneceessary insertion for the implicitDeallocate node if we encounter a dead code.
> Finalization : Finalize with return exit

- src/libasr/stacktrace.cpp
> Make address_to_line_number work with empty vector

- src/bin/CMakeLists.txt
Now the llvm-dwarfdump outputs debugging information.
Fixes #5492.
> macOS: Use system dsymutil first

- run_tests.py
Fixes https://github.com/lfortran/lfortran/pull/5485#discussion_r1858862450
> test: do not check no llvm for semantics only

- src/lfortran/tests/ir.ll
This test works (i.e., fails correctly) in all LLVM versions with:
$ lfortran src/lfortran/tests/ir.ll
src/lfortran/tests/ir.ll:5:20: error: '%b' defined with type 'i64' but expected 'i32'
%s = add i32 %a, %b
^
...
LCompilersException: parse_module(): Invalid LLVM IR
Previously the file `ir.ll` failed in LLVM 11, but succeeded in LLVM 19.
> Tests: Add a simplified version of ir.ll

- .github/workflows/CI.yml
- .gitignore
- pixi.toml
The CI works, but I left it disabled for now to save runners. Once we can replace some existing jobs, then we'll switch.
This ports changes from #5489, except `pixi.lock`, since it's a huge file.
> Add environments to pixi.toml

- examples/cmdline.f90
This example reads a command line argument and uses it in computation. This is a good example to use to test that the runtime library works, such as in WASM.
> Add a cmdline.f90 example

- run_tests.py
- src/bin/lfortran.cpp
- src/libasr/pass/openmp.cpp
- src/libasr/utils.h
- tests/reference/pass_openmp-do_concurrent_01-2a6df8c.json
- tests/reference/pass_openmp-do_concurrent_01-2a6df8c.stdout
- tests/tests.toml
This a first step for GPU offloading.
Let's take do concurrent as the ASR node for offloading.
The node has to be moved into a separate module, which will be 
converted into a MLIR openmp dialect and transform the generated
MLIR to LLVM module and link it with the LLVM module generated by
the LLVM backend. 
Only `do concurrent` is handled by MLIR, rest all the nodes will be
handled by the LLVM backend.
> [Pass] Modify ASR to generate a module for MLIR GPU offloading

- src/lfortran/parser/parser.yy
- tests/implicit1.f90
- tests/reference/ast-implicit1-e201262.json
- tests/reference/ast-implicit1-e201262.stdout
- tests/reference/ast_f90-implicit1-418fb10.json
- tests/reference/ast_f90-implicit1-418fb10.stdout
Simple parser change to allow `IMPLICIT NONE ()` to be accepted.  AST->ASR already handles this case.
* Rename `implicit_none_spec_list` to `implicit_none_spec_star`
* Add `%empty` branch to `implicit_none_spec_star`
* Update `implicit1` test to cover this case.
This closes #5522
> Allow parser to accept `IMPLICIT NONE ()`

- integration_tests/CMakeLists.txt
- integration_tests/array_op_08.f90
- integration_tests/array_op_09.f90
- src/libasr/pass/array_op.cpp
Fixes #5513 
Earlier , we were not visiting arguments of Elemental Function . This PR tries to incorporate this thing in array_op.
MRE 1
```
program test 
integer :: A(3) = [1,2,3]
logical :: X(3)
integer :: tol = 2
X = abs(A) <= max(tol, tol * maxval(abs(A)))
print *, X
end program
```
Output 
```
(lf) ansh_mehta@DESKTOP-VJGRLON:/mnt/d/lfortran2/lfortran$ ./src/bin/lfortran try.f90
T    T    T
```
MRE 2
```
program test 
integer :: A(3) = [1,2,3]
logical :: X(3)
integer :: tol = 2
X = abs(A) <= max(tol,maxval(abs(A)))
print *, X
end program
```
Output 
```
(lf) lordansh@LordAnsh:~/dev/lfort2/lfortran$ ./src/bin/lfortran try.f90
T    T    T
```
MRE 3
```
program test 
integer :: A(3,2) = reshape([1,2,3,4,5,6], [3,2])
integer :: X(2)
X = abs(sum(A, dim=1))
print *, X
end program
```
Output …
> Fix : Handling Intrinsic Elemental Function by visiting its Arguments

- src/libasr/asr_verify.cpp
- src/libasr/pass/intrinsic_functions.h
Removed the repeated use of `ASR Verify:` from 2 different files - `asr_verify.cpp ` and `intrinsic_functions.h` . Fixes #2863
> Fixes issue #2863: Repeated use of ASR verify

- src/lfortran/parser/parser.cpp
- src/libasr/pass/intrinsic_subroutine.cpp
- src/libasr/string_utils.cpp
- src/libasr/string_utils.h
fixes https://github.com/lfortran/lfortran/issues/5534
Output from branch:
```fortran
(lf) ubaid@DESKTOP-TEN39M0:~/projects/lfortran$ cat examples/expr2.f90 
program hello
end
```
```console
(lf) ubaid@DESKTOP-TEN39M0:~/projects/lfortran$ valgrind gfortran examples/expr2.f90
==133657== Memcheck, a memory error detector
==133657== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==133657== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==133657== Command: gfortran examples/expr2.f90
==133657== 
==133657== 
==133657== HEAP SUMMARY:
==133657==     in use at exit: 180,109 bytes in 123 blocks
==133657==   total heap usage: 522 allocs, 399 frees, 239,868 bytes allocated
==133657== 
==133657== LEAK SUMMARY:
==133657==    definitely lost: 7,040 bytes in 50 …
```
> Fix memory issues in lfortran

- src/libasr/lsp.cpp
We just needed to add `diag_capture.SetObject();` before setting the values of its fields.
> Fixes the types of the JSON objects returned by --show-errors

- integration_tests/CMakeLists.txt
- integration_tests/array_indices_array_item.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/pass/array_op.cpp
fixes #4420 
We convert an `ArrayItem` like `x(loc, loc)`, where `loc` is an array, to:
```fortran
do __1_t = lbound(__libasr__created__var__0__array_item, 1), ubound(__libasr__created__var__0__array_item, 1)
do __2_t = lbound(__libasr__created__var__0__array_item, 2), ubound(__libasr__created__var__0__array_item, 2)
__libasr__created__var__0__array_item(__1_t, __2_t) = x(loc(__1_t), loc(__2_t))
end do
end do
```
> feat: add support for array type indices in `ArrayItem`

- integration_tests/array_indices_array_item.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes #5518 
Essentially fixes calls of:
```fortran
print *, arr([1, 2])
```
> Allow for array constants in array item calls

- .github/workflows/CI.yml
Alternative to https://github.com/lfortran/lfortran/pull/5013 with unaltered changes and thus caches for the "Check Out-of-Source Debug build" workflow.
> ci: Use micromamba 2.0 via setup-micromamba 2

- integration_tests/CMakeLists.txt
- integration_tests/write_08.f90
- src/libasr/asr_utils.h
>  fix: cast to `PointerString` when `m_fmt` is a variable with physical type `DescriptorString` in `StringFormat`

- integration_tests/CMakeLists.txt
- integration_tests/modules_60.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/reference/asr-modules_60-baa1105.json
- tests/reference/asr-modules_60-baa1105.stdout
- tests/tests.toml
> fix: retain symbol name for `ExternalSymbol` during import if `m_external` is `ASR::Function_t`

- src/bin/lfortran.cpp
- src/lfortran/parser/parser.cpp
This PR fixes `--show-prescan` compiler flag's short description, and adds a short explanation for it.
> fix: correct `--show-prescan` documentation and add prescan explanation

- integration_tests/CMakeLists.txt
- integration_tests/openmp_41.f90
- src/libasr/pass/openmp.cpp
This PR aims to correctly update the loop variables for each head of DoConcurrentLoop,  continuing #5542 and hence moving towards #4900 and #4818 completion
> Feat: Multiple Headed DoConcurrentLoop: Update of each loop variables

- integration_tests/CMakeLists.txt
- integration_tests/functions_27.f90
- src/libasr/pass/subroutine_from_function.cpp
- src/libasr/pass/subroutine_from_function_simplifier.cpp
Fixes https://github.com/lfortran/lfortran/issues/5564
> Add implicit deallocate before creating a `subroutine_call` in `subroutine_from_function`pass

- integration_tests/CMakeLists.txt
- integration_tests/doloop_12.f90
- src/libasr/pass/subroutine_from_function_simplifier.cpp
Fixes https://github.com/lfortran/lfortran/issues/5563
The fix does the same as other passes do, it makes sure to add the statements pushed in `Vec<ASR::stmt_t*> pass_result` in the appropriate body once we make a nested call that will overwrite the `pass_result` as it's shared by all visitors in the class.
> Fix : Flush pass_result into the body if we'll overwrite it in `subroutine_from_function_simplifier`.

- integration_tests/CMakeLists.txt
- src/libasr/pass/do_loops.cpp
As Do_loop only contains one head we need to convert the multiple_headed DoConcurrentLoops to nested Do_loops , if not using `--openmp` flag 
As pointed out here in [comment](https://github.com/lfortran/lfortran/pull/5582#issuecomment-2518550810)
> fix: Handling of multiple_heads in DoLoopVisitor

- integration_tests/CMakeLists.txt
- integration_tests/functions_28.f90
- src/libasr/pass/pass_array_by_data.cpp
1. Set the `m_old` parameter to the new physical type of the array.
2. Set the dimensions to the array dimensions if necessary.
Creates valid ASR instead of wrong type being passed.
Fixes #5521
> Fix `ArrayPhysicalCast` in `pass_array_by_data` pass

- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/lfortran/fortran_evaluator.h
- src/libasr/codegen/evaluator.cpp
- src/libasr/codegen/evaluator.h
Changes in this PR:
- Simplify the code for handling the MLIR
- Add a new member function `llvm_str` in MLIRModule
- Add a new option `--show-mlir-to-llvm`
> feat: Add an option to print LLVM using the generated MLIR

- integration_tests/CMakeLists.txt
- integration_tests/operator_overloading_07.f90
- src/libasr/pass/pass_utils.h
- src/libasr/pass/subroutine_from_function.cpp
- src/libasr/pass/subroutine_from_function_simplifier.cpp
- tests/reference/llvm-derived_types_32-4684b97.json
- tests/reference/llvm-derived_types_32-4684b97.stdout
- tests/reference/llvm-modules_38-8886f9a.json
- tests/reference/llvm-modules_38-8886f9a.stdout
Towards #2257 (https://github.com/lfortran/lfortran/issues/2257#issuecomment-2041693935) + towards finalization
This handles the descriptorStrings `(character(:), alloctable :: str)` to transform the following code :
```fortran 
program p
print *, func_str()    
contains 
function func_str() result(ret_str)
character(:), allocatable :: ret_str
end function
end program  
```
to 
```fortran
! Fortran code after applying the pass: insert_deallocate
program p
implicit none
character(len=:, kind=1), allocatable :: __libasr__created__var__0__func_call_res
call func_str(__libasr__created__var__0__func_call_res)
print *, __libasr__created__var__0__func_call_res
deallocate(__libasr__created__var__0__func_call_res) ! Implicit deallocate
contains
subroutine func_str(ret_str)
character(len=:, …
```
> enh : Get subroutine_from_function pass to handle strings (right owner)

- .github/workflows/CI.yml
This PR aims to address the comment left here: https://github.com/lfortran/lfortran/pull/5616#pullrequestreview-2486852946
> CMake: Do not use CMAKE_VERBOSE_MAKEFILE in CI.yml

- integration_tests/procedure_07.f90
- integration_tests/procedure_08.f90
- src/libasr/pass/pass_array_by_data.cpp
Towards #4397
Previously function Variable was only updating when call is made but now it updates when we declare `procedure(cb) :: call_back`.
> enh: udpate function variable when `m_type_declaration` is updated

- integration_tests/CMakeLists.txt
- integration_tests/array_indices_array_item_assignment.f90
- src/libasr/pass/array_op.cpp
- try.f90
Towards #5516 
Tries to make assignment with Array Item as Array reference.
MRE 
```
program array_indices_array_item_assignment 
integer :: A(3) = [1,2,3]
integer :: X(2) = [1,2]
integer :: Y = 2
A(X) = Y
print * , A
end program
```
LFortran result
```
(lf) lordansh@LordAnsh:~/dev/lfort3/lfortran$ ./src/bin/lfortran try.f90
2    2    3
```
Still Array Section (like A(X(:)) = Y ) is not addressed in this PR , which I will address in subsequent PR.
> Handling Assignment for Array with Array Argument to represent Array index

- src/libasr/lsp.cpp
- tests/lookup_name2.f90
- tests/reference/lookup_name-lookup_name2-458b8c9.json
- tests/reference/lookup_name-lookup_name2-458b8c9.stdout
- tests/tests.toml
Migrates the corresponding logic from lfortran-lsp to here: https://github.com/lfortran/lfortran-lsp/pull/31
> Adds support for looking up symbols from just right of their word boundaries

- integration_tests/CMakeLists.txt
- integration_tests/array_indices_array_section_assignment.f90
- src/libasr/pass/array_op.cpp
Fixes #5516 
Enables Assignment with ArraySection as Array Reference.
MRE 1 :- 
```
program test 
integer :: A(3) = [1,2,3]
integer :: X(2) = [1,2]
integer :: Y = 2
A(X(:)) = Y
print * , A
end program
```
LFortran output :- 
```
(lf) lordansh@LordAnsh:~/dev/lfort3/lfortran$ ./src/bin/lfortran try.f90
2    2    3
```
MRE 2 :-
```
program test 
integer :: A(4) = [1,2,3,4]
integer :: X(3) = [1,2,3]
integer :: Y = 0
A(X(1:2)) = Y
print * , A
end program
```
LFortran output :- 
```
(lf) lordansh@LordAnsh:~/dev/lfort3/lfortran$ ./src/bin/lfortran try.f90
0    0    3    4
```
> Handling Assignment for Array having Array Section for Array Indexing

- integration_tests/CMakeLists.txt
- integration_tests/external_10.f90
- src/libasr/asr_utils.cpp
Fixes https://github.com/lfortran/lfortran/issues/5294
The program linked in the issue (or the one added as a test case in this PR) already works without any use of `--implicit-interface` (and it's expected to work), but this PR focuses on making that program work with use of `--implicit-interface` as well, as *POT3D* needs `--implicit-interface` flag necessarily.
Currently the MRE in the linked issue when run with `--implicit-interface` on the current-main raises the below error:
```console
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.
--> /Users/gxyd/OpenSource/lfortran/test.f90:3:16
|
3 |     integer :: g = 2
|                ^^^^^ failed here
ASR verify pass error: Var::m_v `g` cannot point outside of its symbol table
--> …
```
> chore: don't call replacer on ExternalSymbol with the same underling symbol

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/continue_compilation_3.f90
- tests/reference/asr-continue_compilation_3-435a232.json
- tests/reference/asr-continue_compilation_3-435a232.stderr
I think this should fix https://github.com/lfortran/lfortran-lsp/issues/21
> rem: unnecessary granular catch at `visit_Name`

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_330.f90
- src/lfortran/semantics/ast_common_visitor.h
Fixes: https://github.com/lfortran/lfortran/issues/5643
> fix: handle more than 2 args for amax0 and max1

- .github/workflows/CI.yml
The third party repository [predsci/POT3D](https://github.com/predsci/POT3D), which is being tracked at the issue: https://github.com/lfortran/lfortran/issues/2862, now compiles to ASR with LFortran.
This PR ensures that we test it at the CI now.
> ci: setup POT3D ci

- src/lfortran/parser/semantics.h
- tests/errors/continue_compilation_2.f90
- tests/reference/asr-continue_compilation_2-a6145a1.json
- tests/reference/asr-continue_compilation_2-a6145a1.stderr
I was trying a small POC to get the following file working using continue-compilation flag that had declaration statement. And this is what I discovered. 
File integer16.f90
```
cat integer16.f90
program integer16
integer*16 x
end
```
Following is the behaviour after this fix.
```
lfortran integer16.f90 --continue-compilation --show-ast
syntax error: kind 16 is not supported yet.
--> integer16.f90:2:2
|
2 |  integer*16 x
|  ^^^^^^^^^^ 
Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
(TranslationUnit
[(Program
integer16
()
[]
[]
[(Declaration
(AttrType
TypeInteger
[(()
16
Value)]
()
()
None
)
[]
[(x
[]
[]
()
()
None
())]
()
)]
[]
[]
)]
)
```
Current behaviour (latest main)
```
lfortran integer16.f90 --continue-compilation …
```
> feat: add parser errors in diagnostics

- doc/src/installation.md
Provide better build instructions in debug mode, following a few repeated questions here:
* https://lfortran.zulipchat.com/#narrow/channel/197339-General/topic/Issue.20.235292
* https://lfortran.zulipchat.com/#narrow/channel/197339-General/topic/issue.20.235604
I haven't made any changes to documenting building in *release mode* to guide towards using `ninja` instead of using `make`, as I'm not really sure if we want to do that or not.
> doc: provide better build instructions in debug mode

- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/continue_compilation_3.f90
- tests/reference/asr-continue_compilation_3-435a232.json
- tests/reference/asr-continue_compilation_3-435a232.stderr
While experimenting on examples with error resiliency, I found:
```fortran
program main
integer :: xy
xy(1) = 1
end program
```
Not working with `--continue-compilation` and `xy` being treated as `statement` function. This PR strengthens the logic for checking `statement` function, and makes the example error resilient.
> fix: `is_statement_function` to not consider scalar constants arguments

- .github/workflows/CI.yml
Now as the issue: https://github.com/lfortran/lfortran/issues/5639 is fixed, I've removed the commit in this branch and added another commit pertaining to updating `mpi.f90` to use interface instead of assumed-rank arrays.
> CI: update branch and commit to use for 'Test POT3D' CI job

- integration_tests/procedure_08.f90
- src/libasr/codegen/asr_to_llvm.cpp
Fixes #5603 
Refer https://github.com/lfortran/lfortran/issues/5603#issuecomment-2525200055.
> Fix: Use Var name in SubCall instead type_decl name

- integration_tests/intrinsics_331.f90
- src/libasr/asr_utils.h
- src/libasr/pass/intrinsic_array_function_registry.h
- src/libasr/pass/simplifier.cpp
Fixes https://github.com/lfortran/lfortran/issues/5689
Currently in *main*, the ttype for allocatable `return_type` of cshift looks like:
```clj
(Allocatable
(Allocatable
(Array
(Real 4)
[(()
())]
DescriptorArray
)
)
)
```
With this branch, that is fixed:
```clj
(Allocatable
(Array
(Real 4)
[(()
())]
DescriptorArray
)
)
```
There are few more things which need to be done:
* fixes in `cshift`, currently the code for `cshift` has a lot of bugs, like the `n_dims` calculation etc. (I'll open issues and fix them separately)
* asr_verify check can be used for `Allocatable` ttype to ensure that there is no underlying `Allocatable` ttype right under that, will create a separate PR for it, might reveal other issues as well
> fix: get_past_allocatable for return_type in cshift intrinsic

- .github/workflows/CI.yml
I am opening this PR to make experimental simplifier default. If the tests pass here (especially third party tests) then I will add a `--no-experimental-simplifier` flag to use the older LFortran.
https://github.com/lfortran/lfortran/issues/5717
> CI: Enhance testing of third party codes with `--experimental-simplifier`

- Dockerfile
The CI job *build-and-push-image* seems to be failing again, yesterday the fix was made here https://github.com/lfortran/lfortran/pull/5704 and merged.
with this PR I attempt to see if reverting that change fix it now or not. This reverts commit 2f3fe4c0a1cebbed4faca30100b790fdf51c1af9.
> CI: Revert "[CI] Fix the command to initialize SHELL for mamba"

- Dockerfile
This is an attempt to fix the version of miniforge to use and hence the version of mamba installed to make sure that we don't get CI failure of *build-and-push* CI job, like we got in https://github.com/lfortran/lfortran/pull/5730.
I'll first check to see if the tests pass or not
> CI: fix version of miniforge in Dockerfile

- CMakeLists.txt
Add support for build caching using `ccache`. 
We do not want to add `ccache` as a project dependency, so we do not build with it by default. The developer can install `ccache` on their own to do a cached build, with this PR we only enable them to do so.
See https://github.com/lfortran/lfortran/pull/5423#issuecomment-2489109206.
> build: add support for cached building using `ccache` through a CMake option

- CMakeLists.txt
- build0.sh
This was extracted from #4183.
I benchmarked the speed of compilation, didn't notice any slowdown.
> Properly detect re2c and bison when building under LFORTRAN_BUILD_ALL

- .github/workflows/CI.yml
There are two main workarounds which have been made use of in this:
* First is https://github.com/gxyd/POT3D/commit/4a85416220bfe18150b4a0d76d747b1bfbfd0ffa, the issue for this is already reported here: https://github.com/lfortran/lfortran/issues/5709, we'll try to fix this as well soon
* second is: https://github.com/gxyd/POT3D/commit/db7edd3a493ae4650c1942f257a60dd29958b6c1, uncommenting all calls to write subroutines for HDF5 format, we should be able to fix this well, I'll report an issue for this soon.
> CI: Test POT3D with LLVM backend with a few workarounds

- integration_tests/CMakeLists.txt
- integration_tests/automatic_allocation_01.f90
- src/bin/lfortran.cpp
As seen in https://wg5-fortran.org/N2201-N2250/N2212.pdf.
'The new features of Fortran 2023' paper linked above talks about the introduction of automatic allocation of character variables but GFortran seems to support this for all variables.
> enh: add support for automatic allocation for `allocatable` with `--std=f23`

- integration_tests/CMakeLists.txt
- integration_tests/class_procedure_args_01.f90
- src/libasr/codegen/asr_to_llvm.cpp
> enh: add support for handling `ASR::ClassProcedure_t` for functions with string parameters

- .github/workflows/CI.yml
the new workaround (see: https://github.com/gxyd/POT3D/commit/fe44c91df5d96856b87dc5df92ce0818948155ea) now uses `FLUSH` as a statement instead of as an intrinsic
the older workaround (see: https://github.com/gxyd/POT3D/commit/4a85416220bfe18150b4a0d76d747b1bfbfd0ffa) which just commented out `call FLUSH(...)`
> CI: update branch and commit for 'Test POT3D' testing

- integration_tests/CMakeLists.txt
- integration_tests/arrays_70.f90
- src/libasr/pass/array_op.cpp
fixes #5656 
MRE :- 
```
program test
integer :: A(4) = [1,2,3,4]
call temp(A)
print *, A
contains
subroutine temp(A)
integer, intent(inout) :: A(:)
A([1,2]) = A([2,1])
end subroutine
end program
```
LFortran Output :- 
```
(lf) lordansh@LordAnsh:~/dev/lfort4/lfortran$ ./src/bin/lfortran try.f90 
2    1    3    4
```
Fortran Code after array_op pass :- 
```
! Fortran code after applying the pass: array_op
program test
implicit none
integer(4) :: __1_k
integer(4), dimension(4), save :: a
__1_k = lbound(a, 1)
a(__1_k) = 1
__1_k = __1_k + 1
a(__1_k) = 2
__1_k = __1_k + 1
a(__1_k) = 3
__1_k = __1_k + 1
a(__1_k) = 4
__1_k = __1_k + 1
call temp(a)
print *, a
contains
subroutine temp(a)
integer(4) :: __1_k
integer(4) :: __1_k1
integer(4) :: __1_k2
integer(4), dimension(2) :: …
```
> fix : Handling Array Asignment in subroutine where Array referrence is Array Constant in both LHS and RHS

- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/reference/asr-private2-d3a4771.json
- tests/reference/asr-private2-d3a4771.stderr
- tests/reference/asr_json-modules_10-93cd62d.json
- tests/reference/asr_json-modules_10-93cd62d.stdout
Fixes #5802.
```console
$ cat a.f90                                      
module A
implicit none
integer :: x
contains
subroutine f(b)
integer, intent(in) :: b
print *, b
end subroutine
end module
$ cat expr2.f90 
program expr2
use A, only: x, f
implicit none
x = (2+3)*5
print *, x
call f(x)
end program
$ lfortran -c a.f90
% lfortran expr2.f90 --show-document-symbols | jq             
[
{
"kind": 2,
"location": {
"range": {
"start": {
"character": 1,
"line": 0
},
"end": {
"character": 10,
"line": 12
}
},
"uri": "uri"
},
"name": "a",
"filename": "a.f90"
},
{
"kind": 12,
"location": {
"range": {
"start": {
"character": 5,
"line": 7
},
"end": {
"character": 18,
"line": 10
}
},
"uri": "uri"
},
"name": "f",
"filename": "a.f90"
},
{
"kind": 13,
"location": {
"range": {
"start": {
"character": …
```
> fix: incorrect location information of `ExternalSymbol`

- integration_tests/CMakeLists.txt
- integration_tests/file_23.f90
- integration_tests/file_23_data.txt
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_utils.cpp
- src/libasr/codegen/llvm_utils.h
- src/runtime/custom/lfortran_intrinsic_custom.f90
fixes https://github.com/lfortran/lfortran/issues/5728
> Fix : use any variable as unit, not just `ASR::Var` + support different kinds integers to be used as unit arg.

- integration_tests/CMakeLists.txt
- integration_tests/loop_var_use_after_loop.f90
- src/libasr/pass/pass_utils.cpp
- tests/reference/pass_do_loops-loop_var_use_after_loop-e26183c.json
- tests/reference/pass_do_loops-loop_var_use_after_loop-e26183c.stdout
- tests/tests.toml
fixes #5761 
When breaking from the loop, we decrement the loop variable by the loop increment value, so when we break out of loop, the default increment by `--use-loop-variable-after-loop` fixes the value.
> fix: decrement loop variable to retain correct value when using loop variable after loop

- src/lfortran/parser/semantics.h
- tests/errors/continue_compilation_2.f90
- tests/reference/asr-continue_compilation_2-a6145a1.json
- tests/reference/asr-continue_compilation_2-a6145a1.stderr
> fix: End function name mismatch with function name generates ast with cc

- .github/workflows/CI.yml
- integration_tests/CMakeLists.txt
- integration_tests/where_15.f90
- src/libasr/pass/simplifier.cpp
Let's see if PRIMA compiles and runs. If so, then I will make simplifier default in the next PR.
> Fix for simplification of `Where`

- src/lfortran/parser/semantics.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/errors/continue_compilation_1.f90
- tests/errors/continue_compilation_2.f90
- tests/reference/asr-continue_compilation_1-04b6d40.json
- tests/reference/asr-continue_compilation_1-04b6d40.stderr
- tests/reference/asr-continue_compilation_2-a6145a1.json
- tests/reference/asr-continue_compilation_2-a6145a1.stderr
> fix: bad_implicit typing generates ast and asr with cc flag

- integration_tests/arrays_71.f90
- src/libasr/pass/implied_do_loops.cpp
- src/libasr/pass/pass_utils.cpp
- src/libasr/pass/pass_utils.h
Transforms : 
```fortran
y2 = [z, x2(1:2,[1,2])]
```
To : 
```fortran
itr = lbound(y2, 1)
y2(itr) = z
itr = itr + 1
do i = lbound(arr_const, 1), ubound(arr_const, 1)
do j = 1, 2, 1
y2(itr) = x2(j, arr_const(i)) 
itr = itr + 1
end do
end do
```
> feat: Support `ArraySection` with array indices inside `ArrayConstructor`

- integration_tests/CMakeLists.txt
- src/libasr/codegen/asr_to_fortran.cpp
This PR adds a Nullify visitor in the fortran backend
```fortran
 aditya-trivedi   lfortran    fortran ≢    cat ./integration_tests/nullify_02.f90 
program nullify_02
implicit none
real, pointer :: p1
real, target :: t1 
integer, pointer :: p2
integer, target :: t2
p1=>t1
p1 = 1
p2=>t2
p2 = 2.
nullify(p1, p2) 
end program nullify_02
 aditya-trivedi   lfortran    fortran ≢    lfortran ./integration_tests/nullify_02.f90 --show-fortran --show-stacktrace
program nullify_02
implicit none
real(4), pointer :: p1
integer(4), pointer :: p2
real(4) :: t1
integer(4) :: t2
p1 => t1
p1 = real(1, kind=4)
p2 => t2
p2 = int(2.00000000e+00, kind=4)
nullify (p1, p2)
end program nullify_02
 aditya-trivedi   lfortran    fortran ≢   
```
> enh:Fortran Backend: Nullify Visitor

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_334.f90
- src/libasr/pass/intrinsic_functions.h
fixes #5634
I think `move_alloc` should be handled as a standalone ASR node, as we can't move the array pointer using ASR statements; It should be handled by the backend explicitly for efficiency.
> fix : don't use allocatable return in `move_alloc` intrinsic.

- src/libasr/asdl_cpp.py
- src/libasr/asr_lookup_name.h
- tests/lookup_name3.f90
- tests/reference/lookup_name-lookup_name3-a06a374.json
- tests/reference/lookup_name-lookup_name3-a06a374.stdout
- tests/tests.toml
Fixes #5829. Although it introduces a regression where `Go To Definition` of `procedure` takes us to variable declaration and not `Function` itself.
> fix: missing location information of variables

- .github/workflows/CI.yml
- CMakeLists.txt
- integration_tests/CMakeLists.txt
- integration_tests/run_tests.py
- src/libasr/codegen/asr_to_mlir.cpp
- src/libasr/pass/do_loops.cpp
Implementation details:
- Use OpenMPDialect (to use MLIR OpenMP dialect) and
OpenMPToLLVMIRTranslation (to transform OpenMP dialect
to LLVM IR)
- Convert DoConcurrentLoop into OpenMP Parallel construct
> [MLIR][OpenMP] Replace DoConcurrentLoop with Parallel construct

- .well-known/funding-manifest-urls
Remove `www` subdomain from URL.
> chore: update funding manifest URL

- integration_tests/CMakeLists.txt
- integration_tests/use_02.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- tests/reference/asr-derived_types_11-c169ea7.json
- tests/reference/asr-derived_types_11-c169ea7.stdout
- tests/reference/asr-modules_31-cd9bfef.json
- tests/reference/asr-modules_31-cd9bfef.stdout
- tests/reference/asr-select_type_04-e8b402f.json
- tests/reference/asr-select_type_04-e8b402f.stdout
- tests/reference/asr-use_02-fe85e54.json
- tests/reference/asr-use_02-fe85e54.stdout
- tests/tests.toml
fixes #5870 
Using `m_original_name` causes incorrect variable names for aliases.
> fix (AST -> ASR): import `ExternalSymbol` with `m_name` instead of `m_original_name`

- .github/workflows/CI.yml
- CMakeLists.txt
- src/libasr/codegen/asr_to_mlir.cpp
- src/libasr/codegen/evaluator.cpp
Fixes: https://github.com/lfortran/lfortran/issues/5863
Issues fixed:
- LLVMPointerType::get(<mlir::Type>) => LLVMPointerType::get(*context)
- We need to specify the element_type for LoadOp, AllocaOp, GEPOp
- addEntryBlock requires builderOp as argument
- Register BuiltinDialectTranslation to fix the error:
"cannot be converted to LLVM IR: missing `LLVMTranslationDialectInterface`
registration for dialect for op: builtin.module"
> [MLIR] Support building with MLIR 19

- integration_tests/intrinsics_218.f90
- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/pass/intrinsic_functions.h
- tests/reference/asr-intrinsics_33-816caef.json
- tests/reference/asr-intrinsics_33-816caef.stdout
> fix: use 1 as length of newline character in `new_line()` intrinsic

- integration_tests/procedure_08.f90
- src/libasr/codegen/asr_to_llvm.cpp
> fix: Use variable in Subroutinecall instead its `m_type_declaration` and create load when function variable is local

- integration_tests/intrinsics_16.f90
- integration_tests/logical_not_01.f90
- src/libasr/pass/array_op_simplifier.cpp
- src/libasr/pass/intrinsic_functions.h
- src/libasr/pass/simplifier.cpp
Closes https://github.com/lfortran/lfortran/issues/5836
`./tests/atom_U/F_atom_U  0.76s user 0.01s system 99% cpu 0.774 total` (this PR)
`./tests/atom_U/F_atom_U  0.83s user 0.02s system 99% cpu 0.847 total` (with `--no-experimental-simplifier`)
Let's see what happens with tests. :D. Will rewrite git history before merging.
> Speed up `dftatom` execution time

- integration_tests/CMakeLists.txt
- integration_tests/pass_array_by_data_09.f90
- src/libasr/pass/pass_array_by_data.cpp
> fix :Visit internals of the symbol instead of passing it if it's identified as classProcedure

- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
https://github.com/lfortran/lfortran/issues/5890
The problem was this below line,
https://github.com/lfortran/lfortran/blob/c219981e5502807afab4ab963b11b7171516176f/src/lfortran/semantics/ast_common_visitor.h#L7333
The above line is executed inside a loop (which is of size `65535`). So in each iteration the `visitor` object gets created and destroyed leading to slow down. I moved the class out, and the `visitor` object creation out of the loop. Then it speeds up.
On my system,
**Before**
`lfortran ../debug.f90 -o a.out  12.52s user 0.24s system 100% cpu 12.745 total`
**After**
`lfortran ../debug.f90 -o a.out  0.37s user 0.11s system 86% cpu 0.557 total`
**Code**
```fortran
program compile_time
implicit none
integer, parameter :: N = 65535
integer, parameter :: sp = kind(1.0)
integer, …
```
> Speeding up compile time evaluation of ImpliedDoLoop

- integration_tests/CMakeLists.txt
- integration_tests/attr_intrinsic.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/lfortran/semantics/ast_to_asr.cpp
earlier 'intrinsic' attribute had almost no effect in ASR creation, this PR makes sure that a declaration like 'intrinsic abs' uses the intrinsic procedure 'abs' even in case of an existing declaration of variable 'abs'
Fixes #5857
> fix: 'intrinsic' attribute refers to intrinsic procedure

- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
The rest of the slowness was due to, 
https://github.com/lfortran/lfortran/blob/9465ce08a8263f65fbbdccbd16a43b031ff77606/src/lfortran/semantics/ast_common_visitor.h#L269
https://github.com/lfortran/lfortran/blob/9465ce08a8263f65fbbdccbd16a43b031ff77606/src/lfortran/semantics/ast_common_visitor.h#L243-L247
It queries a map. So I optimised the map to the most. We can't comment out the above line out (we need it). So this is the best that I could get.
```fortran
program compile_time
implicit none
integer, parameter :: N = 10000000
integer, parameter :: sp = kind(1.0)
integer, parameter :: dp = kind(1.d0)
real(dp), parameter :: pi = 2*asin(1._dp)
real(dp), parameter :: a = 0, b = pi
real(dp), parameter :: dx = (b-a)/N
integer :: i
real(dp), parameter :: X(*) = [(sin(a+(b-a)*i/N), i = 1, N)] …
```
> Speed up compile time evaluation of ImpliedDoLoop

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_337.f90
- src/lfortran/semantics/ast_common_visitor.h
> enh: handling of 'dble', 'float', 'dfloat', 'shifta' as intrinsics

- integration_tests/CMakeLists.txt
- integration_tests/arrays_reshape_19.f90
- src/lfortran/semantics/ast_common_visitor.h
> Fix : Set arrayPhysicalType of Array constructor to desciptorArray when any arg doesn't have compile time size

- integration_tests/CMakeLists.txt
- integration_tests/functions_29.f90
- src/libasr/asr_utils.h
- tests/reference/asr-implicit_interface_allocatable_array-38d4afe.json
- tests/reference/asr-implicit_interface_allocatable_array-38d4afe.stdout
fixes #5933
Looking at the `asr_verify` code for `Allocatable_t` with the `simplifier` pass, we see that it requires an `allocatable` type to have a deferred length to work. This is the required behavior also, but for `ArrayPhysicalCast`, we were setting the `ttype` wrapped inside `Allocatable_t` causing issues. As it turns out, the implementation before the `simplifier` pass had handled this with `Allocatable_t`, but `simplifier` pass is stricter in this regard.
> fix: set `ArrayPhysicalCast` type correctly when passing an `allocatable`  array as argument to a fixed-size array

- integration_tests/CMakeLists.txt
we probably forgot to uncomment these test cases, this probably should've been done once we used label *ONLY_EXPERIMENTAL_SIMPLIFIER*
> tests: uncomments tests and remove TODO

- integration_tests/CMakeLists.txt
- integration_tests/flush_02.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/runtime/lfortran_intrinsics.c
- tests/errors/continue_compilation_1.f90
- tests/flush2.f90
- tests/reference/asr-continue_compilation_1-04b6d40.json
- tests/reference/asr-continue_compilation_1-04b6d40.stderr
- tests/reference/asr-flush2-9767ece.json
- tests/reference/asr-flush2-9767ece.stderr
- tests/reference/asr-flush2-9767ece.stdout
- tests/tests.toml
'FLUSH' intrinsic and 'FLUSH' statement have identifical effect. Other compilers ifx, ifort, gfortran support 'FLUSH' intrinsic as well
We raise a warning to encourage users to use 'FLUSH' statement instead of 'FLUSH' intrinsic.
Fixes https://github.com/lfortran/lfortran/issues/5709
> chore: convert 'FLUSH' intrinsic to 'FLUSH' statement

- .github/workflows/CI.yml
With this, 
**Examples giving exact same output as Gfortran** : 
-->`bobyqa_example_1`
-->`newuoa_example_1`
**Examples very close to Gfortran output (maybe precision bug because of more iterations)** : 
-->`bobyqa_example_2`
-->`newuoa_example_2`
> CI: update CI for `bobyqa_example_2`

- .github/workflows/CI.yml
With this, 
**Examples giving exact same output as Gfortran** : 
-->`bobyqa_example_1`
-->`newuoa_example_1`
-->`uobyqa_example_1`
**Examples very close to Gfortran output (maybe precision bug because of more iterations)** : 
-->`bobyqa_example_2`
-->`newuoa_example_2`
-->`uobyqa_example_2`
> CI: Update PRIMA CI for `uobyqa_example_1` and `uobyqa_example_2`

- src/libasr/asr_utils.h
The duplication of `ASR::stmt_t` nodes like `ASR::Assignment_t` was done incorrectly before causing expressions like `ASR::Var_t` to point to the original scope. We fix it using scoped duplication. Rest of the change is cleanup due to the use of new method.
> refactor: perform scoped duplication of function body and arguments while duplicating `ASR::Function_t`

- .github/workflows/CI.yml
- src/libasr/runtime/lfortran_intrinsics.c
> fix: allocate space for null terminator in string allocations

- integration_tests/CMakeLists.txt
- integration_tests/elemental_11.f90
Towards #3204 
- Add a test for a elemental function with array parameter as `[ 1.0, 2.0, 3.0 ]` and scalar parameter as `1.0`.
> test: add test for elemental function for 1D array

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/continue_compilation_1.f90
- tests/reference/asr-continue_compilation_1-04b6d40.json
- tests/reference/asr-continue_compilation_1-04b6d40.stderr
- tests/reference/asr-continue_compilation_2-a6145a1.json
- tests/reference/asr-continue_compilation_2-a6145a1.stderr
- tests/reference/asr-int_01-9bf3eb9.json
- tests/reference/asr-int_01-9bf3eb9.stderr
- tests/reference/asr-kind_01-6c675be.json
- tests/reference/asr-kind_01-6c675be.stderr
Fixes: https://github.com/lfortran/lfortran/issues/4379
Fixes: https://github.com/lfortran/lfortran/issues/5494
> fix: throw error for non scalar args in or/and/xor and non scalar kind arg

- integration_tests/CMakeLists.txt
- integration_tests/functions_30.f90
- src/libasr/pass/implied_do_loops.cpp
> fix: use fixed size ArrayConstructor directly instead of ArrayPhysicalCast

- integration_tests/CMakeLists.txt
- integration_tests/elemental_12.f90
Towards #3204 
- Add a test for a elemental function with array parameter as `[ [1.0, 2.0, 3.0], [4.0, 5.0, 6.0] ]` and scalar parameter as `1.0`.
> test: add test for elemental function for 2D array

- integration_tests/CMakeLists.txt
- integration_tests/arrays_77.f90
- src/libasr/pass/implied_do_loops.cpp
Fixes #5990 
MRE :- 
```
module a 
contains 
function f2() result(res)
integer(8), allocatable :: res(:)
allocate(res(10))
res = [1,2,3,4,5,6,7,8,9,10]
end function f2
end module a 
program prog
use a
integer :: i
integer :: arr(10)
integer,allocatable :: arr_res(:)
do i = 1 , 10
arr(i) = i+100
end do
allocate(arr_res(11))
arr_res = [arr(f2()),111] ! Error here
print *, arr_res
end program prog
```
LFortran Output :- 
```
(lf) lordansh@LordAnsh:~/dev/lfort1/lfortran$ lfortran try.f90
101
102
103
104
105
106
107
108
109
110
111
```
> fix : Handling ArrayItem in ArrayConstructor having Descriptor Array ttype

- integration_tests/CMakeLists.txt
- integration_tests/test_dshiftr.f90
- src/libasr/pass/intrinsic_functions.h
Fixes: #4002
- Change the `k_val` variable for different kind of integer as `k_val = kind * 8` to ensure it's correctness with gfortran results.
- Updated the `dshiftr` evaluation implementation.
> fix: implementation of `dshiftr` for different kind value

- src/libasr/pass/intrinsic_functions.h
- tests/errors/continue_compilation_1.f90
- tests/reference/asr-continue_compilation_1-04b6d40.json
- tests/reference/asr-continue_compilation_1-04b6d40.stderr
Fixes: #6044 
- Updates the implementation of `dshiftl` such that it gives correct error message
- Updates the error squiggle position for `dshiftr` and `dshiftl`
> fix: handling correct error message for `dshiftl` and `dshiftr`

- integration_tests/array_indices_array_item_assignment_2.f90
- src/libasr/pass/simplifier.cpp
> fix: replace arguments of `Arrayitem` first before creating temporary in `simplifier` pass

- .github/workflows/CI.yml
- integration_tests/CMakeLists.txt
- integration_tests/run_tests.py
- src/bin/lfortran.cpp
- src/lfortran/fortran_evaluator.cpp
- src/lfortran/fortran_evaluator.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/asr_to_mlir.cpp
- src/libasr/codegen/asr_to_mlir.h
- src/libasr/codegen/evaluator.cpp
- src/libasr/codegen/evaluator.h
- src/libasr/pass/openmp.cpp
- tests/reference/pass_openmp-do_concurrent_01-2a6df8c.json
- tests/reference/pass_openmp-do_concurrent_01-2a6df8c.stdout
Design details:
- OpenMP pass creates a module `_lcompilers_mlir_gpu_offloading`,
which has all the items required for GPU offloading. This module will
contain the functions with `abiType::BindC`, 
`deftypeType::Implementation`. MLIR backend will generate the 
required IR and object file.
- The user module will contain the interface function definition with 
`abiType::BindC`, `deftypeType::Interface`. We call this interface and
later link it with the correct BindC function. For these modules, LLVM
backend will generate the IR and object file
- Later, we link both the object files and created an executable.
> [LLVM] Use LLVM backend to generate IR for GPU offloading

- integration_tests/CMakeLists.txt
- integration_tests/arrays_08_size.f90
- src/libasr/codegen/asr_to_llvm.cpp
fix #6147 
MRE
```console
program arrays_08_size
integer :: y = 2
call temp(y)
contains
subroutine temp(x)
integer, intent(inout) :: x
logical :: keep(x)
integer :: result(x)
keep = [.false., .true.]
x = 1
result = trueloc(keep)
print * , result
end subroutine
function trueloc(x) result(loc)
logical, intent(in) :: x(:)
integer(4), allocatable :: loc(:)
integer :: i, j
allocate(loc(count(x)))
j = 1
do i = 1, size(x)
if( x(i) ) then
loc(j) = i
j = j + 1
end if
end do
end function trueloc
end program
```
LFortran output
```console
(lf) lordansh@LordAnsh:~/dev/lfort3/lfortran$ lfortran try.f90
2
0
```
> fix : Handling Array Size in Function call in Pass array by data using Deep copy

- src/lfortran/semantics/ast_common_visitor.h
- tests/errors/continue_compilation_1.f90
- tests/reference/asr-continue_compilation_1-04b6d40.json
- tests/reference/asr-continue_compilation_1-04b6d40.stderr
Fixes: #6158 
- Handles correct error squiggles and throwing error when provided source argument which is not a array
> throw correct error message for reshape intrinsic

- integration_tests/functions_32.f90
- src/libasr/asr_utils.h
- tests/reference/asr-template_04-f41dd3e.json
- tests/reference/asr-template_04-f41dd3e.stdout
- tests/reference/asr-template_array_05-ae2710a.json
- tests/reference/asr-template_array_05-ae2710a.stdout
- tests/reference/asr-template_matrix_01-65b17ae.json
- tests/reference/asr-template_matrix_01-65b17ae.stdout
Fixes #6205 
Removes : https://github.com/Pranavchiku/prima/commit/c79a877e98ffc6c9b9bd33d77ff5024e01d92716
Removes : https://github.com/Pranavchiku/prima/commit/99dbeb7fd7ee5e5635df08d3510bc41cf91437f9
> fix: consider only `intent(in)` scalar argument while creating dimension for temporary

- integration_tests/arrays_09_size.f90
- src/libasr/asr_scopes.h
- src/libasr/pass/function_call_in_declaration.cpp
Based on comments https://github.com/lfortran/lfortran/pull/6245#discussion_r1946370058 and https://github.com/lfortran/lfortran/pull/6235#discussion_r1946366072
> enh : Handle `get_global_scope` using this and change module name in test

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_356.f90
- integration_tests/intrinsics_357.f90
- src/libasr/pass/intrinsic_subroutines.h
> fix : Empty the dimensions of Array Argument passed in random_number function

- .github/workflows/CI.yml
Towards: #4703
- Set the CI to compile and test the `numerical-methods-fortran`
> CI: Test numerical-methods-fortran

- integration_tests/sign_from_value.f90
- src/libasr/pass/pass_utils.cpp
- src/libasr/pass/sign_from_value.cpp
- tests/reference/asr-sign_from_value-b974070.json
- tests/reference/asr-sign_from_value-b974070.stdout
- tests/reference/pass_sign_from_value-sign_from_value-ba1c944.json
- tests/reference/pass_sign_from_value-sign_from_value-ba1c944.stdout
This fix is towards getting PRIMA to compile with `--fast`
***
Example of one issue :
```.f90
program pp
implicit none
integer :: a, b, c
a = 2
b = -3
c = a*sign(1, b)
print *, c
end program pp
```
```console
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ gfortran tt5.f90 && ./a.out 
-2
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ gfortran tt5.f90 -O3 && ./a.out 
-2
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ 
```
LFortran before this PR
```Console
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ lfortran tt5.f90 --fast
-2147483646
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ lfortran tt5.f90 
-2
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ 
```
After
```Console
assem@assem-PC:~/Desktop/fortran/compile_gsnap$ lfortran tt5.f90 --fast
-2 …
```
> Fix : minor fixes in `sign_from_value` pass

- integration_tests/CMakeLists.txt
- integration_tests/arrays_reshape_20.f90
- src/lfortran/semantics/ast_common_visitor.h
Towards #6157 
Current Status:
> fix: taking order and pad arguments in the reshape intrinsic

- integration_tests/CMakeLists.txt
- integration_tests/nullify_05.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/codegen/asr_to_llvm.cpp
resolves #6215 
With the changes in this PR, we wrap `FunctionType` with `Pointer` for procedure pointers. I am not sure why, but the changes are causing unexpected failures. I cross-checked the changes here. I request a careful review from other developers.
If we find that the changes here are not right, a fix for this issue would be to allow procedure pointers in `nullify` as a special case, but this would also incorrectly allow non-pointer procedure variables.
> fix: support nullifying procedure pointer variables

- integration_tests/intrinsics_358.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
Fixes: https://github.com/lfortran/lfortran/issues/6291
> fix: find return_type from attribute only when return var is null

- .github/workflows/CI.yml
I think this will fail currently, even though we are running without comparison with the saved output file.
Locally, I initially got an error:
```console
dyld[94016]: Library not loaded: @rpath/libmpi.40.dylib
Referenced from: <9CECF745-6079-3DDC-8425-592ACBD39F46> /Users/gxyd/OpenSource/lfortran/pot3d/bin/pot3d
Reason: tried: '/Users/gxyd/OpenSource/lfortran/src/bin/../runtime/libmpi.40.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gxyd/OpenSource/lfortran/src/bin/../runtime/libmpi.40.dylib' (no such file), '/Users/gxyd/OpenSource/lfortran/src/bin/../runtime/libmpi.40.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gxyd/OpenSource/lfortran/src/bin/../runtime/libmpi.40.dylib' (no such file) …
```
> CI: run validation script for POT3D with MPI rank 1 & MPI rank 2

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_359.f90
- src/libasr/pass/intrinsic_array_function_registry.h
Fixes: https://github.com/lfortran/lfortran/issues/6313
> fix: handle compile time values correctly in `pack` intrinsic

- integration_tests/sign_from_value.f90
- src/libasr/pass/sign_from_value.cpp
- tests/reference/asr-sign_from_value-b974070.json
- tests/reference/asr-sign_from_value-b974070.stdout
- tests/reference/pass_sign_from_value-sign_from_value-ba1c944.json
- tests/reference/pass_sign_from_value-sign_from_value-ba1c944.stdout
It's utilizing the `BaseExprReplacer` class to efficiently replace `RealBinOp` expression.
> Refactor `Sign_from_value` pass

- .github/workflows/CI.yml
this now removes the workaround: https://github.com/gxyd/POT3D/commit/eef4fdafb6b94e814576b3a9cfb96b2129ec5616
> CI: update the checkout commit for POT3D repository

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_363.f90
- src/libasr/asr_utils.h
fixes: https://github.com/lfortran/lfortran/issues/6320
> enh: support intrinsic array functions in is_value_constant

- integration_tests/intrinsics_339.f90
- src/libasr/pass/intrinsic_array_function_registry.h
fixes: https://github.com/lfortran/lfortran/issues/6409
> fix: support scalar `mask` in minloc and maxloc

- .github/workflows/CI.yml
we've removed two workarounds, and link to commit reversals
* https://github.com/gxyd/POT3D/commit/0c8a7c652ebee393ed29ca973aa7a750e6038a9e use of 'contiguous' attribute in POT3D repo
* https://github.com/gxyd/POT3D/commit/02d74dcf8384f9c44b6dbcc809bd62800b87b75e bug in passing array section to a function call
> CI: update hash commit of *Test POT3D*

- integration_tests/CMakeLists.txt
- integration_tests/implicit_interface_18.f90
- src/libasr/asr_utils.cpp
Fixes #6460. 
It is just a minor check. Now it runs with `--implicit-interface`
> enh: frontend to support optional args with `--implicit-interface`

- integration_tests/CMakeLists.txt
- integration_tests/pass_array_by_data_11.f90
- src/libasr/pass/pass_array_by_data.cpp
> fix: only resolve procedure recursively when scope is different from current

- .github/workflows/CI.yml
With this we setup `6/8` plotting functions of `numerical-methods-fortran` on CI. Considering https://github.com/lfortran/lfortran/issues/4703#issuecomment-2700040746, I suspect Linux checks to fail.
> ci: setup `numerical-methods-fortran` plotting functions

- integration_tests/CMakeLists.txt
- integration_tests/class_14.f90
- src/lfortran/semantics/ast_common_visitor.h
fixes: https://github.com/lfortran/lfortran/issues/1693#issuecomment-2703157527
> fix: handle keyword arguments correctly for class procedure

- integration_tests/struct_allocate.f90
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-struct_allocate-606e066.json
- tests/reference/asr-struct_allocate-606e066.stdout
- tests/tests.toml
Addresses the comments for discussion here: https://github.com/lfortran/lfortran/pull/6434#issuecomment-2703743937
> fix: wrap StructInstanceMember with ArrayItem when in allocate

- integration_tests/CMakeLists.txt
- integration_tests/implicit_typing_04.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
fix : #6479
MRE :-  
```.f90
subroutine outer(x)
implicit real(kind=8) (a-h,o-z), integer(kind=4) (i-n)
contains
function inner()
implicit real(kind=8) (a-h,o-z), integer(kind=4) (i-n)
inner = 1
end function inner
end subroutine outer
```
Corrected ASR for x :- 
```.f90
x:
(Variable
2
x
[]
Unspecified
()
()
Default
(Real 8)
()
Source
Public
Required
.false.
.false.
.false.
)
```
> fix : Create copy for implicit dictionary before nesting

- .github/workflows/CI.yml
this branch has only five extra commits on top of the *main* branch (link to the branch: https://github.com/gxyd/POT3D/tree/hdf5_mpi_namelist_global_workaround)
1. 0739fea85f58ce390dff94688b5cff766f1b826e: HDF5 read
2. 2850c7e609f9f47d53707909245d529980099f46: MPI wrappers
3. 05f66a70bf568cba26e46835e05d4d98ba3b60e9: Namelist workaround
4. a0f0d0e6c4fe4b2375b9a08dcdfe0bd905e422c9: global procedure
5. bd1c773cf5f822ba0a7983797637ca70e521ffb8: adds scripts for building with LFortran & GFortran
> CI: use branch for POT3D with much simplier git history

- .github/workflows/CI.yml
Branch: https://github.com/gxyd/POT3D/tree/hdf5_mpi_namelist_global_deallocate_workaround_3 is where POT3D passes with GFortran's CI with and without optimization applied.
Hence, now we need to get LFortran pass on that same branch with and without fast optimizations applied.
> CI: test POT3D with fixes in MPI wrappers

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_368.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_utils.h
fixes: https://github.com/lfortran/lfortran/issues/1484
fixes: https://github.com/lfortran/lfortran/issues/6596
> fix: handle compile time output for transfer (BitCast) intrinsic and IntegerCompare

- src/bin/lfortran.cpp
- src/bin/lfortran_command_line_parser.cpp
- src/bin/lfortran_command_line_parser.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/pass_manager.h
- src/libasr/utils.h
Towards #6609.
```console
% lfortran examples/expr2.f90 --time-report
25
Time report:
Allocator usage of last chunk (MB): 0.004280
Allocator chunks: 1
File reading: 0 ms
Src -> ASR:  1 ms
Time taken by pass: 
global_stmts: 0.1 ms
init_expr: 0.22 ms
function_call_in_declaration: 0.8 ms
openmp: 0.1 ms
implied_do_loops: 0.19 ms
array_struct_temporary: 0.63 ms
nested_vars: 0.25 ms
transform_optional_argument_functions: 0.27 ms
forall: 0.5 ms
class_constructor: 0.13 ms
pass_list_expr: 0.10 ms
where: 0.7 ms
subroutine_from_function: 0.20 ms
array_op: 0.17 ms
symbolic: 0.7 ms
intrinsic_function: 0.22 ms
intrinsic_subroutine: 0.7 ms
array_op: 0.2 ms
pass_array_by_data: 0.30 ms
array_passed_in_function_call: 0.10 ms
print_struct_type: 0.5 ms
print_arr: 0.13 ms
print_list_tuple: 0.6 ms …
```
> enh: add time take by each pass and LLVM IR creation with `--time-report`

- src/lfortran/semantics/ast_common_visitor.h
`get_fixed_size_of_array()` and `get_fixed_size_of_ArraySection()` both return value of `-1` when they are unable to compute the size of the array. We should hence use an integer value to store the returned value (in order to be able to represent the `-1`). Otherwise, if we use `size_t` we end up with an array size of some large positive number. This later leads to accessing of incorrect/non-existent array value (we loop beyond the length of the array).
Note that the changes in this PR don't fix some issue. But rather they help avoid hitting above mentioned issues.  I don't think adding a test case is necessary for this, because
- the changes seem trivial
- figuring out a test case that hits this issue could be tricky. I stepped across this while debugging another issue.
> Add an ICE (Internal compiler error) message

- src/bin/lfortran.cpp
- src/libasr/pass/pass_manager.h
Towards #6609
```shell
% lfortran examples/expr2.f90 --time-report         
25
Component name                                     Time (ms)
------------------------------------------------------------
Allocator usage of last chunk (MB)                  0.004280
Allocator chunks                                           1
File reading                                               0
Src -> ASR                                                13
Time taken by pass
global_stmts                                     0.127
init_expr                                        2.1
function_call_in_declaration                     0.343
openmp                                           0.1
implied_do_loops                                 0.981
array_struct_temporary                           2.124 …
```
> enh: readability of time report by incorporating changes suggested

- integration_tests/c_ptr_02.f90
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-c_ptr_02-fce1b0e.json
- tests/reference/asr-c_ptr_02-fce1b0e.stdout
> fix: ignore case for `c_null_ptr` in Frontend

- src/bin/lfortran.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/pass_manager.h
Towards #6609.
```console
% lfortran examples/expr2.f90 --time-report
25
Allocator usage of last chunk (MB)                     0.004
Allocator chunks                                       1.000
------------------------------------------------------------
Component name                                     Time (ms)
------------------------------------------------------------
File reading                                           0.328
Src -> ASR                                            13.128
Time taken by pass
global_stmts                                       0.910
init_expr                                          0.792
function_call_in_declaration                       0.450
openmp                                             0.100
implied_do_loops …
```
> fix: indentation issue and align time output for `--time-report`

- integration_tests/CMakeLists.txt
- integration_tests/implicit_typing_06.f90
- src/lfortran/semantics/ast_common_visitor.h
fix #6017 
MRE :- 
```.f90
module mod_implicit_typing_06
implicit none
private
public a
integer, parameter :: a = 1
end module mod_implicit_typing_06
program implicit_typing_06 
use mod_implicit_typing_06
print *, a
end program
```
LFortran Output :- 
```console
(lf) lordansh@LordAnsh:~/dev/lfort4/lfortran$ lfortran try.f90 --std=f23
1
```
Generated ASR for a :- 
```.f90
a:
(Variable
2
a
[]
Local
(IntegerConstant 1 (Integer 4) Decimal)
(IntegerConstant 1 (Integer 4) Decimal)
Parameter
(Integer 4)
()
Source
Public
Required
.false.
.false.
.false.
)
```
> fix : use implicit_dictionary to declare implicit variable

- integration_tests/CMakeLists.txt
- integration_tests/equivalence_10.f90
- src/lfortran/semantics/ast_common_visitor.h
> fix: correct shape of 2nd array in equivalence

- src/libasr/pass/array_struct_temporary.cpp
- src/libasr/pass/intrinsic_array_function_registry.h
Towards #2524. It gives a huge boost for `fortran-primes` compilation as there are large arrays.
For Program: 
```fortran
module prime_constants
integer, parameter :: min_factor(4) = 1
end module
program test
use prime_constants
print *, pack(min_factor,min_factor>=1)
end program
```
**ASR Afer all passes:**
Without this PR:
```fortran
! Fortran code after applying the pass: insert_deallocate
module prime_constants
implicit none
integer(4), dimension(4), parameter :: min_factor = [1, 1, 1, 1]
end module prime_constants
program test
use prime_constants, only: min_factor
implicit none
integer(4) :: __libasr_created__intrinsic_array_function_Count
integer(4), dimension(4), parameter :: __libasr_created__intrinsic_array_function_Pack = [1, 1, 1, 1]
logical(4), dimension(4) :: …
```
> fix: don't create temporary for args of compile time intrinsic function

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_370.f90
- src/libasr/pass/intrinsic_array_function_registry.h
Towards: https://github.com/lfortran/lfortran/issues/6735
> fix: handle return_var correctly for `findloc` intrinsic

- integration_tests/CMakeLists.txt
- integration_tests/interface_18.f90
- src/lfortran/semantics/ast_body_visitor.cpp
> fix : Convert Variable to Function for implicit-interface only when m_type is not FunctionType

- integration_tests/CMakeLists.txt
- integration_tests/derived_types_45.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/insert_deallocate.cpp
Previous reverted PR: #6683 
Fix #1726 
Added a commit to keep track of allocated symbols in body visitor. So we only allocate if not already allocated.
> Implicitly allocate with StructConstructor 2

- .github/workflows/CI.yml
I've pushed a commit: https://github.com/gxyd/POT3D/commit/e2f2a2b6668e81f5d9f1441c20d64b8c7446aa6b to branch `lf_hdf5_mpi_namelist_global_workarounds`.
This is an important change, we definitely should've it in our CI. The linked commit ensures that when validation has failed, we exit with non-zero status.
I shouldn't have missed this change. We can possibly squash this commit with the commit prior to this on the same branch, we also would need to update the commit hash in the blog post as well (can't think of anywhere else though).
> CI: use the commit of pot3d branch which exits with non-zero status on validation failure

- integration_tests/CMakeLists.txt
- integration_tests/nested_vars3.f90
- src/libasr/pass/nested_vars.cpp
> fix: don't assign back `intent(in)` variables in nested_vars

- src/libasr/codegen/asr_to_c.cpp
- src/libasr/codegen/asr_to_cpp.cpp
LP still printed type names b4 the latest sync https://github.com/lcompilers/lpython/issues/2816 but we can't merge there since the sync is completed yet. I checked LF to see if this was already fixed. It was but there were still some 'Type number's left so i went ahead and removed those
Code in asr->c fixed to print type names but still has type number 
https://github.com/lfortran/lfortran/blob/4ffef1008bf6594e55457a2fb3c6f4af45008c97/src/libasr/codegen/asr_to_c.cpp#L389-L391
Similar code in asr->julia doesn't print type number
https://github.com/lfortran/lfortran/blob/4ffef1008bf6594e55457a2fb3c6f4af45008c97/src/libasr/codegen/asr_to_julia.cpp#L310-L313
> Minor fix for codegen type errors

- src/libasr/pass/array_struct_temporary.cpp
Fixes #6789 
Issue was from https://github.com/lfortran/lfortran/issues/6789#issuecomment-2772806937: 
```fortran
deallocate(__libasr_created_string_format)
allocate(__libasr_created_string_format)  
reallocate(__libasr_created_string_format(size(es(1)%ds, 1)))
```
Here due to first allocate ` __libasr_created_string_format` was interpreted as allocated and reallocate was not allocating to `__libasr_created_string_format`
> fix: remove redundant dealloc and alloc for struct temporary

- src/libasr/asr_utils.cpp
Address comment from https://github.com/lfortran/lfortran/pull/6869
> refactor: remove redundant nullptr check

- integration_tests/CMakeLists.txt
- integration_tests/derived_types_48.f90
- src/lfortran/semantics/ast_common_visitor.h
Fix https://github.com/lfortran/lfortran/issues/6833
> fix: use StructConstant inside derived type

- tests/server/tests/conftest.py
Adds missing check on existence of locally compiled lfortran.
Fixes #6906.
> Fixes issue #6906

- tests/server/tests/conftest.py
Passing `capfd` (capture stdout/stderr file descriptors) to the `client` fixture should prevent stderr leaks like those in https://github.com/lfortran/lfortran/issues/6907.
> Explicitly passes capfd fixture to client fixture to prevent stderr leaks

- ci/test_lsp.sh
- src/bin/lfortran_lsp_language_server.cpp
- src/bin/parallel_lfortran_lsp_language_server.cpp
- src/server/base_lsp_language_server.cpp
- src/server/base_lsp_language_server.h
- src/server/logger.cpp
- src/server/logger.h
- src/server/parallel_lsp_language_server.cpp
- src/server/tests/src/llanguage_test_client/lsp_test_client.py
Changes:
1. Adds initial telemetry event which is emitted approximately every 250ms
2. Maintains a histogram on running request and worker threads which is useful for detecting things like deadlocks
3. Fixes an occasional deadlock when the document is being validated while it is being changed
4. Re-enables the parallel tests in the CI on macos
> Adds running thread histogram to telemetry event and fixes occasional deadlock

- integration_tests/CMakeLists.txt
- integration_tests/intrinsics_373.f90
- src/libasr/asr_builder.h
- src/libasr/pass/intrinsic_array_function_registry.h
- src/libasr/pass/pass_manager.h
Closes https://github.com/lfortran/lfortran/issues/5418
Implemented https://github.com/lfortran/lfortran/issues/5418#issuecomment-2787424746 (quoted below),
There are two problems with implementation of spread intrinsic in LFortran,
> 1. The shape of resulting array is generated incorrectly (especially if the input is fixed size array) - The correct > way is, size of i-th dimension of resulting array would be defined as `merge(ncopies, merge(original_shape[i], > original_shape[merge(1, i - 1, i == 1)], i < dim), i == dim)`.
>
> 2. The implementation doesn't need a loop, we need to do,
> 
> ```
> do i = lbound(result, selected_dim), ubound(result, selected_dim)
>    result(..., :, :, :, i, :, :, :, ...) = a
> end do
> ```
> Simply copy paste the original array to the output array while …
> Update ``spread`` implementation to always produce correct results for any dimensions

- src/bin/lfortran_lsp_language_server.cpp
- src/bin/lfortran_lsp_language_server.h
- src/server/lsp_text_document.cpp
- src/server/lsp_text_document.h
- src/server/tests/src/llanguage_test_client/lsp_client.py
- src/server/tests/src/llanguage_test_client/lsp_test_client.py
- src/server/tests/src/llanguage_test_client/lsp_text_document.py
- tests/server/src/lfortran_language_server/lfortran_lsp_test_client.py
- tests/server/tests/test_features.py
Changes:
1. Adds initial implementation of `"textDocument/completion"`
2. Allows negative indices in `LspTextDocument.cursor` (testing framework)
3. Adds `LspTextDocument::symbolAt` to extract the symbol text at some location within the document
> Adds initial implementation of "textDocument/completion"

- src/bin/lfortran_lsp_language_server.cpp
- src/bin/lfortran_lsp_language_server.h
- src/server/lsp_text_document.cpp
- src/server/lsp_text_document.h
- src/server/tests/src/llanguage_test_client/lsp_client.py
- src/server/tests/src/llanguage_test_client/lsp_test_client.py
- src/server/tests/src/llanguage_test_client/lsp_text_document.py
- tests/server/src/lfortran_language_server/lfortran_lsp_test_client.py
- tests/server/tests/test_features.py
Changes:
1. Adds initial implementations of "textDocument/formatting" and "textDocument/rangeFormatting"
2. Adds a few utility methods to LspTextDocument
> Formats whole documents and selections

- doc/src/installation.md
I've taken steps from https://github.com/lcompilers/lpython/blob/afffb0606443377a9e1fb73889d90ca3ef248639/doc/src/installation.md?plain=1#L114-L156 and used them in LFortran's installation docs.
I've skipped from adding the section:
```
In case you have recently updated macOS, you may get a warning like below in some test cases:
```
Because I'm neither sure if that problem occurs or not and neither are the steps below it tested from my end, (e.g. in LFortran's repository there is no `./build.sh` script as mentioned in LPython's doc), so I've skipped from adding it. It's better to add well tested installation instructions than (possibly) incorrect ones.
> docs: add section for Testing in installation docs

- integration_tests/allocate_17.f90
- src/lfortran/semantics/ast_body_visitor.cpp
> fix: don't throw error if source shape is assumend

- integration_tests/CMakeLists.txt
- integration_tests/iso_c_binding_02.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
- tests/reference/asr-c_ptr_02-fce1b0e.json
- tests/reference/asr-c_ptr_02-fce1b0e.stdout
- tests/reference/asr_openmp-openmp_37-2c7ae83.json
- tests/reference/asr_openmp-openmp_37-2c7ae83.stdout
- tests/reference/asr_openmp-openmp_38-2731560.json
- tests/reference/asr_openmp-openmp_38-2731560.stdout
- tests/reference/asr_openmp-openmp_39-aaf2ba8.json
- tests/reference/asr_openmp-openmp_39-aaf2ba8.stdout
> enh: introduce `c_null_funptr` to intrinsic `iso_c_binding`

- .github/workflows/CI.yml
Towards #3382. To ensure that we do not lose any progress made in this front.
> ci: test `stdlib` with less workarounds

- integration_tests/CMakeLists.txt
- integration_tests/compiler_version_02.f90
- integration_tests/compiler_version_03.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/pass/intrinsic_function_registry.h
- src/runtime/pure/lfortran_intrinsic_iso_fortran_env.f90
- tests/reference/asr-submodule_02-9152b7b.json
- tests/reference/asr-submodule_02-9152b7b.stdout
- tests/reference/asr-use_02-fe85e54.json
- tests/reference/asr-use_02-fe85e54.stdout
Fixes #6981. Fixes #6731. Fixes #6553. Fixes #4928. Closes #4248.
> fix: import error for `compiler_version` from `iso_fortran_env`

- integration_tests/CMakeLists.txt
- integration_tests/derived_types_49.f90
- integration_tests/derived_types_50.f90
- src/libasr/codegen/llvm_utils.cpp
Fix https://github.com/lfortran/lfortran/issues/7031
Fix https://github.com/lfortran/lfortran/issues/7034
First 2 commits fix the extended derived types assignment.
Third commit skips `GenericProcedure` in deepcopy which fixes #7034
> fix: extended derived types assignment

- integration_tests/CMakeLists.txt
- integration_tests/allocate_18.f90
- integration_tests/automatic_allocation_02.f90
- integration_tests/automatic_allocation_03.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/llvm-automatic_allocation_02-2a7afc4.json
- tests/reference/llvm-automatic_allocation_02-2a7afc4.stdout
- tests/reference/llvm-derived_types_45-ae31b1c.json
- tests/reference/llvm-derived_types_45-ae31b1c.stdout
- tests/tests.toml
Add automatic allocation for allocatable `integer`, `real`, `complex` and `logical`.
> enh: lhs reallocation for intrinsic types

- integration_tests/file_28.f90
- src/libasr/codegen/asr_to_llvm.cpp
For unformatted write, in `_lfortran_file_write_` we pass data like `(int32_t size, void * data, ......)` 
Now for `write(u) 1,2,3`, we don't have pointer to these constant values, so I have made new pointers for them to maintain similarity.
I am not sure if this is correct solution or not.
> fix: pass pointer for constant also in `file_write`

- integration_tests/CMakeLists.txt
- integration_tests/functions_36.f90
- src/lfortran/semantics/ast_common_visitor.h
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/libasr/asr_utils.h
- src/libasr/asr_verify.cpp
- src/libasr/pass/pass_utils.h
- tests/reference/asr-string_17-29e01e3.json
- tests/reference/asr-string_17-29e01e3.stdout
- tests/reference/asr-string_19-d880475.json
- tests/reference/asr-string_19-d880475.stdout
Fixes https://github.com/lfortran/lfortran/issues/7066
> Fix : [GenericProcedure] Build the symbolTable is this order (Functions -> GenericProcedures -> Variables depending on calls to genericProcedures)

- src/lfortran/semantics/ast_body_visitor.cpp
- src/lfortran/semantics/ast_common_visitor.h
- src/libasr/asr_verify.cpp
- tests/errors/incorrect_allocate_for_array.f90
- tests/reference/asr-incorrect_allocate_for_array-b52ea30.json
- tests/reference/asr-incorrect_allocate_for_array-b52ea30.stderr
- tests/tests.toml
Closes https://github.com/lfortran/lfortran/issues/6823
> Raise `SemanticError` in `allocate` if array has no dimensions specified

- tests/reference/asr-continue_compilation_ff_1-c2d5950.json
- tests/reference/asr-continue_compilation_ff_1-c2d5950.stdout
This fixes failing CI in our *main* as of https://github.com/lfortran/lfortran/commit/e1d85b2eefea8990f14f897bfee3e0776f07f5ca
e.g.; CI run failure: https://github.com/lfortran/lfortran/actions/runs/14769610223/job/41467364462
we made changes in ASR in PR #7117, but the PR #7106 was merged right after that and hence it didn't take into account the updation of reference tests in `Variable` ASR node
> tests: update reference tests in accordance with #7117

- integration_tests/CMakeLists.txt
- integration_tests/separate_compilation_03.f90
- integration_tests/separate_compilation_03a.f90
- integration_tests/separate_compilation_03b.f90
- src/libasr/pass/intrinsic_array_function_registry.h
Fixes #7138. With this we can successfully compile `dftatom` in separate compilation mode.
> enh: prefix `IntrinsicArrayFunction` with `_lcompilers_`

- ci/test_third_party_codes.sh
- integration_tests/CMakeLists.txt
- integration_tests/separate_compilation_05.f90
- integration_tests/separate_compilation_05a.f90
- integration_tests/separate_compilation_05b.f90
- src/bin/lfortran.cpp
- src/bin/lfortran_command_line_parser.cpp
- src/libasr/asr_scopes.cpp
- src/libasr/asr_utils.cpp
- src/libasr/pass/unique_symbols.cpp
- src/libasr/utils.h
Fixes #7164. With this we set `Numerical Codes Fortran` with separate compilation at CI.
> enh: handling of intrinsic modules in separate compilation

- .github/workflows/LSP.yml
Changes:
- Moves test logic into bash script within the LSP workflow
- Makes testing parameters configurable
- Retries parallel tests up to 3 times
> Retries parallel tests on time-outs

- src/lfortran/semantics/ast_body_visitor.cpp
- tests/errors/continue_compilation_1.f90
- tests/reference/asr-continue_compilation_1-04b6d40.json
- tests/reference/asr-continue_compilation_1-04b6d40.stderr
Apply suggestion from https://github.com/lfortran/lfortran/pull/6638#pullrequestreview-2823049951
> chore: add errors for unsupported `mold` argument in allocate statements

- .github/workflows/CI.yml
Intends to fix: https://github.com/lfortran/lfortran/issues/7295
The branch added in this PR, i.e.: https://github.com/gxyd/lapack/tree/lf_07 has only commit on top of the older branch (i.e. https://github.com/Pranavchiku/lapack/tree/lf_06), and the commit is: https://github.com/gxyd/lapack/commit/9d9e48987ca109d46b92d515b59cb591fab9859a
So, the change in this PR fixes the version of rhash in `build/environment_unix.yml` in LAPACK's repository to build with LFortran
> CI: fix version of rhash for building LAPACK

- integration_tests/CMakeLists.txt
- integration_tests/cond_05.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Fixes https://github.com/lfortran/lfortran/issues/7311
> fix: allow comparison of boolean pointer

- ci/test_third_party_codes.sh
- integration_tests/CMakeLists.txt
- integration_tests/intent_03.f90
- src/libasr/codegen/asr_to_llvm.cpp
Fixes #7380. Towards #7328, with this we get `fortran-primes` working with separate compilation.
> enh: handling of call arguments in case of specified intent

- ci/test_third_party_codes.sh
We are removing an outdated test for POT3D that is no longer necessary.
POT3D is already being tested in LFortran’s CI pipeline (https://github.com/lfortran/lfortran/blob/5208cd61d15fde932f1c59de34d4a72a93627a31/ci/test_third_party_codes.sh#L70-L96). This existing test uses the latest version of the lfortran/fortran_mpi wrappers (perhaps missing just a few recent commits).
The test we are removing was originally added when we published our [blog post](https://lfortran.org/blog/2025/03/lfortran-compiles-pot3d/) demonstrating LFortran compiling POT3D. That blog post used an older version of the wrappers.
Since then, we’ve updated the wrappers and already test the same POT3D branch using these updated wrappers in the current CI setup. Therefore, keeping the older test is redundant.
In …
> CI: don't test older branch of POT3D with older fortran_mpi

- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/inline_function_calls.cpp
- tests/reference/pass_inline_function_calls-functions_05-5502cc1.json
- tests/reference/pass_inline_function_calls-functions_05-5502cc1.stdout
- tests/reference/pass_inline_function_calls-functions_07-bb03cfd.json
- tests/reference/pass_inline_function_calls-functions_07-bb03cfd.stdout
The said feature is allowed. However there are some restrictions,
1. Any call with `ArrayPhysicalCast` isn't inlined.
2. Any function with multiple return statements or single return statement which is not in the last line of the function body isn't inlined.
We use local pointers for array arguments, so no deep copy happens. This anyways happens when you pass the array to the function call. So all should be safe.
> Allow inlining function calls with arrays

- integration_tests/CMakeLists.txt
- integration_tests/class_20.f90
- integration_tests/class_21.f90
- integration_tests/class_22.f90
- integration_tests/select_type_06.f90
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/codegen/llvm_utils.cpp
- src/libasr/codegen/llvm_utils.h
- tests/reference/llvm-class_04-290b898.json
- tests/reference/llvm-class_04-290b898.stdout
- tests/reference/llvm-derived_types_45-ae31b1c.json
- tests/reference/llvm-derived_types_45-ae31b1c.stdout
- tests/reference/llvm-modules_36-53c9a79.json
- tests/reference/llvm-modules_36-53c9a79.stdout
Fix https://github.com/lfortran/lfortran/issues/7355, Fix https://github.com/lfortran/lfortran/issues/7340, Fix https://github.com/lfortran/lfortran/issues/7324, Fix https://github.com/lfortran/lfortran/issues/7383
Implement allocation for class allocatable variables.
- Implement the `allocate` statement for class allocatable variables.
- Support extended types in `allocate_array_members_of_struct()`.
- `integration_tests/class_10.f90` is commented out because we need to support nested `StructInstanceMember` recursively. We need to also improve, or maybe merge, `visit_SubroutineCall()` and `visit_FunctionCall()` in the llvm backend.
> enh: implement class allocatable variables

- integration_tests/CMakeLists.txt
- integration_tests/nested_12.f90
- src/libasr/pass/nested_vars.cpp
Previous Error:
```console
ASR verify pass error: ExternalSymbol::m_original_name must match external->m_name
Binary file "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran", in _start
File "./csu/../csu/libc-start.c", line 360, in __libc_start_main
File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2696, in main
return main_app(argc, argv);
File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line 2579, in main_app(int, char**)
return compile_src_to_object_file(opts.arg_file, outfile, compiler_options.time_report, false,
File "/home/jinang_shah/Desktop/lfortran/src/bin/lfortran.cpp", line …
```
> fix: correct `m_original_name` for structs in nested pass

- build1.sh
The lack of colours in a ninja build made it a bit difficult to find failures. Now we have some colours in the build.
> build: add color diagnostics flags

- integration_tests/intrinsics_378.f90
- src/lfortran/semantics/ast_body_visitor.cpp
Fixes #7400 
I am not sure if this is the best way to do it but we handle the `move_alloc` logic similarly by the function `instantiate_moveAlloc`. 
We can add semantic checks in the function `handle_moveAlloc` itself to prevent any invalid code from executing, and throw errors for wrong arguments like we do in `create_MoveAlloc` function.
> fix: handle `move_alloc` for unallocated variables

- integration_tests/CMakeLists.txt
- integration_tests/external_12.f90
- integration_tests/external_12_module.f90
- src/libasr/asr_verify.cpp
Fixes https://github.com/lfortran/lfortran/issues/7454
Towards: #7445
> fix: use 'check_external' to only apply ASR verify after visiting FixExternalSymbol

- integration_tests/CMakeLists.txt
- integration_tests/class_30.f90
- src/libasr/codegen/asr_to_llvm.cpp
> fix: correct `Struct` name order in `visit_arrayitem` and CreateLoad for nested SIM

- integration_tests/CMakeLists.txt
- integration_tests/class_28.f90
- src/libasr/codegen/llvm_utils.cpp
> fix : Do not call Deepcopy in LLVM for unlimited polymorphic variable (abstract_type)

- integration_tests/CMakeLists.txt
- integration_tests/class_29.f90
- src/libasr/codegen/asr_to_llvm.cpp
> fix: get type pointer for classes in `associated`  and `allocated` intrinsics

- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/codegen/asr_to_fortran.cpp
- src/libasr/intrinsic_func_registry_util_gen.py
- src/libasr/pass/intrinsic_function_registry.h
- src/libasr/pass/intrinsic_functions.h
- src/libasr/pass/intrinsic_subroutine_registry.h
- src/libasr/pass/intrinsic_subroutines.h
Fixes #7473 
As discussed in the last meeting, I have ported the `move_alloc` function from intrinsic functions to intrinsic_subroutine as per https://github.com/lfortran/lfortran/pull/7404#pullrequestreview-2871949502
> change `move_alloc` from intrinsic functions to intrinsic subroutine

- .github/workflows/CI.yml
The PR: https://github.com/lfortran/lfortran/pull/7561 made changes to how the github group is assigned to PR's merged in main, but I forgot to update the same in debugging info, which is used to understand how things work for github's group.
> CI: fix debugging info about github group

- integration_tests/CMakeLists.txt
- integration_tests/openmp_48.f90
- integration_tests/openmp_49.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/ASR.asdl
- src/libasr/pass/openmp.cpp
Towards #7332 and #7365
This will form base for implementing the `TASK` Construct in subsequent PR, I just thought to keep it separate so as to keep reviewing simpler hence make separate PR
> [OPENMP] FEAT: Implement Single/Master Construct

- integration_tests/CMakeLists.txt
- integration_tests/procedure_19.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
Fixes https://github.com/lfortran/lfortran/issues/5759
> fix: don't add procedure of ExternalSymbol to class SymbolTable

- integration_tests/CMakeLists.txt
- integration_tests/class_49.f90
- integration_tests/class_50.f90
- src/libasr/codegen/llvm_utils.cpp
- src/libasr/pass/pass_utils.h
Fix https://github.com/lfortran/lfortran/issues/2940
First commit is fixing a bug I found.
> fix: early return after temporary variable is created in replace_StructConstructor

- integration_tests/CMakeLists.txt
- integration_tests/class_52.f90
- src/lfortran/semantics/ast_body_visitor.cpp
- src/libasr/codegen/asr_to_llvm.cpp
Fix https://github.com/lfortran/lfortran/issues/7707
Also revert a change from https://github.com/lfortran/lfortran/pull/7700, which inserted `Allocate` in ASR. Instead use `check_and_allocate()` in llvm backend.
> fix: bitcast class allocatable to required type and do automatic allocation of StructType in backend instead of ASR

- integration_tests/CMakeLists.txt
- integration_tests/iso_fortran_env_01.f90
- integration_tests/iso_fortran_env_02.f90
- src/runtime/pure/lfortran_intrinsic_iso_fortran_env.f90
- tests/reference/asr-nested_struct_proc_01-3b9017b.json
- tests/reference/asr-nested_struct_proc_01-3b9017b.stdout
> enh: add `iostat_eor` in `iso_fortran_env`

- integration_tests/CMakeLists.txt
- integration_tests/class_38.f90
- integration_tests/subroutines_20.f90
- src/libasr/pass/array_struct_temporary.cpp
Fix https://github.com/lfortran/lfortran/issues/7562
Also uncomment a todo in `class_38.f90`.
> fix: don't create temporary variable when intent is inout or out

- integration_tests/CMakeLists.txt
- integration_tests/operator_overloading_12.f90
- src/lfortran/semantics/ast_common_visitor.h
> enh: populate all intrinsic op types in hashmap

- ci/test_third_party_codes.sh
This PR:
- Add test for the `stdlib_logger`
- Remove all workaround from `stdlib_array` & enable example for the `stdlib_array`
> CI: Enable test for logger & remove all workaround of array

- integration_tests/CMakeLists.txt
- integration_tests/operator_overloading_13.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
> fix: lower `remote_sym` name before checking it in symbol table

- src/libasr/codegen/llvm_utils.cpp
Fixes: https://github.com/lcompilers/lpython/issues/2741
Based on: https://github.com/lcompilers/lpython/pull/2805
Tested locally with
```f90
program name
implicit none
_lfortran_list(integer):: x
integer:: i, g
do i = 1, 100000
call _lfortran_list_append(x, i)
end do
do i = 1, 100000
g = _lfortran_pop(x, 0)
end do
end program name
```
Unoptimized
```bash
(lf_20) $ time lfortran test.f90
lfortran test.f90  17.23s user 0.12s system 98% cpu 17.573 total
(lf_20) $ time lfortran test.f90 --fast
lfortran test.f90 --fast  0.91s user 0.12s system 69% cpu 1.488 total
```
Optimized
```bash
(lf_20) $ time lfortran test.f90
lfortran test.f90  0.92s user 0.26s system 36% cpu 3.261 total
(lf_20) $ time lfortran test.f90 --fast
lfortran test.f90 --fast  0.92s user 0.05s system 74% cpu 1.300 total
``` …
> pop optimization

- src/libasr/asr_builder.h
- src/libasr/asr_utils.h
- src/libasr/codegen/asr_to_llvm.cpp
- src/libasr/pass/intrinsic_subroutines.h
- src/libasr/runtime/lfortran_intrinsics.c
- src/libasr/runtime/lfortran_intrinsics.h
is that cbind function can't return `char*` so we pass a variable to receive the return (like how we do with pass `subroutine_from_function`)
***
- get_environment_variable
- data_and_time
- get_command
***
- Refactor the interface declaration return `void` instead of `char*` and received the return in some passed argument to the C function.
- Declare the interface parameter types correctly (we're concerned about how to represent `char*` in C with proper C interoperability)
> Refactor : Refactor intrinsic subroutine (cbind returning string)

- integration_tests/intrinsics_387.f90
- src/libasr/pass/intrinsic_subroutines.h
- tests/reference/asr-cmd_02-ba58262.json
- tests/reference/asr-cmd_02-ba58262.stdout
- tests/reference/llvm-execute_command_line-0e9cd63.json
- tests/reference/llvm-execute_command_line-0e9cd63.stdout
fixes: https://github.com/lfortran/lfortran/issues/7972
> support keyword args in execute_command_line intrinsic

- integration_tests/CMakeLists.txt
- integration_tests/separate_compilation_16.f90
- integration_tests/separate_compilation_16a.f90
- integration_tests/separate_compilation_16b.f90
- integration_tests/separate_compilation_17.f90
- integration_tests/separate_compilation_17a.f90
- integration_tests/separate_compilation_17b.f90
- integration_tests/separate_compilation_18.f90
- integration_tests/separate_compilation_18a.f90
- integration_tests/separate_compilation_18b.f90
- integration_tests/separate_compilation_19.f90
- integration_tests/separate_compilation_19a.f90
- integration_tests/separate_compilation_19b.f90
- integration_tests/submodule_04.f90
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/asr-submodule_04-987b68b.json
- tests/reference/asr-submodule_04-987b68b.stdout
Towards #536 
Fixes #7270
Addresses https://github.com/lfortran/lfortran/pull/8010#pullrequestreview-3004223332
> fix : Do not return from instantiate function and populate llvm_symtab_fn for class interfaces

- integration_tests/CMakeLists.txt
- integration_tests/modules_61.f90
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/llvm-class_01-82031c0.json
- tests/reference/llvm-class_01-82031c0.stdout
- tests/reference/llvm-class_02-82c2f9c.json
- tests/reference/llvm-class_02-82c2f9c.stdout
- tests/reference/llvm-modules_11-a28ab77.json
- tests/reference/llvm-modules_11-a28ab77.stdout
- tests/reference/llvm-nested_03-2eacab7.json
- tests/reference/llvm-nested_03-2eacab7.stdout
- tests/reference/llvm-nested_04-39da8f9.json
- tests/reference/llvm-nested_04-39da8f9.stdout
- tests/reference/llvm-nested_05-0252368.json
- tests/reference/llvm-nested_05-0252368.stdout
- tests/reference/llvm-nested_06-fa1a99f.json
- tests/reference/llvm-nested_06-fa1a99f.stdout
- tests/reference/llvm-program_03-374e848.json
- tests/reference/llvm-program_03-374e848.stdout
- tests/reference/llvm-recursion_01-95eb32d.json
- tests/reference/llvm-recursion_01-95eb32d.stdout
- tests/reference/llvm-recursion_02-76da7b3.json
- tests/reference/llvm-recursion_02-76da7b3.stdout
- tests/reference/llvm-recursion_03-3285725.json
- tests/reference/llvm-recursion_03-3285725.stdout
> enh: mangle parent name as prefix for module variables

- integration_tests/boz_01.f90
- src/lfortran/semantics/ast_common_visitor.h
- tests/reference/asr-boz_01-dedad59.json
- tests/reference/asr-boz_01-dedad59.stdout
- tests/reference/llvm-boz_01-def9db5.json
- tests/reference/llvm-boz_01-def9db5.stdout
Towards #7839 
Here, I have implemented the logic to convert BOZ Literal to Real Values. The approach, based on the AMD compiler's handling, is as follows:
1. Find the minimum float value the compiler supports on given platform (in decimal).
2. Treat this value as the lowest real value, then multiply it by the bits extracted from the BOZ literal string to obtain the final value.
I have modified the Visit_BOZ function, and tested it on a basic scalar initialization of Data Statement to check correctness. Kindly verfiy and suggest changes required. 
Once those changes are verified, it shall be easy to integrate the actual compliance towards Fortran 2023 guidelines regarding BOZ Literals.
Thank you for your valuable time!
> Implementing BOZ to Real Conversion

- integration_tests/CMakeLists.txt
- integration_tests/submodule_07.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
fixes #7229
For now, this should work, but I suggest that we need to change the way `use` includes symbols in a module. Right now, `use` adds the symbols of the target module to the symbol table's scope of the module in which it is used. However, I think we need to separate the used symbols from those that are defined inside the module.
> feat: allow a submodule to use the same module as the parent

- src/libasr/runtime/lfortran_intrinsics.c
Previously print would just give `Unknown Type` since `uint` wasn't handled in `print_into_string`
> Unsigned int print fix

- src/lfortran/semantics/ast_common_visitor.h
This PR moves the existing semantic check for BIND(C) procedures to the end of the `TypeCharacter` handling block in the `determine_type()`
> Relocated semantic check for bindC character length

- integration_tests/CMakeLists.txt
- integration_tests/derived_types_71.f90
- src/libasr/pass/pass_utils.h
> fix: create association for pointer member during replacing `StructConstructor` 

- integration_tests/separate_compilation_20b.f90
- integration_tests/submodule_09.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
Addresses https://github.com/lfortran/lfortran/pull/8126#discussion_r2231316807
PR also adds support for declarations made in module procedures. For eg :- 
```.f90
submodule (stdlib_error) f18estop
implicit none
contains
module procedure error_stop
integer, parameter :: i = 3 
code = i
end procedure
end submodule f18estop
```
> enh : Support Declarations made in Module Procedures

- integration_tests/CMakeLists.txt
- integration_tests/string_67.f90
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/llvm-derived_types_32-4684b97.json
- tests/reference/llvm-derived_types_32-4684b97.stdout
- Make sure to allocate stack memory at entry point (for a temporary that isn't part of the ASR, hence could lead to stack overflow).
- Add an integration test
***
closes https://github.com/lfortran/lfortran/issues/8143
> create `alloca` at the entry point when used to change function return type into pointer

- integration_tests/derived_types_72.f90
- src/libasr/asr_utils.cpp
> fix: get correct struct symbol from implied do loop

- integration_tests/separate_compilation_21.f90
- integration_tests/separate_compilation_21a.f90
- integration_tests/separate_compilation_21b.f90
- integration_tests/submodule_10.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
Towards #536 
Fixes #8208 
Addresses https://github.com/lfortran/lfortran/pull/8142#discussion_r2233019689
> fix : Update current scope to parent scope after visiting procedure in ast symboltable visitor

- ci/test_third_party_codes.sh
This PR removes Submodule workarounds from all packages (excpet `stdlib stats`) from Stdlib in Separate Compilation mode.
> CI : Revert Submodule workarounds (except `stdlib stats`) from Stdlib Separate Compilation

- integration_tests/intrinsics_334.f90
- src/libasr/codegen/asr_to_llvm.cpp
- tests/reference/asr-intrinsics_334-6d740cf.json
- tests/reference/asr-intrinsics_334-6d740cf.stdout
Fixes #8334 
```fortran
! Fortran code after applying the pass: unique_symbols
program intrinsics_334
implicit none
type, abstract :: base
integer(4) :: id
end type base
type, extends(base) :: toml_value
integer(4) :: x = 0
end type toml_value
class(toml_value), allocatable :: struct_from3
class(base), allocatable :: struct_to3
allocate(struct_from3)
allocate(toml_value::struct_to3)
struct_from3%id = 123
struct_from3%x = 456
struct_to3 = struct_from3
select type(struct_to3)
type is (toml_value)
print *, struct_to3%x
if (struct_to3%x /= 456) error stop
end select
end program intrinsics_334
```
For classType assignments:
Previous:
```llvm
%37 = getelementptr %toml_value_polymorphic, %toml_value_polymorphic* %struct_from3, i32 0, i32 1
%38 = load %toml_value*, %toml_value** %37, align 8
%39 …
```
> fix: get rhs class type object and store in rhs using bitcast

- integration_tests/CMakeLists.txt
- integration_tests/string_69.f90
- src/libasr/pass/implied_do_loops.cpp
- tests/reference/pass_implied_do_loops-modules_35-c089638.json
- tests/reference/pass_implied_do_loops-modules_35-c089638.stdout
Fixes #8343
Original code:
```fortran
program m
implicit none
character(len=7) :: value
character(len=:), allocatable :: keywords(:)
integer :: ii
ii = 7
value = "version"
keywords = [character(len=ii) :: value]
print *, len(keywords), keywords(1)
end program
```
Code after `implied do loop` pass:
Before:
```fortran
! Fortran code after applying the pass: implied_do_loops
program m
implicit none
integer(4) :: __1__libasr_index_
integer(4) :: ii
character(len=ii, kind=1), dimension(1) :: __libasr__created__var__0__array_constructor_
character(len=:, kind=1), dimension(:), allocatable :: keywords
character(len=7, kind=1) :: value
ii = 7
value = "version"
__1__libasr_index_ = lbound(__libasr__created__var__0__array_constructor_, 1)
__libasr__created__var__0__array_constructor_(__1__libasr_ind …
```
> fix: create allocatable temporary if string len is runtime

- integration_tests/CMakeLists.txt
- integration_tests/separate_compilation_24.f90
- integration_tests/separate_compilation_24a.f90
- integration_tests/separate_compilation_24b.f90
- src/lfortran/semantics/ast_symboltable_visitor.cpp
- src/libasr/asr_utils.cpp
- src/libasr/asr_utils.h
Fixes https://github.com/lfortran/lfortran/issues/8264
> fix : Load all the dependent Submodules for a module that is already loaded in global scope

- tests/errors/floatStringInput.f90
- tests/errors/integerStringInput.f90
- tests/errors/integerStringInput_64.f90
- tests/reference/run-floatStringInput-95c963d.json
- tests/reference/run-integerStringInput-16e7ff7.json
- tests/reference/run-integerStringInput_64-3a7e5be.json
The current test creates files in the parent directory of the lfortran project, i.e., outside the project directory. This behavior is undesirable. This PR updates the input file reference to ensure files are created/referenced from within the project directory. Reference tests have been updated.
Test Plan
- Verified by running ./run_tests.py successfully.
- Confirmed that no stray files are generated in the parent directory of the lfortran project.
> Fix test creating file outside project
